### ISSUE TITLE
[BUG] LFS pull fails on a migrated repo in Gitea

### ISSUE THREAD

**Issue by deniscep** [microsoft/AzureTRE#1018]
- Open VM Jumpbox
- Install Git client from git-scm.com
- Open Gitea and migrate a repo (e.g. https://github.com/microsoft/InnerEye-DeepLearning/) with LFS enabled.
- From git bash, do git clone, git lfs install, git lfs pull -> Gitea responds with 404

As an investigation step, I'd recommend setting up a stand-alone Gitea and verifying that LFS actually works as this feature has been added fairly recently.

**Comment by guybartal** [comment]
Managed to reproduce 404 locally in stand-alone Gitea

![image](https://user-images.githubusercontent.com/3179107/136688985-de2dea39-dc1c-415c-9e54-7fcbc896cd0a.png)

**Comment by deniscep** [comment]
Thanks and great job @guybartal on researching this! Let's then also raise our findings with Gitea and track the issue from that side. For now, we'll have to live without LFS; let's see if we can get [InnerEye tests running without it](#1020), or do we need to ask MSR to update their repo.

**Comment by adishachar** [comment]
great research @guybartal , adding @marrobi @Lybecker

**Comment by christoferlof** [comment]
Moving off the board for the time being as we're blocked on Gitea issue 16935.
https://github.com/go-gitea/gitea/issues/16935

**Comment by marrobi** [comment]
@chboudry have you seen this when working on Inner Eye at all?

**Comment by marrobi** [comment]
Closing as this is an issue with Gitea and not aware of anybody being blocked by it.
