### ISSUE TITLE
Add service bus connectivity and resource processor health to status endpoint

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#1040]
## Description

As a TRE Administrator
I want to know if the system is healthy
So that I can report issues quickly

## Acceptance criteria

- [x] #1361
- [x] Status endpoint returns resource processor health as per cosmos. Requires #701

**Comment by anatbal** [comment]
@marrobi, @tamirkamara   After taking a look at [#119](https://github.com/microsoft/AzureTRE/pull/119) it seems like this task means bringing /api/status and /api/health back together, if I understand correctly?
