### ISSUE TITLE
Base Workspace KeyVault needs firewall enabling

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#1047]
Firewall is not enabled on the base workspace KeyVault.

**Comment by ross-p-smith** [comment]
@marrobi - Can I clarify? Do you wish to only allow traffic from the core vnet to be able to access Key Vault? Which subnets do you want to have access? There are 6 subnets at the moment

**Comment by marrobi** [comment]
Only the workspace should have access to the Key Vault. So the subnets in the base workspace template.
