### ISSUE TITLE
Running `/scripts/workspace-app-reg.py` script results with execute permissions issue and missing python libraries inside the devcontainer

### ISSUE THREAD

**Issue by christoferlof** [microsoft/AzureTRE#1049]
running script /scripts/workspace-app-reg.py results with execute permissions issue and missing python libraries inside the devcontainer:

https://github.com/microsoft/AzureTRE/blob/develop/docs/tre-admins/setup-instructions/installing-base-workspace.md#creating-a-base-workspace

**Comment by marrobi** [comment]
Will complete #1076  and remote the Python script.

**Comment by marrobi** [comment]
Python script has been removed and replaced by single bash script.
