### ISSUE TITLE
[STORY] Change health endpoint from ping to health. Also move health to status

### ISSUE THREAD

**Issue by sachinkundu** [microsoft/AzureTRE#108]
## Description

As a TRE Admin
I want to check health at a more intuitive endpoint such as /api/health
So that I don't have to remember /api/ping as the health endpoint

## Acceptance critiera

- [ ] On management API health is available at /api/health
- [ ] App GW uses /api/health for custom health probe
- [ ] Current /api/health is renamed to /api/status

**Comment by msebragge** [comment]
Closed with PR #119
