### ISSUE TITLE
Building InnerEye Workspace from API fails if Location set to UKSouth

### ISSUE THREAD

**Issue by dram1964** [microsoft/AzureTRE#1081]
**InnerEye Workspace Deploy fails if Region set to UK South**

When building an InnerEye workspace via the API, the deployment fails if location for resources is set to 'uksouth'. 'uksouth' is not in the list of allowed locations for both:
1. templates > workspace_services > azureml > user_resources > aml_compute > terraform > deploypl_compute_instance.json and
2. templates > workspace_services > innereye > terraform > nopipcompute > deploypl_compute_cluster.json

**Error Message from Deploy**
Original Error: Code="InvalidTemplate"
Message=Deployment template validation failed: 
The provided value 'uksouth' for the template parameter 'location' at line '1' and column '581' is not valid. The parameter value is not part of the allowed value(s): 'eastus,southcentralus,westus2,eastus2,westeurope'.
with azurerm_resource_group_template_deployment.deploy_compute_cluster

**Steps to reproduce**

1. Set location in devops > .env to 'uksouth'
2. Deploy TRE
3. Publish tre-workspace-innereye using porter build and publish_register_bundle.sh script
4. Deploy InnerEye Workspace via POST to /api/workspaces
5. Check Deployment Status via GET /api/workspacess/{workspace_id}

**Temporary Fix**
Add 'uksouth' to list of parameters > location > allowedValues in both:
1. templates > workspace_services > azureml > user_resources > aml_compute > terraform > deploypl_compute_instance.json and
2. templates > workspace_services > innereye > terraform > nopipcompute > deploypl_compute_cluster.json
This allows deployment to proceed

**Comment by marrobi** [comment]
@dram1964 Thanks. Yes, initially the AML private compute was only available in certain regions, most of us have been working in west europe, so good you are giving UK a try. I will remove the allowed values given this is now more broadly available.

**Comment by marrobi** [comment]
Fixed in #1082 1082
