### ISSUE TITLE
TRE Swagger UI unable to Authenticate with TRE API

### ISSUE THREAD

**Issue by dram1964** [microsoft/AzureTRE#1086]
**Authorisation not working on /api/docs**
When clicking the 'Authorize' link on the TRE API page (<fqdn>/api/docs), authorisation fails with the following error:
```
Auth error[invalid_client]: AADSTS650053:+The+application+'TRE+Swagger+UI'+asked+for+scope+'Workspace.Read'+that+doesn't+exist+on+the+resource+'466c7ccb-9216-438a-bb91-9a1c417f46fd'.+Contact+the+app+vendor.
Trace+ID:+9e8367ef-2fd6-4b16-86ff-63cd8963ec00
Correlation+ID:+7474ffb5-df0c-458f-82f7-614c57e13f6a
Timestamp:+2021-11-26+14:45:35Z.
```

**Steps to reproduce**

1. Newly deployed TRE from repository (commit: c9afe)
2. Connect to TRE Swagger UI (https://fqdn/api/docs)
3. Click 'Authorise' button
4. Client id is set to TRE Swagger ID
5. Click 'Authorise' again

**Additional Comments**
466c7ccb-9216-438a-bb91-9a1c417f46fd' is the app id for the TRE. API Permissions on this app are only:

1. Directory.Read.All
2. User.Read.All

No sign of a 'Workspace.Read' permission

**Comment by marrobi** [comment]
Hi @dram1964 we updated how auth works this week, along with the app registration creation scripts. Looks like something has snuck through in the PR. Our end to end tests don't use swagger hence looks like something has slipped through. I can see the issue and will do a PR ASAP, apologies for the inconvenience. 

If you want to try yourself replace `Workspace.Read` with `user_impersonation` in `api_app/api/routes/api.py`.

The app registration script used for both the TRE app reg and workspace app reg (the python one has now gone) should be creating this here - https://github.com/microsoft/AzureTRE/blob/c9afe0b44b3509ae05be210cf7526d51caa6460c/scripts/aad-app-reg.sh#L279 . 

Thanks again for raising this.

**Comment by marrobi** [comment]
@dram1964 this is now merged into main.

We've also added a new docs page here:https://microsoft.github.io/AzureTRE/tre-admins/setup-instructions/installing-workspace-service-and-user-resource/

Note the new per workspace URL for the workspace API swagger endpoint.

Any issues, let me know. Thanks again.
