### ISSUE TITLE
Problem using Nexus to proxy docker hub

### ISSUE THREAD

**Issue by dvoet** [microsoft/AzureTRE#1089]
**Describe the bug**
I am trying to setup nexus in the AzureTRE environment to proxy docker hub. I believe I have nexus setup correctly and appropriate docker hosts added the the firewall rules. When I try to run `docker login` from a VM running in a workspace shared service subnet I see error similar to what is described [here](https://stackoverflow.com/questions/49127414/docker-login-on-private-nexus-error-response-from-daemon-login-attempt-to-ht). According to [Sonatype docs](https://help.sonatype.com/repomanager3/formats/docker-registry/ssl-and-repository-connector-configuration) docker needs to be exposed on a different port than the standard ssl port nexus is already running on. However nexus is running in an Azure App Service and I don't see a way to expose custom ports.
**Steps to reproduce**

1. setup Nexus to [proxy docker hub](https://help.sonatype.com/repomanager3/formats/docker-registry/proxy-repository-for-docker)
1. add `*.docker.io` and `*.docker.com` to firewall rules to allow nexus to access them
1. create workspace and start vm in shared services subnet
1. connect to vm using bastion and run `docker login nexus-[tre_id].azurewebsites.net:[port]`
1. see timeout error

Acceptance criteria

- [x] #1479 
- [x] #1480 
- [x] #1481 
- [ ] Configure Docker Hub proxy in Nexus using a standalone port

**Comment by oliver7598** [comment]
Can this be assigned to me

**Comment by tamirkamara** [comment]
@oliver7598 do you have an idea on how to address this?

**Comment by oliver7598** [comment]
@tamirkamara myself and @jjgriff93 are going to pair on this as a priority over the next sprint

**Comment by tamirkamara** [comment]
Sounds good. Can you please share more details on the plan once you have it?
IIRC, I was the one who added this to begin with, so let me know if there's something I can help with...

**Comment by marrobi** [comment]
This doc will be useful - might be we add a second app service just for docker?

**Comment by jjgriff93** [comment]
Current challenge is exposing a second port in App Service to allow docker hub connections, which is prevented by this limitation: https://docs.microsoft.com/en-us/archive/blogs/waws/things-you-should-know-web-apps-and-linux#you-can-only-expose-one-port-to-the-outside-worldapplies-to-web-app-for-containers

**Comment by jjgriff93** [comment]
Potential solution is moving nexus to container instances which does support multiple ports, Oliver and I will do some investigation into this

**Comment by marrobi** [comment]
Container instances could work, still need an SSL certificate. VM is potentially a better option - easier to mount disks, backup etc.

Either way I don't think we can avoid generating SSL certificates with ACI or a VM.

**Comment by jjgriff93** [comment]
We had this thought also, will require some testing as to whether Nexus would support that - I don't think we'd be able to configure anything because we couldn't post configuration to the Nexus API to set up the docker proxy if we've exposed a different port for that instance

**Comment by jjgriff93** [comment]
Have set up a meeting to discuss further after tomorrow's stand-up - @tamirkamara have invited you if you're able to attend as your input would be valued. If not feel free to post your thoughts on this ticket. Summary of the planned meeting discussion:

 - How best to enable two exposed ports (limited to one for app service) so we can proxy docker hub on a separate port to the general nexus port (as per https://help.sonatype.com/repomanager3/nexus-repository-administration/formats/docker-registry/ssl-and-repository-connector-configuration)
- If we choose to host Nexus on container registry / VM to get around port issues, how we then plan to set up SSL certs in lieu of the app service provided one

**Comment by stuartleeks** [comment]
Possible approach for working with private VM endpoint proposed by @marrobi in a discussion on this (in terms of supporting dev environments)

```


 ┌──────────────────────────────────────────┐    ┌────────────────────────────────┐
 │                                          │    │                                │
 │ Public IP: mytre123.uksouth.cloudapp.net │    │  Storage static site           │
 │                                          ├───►│                                │
 │                                          │    │                                │
 └──────────────────────────────────────────┘    └────────────────────────────────┘
                                                        ▲
                                                        │
                                                        │
                                                        │
                                                        │
                                                        │
 ┌──────────────────────────────────┐                   │
 │                                  ├───────────────────┘
 │  Letsencrypt cert                │
 │  processor (run on schedule)     ├────────────────────┐
 │                                  │                    │
 └──────────────────────────────────┘                    │
                                                         │       ▼
                                                         │
                                                         │
                                                         │
                                                 ┌───────▼────────────────────────┐
                                                 │                                │
                                                 │  Key Vault                     │
                                                 │                                │
                                                 └────────────────────────────────┘
                                                         ▲
                                                         │
                                                         │
                                                         │
                          ┌──────────────────────────────┼────────────────────────────────────┐
                          │                              │                                    │
                          │   VNET                       │                                    │
                          │                              │                                    │
                          │                              │                                    │
                          │                      ┌───────┴─────────────────────────────┐      │
                          │                      │                                     │      │
                          │                      │ VM                                  │      │
                          │                      │                                     │      │
                          │                      │                                     │      │
                          │                      └─────────────────────────────────────┘      │
                          │                                                                   │
                          │                                                                   │
                          │                                                                   │
                          │                      ┌─────────────────────────────────────┐      │
                          │                      │                                     │      │
                          │                      │  Private DNS Zone:                  │      │
                          │                      │  map mytre123.uksouth.cloudapp.net  │      │
                          │                      │         to VM IP address            │      │
                          │                      │                                     │      │
                          │                      │                                     │      │
                          │                      │                                     │      │
                          │                      └─────────────────────────────────────┘      │
                          │                                                                   │
                          │                                                                   │
                          │                                                                   │
                          └───────────────────────────────────────────────────────────────────┘
                          
```

**Comment by jjgriff93** [comment]
Have added too new issues (see above) to start tracking the work on this

**Comment by martinpeck** [comment]
The three tasks associated with this bug are close, and the PR #1584 is merged, so closing this one out.

Thanks all!
