### ISSUE TITLE
[BUG] exfiltration path to storage accounts outside workspace

### ISSUE THREAD

**Issue by dvoet** [microsoft/AzureTRE#1091]
**Describe the bug**
One of the stated goals of a workspace is "The workspace is a security boundary and there should be zero transfer of data out from the workspace unless explicitly configured." However, I found that in the base workspace's services subnet the [`Microsoft.Storage` service endpoint is enabled](https://github.com/microsoft/AzureTRE/blob/main/templates/workspaces/base/terraform/network.tf#L16). According to [this page](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-udr-overview) that means storage account calls are routed differently and bypass all other workspace controls. Thus it becomes easy for a user to copy data from within the workspace to a storage account outside the workspace.

**Comment by marrobi** [comment]
Great catch. Looks like it was added as part of getting AML integrated which we know has certain limitations around storage access.

Will get this removed. 

Will also add an issue to create some end to end tests to catch this sort of regression.

**Comment by marrobi** [comment]
Thinking about this, the specific storage account still needs to be linked to the VNet I believe. Will give it a test.

**Comment by dvoet** [comment]
Leaving the service endpoint enabled would be ok if there is also an [endpoint policy](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-service-endpoint-policies-overview) in place and the storage account is configured to access traffic from the workspace VNet.

Alternately a private endpoint can be configured on the storage account in the workspace VNet.

**Comment by marrobi** [comment]
I've never actually tested without a policy - it does not make sense to have one without the other. You are correct - just verified. Will PR a fix now.

**Comment by marrobi** [comment]
@dvoet thanks very for point that out, fix is now merged. I couldn't replicate initially as I was still running an older version of the base workspace.

It might cause an issue with Azure Machine Learning in a a workspace - but that's not a reason to allow the traffic out and AML team are working on these challenges.

**Comment by marrobi** [comment]
E2E failed. Will investigate.
