### ISSUE TITLE
Documentation error : Installing Workspace Service and User Resource

### ISSUE THREAD

**Issue by mike-westaway** [microsoft/AzureTRE#1095]
There are 2 errors in the URL templates for [Installing Workspace Service and User Resource](https://microsoft.github.io/AzureTRE/tre-admins/setup-instructions/installing-workspace-service-and-user-resource/)

There are two references to api/<workspace_id>
Which should be: api/workspaces/<workspace_id>

**Comment by marrobi** [comment]
Thanks @mike-westaway . Fixed.
