### ISSUE TITLE
Guacamole redirect URL needs adding to the app registration. 

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#1096]
**Describe the bug**
When deploy Guacamole workspace service cannot log on as the redirect URL is not on the app registration. 

**Steps to reproduce**

1. Deploy guacamole workspace service
2. Visit connection_uri

Note: we should consider passing existing tokens to avoid the login loop, or using using the same redirect URL for all oidc services.

**Comment by eladiw** [comment]
One of these should be marked as duplicates:
https://github.com/microsoft/AzureTRE/issues/1352

its about getting the redirect url automatically ...

**Comment by joalmeid** [comment]
Duplicate of #1352
