### ISSUE TITLE
Internal Server error on API GET request to /api/workspaces/{workspace_id}

### ISSUE THREAD

**Issue by dram1964** [microsoft/AzureTRE#1098]
**Receiving an Error when querying /api/workspace/{workpace_id}**
Following the [instructions](https://microsoft.github.io/AzureTRE/tre-admins/setup-instructions/installing-base-workspace/) to install a base workspace after a fresh deployment of the TRE. After executing a POST to /api/workspaces, I get an '500: Internal Server Error' when attempting to GET /api/workspaces/{workspace_id}. However when executing a GET to /api/workspaces, I can see the deployment status of the workspace matching the {workspace_id}

**Steps to reproduce**

1. Create app registration for a new workspace
2. Add 'Workspace Owner' and 'Workspace Researcher' roles to my Azure logon on the corresponding Enterprise App
3. POST payload for a tre-workspace-base to /api/workspaces
4. Collect workspace_id from response
5. GET /api/workspaces/{workspace_id}
6. Server Response: 500: Internal Server Error
7. GET /api/workspaces produces a successful response and includes the workspace_id queried at (5)

**Comment by dram1964** [comment]
Documentation suggests that the User needs 'TRE Owner' and 'TRE Researcher' to query /api/workspaces/{workspace_id}. These roles are not defined when creating the app. Instead the only roles are 'Workspace Owner' and 'Workspace Researcher'

**Comment by marrobi** [comment]
Hi @dram1964 , Workspace Owner or Workspace Researcher should be fine. That route has a dependancy on 'get_current_workspace_owner_or_researcher_user_or_tre_admin'  here:

https://github.com/microsoft/AzureTRE/blob/af05ee38504dd5f302a40365105b7794d758decd/api_app/api/routes/workspaces.py#L98

Might need to update the docs - can you point me to where that is stated?

The 500 error - can you see anything in application insights under failures - or in the web app console logs? I'm guessing it's likely down to the app registration.

If there is nothing clear, then need to add an application setting of Debug=True to the web app, and give it another go, and see if we get some more information.

**Comment by dram1964** [comment]
The docs error is at the bottom of the [Installing Base Workspace](https://microsoft.github.io/AzureTRE/tre-admins/setup-instructions/installing-base-workspace/) in the 'Info' block

**Comment by dram1964** [comment]
I found this corresponding to the exception in Application Insights (lines 71 to 74 appear to be at the crux of the problem):
[api_get_workspace_by_workspace_id.txt](https://github.com/microsoft/AzureTRE/files/7692853/api_get_workspace_by_workspace_id.txt)

**Comment by marrobi** [comment]
Thanks. The error is `jwt.exceptions.InvalidAudienceError: Invalid audience`

The token in the audience isn't matching.

Think I've managed to replicate it. Will try track down the issue.

Can you try going to `https://<your_dns_name>/api/workspaces/<workspace_id>/docs`

The same API operation should exist there. Can you give that a go.

Thanks.

**Comment by marrobi** [comment]
Looks like https://github.com/microsoft/AzureTRE/blob/f027b4694fde23b71fd7f7d856e81d2c6959edf1/api_app/services/aad_authentication.py#L52

Needs to catch j`wt.exceptions.InvalidAudienceError` too. 

Will do a PR to fix both this and the docs issue. Hopefully can use the workspace specific API and are not blocked.

Thanks for reporting this,

**Comment by dram1964** [comment]
The workspace specific api works fine (as does GET on /api/workspaces) - so still able to progress the build. Cheers

**Comment by marrobi** [comment]
@dram1964 PR to fix this now merged. Thanks.
