### ISSUE TITLE
Reduce Number of Workflows (Github Actions)

### ISSUE THREAD

**Issue by martinpeck** [microsoft/AzureTRE#1117]
There appear to be more workflows than needed. There are currently 10. 

- `Build & Test` hasn't run for 6 months
- `Build Validation - Main` hasn't run for 8 months
- `Docker build and push` hasn't run for 4 months
- `Linting` hasn't run for 8 months

Suggest removing these 4, and also making sure those that *are* running are still useful.

![image](https://user-images.githubusercontent.com/1524451/149145710-b7030651-5e4c-461a-9edf-30bcbedde48e.png)

**Comment by marrobi** [comment]
I've removed some of these. I cant remove the disabled ones until the workflow history is deleted.

**Comment by tamirkamara** [comment]
I have removed the rest by deleting all the runs of the obsolete workflows a couple of weeks ago. I think we can close this issue @martinpeck.

**Comment by martinpeck** [comment]
Agreed. Will close this now. Thanks @tamirkamara
