### ISSUE TITLE
Jumpbox Username and Password in KeyVault Not In Obvious Format and Docs Lack Clarity

### ISSUE THREAD

**Issue by martinpeck** [microsoft/AzureTRE#1118]
In order to complete setup you need to set up Shared Services:

https://microsoft.github.io/AzureTRE/tre-admins/setup-instructions/configuring-shared-services/

During this phase you are asked to connect to the jumpbox using credentials stored in KeyVault.
The creds, in keyvault, are not clearly labelled "username" or "password", so it's not obvious which is which. Or, in fact that there's both a username and password present. You simply see something like this (not real)...

```
sd4f
Ds09435hc=&3w4hj@
```
... with no guidance that the first is a username, and the second is a password. They both look like part of a password that has wrapped across 2 lines.

Suggest: 

- add labels into this secret to make it clearer, or
- make the instructional text in the docs explain the format of this secret, or
- or, make the username look much more like a username (e.g. prefix it with `user_`)

Or all of the above

**Comment by marrobi** [comment]
Linked to #1120 . I feel the jump box should be Azure AD joined so activity can be audited on a per user basis, rather than generic credentials.

**Comment by tamirkamara** [comment]
AD authentication isn't available in the basic tier of Azure Bastion. IMO it's not worth to upgrade just for this VM which is anyway not used often, so I think we'll keep the local account for now.
But, I suggest simplifying the approach with using a known user account (vs. a random one).
