### ISSUE TITLE
Jumpbox Setup Has Too Many Manual Steps

### ISSUE THREAD

**Issue by martinpeck** [microsoft/AzureTRE#1119]
https://microsoft.github.io/AzureTRE/tre-admins/setup-instructions/configuring-shared-services/

The instructions for setting up the jumpbox have a large number of manual steps.
These should be converted into scripted steps.
Ideally, many of these steps should be moved into deployment/setup automation.

At present, the steps are manual and there is little to no guidance on the setup (e.g. which settings to set while running Windows installers)

**Comment by marrobi** [comment]
We need to revisit how share services are deployed and configured as part of #23. I have some ideas around this. Will add to 0.3 and add design label.

**Comment by vidit2011998** [comment]
> https://microsoft.github.io/AzureTRE/tre-admins/setup-instructions/configuring-shared-services/
> 
> The instructions for setting up the jumpbox have a large number of manual steps. These should be converted into scripted steps. Ideally, many of these steps should be moved into deployment/setup automation.
> 
> At present, the steps are manual and there is little to no guidance on the setup (e.g. which settings to set while running Windows installers)

Hi, Were you able to figure out the steps for configuring shared services? I am not able to understand it

**Comment by marrobi** [comment]
@vidit2011998 which bit are you struggling with?
