### ISSUE TITLE
User is Required to Login to az cli on Jumpbox

### ISSUE THREAD

**Issue by martinpeck** [microsoft/AzureTRE#1120]
https://microsoft.github.io/AzureTRE/tre-admins/setup-instructions/configuring-shared-services/

While setting up the jumpbox an individual user is used to perfom  `az login`

![image](https://user-images.githubusercontent.com/1524451/149229614-cf2634b1-7f93-447b-b8e2-f125abb69b3c.png)

Shouldn't this use a managed identity, or some other form of credentials that are not tied to a single user?

This would currently result in anyone with access to the keyvault, and able to access the jumpbox, being able to act on behalf of the user who set the jumpbox up.

**Comment by tamirkamara** [comment]
I don't think we have that step anymore. Can we close this issue @marrobi, @martinpeck ?

**Comment by tamirkamara** [comment]
I couldn't find the text/area this issue is referring to so closing for now.
