### ISSUE TITLE
When registering user resource template and workspace service template is not found exception not clear

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#1122]
**Describe the bug**
When try and register a user resource template, but the workspace service template does not exist the error message is not clear. 

`TEMPLATE_DOES_NOT_EXIST = "Could not retrieve the 'current' template with this name"`

need to add 

`WORKSPACE_SERVICE_TEMPLATE_DOES_NOT_EXIST = "Could not retrieve the workspace service template specified"`

**Comment by gauravagrwal** [comment]
Hi @marrobi, here we need to replace the current error message with the new one. right?
