### ISSUE TITLE
Error in terraform for core state-store

### ISSUE THREAD

**Issue by mike-westaway** [microsoft/AzureTRE#1129]
In templates\core\terraform\state-store\statestore.tf

The reference to the scope in azurerm_management_lock is incorrect

This (including 'resource.') ..
resource "azurerm_management_lock" "tre-db" {
  name       = "tre-db-lock"
  scope      = resource.azurerm_cosmosdb_sql_database.tre-db.id
  lock_level = "CanNotDelete"
  notes      = "Locked to prevent accidental deletion"
}

Should be changed to.. 
resource "azurerm_management_lock" "tre-db" {
  name       = "tre-db-lock"
  scope      = azurerm_cosmosdb_sql_database.tre-db.id
  lock_level = "CanNotDelete"
  notes      = "Locked to prevent accidental deletion"
}

**Comment by marrobi** [comment]
@mike-westaway Thanks for reporting. Does the TF return an error? I've not seen one personally. We are likely to do some refactoring of the TF shortly so will look at this then.

**Comment by mike-westaway** [comment]
Marcus,

It halts the execution of 'make all'.

Making the change allows 'make all' to proceed

Mike

**Comment by marrobi** [comment]
That's strange as I've (and others) have deployed from scratch this week without any issues. Will check with the team.

Are you running from inside the dev container? Wonder if its a Terraform change.
