### ISSUE TITLE
Start/Stop TRE requires you to log into PowerShell when you have been using bash up to this point

### ISSUE THREAD

**Issue by ross-p-smith** [microsoft/AzureTRE#1132]
Using the make files assumes that you have used `az login` at the start. When you want to `make tre-stop`, you then have to log into PowerShell.

1. az login
2. make all
3. make tre-stop

**Comment by daltskin** [comment]
Thinking is to remove the PowerShell script and run the commands in bash - removing the need for PowerShell altogether.   However the Azure Firewall PowerShell commands for allocating/deallocating are not available in az cli (this has been raised here: https://github.com/Azure/azure-cli-extensions/issues/4301)

Looking at the PowerShell $firewall.[Deallocate()](https://github.com/Azure/azure-powershell/blob/cd035673d8152c56c89fc91f4f77779918d8d3e4/src/Network/Network/Models/AzureFirewall/PSAzureFirewall.cs#L211) method - it's setting the IpConfigurations to an empty list: 

Which could be achieved by running the following az command: https://docs.microsoft.com/en-us/cli/azure/network/firewall/ip-config?view=azure-cli-latest#az-network-firewall-ip-config-delete

The $firewall.[Allocate()](https://github.com/Azure/azure-powershell/blob/cd035673d8152c56c89fc91f4f77779918d8d3e4/src/Network/Network/Models/AzureFirewall/PSAzureFirewall.cs#L144) method creates a new ManagementIPConfiguration which could be achieved using [az network firewall ip-config delete](https://docs.microsoft.com/en-us/cli/azure/network/firewall/ip-config?view=azure-cli-latest#az-network-firewall-ip-config-create)

az network application gateway start/stop is already supported in az cli: https://docs.microsoft.com/en-us/cli/azure/network/application-gateway?view=azure-cli-latest#az-network-application-gateway-start

@marrobi thoughts?

**Comment by marrobi** [comment]
If we can do without the PowerShell and stops it costing, all good with me!
