### ISSUE TITLE
[BUG] Subscription owner resource is being replaced when not changed

### ISSUE THREAD

**Issue by tanya-borisova** [microsoft/AzureTRE#1161]
**Describe the bug**

This bug was split out from bug https://github.com/microsoft/AzureTRE/issues/700.

Each time `make tre-deploy` is ran, resource `module.resource_processor_vmss_porter[0].azurerm_role_assignment.subscription_owner` is being updated:

```
module.resource_processor_vmss_porter[0].azurerm_role_assignment.subscription_owner must be replaced
-/+ resource "azurerm_role_assignment" "subscription_owner" ***
      ~ id                               = "/subscriptions/***/providers/Microsoft.Authorization/roleAssignments/deb370d9-e9c0-6ede-a44b-1f1ee3d2146d" -> (known after apply)
      ~ name                             = "deb370d9-e9c0-6ede-a44b-1f1ee3d2146d" -> (known after apply)
      ~ principal_type                   = "ServicePrincipal" -> (known after apply)
      ~ role_definition_id               = "/subscriptions/***/providers/Microsoft.Authorization/roleDefinitions/8e3af657-a8ff-443c-a75c-2fe8c4bcb635" -> (known after apply)
      ~ scope                            = "/subscriptions/***" -> (known after apply) # forces replacement
      + skip_service_principal_aad_check = (known after apply)
        # (2 unchanged attributes hidden)
    ***
```

This is happening even despite the fact that the value of the scope parameters doesn't change between updates.

**Steps to reproduce**

1. Run `make tre-deploy`
2. Run `make tre-deploy` again and watch the resource being updated

**Comment by tamirkamara** [comment]
@tanya-borisova do you have any idea on this?
I remember reading in the past that other have the same issue but no real solution. Not a 100% sure but I think this is the [link](https://github.com/hashicorp/terraform-provider-azurerm/issues/7549)
