### ISSUE TITLE
Deleting user resources through API fails due to ARM dependencies

### ISSUE THREAD

**Issue by jjgriff93** [microsoft/AzureTRE#1163]
**Describe the bug**
When trying to use the DELETE API for user resources (i.e. to delete a research VM), it will accept the request, however the deletion will fail after approx 20 mins (querying the GET user resources will show deleting failed status) with:

```
Code=\"NicInUse\" Message=\"Network Interface /subscriptions/*******/resourceGroups/rg-jjgriff93-ws-233d/providers/Microsoft.Network/networkInterfaces/internal-nic-jjgriff93-ws-233d-svc-293a is used by existing resource /subscriptions/*******/resourceGroups/rg-jjgriff93-ws-233d/providers/Microsoft.Compute/virtualMachines/win10vm293a. In order to delete the network interface, it must be dissociated from the resource. 
```

And

```
Error purging of Secret \"win10vm293a-admin-credentials\" (Key Vault \"https://kv-jjgriff93-ws-233d.vault.azure.net/\") : keyvault.BaseClient#PurgeDeletedSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code=\"Forbidden\" Message=\"Operation \\\"purge\\\" is not allowed because purge protection is enabled for this vault. Key Vault service will automatically purge it after the retention period has passed.
```

**Steps to reproduce**

1. Follow the [TRE setup instructions](https://microsoft.github.io/AzureTRE/tre-admins/setup-instructions)
1. Then once the Guacamole Vm user resource is deployed, first use the user resource PATCH API passing its id and set `{ "enabled": false }` so it can be deleted
1. Then use the DELETE user resource API passing the same id
1. Wait 20+ mins and use GET user resources to query deletion status. Should change from 'deleting' to 'deleting_failed' and the error message above

**Comment by marrobi** [comment]
@martinpeck got this again today when trying to delete a VM:

> │ Error: purging of Secret "linuxvm6dd2-admin-credentials" (Key Vault "https://kv-mrtredev-ws-5503.vault.azure.net/") : keyvault.BaseClient#PurgeDeletedSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Operation \"purge\" is not allowed because purge protection is enabled for this vault. Key Vault service will automatically purge it after the retention period has passed.\r\nVault: kv-mrtredev-ws-5503;location=westeurope"
│ 
│ 
╵
