### ISSUE TITLE
Running `make tre-stop` causes the next `make tre-deploy` to fail

### ISSUE THREAD

**Issue by tanya-borisova** [microsoft/AzureTRE#1165]
**Describe the bug**

Running `make tre-stop` will cause the next `make tre-deploy` ran in the same environment to fail.

**Steps to reproduce**

1. Run `make tre-deploy tre-start tre-stop` 
2. Run `make tre-deploy` again

**Investigation**

This seems to be due to the fact that commands `make tre-start` and `make tre-stop` are [manipulating](https://github.com/microsoft/AzureTRE/blob/main/devops/scripts/control_tre.sh#L8) the resource `fw-ip-configuration` which is [managed by terraform](https://github.com/microsoft/AzureTRE/blob/main/templates/core/terraform/firewall/firewall.tf#L17). 

Because of this, Terraform wants to recreate it:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/52954123/150855645-b9ffd677-90ff-4d0f-a50c-3ebfd7b28db7.png)

However there is also a [lock](https://github.com/microsoft/AzureTRE/blob/main/templates/core/terraform/firewall/firewall.tf#L25) on its parent resource. Because of this, Terraform fails to recreate it: 

![image](https://user-images.githubusercontent.com/52954123/150855989-e500fc6b-5c25-45b4-9903-da37f8578d44.png)

Given that the resource managed by Terraform is also modified elsewhere, I think we should add a `lifecycle` [attribute](https://www.terraform.io/language/meta-arguments/lifecycle#ignore_changes) there, to reflect the fact that the `fw-ip-configuration` resource is modified by processes outside Terraform:

```
lifecycle {
    ignore_changes = [
      ip_configuration,
    ]
  }
```

**Comment by marrobi** [comment]
The lock is only a do not delete lock, so confused as to which it cannot create the IP - its trying to replace the entire firewall from what I can see.

I'm happy with ignoring changes on ip configuration if it fixes it. 

Good investigation work.

**Comment by tanya-borisova** [comment]
> confused as to which it cannot create the IP - its trying to replace the entire firewall from what I can see

Confused about this as well, from what I understand this can happen if there's no way to update the firewall in the API (or it's not implemented in the provider). I'll look again into this today

**Comment by tanya-borisova** [comment]
Looks like we can't solve the problem by adding `lifecycle { ignore_changes = [ip_configuration] }` as the ip_configuration resource is used in the `firewall` module outputs. More information on this can be found here: https://stackoverflow.com/questions/64319242/terraform-ignore-changes-for-resource-output 

It seems that Terraform doesn't like it very much when a resource is updated both within and outside of Terraform. 
The way to solve this seems to be to add a `data` import to Terraform for any dependencies, but manage the firewall object from outside of this Terraform state.

@marrobi  said there are plans on extracting the firewall out into a shared service. I think once we do it, this problem will go away, so this sounds like the best course of action.

**Comment by tanya-borisova** [comment]
Leaving this bug open for now just so that we remember that we are incurring additional costs at the moment.

**Comment by daltskin** [comment]
As an interim, we could leave make tre-stop/start in place, and comment out the firewall changes from https://github.com/microsoft/AzureTRE/blob/main/devops/scripts/control_tre.sh

That way we stop the App Gateway from incurring further costs.  Depends on time required for https://github.com/microsoft/AzureTRE/issues/1177

**Comment by daltskin** [comment]
Can not reproduce following recent changes. Closing.
