### ISSUE TITLE
Vanilla workspace bundle to store Terraform state in Azure backend

### ISSUE THREAD

**Issue by tompaana** [microsoft/AzureTRE#117]
## Description

Currently the Terraform state of the vanilla workspace bundle is [tracked by Porter](https://github.com/getporter/terraform-mixin#terraform-state). This results in installation not being idempotent. Moving the state to Azure backend will solve the issue.

## Acceptance critiera

- [x] The Terraform state of the vanilla workspace bundle managed by Azure backend

**Comment by Lybecker** [comment]
I suggest we solve this by always mount the same storage account for the same Workspace when running the bundle

**Comment by marrobi** [comment]
@Lybecker we can use a single storage account for all, just use a different state key for each workspace (and in future service). This is how I am iterating the TF at present.
