### ISSUE TITLE
Extract `bootstrap` step from `make all`

### ISSUE THREAD

**Issue by martinpeck** [microsoft/AzureTRE#1188]
Currently, `make all` runs the `bootstrap` step.
This results in the CI/CD pipeline running the bootstrap every time.
We should move this out of `make all`, run it once, and in the process also tidy up how this is run and how outputs from `bootstrap` are fed into the main workflow.

**Comment by ross-p-smith** [comment]
I still think that there is benefit in a `make all`. This should be for the inquisitive person who just wants to clone and get everything working. I think what we are really after is amending our CI pipelines to not call bootstrap. Or am I wrong?

**Comment by marrobi** [comment]
@ross-p-smith yes, I agree. Need to chose which make steps run in CI when in an informed manner, `make all` is a just get me up and running.

**Comment by tamirkamara** [comment]
We're going to keep `make all` mainly for developers. CICD pipelines usually use the steps individually and not the `all` target.
