### ISSUE TITLE
Design Management API surface

### ISSUE THREAD

**Issue by christoferlof** [microsoft/AzureTRE#12]
The Management API should allow for control plane and eventually data plane operations to provision resources , list metadata about resources, update the state of resources etc.

The Management API will evolve as new concepts and features are introduced but we anticipate the core operations to manage workspaces and services to be part of the initial API version.

We envision a RESTful HTTP API along the lines of:
* `GET /workspaces` - Get workspaces
* `POST /workspaces` - Create workspace
* `GET /workspaces/{workspace_id}` - Get specific workspace
* `DELETE /workspaces/{workspace_id}` - Delete specific workspace
* `GET /sharedservices` - Get core (shared) services
* `GET /sharedservices/{shared_service_id}` - Get core (shared) service
* `GET /workspaces/{workspace_id}/services` - Get workspace services
* `POST /workspaces/{workspace_id}/services` - Create workspace service
* `DELETE /workspaces/{workspace_id}/services` - Delete workspace service
* `GET /workspaces/{workspace_id}/services/{workspace_service_id}/resources` - Create workspace service resources
* `POST /workspaces/{workspace_id}/services/{workspace_service_id}/resources` - Create a workspace service resource
* `GET /workspaces/{workspace_id}/services/{workspace_service_id}/resources/{workspace_service_resource_id}` - Get workspace service resource
* `DELETE /workspaces/{workspace_id}/services/{workspace_service_id}/resources/{workspace_service_resource_id}` - Get workspace service resource

## Examples
These requests are very simplistic just to illustrate the conceptual journey of creating a workspace containing a [Data Science Virtual Machine](https://docs.microsoft.com/en-us/azure/machine-learning/data-science-virtual-machine/overview). Actual spec to be developed as part of closing this issue.

### Create workspace
```http
POST /workspaces
Content-Type: application/json

{
    "name": "Workspace One",
    "owner": "chris"
}
```
```http
# this will probably have to be async with a 202 Accepted in reality
201 Created
Location: /workspaces/1

{
    "id": 1,
    "name": "Workspace One",
    "owner": "chris"
}
```

### Create workspace service - Virtual Desktops with shared Firewall 
```http
POST /workspaces/1/services
Content-Type: application/json

{
    "service_type": "virtual_desktops",
    "firewall": "shared"
}
```
```http
201 Created
Location: /workspaces/1/services/2

{
    "id": 2,
    "service_type": "virtual_desktops",
    "firewall": "shared"
}
```

### Create workspace service resource - Linux DS VM
```http
POST /workspaces/1/services/2/resources
Content-Type: application/json

{
    "name": "DS VM One",
    "size": "Standard_DS3_v2",
    "image": {
        "publisher": "microsoft-dsvm",
        "offer": "ubuntu-1804",
        "version": "latest"
}
```
```http
201 Created
Location: /workspaces/1/services/2/resources/3

{
    "id": 3,
    "name": "DS VM One",
    "size": "Standard_DS3_v2",
    "image": {
        "publisher": "microsoft-dsvm",
        "offer": "ubuntu-1804",
        "version": "latest"
}
```

**Comment by jjcollinge** [comment]
Just going to share the API from our initial design doc:
```
|Route|Method|Scope|
|--|--|--|
|`/users`|GET|  |
|`/user/<userId>`|GET|  |
|`/workspaces`|GET, POST|  |
|`/workspaces/<workspaceId>`|GET, DELTE, PUT|  |
|`/workspaces/<workspaceId>/operations`|GET|  |
|`/workspaces/<workspaceId>/operations/<operationId>`|GET|  |
|`/workspaces/<workspaceId>/users`|GET, POST|  |
|`/workspaces/<workspaceId>/users/<userId>`|DELETE|  |
|`/workspaces/<workspaceId>/policy`|GET, POST|Out of scope.|
|`/workspaces/<workspaceId>/policy/<policyId>`|GET, DELETE, PUT|Out of scope.|
|`/workspaces/<workspaceId>/services`|GET, POST|  |
|`/workspaces/<workspaceId>/services/<serviceId>`|GET, DELETE, PUT|  |
|`/workspaces/<workspaceId>/services/<serviceId>/operations`|GET|  |
|`/workspaces/<workspaceId>/services/<serviceId>/operations/<operationId>`|GET|  |
|`/workspaces/<workspaceId>/services/<serviceId>/actions`|GET, POST|  |
|`/workspaces/<workspaceId>/services/<serviceId>/actions/<actionId>`|GET|  |
|`/workspaces/<workspaceId>/services/<serviceId>/actions/<actionId>/operations`|GET|  |
|`/workspaces/<workspaceId>/services/<serviceId>/actions/<actionId>/operations/<operationId>`|GET|  |
|`/workspaces/<workspaceId>/services/<serviceId>/policy`|GET, POST|Out of scope.|
|`/requests`|GET, POST|Out of scope.|
|`/requests/<requestId>`|GET, DELETE, PUT|Out of scope.|
|`/schemas`|GET|  |
|`/schemas/<schemaId>`|GET|  |
|`/healthz`|GET|Out of scope.|
|`/search`|GET|Out of scope.|
```

**Comment by christoferlof** [comment]
Thanks @jjcollinge . I fixed the formatting of the table, why the post says it was edited by me.

**Comment by marrobi** [comment]
@jjcollinge  in your implementation what is a "service"? Is it a single VM?

Know the scope was narrower in places than some of the options we have been considering.

**Comment by jjcollinge** [comment]
A service can be anything defined by a terraform configuration. The workspace provides a virtual network for which the service is deployed. We only have a definition for a DSVM service in our implementation which means we haven't got a concrete design for ingress etc.

**Comment by christoferlof** [comment]
We will be focusing on workspace management initially. 
Management of workspace service resources will be removed from the TRE API for now and we'll rely on the API's that are coming with each service. This simplifies the Management API and boundaries and concerns becomes clearer. 

First 

* `GET /workspaces` - Get workspaces
* `POST /workspaces` - Create workspace
* `GET /workspaces/{workspace_id}` - Get specific workspace
* `DELETE /workspaces/{workspace_id}` - Delete specific workspace

Then

* `GET /sharedservices` - Get core (shared) services
* `GET /sharedservices/{shared_service_id}` - Get core (shared) service
* `GET /workspaces/{workspace_id}/services` - Get workspace services
* `POST /workspaces/{workspace_id}/services` - Create workspace service
* `DELETE /workspaces/{workspace_id}/services` - Delete workspace service
