### ISSUE TITLE
Debug and Purge Protection Core and Workspace

### ISSUE THREAD

**Issue by mike-westaway** [microsoft/AzureTRE#1201]
Remember to label the issue with the appropriate area, and also assign it to yourself if you plan to work on the issue in the near future.

**Describe the bug**
Setting debug to true disables Purge Protection in the core
https://microsoft.github.io/AzureTRE/tre-admins/environment-variables/#for-shared-management-resources-in-devopsenv

Workspace are still created with Purge Protection enabled (and it cannot be disbaled)

Suggest that debug should consistently set Purge Protection for both core and workspace

This could be done by replicating the setting in
https://github.com/microsoft/AzureTRE/blob/main/templates/core/terraform/keyvault/keyvault.tf
to
https://github.com/microsoft/AzureTRE/blob/main/templates/workspaces/base/terraform/keyvault.tf

**Steps to reproduce**

1. Follow setup instructions https://microsoft.github.io/AzureTRE/tre-admins/setup-instructions/getting-started/
2. In Step 2 set Debug="false"
3. Create Workspace, observe that in the core KeyVault Purge protection is disabled and in the Workspace KeyVault purge protection is enabled

**Comment by marrobi** [comment]
Linked to #1163
