### ISSUE TITLE
webapp.tf resource upload_nexus_props command error

### ISSUE THREAD

**Issue by oliver7598** [microsoft/AzureTRE#1203]
Trailing \ missed off of command following reformatting.
Share name in command replaced with var.storage_account_name rather than azurerm_storage_share.nexus.name which is incorrect.

**Steps to reproduce**
1. Pull latest code from main
2. 1. Run make tre-deploy
3. 2. Failure when creating the share

**Comment by marrobi** [comment]
@oliver7598 think this was fixed -  #1194 

Have you got the latest from main?

**Comment by oliver7598** [comment]
@marrobi Just seeing that now - was the pull request only recently approved as I rebased my code this morning and change is showing as 22h ago
