### ISSUE TITLE
Assign users Azure ML and prevent the deployment of compute other than via TRE API

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#1204]
## Description
As a TRE Administrator
I want Workspace Researchers to be automatically granted access to Azure ML
So that they can access the workspace without configuration in Azure

As a TRE Administrator 
I do not want AML Users to be able to create compute outside of that enabled via TRE user resources
So that compute is incorrectly configured allowing data exfiltration

This will likely need a group creating for each application role and that group assigning to an Azure ML RBAC role.

Or alternatively a script as part of the bundle that reads assigned users to the application role and grants them access to Azure ML. This will need to be "refreshed" via a custom action.

**Comment by CalMac-tns** [comment]
1.	AzureML we need to be able restrict access via IP (Whitelist / Conditional access / Guacamole server etc)
2.	Any compute must be within virtual network of the workspace / subnet etc.
3.	It must NOT be possible to create a linked service to anything else
4.	The same rules for GIT and PIP apply to the AzureML workspace.
5.	I must be able to monitor and control costs automatically, the cost control needs to fall within the workspace.
6.	Compute within the AzureML workspace must scale back or turn off (Compute Instance) when not in use.
7.	I must be able to use MLFlow from within AzureML
8.	I must be able to track my ML workflow locally or from with Azure ML.
9.	I must be able to track my projects execution
10.	I must be able to reproduce runs across multiple platforms
11.	I must be able to deploy models across multiple platforms
12.	I must be able to manage my ML models in a central registry
13.	I must be able to use the following applications WITHIN Azure ML and with MLFlow
a.	Jupyter notebooks
b.	Jupyter Lab
c.	VS Code
14.	I must be able to access my ML experiments from:
a.	The Virtual Machine (Linux or Windows VM)
b.	From ML compute (via hosted scripts or from within Jupyter) (Restricted to TRE workspace)
15.	I must be able to access data from a secure area, such as a restricted area such as Azure Storage (Access and write to)
16.	I must be able to export artefacts from the Azure ML workspace to other TRE Workspace users:
a.	To either share with another TRE user OR
b.	Copy externally outside of the TRE (Via agreed route, or no agreed route then this is not a requirement) 
17.	Artefacts in the secure area must be shareable by delegation.
18.	Artefacts within the ML workspace should be sharable with other TRE users (within the TRE workspace)
19.	I must be able to select different computes (from a restricted list)
a.	For Compute instance (Fixed compute / Compute Instances)
b.	For inference (Scalable compute / Compute clusters)
20.	I must be able to deploy my models either:
a.	Kubernetes
b.	Azure Compute Instance
21.	I must be able to configure Python packages from the compute instances / clusters inside Azure ML
22.	I must have secure access to PaaS Databases such as:
a.	SQL Server
b.	Postgres
23.	PaaS database service performance should be selectable from a predefined t-shirt sized templates (small / medium / large)
a.	Access to these databases should be restricted to only TRE workspace users and then only by invite.

**Comment by marrobi** [comment]
@LizaShak @anatbal I could do with passing the output of `_get_batch_users_by_role_assignments_body` to the resource processor so the AML bundle can assign AML roles to the principal Ids.

What approach would you take? I know we discussed having APIs returning users for a workspace.
