### ISSUE TITLE
Swagger cdn blocked by firewall defaults

### ISSUE THREAD

**Issue by chboudry** [microsoft/AzureTRE#1212]
**Describe the bug**
With the default setup, swagger page is unable to load because he can't reach the CDN
![image](https://user-images.githubusercontent.com/51988290/151814822-b5b7b307-f273-4279-b18c-4a144c307fe9.png)

Once you create firewall rules | disable route :
![image](https://user-images.githubusercontent.com/51988290/151814843-2698d889-afa6-4926-bbed-376466638877.png)

**Steps to reproduce**
1.Follow the default set up of the doc

notice : if you enable the firewall on an existing working setup, CDN data are cached in browser and it's likely you won't have the issue.

**Comment by marrobi** [comment]
@chboudry Thanks. Where are you trying to access the Swagger API from?

The correct URL should be similar to:

`https://<your_tre_id>.<your_region>.cloudapp.azure.com/api/docs`

As per the output of make all, specified here: https://microsoft.github.io/AzureTRE/tre-admins/setup-instructions/deploying-azure-tre/#validate-the-deployment

Unless the URL is incorrect in the docs somewhere?

**Comment by chboudry** [comment]
This is the URL I used for troubleshooting.

You have the same issue with the correct URL except the error is less readable

**Comment by marrobi** [comment]
@chboudry not sure I follow, if you use the app gateway URL what error do you get? The app gateway is definitely externally exposed. I have just completed a deployment and connected to the API.

**Comment by chboudry** [comment]
As discussed, i was trying to access the Swagger URL from the jumpbox VM, while swagger should actually directly access remotely.
