### ISSUE TITLE
PR validation should test deployment and E2Es

### ISSUE THREAD

**Issue by tamirkamara** [microsoft/AzureTRE#1224]
## Description

As a TRE Developer
I want a stronger PR validation that tests deployment and some of the E2E tests
So that I'll be less likely to break the main branch.

* Need to find a good balance between this goal and the time we wait for validation to run.

## Acceptance criteria

- [ ] PR validation tests deployment of a TRE
- [ ] PR validation tests core E2E scenarios
- [ ] Validation runs or different PRs don't interfere with each other 
- [ ] Resources provisioned for validation are deleted automatically to reduce cost

**Comment by ross-p-smith** [comment]
Are we saying that a PR build should build a fresh copy of TRE and run the E2E tests in order to merge. Then the build of main deploys over the top of a persistent environment?

**Comment by tamirkamara** [comment]
Yes @ross-p-smith. 
It remains to be defined what is the difference between the E2E that run in the PR and the one after merge to main. If there's no difference probably we don't need both.
As to the persistent environment - I wonder if anyone actually use it but that's a different discussion.

**Comment by martinpeck** [comment]
What's the time budget for these builds?
Are we holding ourselves to (for example) 20 mins for a PR build to complete?
Is there a different budget for the main build?

**Comment by tamirkamara** [comment]
@martinpeck I really wanted to meet that 20 mins mark... However the deploy itself runs for ~20 mins, add to that building images, running tests, pulling devcontainers and we get a higher number.
