### ISSUE TITLE
'make letsencrypt' fails while configuring network storage rules

### ISSUE THREAD

**Issue by dram1964** [microsoft/AzureTRE#1233]
'make letsencrypt' target fails to run because of an error in the ./core/terraform/scripts/letsencrypt.sh

**Error Message**
When running 'make letsencrypt', the command errors with: the following arguments are required: --resource-group/-g

**Steps to reproduce**

1. Following TRE instructions at [TRE docs](https://microsoft.github.io/AzureTRE/tre-admins/setup-instructions/deploying-azure-tre/)
2. Run make all to build TRE
3. Run 'make letsencrypt'

**Suggested Fix**
Added '--resource-group ${RESOURCE_GROUP} to the `az storage account network-rule` commands on lines 16 and 106 of the letsencrypt.sh file. 'make letsencrypt' then completes without error.

**Comment by ross-p-smith** [comment]
Just out of interest do you use default azure config? Do you have anything set if you type `az config get`?
