### ISSUE TITLE
Shared Service Templates in API

### ISSUE THREAD

**Issue by damoodamoo** [microsoft/AzureTRE#1238]
Feature #23 

The API needs extra endpoints to cater for `shared-service-templates`. These will work in the same way as `workspace-services`.

Acceptance:
- [ ] A new shared service template can be `POST`ed and seen in the data store
- [ ] Shared service templates can be listed via `GET`s
- [ ] Appropriate unit tests

**Comment by daltskin** [comment]
@tanya-borisova the PR looks like it addresses all of the acceptance criteria above - ok for me to close this?
