### ISSUE TITLE
Update Resource Properties via API

### ISSUE THREAD

**Issue by damoodamoo** [microsoft/AzureTRE#1240]
Feature #23 

The API needs to accept `PATCH` operations for all resources which update the state of the resource in the data store. To avoid data loss, the existing `properties:{}` block should be copied into a `history:[]` array within the resource document. The `history` item should include audit details about who / what  and when the change was made.

As part of allowing updates to properties, eTag checking should be implemented across _all_ `PATCH` endpoints, to ensure each submission contains the most up-to-date information and one change is not overwriting another. 

eg: 
```json
{
    "id": "95fa5b15-e0ec-4277-aee4-964a5bcb0c52",
    "templateName": "tre-workspace-base",
    "templateVersion": "0.1.5",
    "resourceVersion": 1,
    "properties": {
        "display_name": "Updated Title",
        "description": "I've made an update",
        "app_id": "6d8aabae-0318-4a4b-a433-848607dd0db5",
        "address_space": "10.1.5.0/24",
    },
    "history": [
         {
            "resourceVersion": 0,
            "updatedBy": "user@provider.com",
            "timestamp": 123456765.1234,
            "properties": {
               "display_name": "My new workspace",
               "description": "Initial desc",
               "app_id": "6d8aabae-0318-4a4b-a433-848607dd0db2",
               "address_space": "10.1.5.0/24"
           },
          { ... },
          { ... },
          { ... },
    ]
   ...
 }
```

Acceptance:
- [x] Ability to send a `PATCH` request to each resource type
- [x] All previous properties moved to history
- [x] Appropriate unit testing
- ~[ ] E2E test added for `PATCH`~ 

> NOTE: Currently each resource accepts a `PATCH` which _only_ sets the `enabled` property. These will be updated to cover all properties, including the `enabled` flag, if sent.

TO DO:
- [x] `enabled` flag moved to top level of resource document
- [x] Allow update of `isEnabled`, and `properties`.
- [x] Unit tests for property history
- [x] custom annotation added to schema docs to indicate the property is updateable
- [x] translate `updateable: false` custom annotation into `readOnly` when validating `PATCH`ed properties
- [x] validate properties from resource template
- [x] return `_etag` in all resources
- [x] require `etag` in all `PATCH`es

**Comment by tanya-borisova** [comment]
I had a brief thought about only using the `history` block and treating the top history item as a current property block, but actually it will make things more complicated without a clear benefit. So I think your design is good as it is written up here!

**Comment by damoodamoo** [comment]
Moving the e2e test requirement to #1243
