### ISSUE TITLE
Guacamole: Connection to user resource fails if allocated IP address of old resource which has failed to delete

### ISSUE THREAD

**Issue by oliver7598** [microsoft/AzureTRE#1241]
As mentioned in issue #1201 and #1163 User Resources currently fail to delete due to Key Vault purge protect.
This happens after the Virtual Machine is deleted and the IP used is freed.
If a new resource is then created and the old IP allocated, the connection uri created will match that of the previous resource.
On attempting to connect to the virtual machine a connection error is presented.

**Steps to reproduce**
1. Create a user resource in a Guacamole service
2. Delete the user resource
3. Wait for the delete to fail so the IP is free
4. Create a new user resource
5. Wait for it to be ready to use
6. Go to connection uri provided
7. Connection error

NOTE:  I have only tested this on a Ubuntu deployment.  Unsure if the same would happen for a Windows VM although I would expect it to.

**Comment by marrobi** [comment]
I think the issue here is IP addresses are being used for connection name, we should be using the VM name which should always be unique for the workspace service.

**Comment by marrobi** [comment]
I think his will be fixed if #1729 is completed.
