### ISSUE TITLE
Deploy InnerEye Workspace fails during deploy_compute_cluster

### ISSUE THREAD

**Issue by dram1964** [microsoft/AzureTRE#1255]
The deployment of an InnerEye Workspace through the API fails during the deployment of a compute cluster. 

**Error Message**
```
    {"code":"BadRequest",
     "message":"{  
    	    "error": {    
    	        "code": "UserError",    "severity": null,    "message": "Client address is not authorized and caller was ignored because bypass is set to NoneClient address:",   "messageFormat": null,   "messageParameters": null,   "referenceCode": null,   "detailsUri": null,   "target": null,   "details": [],   "innerError": null,   "debugInfo": null,   "additionalInfo": null 
    	    }, 
    		"correlation": {   "operation": "ae5be03fdf365947a3f83ad4697ff49a",   "request": "d99682c5bf306541" },
    		"environment": "uksouth", 
    		"location": "uksouth", 
    		"time": "2022-02-06T20:01:46.5017702+00:00", 
    		"componentName": "machinelearningcompute"rn
    	}"
    }
```
**Steps to reproduce**

1. Deploy new TRE
2. Correct version numbers in templates > workspaces > innereye > install_service_innereye.sh and install_workspace base.sh. Should be v0.1.6 not v0.1.5
3. Deploy all workspace, workspace_service and user_resource templates using make register-bundle and post payload to API
4. Create app registration for workspace and service principal for inference service
5. Deploy an new InnerEye Workspace by POST to /api/workspaces
6. Check status of deployment

**Comment by dram1964** [comment]
I commented out the contents of compute.tf in templates > workspace_services > innereye > terraform and after republishing the workspace service, have managed to successfully complete the deployment of the innereye workspace via the API.

**Comment by marrobi** [comment]
@dram1964 going to close this given the age and we removed the InnerEye workspace and now just have an InnerEye service. Be good to run through this again in person and ensure we have an optimal experience.
