### ISSUE TITLE
Buildkit setting doesn't get into the devcontainer in CI

### ISSUE THREAD

**Issue by tamirkamara** [microsoft/AzureTRE#1271]
**Describe the bug**
When running github actions using the devcontainer, the value of docker buildkit isn't passed to the docker run command. This prevents optimizations when building images (like cache)

**Steps to reproduce**
1. Look into the custom action file: .github/actions/devcontainer_run_command/action.yml
1. The input includes DOCKER_BUILDKIT with a default of 1 (which is good)
1. The run command step doesn't make use of this input which means buildkit is off

**Comment by ross-p-smith** [comment]
Is the bug that you don't need DOCKER_BUILD_KIT in .github/actions/devcontainer_run_command/action.yml?

I was under the impression that you only needed buildkit to build the image, not run it.

**Comment by tamirkamara** [comment]
The opposite @ross-p-smith.
.github/actions/devcontainer_run_command/action.yml has an input for it but it's not passed along with the docker run command. This means that all make build-and-push* are running without buildkit which would be useful for reducing build time.
I have a pending fix for it...

**Comment by ross-p-smith** [comment]
So you mean when the devcontainer builds other docker images? I understand, it's not that the docker run needs it, it's just that the ENV should be set inside the devcontainer? Just to be clear
