### ISSUE TITLE
Add Docker apt repository to default nexus configuration

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#1274]
## Description

As a Researcher
I want to use Docker on my Linux VM
So that I can run containers

See: https://docs.docker.com/engine/install/ubuntu/

## Acceptance criteria

- [x] Docker apt repository part of Nexus default configuration
- [x] I can install docker on a Linux VM as per the instructions at https://docs.docker.com/engine/install/ubuntu/

**Comment by oliver7598** [comment]
This will be achieved as part of the work for issue #1089

**Comment by oliver7598** [comment]
This can be closed
