### ISSUE TITLE
Simplify automatic bundle registration

### ISSUE THREAD

**Issue by tamirkamara** [microsoft/AzureTRE#1278]
## Description

As a TRE Administrator/Developer
I want to register bundles in a simple "atomic" way
So that I could perform the action manually and automatically through CICD

We currently have multiple make targets involved / look similar, with multiple script files that in turn call other make targets. This makes it hard to split the build/public/register activities in different stages in the ci that could reduce the total run time.

## Acceptance criteria

- [ ] A single make target (and script) that is able to register the bundle without build/publish (will reference a remote-published bundle)
- [ ] The target/script supports getting an access token for the TRE API
- [ ] Existing logic in make build-and-register-bundle, register-bundle-payload is removed
- [ ] Existing logic in scripts: devops/scripts/publish_register_bundle.sh, devops/scripts/build_and_register_bundle.sh is removed

**Comment by tamirkamara** [comment]
Question: is there any scenario where one might need to register a bundle that wasn't publish to a remote registry?

**Comment by marrobi** [comment]
This is my desired solution: https://github.com/microsoft/AzureTRE/issues/424

**Comment by tamirkamara** [comment]
@marrobi, the issue you mentioned is bigger than what I thinking about... The thing I suggest here is to simplify how we register bundles in the CI and manually (devs) and I think it's a small story.
Do you see any reason to not go ahead with it?

**Comment by marrobi** [comment]
Ok, no reason not to, although we still need a step that will output a JSON payload if no token is provided.

**Comment by stuartleeks** [comment]
I'm not sure I understand all of the acceptance criteria, but I agree that there is quite a bit of complexity in the existing make targets/scripts. 

If the scripts can be simplified then that seems positive to me, especially if it supports the build and publish being separated.
