### ISSUE TITLE
sudo required for all commands 

### ISSUE THREAD

**Issue by mike-westaway** [microsoft/AzureTRE#1288]
VSC could not start the devcontainer, complaining about docker compose even though it was available in WSL and DOS
az cli upgrade from 2.32 to 2.33 may have triggered this, not sure
pulled down the latest devcontainer source files and was able to restart the devcontainer in VSC
Now az login and make all require sudo to run, otherwise I get python errors, related to a missing file under /home/vscode/.azure/

Remember to label the issue with the appropriate area, and also assign it to yourself if you plan to work on the issue in the near future.

**Describe the bug**

**Steps to reproduce**

1.
1.
1.

**Comment by daltskin** [comment]
Quick check - docker compose was removed in #1159.  Have you rebuilt the devcontainer since your latest pull from main?

**Comment by mike-westaway** [comment]
My snapshot of TRE main branch was from Jan 14th 
Today (Feb 11th) I pulled down the contents of .devcontainer (but not the rest of TRE) and that resolved the issue
However, after doing this I did need to use sudo to get any commands to work

**Comment by ross-p-smith** [comment]
Hi Mike, which commands do you have to run as sudo. Is it explicitly docker commands? As Jamie mentioned, there have been changes to remove docker compose for the devcontainer and there have been some changes to run the devcontainer as a non root user, this could cause teh changes that you are seeing. I would rebuild your devcontainer after pulling the latest from within vscode, this should then rebuild teh container to run as a non root user. If you still get problems with running docker commands, then run this 
```bash
getent group docker
```
on both your WSL host and from within the devcontainer. These should be the same, if they are not, then you have to tell teh devcontainer what group your docker is in when you build it. The steps to do this are defined /workspaces/AzureTRE/.devcontainer/devcontainer.json on line 10. Let me know if that doesn't fix you up

**Comment by mike-westaway** [comment]
Thanks for the feedback. I'm using the environment for a Spark session on Friday, so I dont want to tweak it now. But after the event I'll follow your suggestions thanks.

**Comment by ross-p-smith** [comment]
I have just encountered this same problem. for anybody else that comes across this moving from az cli 2.32 to 2.33, then clean your devcontainer image and docker systrem prune and then rebuild your devcontainers. I am back working again after this
