### ISSUE TITLE
Explore deployment service and management API and configuration store options

### ISSUE THREAD

**Issue by christoferlof** [microsoft/AzureTRE#13]
This issue is to explore how to implement three components which are interconnected namely the:
* Deployment Service - reliable and auditable deployments of workspaces and services (aka resources)
* Configuration Store - metadata and desired configuration for resources
* Management API - API surface for apps and scripts to invoke the deployment service and read (and update) the configuration store.

![image](https://user-images.githubusercontent.com/166592/110518221-237e4300-810c-11eb-828f-86e042a3d30a.png)

## High-level requirements
* Repeatable and reliable deployment runs - Ability to re-run and retry in cases of intermittent errors etc.
* Auditable deployment runs - Need to know who initiated a deployment run when.
* Declarative resource definitions
* Open for extensibility - Allow others to extend with additional service types etc.
* Management API needs to retrieve configuration data to serve requests from callers - i.e *List services in workspace 'a'*
* Handle operations across several control planes such as identity provider, resource providers, resource data plane.
* Clean up and removal - i.e *delete a workspace*
* Deployment services are managed by an Azure operations generalist - monitor health and troubleshoot deployments.
* Also see #12 

## Edge cases we need to cater for
* Simultaneous updates of a shared resource - Example: Two workspace deployment runs are trying to update the same shared Firewall with their required rules
* Hide eventual consistency of the system to the users - show the actual resource state and not the desired state. Example: resource being updated or deleted.

## Implementation
- [ ] Review past implementations
- [ ] Create spike

## Ideas
Given above requirements, Terraform and GitHub actions would probably take us a long way. Let's discuss.

**Comment by jjcollinge** [comment]
A few other requirements:
- Must support a mechanism to expose the deployment outputs back to the management API.
- Must support a mechanism to handle secrets securely i.e. return secret references rather than the secret in plaintext.
I'll probably add a few more as I think about them.

**Comment by TessFerrandez** [comment]
Decision was made that at a high level we will re-use a lot of the design from an internal engagement by the Clarke team - but remove dependencies on CAF and moving to python where possible
