### ISSUE TITLE
Tidy DevContainer ACR on branch delete and/or PR closing

### ISSUE THREAD

**Issue by ross-p-smith** [microsoft/AzureTRE#1320]
## Description

As a Build User 
I want to remove unneeded tags from the DevContainer Azure Container Registry in the tredev repository.
So that we keep the costs down.

## Acceptance criteria

- [ ] When a branch is deleted, work out the refid and then delete the tag
- [ ] When a PR is closed, work out the refid and then delete the tag
- [ ] If a tag is older than 30 days delete it
- [ ] Do not delete latest!
- [ ] Add some docs in how to setup the ACR

**Comment by tamirkamara** [comment]
I suggest a simple approach like this
```sh
PURGE_CMD="acr purge --filter 'tredev:[0-9a-fA-F]{8}' --ago 7d --untagged"

az acr task create --name dailyPurgeTask \
  --cmd "$PURGE_CMD" \
  --schedule "4 4 * * *" \
  --registry myregistry \
  --context /dev/null
```

**Comment by stuartleeks** [comment]
As a safety net, I am going to add a delete lock on `latest` ([docs](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-image-lock#protect-an-image-from-deletion)). This would allow the `latest` tag to be updated, but not deleted until the lock is removed.

```bash
az acr repository update \
    --name myregistry --image myimage:tag \
    --delete-enabled true --write-enabled true
```

Then I'll add the scheduled task to purge the images as per the [comment ](https://github.com/microsoft/AzureTRE/issues/1320#issuecomment-1046941508 )above

**Comment by stuartleeks** [comment]
I've put the following in place.

Lock `latest` tag:

```bash
az acr repository update \
    --name $REGISTRY \
    --image tredev:latest \
    --delete-enabled true \
    --write-enabled true
```

Scheduled task to purge old images:

```bash
PURGE_CMD="acr purge --filter 'tredev:[0-9a-fA-F]{8}' --ago 7d --untagged"

az acr task create --name devContainerImagePurgeTask \
  --cmd "$PURGE_CMD" \
  --registry $REGISTRY \
  --schedule "4 18 * * *" \
  --context /dev/null \
  --base-image-trigger-enabled false
```

**Comment by martinpeck** [comment]
Reopened to cover adding Docs
