### ISSUE TITLE
This region has quota of 0 PremiumV3 instances for your subscription

### ISSUE THREAD

**Issue by vidit2011998** [microsoft/AzureTRE#1333]
Remember to label the issue with the appropriate area, and also assign it to yourself if you plan to work on the issue in the near future.

**Describe the bug**
Unauthorized" Message="This region has quota of 0 PremiumV3 instances for your subscription. Try selecting different region or SKU." Details=[{"Message":"This region has quota of 0 PremiumV3 instances for your subscription. Try selecting different region or SKU."},{"Code":"Unauthorized"},{"ErrorEntity":{"Code":"Unauthorized","ExtendedCode":"52039","Message":"This region has quota of 0 PremiumV3 instances for your subscription. Try selecting different region or SKU.","MessageTemplate":"{0}. Try selecting different region or SKU.","Parameters":["This region has quota of 0 PremiumV3 instances for your subscription"]}}]
**I tried multiple regions like estus and centralus but the error is the same every time.**

**Steps to reproduce**

In the last step of make all

**Comment by marrobi** [comment]
@vidit2011998 you will need to put in a support request to increase the quota as per https://docs.microsoft.com/en-us/azure/azure-portal/supportability/view-quotas . Often MSDN/trial subscriptions start with no PremiumV3 app service quota.

The other option is if you have quota for PremiumV2 you could switch the sku in the terraform. 

Will close this bud as isn't a AzureTRE issue, but an an Azure subscription support issue. We are looking to help in this area with #970  . Thanks.

**Comment by vidit2011998** [comment]
Hello, Thank you for the reply. I changed to V2 LRS but it has the error "Block blobs not supported". Could you suggest an option with which I can deploy using my trial subscription?

Thank you
