### ISSUE TITLE
Extended tests failing on main

### ISSUE THREAD

**Issue by ross-p-smith** [microsoft/AzureTRE#1336]
**Describe the bug**
The extended e2e tests on main have a failing test

**Steps to reproduce**

1. run the "Deploy Azure TRE" workflow on main
1. https://github.com/microsoft/AzureTRE/runs/5246833399?check_suite_focus=true

______________ test_create_guacamole_service_into_base_workspace _______________

admin_token = '***'
workspace_owner_token = '***'
verify = False

    @pytest.mark.extended
    @pytest.mark.timeout(3000)
    async def test_create_guacamole_service_into_base_workspace(admin_token, workspace_owner_token, verify) -> None:
    
        payload = {
            "templateName": "tre-workspace-base",
            "properties": {
                "display_name": "E2E test guacamole service",
                "description": "workspace for E2E",
                "address_space_size": "small",
                "app_id": f"{config.TEST_WORKSPACE_APP_ID}"
            }
        }
    
>       workspace_path, workspace_id = await post_resource(payload, strings.API_WORKSPACES, 'workspace', workspace_owner_token, admin_token, verify)

test_workspace_service_creation.py:50: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

payload = {'properties': {'address_space_size': 'small', 'app_id': '***', 'description': 'workspace for E2E', 'display_name': 'E2E test guacamole service'}, 'templateName': 'tre-workspace-base'}
endpoint = '/api/workspaces', resource_type = 'workspace'
token = '***'
admin_token = '***'
verify = False

    async def post_resource(payload, endpoint, resource_type, token, admin_token, verify):
        async with AsyncClient(verify=verify) as client:
    
            if resource_type == 'workspace':
                auth_headers = get_auth_header(admin_token)
            else:
                auth_headers = get_auth_header(token)
    
            full_endpoint = f"https://{config.TRE_ID}.{config.RESOURCE_LOCATION}.cloudapp.azure.com{endpoint}"
            print(f'POSTING RESOURCE TO: {full_endpoint}')
    
            response = await client.post(full_endpoint, headers=auth_headers, json=payload)
    
            assert (response.status_code == status.HTTP_202_ACCEPTED), f"Request for resource {payload['templateName']} creation failed"
    
>           resource_path = response.json()["operation"]["resourcePath"]
E           KeyError: 'operation'

helpers.py:63: KeyError
----------------------------- Captured stdout call -----------------------------
POSTING RESOURCE TO: https://***.***.cloudapp.azure.com/api/workspaces
--------- generated xml file: /workspaces/tre/e2e_tests/pytest_e2e.xml ---------
=========================== short test summary info ============================
FAILED test_workspace_service_creation.py::test_create_guacamole_service_into_base_workspace
======================= 1 failed, 16 deselected in 3.04s =======================
make: *** [Makefile:243: test-e2e-extended] Error 1

**Comment by eladiw** [comment]
This was due to app service with older version. a restart fixed it
