### ISSUE TITLE
error "(LocationNotValid) Supplied location uksouth is not valid.

### ISSUE THREAD

**Issue by vidit2011998** [microsoft/AzureTRE#1342]
Remember to label the issue with the appropriate area, and also assign it to yourself if you plan to work on the issue in the near future.

**Describe the bug**
# error "(LocationNotValid) Supplied location uksouth is not valid." 
I am creating a PremiumV2 ZRS account using CLI but it produces the following error shown in the screenshot. I am able to create it on the azure portal but not from the env.

**Steps to reproduce**

My tf file has:
resource "azurerm_storage_account" "state_storage" {
  name                     = var.mgmt_storage_account_name
  resource_group_name      = azurerm_resource_group.mgmt.name
  location                 = azurerm_resource_group.mgmt.location
  account_tier             = "Premium"
  account_kind             = "StorageV2"
  account_replication_type = "ZRS"
  allow_blob_public_access = false

bootstrap file has:
--kind StorageV2 --sku Premium_ZRS -o table
![Screenshot 2022-02-19 at 2 20 49 AM](https://user-images.githubusercontent.com/30552941/154780408-aac8153a-dfdb-42f4-9acb-4d0e02d2232a.png)

**Comment by marrobi** [comment]
Hi @vidit2011998, apologies for the delay, did you manage to resolve this? It isn't something we have seen. Imagine it's linked to the subscription being a trial.

**Comment by vidit2011998** [comment]
Hi, actually this was because of the limit of free subscription. Worked after I upgraded it. Thanks
