### ISSUE TITLE
App registration's redirect url should be set automatically when creating a workspace

### ISSUE THREAD

**Issue by eladiw** [microsoft/AzureTRE#1352]
## Description

As a TRE Workspace Owner/Azure TRE Developer
I want the redirect url to be set automatically in the app registration
So that I won't need this manual step before I can use services such as Guacamole

## Acceptance criteria

- [ ] When creating a new WS, the app registration for guacamole can be determined and set, automatically
- [ ] Either in the script or using the RP 
- [ ] Design is needed as part of this user story
- [ ] ~~#220 will add the AAD Application automatically when the workspace is created.~~

**Comment by joalmeid** [comment]
Duplicate of #1096

**Comment by martinpeck** [comment]
@ross-p-smith  to add a few dependencies and details
