### ISSUE TITLE
AzureTRE documentation aimed at business stakeholders

### ISSUE THREAD

**Issue by daltskin** [microsoft/AzureTRE#1366]
The current AzureTRE documentation assumes you know what you are already looking for, it would be useful to have the business requirements that AzureTRE resolves for creating and managing trusted research environments.  This could be in the form of:

- Case studies
- Videos/Interviews
- Example deployments

- [ ] #1367

**Comment by martysharkey** [comment]
We actually have a good case study from Imperial College which focuses on the business element rather than engineering. Happy to share this but we could consider how this could be made available in the Github Repo too. @PoojanumN

**Comment by martysharkey** [comment]
hey @marrobi and @daltskin here is the Imperial casestudy from our website. [Imperial College London Case Study](https://www.cloudkubed.com/case-studies/imperial-college-london-trusted-research-environment/). 

We can use our PDF version and upload it here if that works. 

@marrobi you can move this one to in progress and I can get the team to get the pdf uploaded.

**Comment by marrobi** [comment]
@martysharkey https://github.com/microsoft/AzureTRE/issues/1367 is the case study issue. Feel free to provide a case study/link using a pull request to the docs. Will leave it to @PoojanumN to manage the issue status etc.
