### ISSUE TITLE
AzureTRE Case study

### ISSUE THREAD

**Issue by daltskin** [microsoft/AzureTRE#1367]
## Description

As a customer or partner, I want to read a real world case study of an AzureTRE implementation
So that I can understand the business requirements customers often face when choosing this AzureTRE solution.

## Acceptance criteria

- [ ] Case study available either as a part of the documentation or linked from it

**Comment by marrobi** [comment]
We should add a case studies/articles page to the docs. Including items such as:

https://www.databricks.com/blog/2023/03/27/trusted-research-environments-health-and-life-sciences.html
