### ISSUE TITLE
Guacamole extension should pass an access-token to the TRE API rather than id-token

### ISSUE THREAD

**Issue by eladiw** [microsoft/AzureTRE#1386]
## Description

As a Azure TRE Developer 
I want to pass the access token to the underlying API
So that the authentication is according to best practices

on top of that, if needed, refresh tokens support may be added (today they are not supported) - Issue #1110 .

## Acceptance criteria

- [ ] id token is received at first
- [ ] id token is validated, only continue if token itself is valid + all required scopes/aud/etc is valid and matching (exists today)
- [ ] only if validated. an access token is requested (whether via OBO flow, code flow or other - need to choose best suitable)
- [ ] access token is sent to the TRE API
- [ ] if needed, fix TRE API to support the new token (probably not needed)

Technical notes:
1. Today we are using the [openid extension](https://guacamole.apache.org/doc/gug/openid-auth.html) which is using the [implicit grant flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow) to provide an id_token
2. the open id extension is loading first (either configuration or alphabetically)
3. redirected back to guacamole with the id_token
4. Can't use another implicit grant to get the access token as it will create an infinite loop. on top of that, implicit grant [can't be used to refresh token](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow#refreshing-tokens) and also are not supported for browsers with [3rd party cookies blocked](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow#prefer-the-auth-code-flow)
5. Need to see if the openid extension can be used with [OBO flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows#on-behalf-of)
6. another option is to avoid using the openid extension and implement the complete flow
7. Last point, need to verify that without issuing refresh token, guacamole does disconnect after a period of time

**Comment by tamirkamara** [comment]
@eladiw can this be closed now that we moved to the oauth2-proxy?

**Comment by eladiw** [comment]
> @eladiw can this be closed now that we moved to the oauth2-proxy?

yes
