### ISSUE TITLE
Guacamole user resource authentication requires email claim in the token

### ISSUE THREAD

**Issue by chboudry** [microsoft/AzureTRE#1397]
**Describe the bug**
When accessing the guacamole VM, if your token is missing a email claim, the authentication will loop forever

**Steps to reproduce**
Connect to guacamole with an AAD account (guest or member) that does not have an email claim

**workaround** 
add an email :) (verification is not done so it just need some text)

**Comment by marrobi** [comment]
Thanks for reporting this. I'll close the issue, as not sure how we can resolve as believe its Guacamole that is requiring the email claim. Short of failing on auth if the claim doesn't exist.

Good to have this as a reference.
