### ISSUE TITLE
[BUG] make letsencrypt expects certbot, while not installed

### ISSUE THREAD

**Issue by deniscep** [microsoft/AzureTRE#143]
**Describe the bug**
make letsencrypt is expecting an venv in /opt/certbot/bin/ and certbot installed, while neither might not be present.

Devcontainer has steps to setup venv and install certbot; these should be part of base make scripts as well so that CD can utilize them as well.

**Steps to reproduce**

1. run make letsencrypt on blank WSL/Linux machine

**Comment by marrobi** [comment]
@deniscep  is this to check for the prerequisites as we do with terraform and docker, or to actually install it? If to install then we should do all prerequisites?

**Comment by christoferlof** [comment]
Add as prereq to docs.
