### ISSUE TITLE
make tre-destroy fails when keyvault has purge protection

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#1446]
**Describe the bug**
Run make tre-destroy when key vault has purge protection enabled

`Deleting keyvault: kv-mrtredemo
Warning! If you have soft-delete protection enabled on this key vault, you will not be able to reuse this key vault name until the key vault has been purged from the soft deleted state. Please see the following documentation for additional guidance.
https://docs.microsoft.com/azure/key-vault/general/soft-delete-overview
Purging keyvault: kv-mrtredemo
(MethodNotAllowed) Operation 'DeletedVaultPurge' is not allowed.
Code: MethodNotAllowed
Message: Operation 'DeletedVaultPurge' is not allowed.
make: *** [Makefile:183: tre-destroy] Error 1
`

Commenting out this step allowed me to continue.

cc @tamirkamara

**Comment by tamirkamara** [comment]
@marrobi,
1. Were you using the latest version (I had something changed last Tuesday IIRC)?
2. Do you have the script output by any chance?
