### ISSUE TITLE
E2E tests workflow doesn't work

### ISSUE THREAD

**Issue by tamirkamara** [microsoft/AzureTRE#1447]
**Describe the bug**
The E2E tests workflow doesn't work

**Steps to reproduce**

1. Go to Github Actions - workflows - e2e
1. Run it on a branch of your choice
1. See that it fails

**Comment by marrobi** [comment]
@tamirkamara will delete workflow once verified is no longer needed.

@ross-p-smith can you confirm this can go?

**Comment by ross-p-smith** [comment]
I created it ages ago as I thought it would be nice to just run the Tests - it's safe to delete as I dont think it works anymore
