### ISSUE TITLE
Deployment fails with "Resource group 'rg-tresl' could not be found" on `make all` 

### ISSUE THREAD

**Issue by stuartleeks** [microsoft/AzureTRE#1451]
**Describe the bug**
When running `make all` for a fresh deployment, the following error is reported and the deployment fails:

```
Resource group 'rg-tresl' could not be found
```

**Steps to reproduce**

1. Delete any resource groups from previous Azure TRE deployments
1. Delete `.terraform` folders locally
1. Run `make all`

**Comment by vidit2011998** [comment]
> **Describe the bug** When running `make all` for a fresh deployment, the following error is reported:
> 
> ```
> Resource group 'rg-tresl' could not be found
> ```
> 
> **Steps to reproduce**
> 
> 1. Delete any resource groups from previous Azure TRE deployments
> 2. Delete `.terraform` folders locally
> 3. Run `make all`

run the "make all" command again. It will work

**Comment by marrobi** [comment]
I'm getting this today too.


```
ERROR: (ResourceGroupNotFound) Resource group 'rg-mrtredemo' could not be found.
Code: ResourceGroupNotFound
Message: Resource group 'rg-mrtredemo' could not be found.
make: *** [Makefile:169: tre-start] Error 3
```

**Comment by stuartleeks** [comment]
@marrobi - the issue I hit was because I have configured `az` to use table output by default. The change in #1453 is to force JSON output where JSON is expected.

If you run `az configure`, what do you see as the `output` value?

<img width="338" alt="image" src="https://user-images.githubusercontent.com/1824461/157207803-693b875d-dba4-4635-af1e-9de28fdf47a0.png">

**Comment by stuartleeks** [comment]
@vidit2011998 for my scenario, re-running `make all` still failed with the same error

**Comment by marrobi** [comment]
```
[core]
first_run = yes
output = table
collect_telemetry = yes
cache_ttl = 10
```

Something must have changed this... either the default has changed or something in the dev container?

**Comment by marrobi** [comment]
@stuartleeks this is a fresh deployment, then tre-start is running, but checks the resource group exists, but its not going to as hasn't been deployed yet. If the resource group doesn't exist we shouldn't exit, just not try to start?

**Comment by marrobi** [comment]
Reopening as still an issue.

I worked round this by changing the `control_tre.sh` script:

```
if [[ $(az group list --output json --query "[?name=='rg-${TRE_ID}'] | length(@)") == 0 ]]; then
  echo "TRE resource group doesn't exist. Exiting..."
else
  # other start stuff.
```

**Comment by stuartleeks** [comment]
@marrobi  - what is changed in the script snippet you gave compared to the [latest code ](https://github.com/microsoft/AzureTRE/blob/main/devops/scripts/control_tre.sh#L14-L17)?

**Comment by marrobi** [comment]
Removed the exit 0, and sandwiched the start commands between the `else` in my snippet and `fi`.

**Comment by stuartleeks** [comment]
Doesn't that effectively do the same thin in both cases?

In the code in main, it detects that the resource group doesn't exist, outputs the message and then exits (with 0 to indicate success)

In the code you pasted above, it detects that the resource group doesn't exist, outputs the message, and then skips the remaining commands because you pushed them into the `else` block.

The original issue I was facing was that the deployment was failing with this error. For me, this was because this block at the top wasn't catching the condition, so later steps failed because the resource group didn't exist.

**Comment by marrobi** [comment]
Exit 0 seems to exit completely, not just the control script, but the following commands in the make file, such as deploy do not run.

**Comment by stuartleeks** [comment]
I'm just re-testing this with fresh environment and `make all`

**Comment by daltskin** [comment]
Closing - can re-open if we can reproduce.
