### ISSUE TITLE
This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant.

### ISSUE THREAD

**Issue by vidit2011998** [microsoft/AzureTRE#1475]
Hi, did anyone face this issue during registration phase?

**Describe the bug**
Failed to obtain auth token for API:
{"error":"unauthorized_client","error_description":"AADSTS700016: Application with identifier '__CHANGE_ME__' was not found in the directory 'Default Directory'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.\r\nTrace ID: 03bca4cc-e241-4760-ac21-8cb00f751d01\r\nCorrelation ID: 9510b560-f8aa-4e56-9209-5720cfeb09a0\r\nTimestamp: 2022-03-10 07:37:21Z","error_codes":[700016],"timestamp":"2022-03-10 07:37:21Z","trace_id":"03bca4cc-e241-4760-ac21-8cb00f751d01","correlation_id":"9510b560-f8aa-4e56-9209-5720cfeb09a0","error_uri":"https://login.microsoftonline.com/error?code=700016"}
make: *** [Makefile:260: bundle-register] Error 2

**Steps to reproduce**

make bundle-register DIR=./templates/workspaces/base BUNDLE_TYPE=workspace

**Comment by marrobi** [comment]
Being fixed in: https://github.com/microsoft/AzureTRE/pull/1471

Comment out the sample variables starting AUTOMATION_

**Comment by vidit2011998** [comment]
> Being fixed in: #1471
> 
> Comment out the sample variables starting AUTOMATION_

Hi @marrobi , Could you please tell me in which file I have to make these changes?
Thank you

**Comment by marrobi** [comment]
/templates/core/.env

If there are two variables starting AUTOMATION_ they need commenting out l.

**Comment by marrobi** [comment]
Closing this as we know the issue, and PR to be merged today.
