### ISSUE TITLE
The user is missing a required role: ['TREUser', 'TREAdmin']

### ISSUE THREAD

**Issue by vidit2011998** [microsoft/AzureTRE#1477]
Hi, I am facing this error in installing the base workspace.

**Describe the bug**
The user is missing a required role: ['TREUser', 'TREAdmin']
403 Error forbidden
202 successful response
422 validation error

**Steps to reproduce**

1. Once logged in, click Try it out on the POST /api/workspace-templates operation
2. Paste the payload json generated earlier into the Request body field, then click Execute. Review the server response.3. 
![Screenshot 2022-03-10 at 3 39 00 PM](https://user-images.githubusercontent.com/30552941/157639618-e1685c24-075a-48fc-86e4-23b5d5939761.png)
![Screenshot 2022-03-10 at 3 38 44 PM](https://user-images.githubusercontent.com/30552941/157639636-2047809b-c780-44d8-bd25-de83031cdaa1.png)

**Comment by marrobi** [comment]
@vidit2011998 have you granted the appropriate roles to you user in the Azure AD Enterprise Application as per https://microsoft.github.io/AzureTRE/tre-admins/setup-instructions/pre-deployment-steps/#add-admin-user ?

**Comment by vidit2011998** [comment]
> @vidit2011998 have you granted the appropriate roles to you user in the Azure AD Enterprise Application as per https://microsoft.github.io/AzureTRE/tre-admins/setup-instructions/pre-deployment-steps/#add-admin-user ?
> 
> See: https://microsoft.github.io/AzureTRE/tre-admins/auth/#enabling-users

Hi @marrobi , Yes I gave the --admin-consent parameter while running the /scripts/aad-app-reg.sh. But I am stuck here in installing the base workshop part.

**Comment by marrobi** [comment]
If you view the Enterprise Application in Azure AD, under Users and Groups do you see the users listed?

The users/your user needs assigning the TRE Administrator role.

**Comment by daltskin** [comment]
Closing this for now, if you are still facing issues let us know.
