### ISSUE TITLE
(Nexus Docker Hub) Change Nexus hosting to VM

### ISSUE THREAD

**Issue by jjgriff93** [microsoft/AzureTRE#1479]
As part of a solution to #1089, we need to host Nexus on a service that allows for exposing multiple custom ports. Currently App Service only allows one which is already consumed by Nexus' standard traffic over port 8081.

We need to move the Nexus container to be hosted by a VM:

- [x] Update the Terraform for the Nexus shared service to deploy a Linux VM
- [x] Use a cloudinit script to install necessary dependencies (i.e. Docker engine)
- [x] Also use this script to start the Nexus container and expose the port
- [x] Modify any related networking components to allow traffic to and from Nexus

**Comment by marrobi** [comment]
You are still going to require a SSL cert and private endpoint to enable
 apt and pypi to work.

**Comment by jjgriff93** [comment]
Yep good point, I've removed the test at the end as we don't expect this to work until the follow on task is completed
