### ISSUE TITLE
Publish docs from main branch failing

### ISSUE THREAD

**Issue by daltskin** [microsoft/AzureTRE#1488]
**Describe the bug**
Publishing docs via GitHub Pages is currently erroring from the workflow on main branch

**Steps to reproduce**

1. Make change to mkdocs documentation 
1. View the `Publish docs via Github Pages` workflow result after merge to main

Example: 

https://github.com/microsoft/AzureTRE/runs/5479916535?check_suite_focus=true

![image](https://user-images.githubusercontent.com/1678318/157739884-d0b22eee-3d7e-4fe9-b530-74bd08776dd9.png)

**Comment by daltskin** [comment]
Possibly now fixed with #1509

**Comment by stuartleeks** [comment]
Added #1510 to enable manually running the docs publish to verify

**Comment by stuartleeks** [comment]
https://github.com/microsoft/AzureTRE/runs/5550781660?check_suite_focus=true

![image](https://user-images.githubusercontent.com/1824461/158342649-2651283a-f0a1-4da1-9bb8-f4f582bd566d.png)

😄
