### ISSUE TITLE
Add OHDSI Atlas Workspace Service

### ISSUE THREAD

**Issue by daltskin** [microsoft/AzureTRE#1505]
ATLAS https://github.com/OHDSI/Atlas is an open source software tool for researchers to conduct scientific analyses on standardized observational data converted to the OMOP Common Data Model.

# Acceptance Criteria
- [ ] Workspace Owner can deploy and OHDSI Atlas workspace service including Achillies ( https://github.com/OHDSI/Achilles )
- [ ] Researcher can connect using trusted SSL certificate 
- [ ] Cohort selection and prediction tasks can be carried out
- [ ] Documentation and workspace service PR merged

**Comment by wereinse** [comment]
For the  third acceptance criteria we need something more specific there to know we completed it

**Comment by timmyreilly** [comment]
I'd be happy to take a look at this next week. @marrobi
