### ISSUE TITLE
Deployment fails on retry: Gitea secrets

### ISSUE THREAD

**Issue by damoodamoo** [microsoft/AzureTRE#1511]
When running the same query to list KeyVaults via “az rest” from 2 different locations (my local PC and cloud shell) I see different responses. The only difference I can see in the responses is the “x-ms-routing-request-id” . Responses that contain the expected data have this value set to WESTEUROPE, and empty responses show UKSOUTH. We have also seen a similar difference between US east and US west regions, but I was unable to capture those. 

It's been suggested that this relates to the ARM API cache across regions, where the KV being created in a region is immediately added to that cache, whereas there may be a lag for other regions. It's possible it's a temporary, Azure-only issue, but this issue tracks it.

**Comment by stuartleeks** [comment]
Related issue in `azurerm` provider: https://github.com/hashicorp/terraform-provider-azurerm/issues/15048

**Comment by damoodamoo** [comment]
Not 'fixed' - but...
- Not currently reproducing
- Have spoken with ARM API team and confirmed it was a cross-region caching issue. Given this is out of our control since Terraform interacts with the ARM API, we're limited in what we can do. 

Closing for now, but can reopen if we need to revist.
