### ISSUE TITLE
[Bug] Reconcile the state in case of errors during create workspace flow

### ISSUE THREAD

**Issue by tompaana** [microsoft/AzureTRE#154]
## Description

Workspace creation E2E flow needs to inspected and made robust so that errors during the flow will not cause an unrecoverable state.

Depends on #606 

Example:

1. Create workspace flow is initiated by the API
1. API changes the state in DB
1. API tries to send a service bus message, but fails
1. DB change should be rolled back

**Comment by Lybecker** [comment]
We should add retries to DB and Service Bus (the SDK might do it automatically)

If the user can perform a _none change_ to a Workspace, meaning HTTP PUT without any changes. The bundles are idempotent, so it will not result in any changes.

**Comment by TessFerrandez** [comment]
Please note that this is now also a TODO in the creation of workspace-services - that should be fixed with this
