### ISSUE TITLE
Extended E2Es fail due to missing etag

### ISSUE THREAD

**Issue by tamirkamara** [microsoft/AzureTRE#1545]
**Describe the bug**

One of the steps in the extended E2E test has recently began to fail due to a problem with the etag

**Steps to reproduce**

1. check this run: https://github.com/microsoft/AzureTRE/runs/5614714266?check_suite_focus=true

**Comment by tamirkamara** [comment]
@damoodamoo something you changed in the API?

**Comment by daltskin** [comment]
@tamirkamara this looks to be resolved in #1554 - ok to close?

**Comment by stuartleeks** [comment]
@damoodamoo  - can this be closed now?
