### ISSUE TITLE
"State Store endpoint is not responding" in PR build

### ISSUE THREAD

**Issue by stuartleeks** [microsoft/AzureTRE#1573]
This build run failed: https://github.com/microsoft/AzureTRE/runs/5639936288?check_suite_focus=true#step:3:346

```
State Store endpoint is not responding

make: *** [Makefile:274: bundle-register] Error 1
Warning: Template API check for workspace_service tre-service-guacamole returned http status: 404
Error: Process completed with exit code 2.
```

Re-running succeeded, so it may be a timing/dependency issue.

**Comment by stuartleeks** [comment]
The theory is that the error in the description was because the API wasn't up and running. #1574 does nothing to address the cause of the API not running, but adds a check earlier in the process to make it easier to detect. 

Since this will change the error, we could close this and open an issue if we encounter problems with the API not being ready?

**Comment by tamirkamara** [comment]
Closing as this hasn't been seen for a while.
