### ISSUE TITLE
Azure CycleCloud shared service

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#1599]
# Description

CycleCloud enables users to create  manage, operate HPC and compute clusters  on Azure.  https://azure.microsoft.com/en-gb/features/azure-cyclecloud/.

Research teams often require the use of HPC within a research workspace.

A workspace service needs to be created that deploys a cycle cloud virtual machine and enables researchers to create HPC clusters.

# Acceptance Criteria
- [ ] #2025
- [ ] #2230
- [ ] SSL connection to cycle cloud enabled with trusted SSL https://docs.microsoft.com/en-gb/azure/cyclecloud/how-to/ssl-configuration?view=cyclecloud-8
- [ ] Workspace service documented and PR to AzureTRE repository complete

**Comment by msebragge** [comment]
assign to me

**Comment by marrobi** [comment]
Having done some investigation, to ensure security boundaries remain, cyclecloud would be best built as a shared service.

In the first instance a TRE administrator can manage the creation of clusters in the appropriate resource group, and with appropriate network setting, longer term workspace service could use the cycle cloud cli to create a cluster with appropriate network settings.
