### ISSUE TITLE
TRE cost can be reduced by stopping MySQL

### ISSUE THREAD

**Issue by tamirkamara** [microsoft/AzureTRE#1605]
## Description

As a TRE Developer I want to better control the cost of my environment by stop/start the MySQL in the core RG. 
This resource is number 4 in the cost breakdown and the next one in the list we can stop (after the firewall and appgw)
This is around 150$/month

## Acceptance criteria

- Control script is able to stop and start the MySQL

**Comment by marrobi** [comment]
Any reason we can't stop any mysql and postgres instances in the workspaces too? Also VMs?

**Comment by tamirkamara** [comment]
I also had that thought but we currently don't "scan" the workspace resource groups. We can think about converting the entire control script to be tag based since we have a "tre_id" tag on all RGs, but looks like a bigger undertaking and not sure how much money it will save us the developers...
