### ISSUE TITLE
Docs and Code Still Refer to the Removed Endpoint /api/status

### ISSUE THREAD

**Issue by martinpeck** [microsoft/AzureTRE#1615]
We have removed the /api/status endpoint, but the docs still refer to it:

https://microsoft.github.io/AzureTRE/tre-admins/setup-instructions/deploying-azure-tre/#validate-the-deployment

**Comment by martinpeck** [comment]
`strings.py` also refers to this endpoint
`test_provisioned_health_api.py` still has a test for this endpoint

**Comment by anatbal** [comment]
@martinpeck I can't seem to find a reference for it in strings.py. Do you mind pointing out where?
