### ISSUE TITLE
Deploy fails on creating Public IPs in a location which is not an availability zone

### ISSUE THREAD

**Issue by LizaShak** [microsoft/AzureTRE#1632]
**Describe the bug**

When deploying TRE to a  location which is not an availability zone the deployment fails on the public ip creation. We could avoid getting this error and having all the resource deployed beforehand by pre checking the location is in availability zones. 

**Steps to reproduce**

1. Define LOCATION env variable to be a non [availability zone](https://docs.microsoft.com/en-us/azure/availability-zones/az-overview)
1. Deploy TRE

**Comment by tamirkamara** [comment]
We can't reproduce it in a region like ukwest. I think it is now handled more gracefully by Terraform's newer version we started to use.
