### ISSUE TITLE
API health endpoint and solution monitoring

### ISSUE THREAD

**Issue by tamirkamara** [microsoft/AzureTRE#1673]
## Description

As a TRE Administrator, I want to know the status of my TRE solution so that I can address potential issues with its components.
As an App Gateway, I want to know if the API is healthy so that I can forward it requests.

The current use of the API health endpoint to do both is causing issues and we need to figure out what requirements are important for us and how to address them.

## Acceptance criteria

TBD

**Comment by marrobi** [comment]
My preference:

We need a "system health" - which provides full system health as at present. It is important this does not always return 200 so can be used by external monitoring systems. However I do think we need to auth on this endpoint as is there not a risk of DDoS on downstream services.

Then for the app gateway API health probe we should probe a basic "api health" endpoint. Be that a simple ping, or actually includes cosmos health too is open to discussion.

**Comment by damoodamoo** [comment]
This sounds like we just need to move back to 2 health endpoints:
- "api-health": ping response, used solely for APPGW health probe
- "!system-health": query of services, return 503 if any are down

Could even tidy the routing such `/api/health/ping` and `/api/health/status` 

Think that covers it?

**Comment by tamirkamara** [comment]
* If Application Gateway probes a simple ping endpoint, it has little value (IMO) since the only thing it "saves" the external party is getting a timeout when the API application is actually down. All other malfunction cases aren't covered. 
* IMO, the API isn't operational if it doesn't have access to Cosmos or Service Bus so this might be a case to have Application Gateway return a 503. 
The RP is just an FYI as it doesn't impact the ability to do "online" interaction with the system (although no changes could probably be made).
* I don't understand the notion of an api exposing the whole health of the system. If this is meant for a developer / admin then it's not something I'd have liked to use... If an external system wants to know the full state of the system then maybe we should provide that by other means (azure metrics, app insights, etc.)

**Comment by damoodamoo** [comment]
I'm probably wrong but I thought the point of the health probe was to stop app gateway forwarding requests to bad nodes, in the case that the API app service is on more than one node - which it presumably would be in a prod scenario? If that's the case I think there probably is a value in it.

The cosmos and service bus calls are synchronous, so will return 503 to the user if those calls fail - so I don't think we want app gateway getting in the way there to shut down the API?

I agree in terms of system health - I can see a simple endpoint would be useful for a dashboard but really we must want some 'real' monitoring too - maybe this is down the line?
________________________________

**Comment by ross-p-smith** [comment]
Could we add a requirement so you could `GET` on `api/version` and return the version of the API and/or any downstream systems (Cosmos, RP, Core)
