### ISSUE TITLE
Fix bash linting on outputs.sh 

### ISSUE THREAD

**Issue by anatbal** [microsoft/AzureTRE#1700]
Remember to label the issue with the appropriate area, and also assign it to yourself if you plan to work on the issue in the near future.

**Describe the bug**

On #1552 , we have touch ./templates/core/terraform/outputs.sh script which copies so vars into the private.env. Since we enabled a new bash linter, it has thrown a bunch of linting errors which I had to disable since I didn't want to break anything that is already been working, but needs to be fixed.

**Comment by tamirkamara** [comment]
We won't be able to change the file without changing the whole method by which we load and use environment variables.
