### ISSUE TITLE
Add a doc on building a Porter bundle, compatible with TRE

### ISSUE THREAD

**Issue by tanya-borisova** [microsoft/AzureTRE#1710]

**Comment by marrobi** [comment]
@tanya-borisova are we able to cover the different types of bundles here - workspace, workspace service, user resource, shared service and how they differ from a creation perspective? This was created a while ago - https://microsoft.github.io/AzureTRE/tre-workspace-authors/authoring-workspace-templates/ but imagine things have changed.

**Comment by tanya-borisova** [comment]
@marrobi It might be best to have separate pages to build different types of bundles, and also perhaps this shouldn't be under this page. I will close this and we can create a separate story for templates, or use the one you linked.
