### ISSUE TITLE
On first connection to a VM often get sent to the Guacamole connection listings, rather than a specific VM

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#1724]
Could this be as the connection list is only loaded on a visit to /guacamole, rather than to the VM. So if connect to the VM directly is no list?

When is the VM list populated - at login or visit to /guacamole? Has there been a change to ensure the VM list is refreshed?

**Comment by eladiw** [comment]
Interesting. When I've tested it it worked OOTB.
I am interested to know how many VMs you had before the first attempt to connect. to be specific, if you have just 1 vm deployed, do you get the listing with 1 vm? or guacamole auto-redirect you?

**Comment by marrobi** [comment]
Usually at least one Windows and one Linux, so two. If one, then the default for Guacamole, even without a connection, is too send to the only VM that exists.

**Comment by eladiw** [comment]
so, just to make sure, if we have just 1 vm, the test is incorrect, as it will always be sent to that vm.
At least 2 VMs are required to verify the behavior

**Comment by marrobi** [comment]
I think that is correct, as with one never see the listing page.
