### ISSUE TITLE
Databricks workspace service

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#1725]
# Description
Research teams have requested the ability to use Databricks within a TRE workspace.

A workspace service needs to be created that deploys Databricks, the following work is likely a good starting point:

https://github.com/Azure-Samples/modern-data-warehouse-dataops/blob/main/single_tech_samples/databricks/sample2_enterprise_azure_databricks_environment/README.md

# Acceptance Criteria
- [x] Workspace Owner can deploy Databricks into a workspace
- [ ] Researchers can carry out steps TBD
- [x] Any required outbound connectivity is configured as part of the deployment and documented
- [x] Workspace service documented and PR to AzureTRE repository complete
- [x] Workspace configured with private link with option to expose internally/externally.

**Comment by wereinse** [comment]
@marrobi  I would delete the second acceptance criteria if we are not clear on the steps a researcher would take.

**Comment by marrobi** [comment]
@wereinse work is in progress to define them.

**Comment by promisinganuj** [comment]
Hi @marrobi , please feel free to assign it to me.

**Comment by guybartal** [comment]
Related stories:

- [Allow researchers to install packages using the Nexus shared service on Azure Databricks service clusters](https://github.com/microsoft/AzureTRE/issues/3120)
- [Allow TRE workspace owners manage permissions for researches and data engineers using the Unity Catalog in Azure Databricks workspace service](https://github.com/microsoft/AzureTRE/issues/3145)
