### ISSUE TITLE
Restructure Repository

### ISSUE THREAD

**Issue by martinpeck** [microsoft/AzureTRE#1752]
This repository has a large number of top level folders, and the purpose of these folders is either not obvious, or confused:

```
.
├── api_app
├── api_http_requests
├── core
├── devops
├── docs
├── e2e_tests
├── mkdocs-overrides
├── resource_processor
├── scripts
└── templates 
```

For example....

- there is a `core` folder, but there are aspects of `core` under `templates`
- the `resource_processor` is part of `core`, but not under `core`

It is not clear to newcomers what these folders are, where to find code related to a given area of the AzureTRE, or where to add new code.

This folder structure also doesn't lend itself to additional components being added. For example, if we were to add a UI to this project would is live under `core`, under a new folder named `ui`, or somewhere else? Would the end to end tests for that UI live in `e2e_tests`?

The tasks are therefore:

- [ ] Design and Approve a new Repo Folder Structure
- [ ] Move Existing Code into New Repo Folder Structure

**Comment by marrobi** [comment]
@tamirkamara @martinpeck think this should be closed or intend to move more things around?

**Comment by tamirkamara** [comment]
I also wish there were less top level folders. Like:
1. Move our 3 apps under the same root folder
2. Move core & devops under infra

But the most pressing thing for me was move core out of the templates. My other ideas aren't the important. 
@martinpeck WDYT? Should we close this?

**Comment by martinpeck** [comment]
Let's close it.
I'm closing it.
It's closed.
