### ISSUE TITLE
Initial auth based on AAD and OIDC flow

### ISSUE THREAD

**Issue by christoferlof** [microsoft/AzureTRE#1779]
Initial auth implementation to authenticate and authorize the user for the TRE instance landing page and for a specific Workspace.

* Initial MSAL implementation to authenticate the user and authorize the user for the TRE instance landing page.
* Initial auth against a specific workspace app i.e., the workspace landing page.

**Comment by damoodamoo** [comment]
initial auth is in place. Will add more tasks for RBAC and timed-out token management
