### ISSUE TITLE
.gitignore is ignoring all index.html files

### ISSUE THREAD

**Issue by martinpeck** [microsoft/AzureTRE#1799]
We have an entry in `.gitignore` that currently ignores *all* instances of `index.html`.

Unfortunately, this means that subfolders, such as the `ui` project, can't have instances of `index.html`
The fix is to ignore it in the root only (which is where we generate temp `index.html` files for letsencrypt) and if we need to add additional locations, add them explicitly.

**Comment by martinpeck** [comment]
cc @stuartleeks @damoodamoo 

@stuartleeks : can you confirm the suggested fix makes sense. I think you added the entry to .gitignore, so if you can think of a scenario where "exclude it only in the root" doesn't work, please shout.

**Comment by stuartleeks** [comment]
Yeah, my bad. I'm pretty sure that I only needed to ignore `index.html` in the repo root

**Comment by martinpeck** [comment]
Cool. No problem. Just wanted to double check the intent. Thanks @stuartleeks

**Comment by martinpeck** [comment]
PR #1800 fixed this, so closing
