### ISSUE TITLE
Apache Guacamole Virtual Desktop workspace service

### ISSUE THREAD

**Issue by christoferlof** [microsoft/AzureTRE#18]
## High-level requirements
- Virtual Desktops is in many cases the entry point into the TRE.
- Virtual Desktops can be configured to be access from the Internet over secure channel.
- Virtual Desktops can be configured to only be access from a private network.
- Ability to provision both Windows and Linux [Data Science Virtual Machines](https://azure.microsoft.com/en-us/services/virtual-machines/data-science-virtual-machines/).
   - Add additional base images in case the DSVM image is not desirable.
- Offer a defined set of Virtual Machine configurations, e.g. Small, Medium, Large and image.
- End-users should be able to connect to Virtual Desktops from Windows, Linux and Mac OSes.
- Ability to control how data is allowed to be moved from/to the VM and the connecting client
   - Clipboard: one-way / no-way / both-ways
   - Import and export data from the VM. 
- Ability to mount user scoped storage across VMs 
- Ability for end-user to start and stop VMs
- Scheduled start and stop of individual VMs
   - Whole workspace scheduling
- Ability to resize VM
- Updates management - Ability to pause or reschedule or apply updates to the VM.
- Ability to install licensed applications , e.g. Office 365 and Matlab applications 
- Note: Azure subscription tenant might not be the same as the tenant the researcher was authenticated by.

### Milestone 0.2

- [x] #26
- [x] Update this issue with additional tasks based on outcomes from above.
- [x] #490 
- [x] #501
- [x] #504
- [x] #500
- [x] #553 
- [x] #482 
- [x] #548
- [x] #561 
- [x] #483
- [x] #502
- [x] #503
- [x] #658 
- [x] #692

### Currently planned for milestone 0.3

- [x] #757 
- [x] #756 
- [x] #1137
- [x] #1096
- [x] #864
- [x] #848
- [x] #582
- [x] #1110
- [x] #1114
- [ ] #1148
- [x] #1386
- [x] #1241
- [x] #1200
- [x] #1729
- [x] #2087
- [x] #1724

**Comment by christoferlof** [comment]
Azure DevTest Labs provide some of the capabilities listed above, which we should look into in a bit more detail.

**Comment by christoferlof** [comment]
Apache Guacamole ticks several of the boxes also.

**Comment by iankelly-github** [comment]
The ATRE is a highly controlled environment, many 'apps' will need configuring at the 'user' profile level for them to operate properly. For example if a network proxy is used for auditing then the browser, git client, conda, PyCharm, Azure storage explorer will all need to be configured to use it. This can be a big headache users as each time they login to a system they need to remember these configuration changes. We should make this as automated as we can to reduce the cost of adoption.

**Comment by ktakeda1** [comment]
@iankelly-github good points. We should pre-install everything that a user might need into the VM and have this configured to work seamlessly within the Azure TRE Workspace. TRE Admins are probably the people to provide significant additional customisations. Basically the same experience as managed desktops, not what people love, but people do understand this model at least. We do want to make the TRE user experience great though, so anything we can do to provide flexibility within the constraints of the environment is fantastic!

**Comment by marrobi** [comment]
@iankelly-github  100%. This is an interesting challenge, one way we have approached this is by using common DNS names across workspaces. So have `packages.drednsname.com` resolve to the package "server" IP address. In certain occasions can "hijack" the DNS name of the public package repo, but SSL can become a challenge.

**Comment by marrobi** [comment]
The following diagram created with @christoferlof  might be a good starting point when thinking about user stories:
![image](https://user-images.githubusercontent.com/17089773/124632697-7d093b00-de7c-11eb-88cb-5294210305e1.png)

**Comment by iankelly-github** [comment]
I really like the diagram, very useful for brain-storming use cases. Should we capture all suggestions as issues or as 'ideas' under discussions?

**Comment by marrobi** [comment]
@iankelly-github If they are specific to virtual desktops/users creating compute along the lines of the diagram above, continue this chat. 

If they are separate feature requests, feel free to create issues and will add them to the backlog, refine, and prioritize.

**Comment by iankelly-github** [comment]
Thanks for clarifying @marrobi. I just reviewed this issues requirements again and most of the use cases that I immediately thought of are already included :-) The only additional use case would be 'create a snapshot my VM/disks'.

**Comment by marrobi** [comment]
It's worth noting that Azure Virtual Desktop will be a valid alternative to a custom virtual desktop solution for some customers. We should define this in a separate story.
