### ISSUE TITLE
Airlock Create request / Submit request API

### ISSUE THREAD

**Issue by joalmeid** [microsoft/AzureTRE#1832]
As a TRE developer,
I want to have the endpoints stubs for the Create and Submit Airlock request 
So that I can have the structure, and related capabilities for the implementation

**Acceptance Criteria**
- [ ] The stubs should include Create draft Airlock Request
- [ ] The stubs should include Submit Airlock Request
- [ ] The stubs should implement workspace authorization
- [ ] The stubs should include swagger doc

**Comment by eladiw** [comment]
merged with #1833
