### ISSUE TITLE
Orchestrator acts on threads found during the malware scanning

### ISSUE THREAD

**Issue by joalmeid** [microsoft/AzureTRE#1837]
As an Airlock Orchestrator in TRE
I want to be able to consume the Malware Scanning result event
So that I can verify a threat was found 

**Acceptance Criteria**
- [ ] The Airlock process status is updated to a terminal status: blocked
- [ ] Notify the requester, the airlock process terminated with status blocked 
- [ ] Malware Scanning results  are logged for auditing purpose

**Comment by eladiw** [comment]
merged into #1838
