### ISSUE TITLE
Airlock processor handles request approval

### ISSUE THREAD

**Issue by joalmeid** [microsoft/AzureTRE#1841]
As an Airlock processor in TRE
I want to be able to be able to consume and operate on the approval event 
So that requests approval are handled

**Acceptance Criteria**
- [ ] Data artifact are no longer available in `In-progress storage` (which is handled by #1963  )
- [ ] Data artifact are available in `Approved storage`
- [ ] Step result event is sent by the airlock processor when the data copy is done
- [ ] Data movement is logged for auditing purpose
- [ ] Data Steward can no longer access the `In-progress storage`
- [ ] A notification event with all the details sent to Event grid (to be consumed by #1964 )

**Comment by eladiw** [comment]
Fixed by #2091
