### ISSUE TITLE
Resource processor hangs as out of memory

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#1884]
The resource processor stops responding.

When go onto the serial console shows:

```
[  940.705287] Out of memory: Killed process 1782 (python) total-vm:3987056kB, anon-rss:3572796kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:7140kB oom_score_adj:0
[ 3088.285942] Out of memory: Killed process 3234 (python) total-vm:4136568kB, anon-rss:3574636kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:7164kB oom_score_adj:0
```

@tanya-borisova @martinpeck any chance you can look into this, I think it could be related to the logging, but might be completely wrong.

**Comment by martinpeck** [comment]
I'll take a quick look

**Comment by marrobi** [comment]
Apologies, this was down to some DNS zones missing on my deployment causing logs to back up.

This has been resolved by redeploying the AMPLS resources.
