### ISSUE TITLE
[Task] Create a VM runner for Porter

### ISSUE THREAD

**Issue by deniscep** [microsoft/AzureTRE#189]
Create a base VM setup that should:

- Be able to pull and install Porter bundle
- Be able to communicate with resources inside of VNET
- Be able to use MSI for authentication
- On startup run the function app that listens to service bus messages (resource processor) and invokes Porter

**Comment by christoferlof** [comment]
Adding a link to #149 since this task is a consequence of that issue

**Comment by christoferlof** [comment]
#149 resolved, continuing with container instances for now, closing this one.
