### ISSUE TITLE
Jumpbox VM OS disk is not tagged as core service

### ISSUE THREAD

**Issue by guybartal** [microsoft/AzureTRE#1915]
**Describe the bug**
Jumpbox VM OS disk is not tagged as core service, os_disk doesn't support tags in terraform file:

![image](https://user-images.githubusercontent.com/3179107/170229595-8851cb12-6160-44f1-b500-5ab86c4ce90d.png)
[terraform registry - windows vm docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine)

**Related issue**
#1888 

**Steps to reproduce**

1. Deploy TRE Instance
1. Go to Azure portal, search for vm-dsk-[your_tre_id] resource
1. The resource won't have the needed tags (tre_id, and tre_core_service_id)

**Comment by tamirkamara** [comment]
@guybartal Is this resolved already?

**Comment by guybartal** [comment]
> @guybartal Is this resolved already?

Terraform doesn't support tagging for os_disk:
[https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine#argument-reference](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine#argument-reference)
