### ISSUE TITLE
Remove the need for Guacamole to read DOCKER_REGISTRY_SERVER_PASSWORD from App Settings

### ISSUE THREAD

**Issue by ross-p-smith** [microsoft/AzureTRE#1940]
## Description

As a TRE Workspace Owner
I do not want read secrets, like DOCKER_REGISTRY_SERVER_PASSWORD, from App Settings
So that I secure any secrets of TRE

## Acceptance criteria

- [ ] Guacamole App Service setting for DOCKER_REGISTRY_SERVER_PASSWORD is removed
- [ ] Search for other occurrences of this

**Comment by tamirkamara** [comment]
I would say that we shouldn't use it at all since use can have all access authentication with a managed identity

**Comment by tamirkamara** [comment]
Was done as part of #2233
