### ISSUE TITLE
Deleting Guacamole VM results in KeyVault purge protection error

### ISSUE THREAD

**Issue by ross-p-smith** [microsoft/AzureTRE#1951]
**Describe the bug**
Unable to delete a Guacamole VM because of the key vault purge protection settings

**Steps to reproduce**

1. Create a tre-service-guacamole-windowsvm
1. Delete it from the Swagger Endpoint
.

Error context message = \x1b[31m╷\x1b[0m\x1b[0m \x1b[31m│\x1b[0m \x1b[0m\x1b[1m\x1b[31mError: \x1b[0m\x1b[0m\x1b[1mpurging of Secret "windowsvm7cd6-admin-credentials" (Key Vault "https://xxxxxx-ws-765b.vault.azure.net/") : keyvault.BaseClient#PurgeDeletedSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Operation \\"purge\\" is not allowed because purge protection is enabled for this vault. Key Vault service will automatically purge it after the retention period has passed

**Comment by marrobi** [comment]
@ross-p-smith  are we close to resolving this? Fresh deploy and bundles this week.
