### ISSUE TITLE
Tag Innereye workspace template in Terraform

### ISSUE THREAD

**Issue by joalmeid** [microsoft/AzureTRE#1960]
As a TRE developer,
I want to tag Innereye Workspace template 
So that this template include information for TRE id and TRE Workspace id

**Acceptance Criteria**
- [ ] Have `tre_id` tag in the Innereye Workspace template 
- [ ] Have `tre_workspace_id` tag in the Innereye Workspace template

**Comment by guybartal** [comment]
closing this story as there's nothing to tag here, the workspace is based on base workspace which was tagged in #1970  and innereye workspace service which was tagged in #1894
