### ISSUE TITLE
Airlock - create notification mechanism

### ISSUE THREAD

**Issue by eladiw** [microsoft/AzureTRE#1964]
## Description

As a TRE developer
I want to be able to receive notifications event from the SB and send notifications based on the included data
So that Data stewards or researchers can be notified on changes to the request

## Acceptance criteria

- [ ] Mechanism is written is a separate component (logic app, function app, etc)
- [ ] receive the event and issue an email
- [ ] Includes the TF deployment scripts

**Comment by tamirkamara** [comment]
Duplicate.
