### ISSUE TITLE
Remove App-Service based (V1) Nexus

### ISSUE THREAD

**Issue by jjgriff93** [microsoft/AzureTRE#1981]
## Description

Currently there are two versions of Nexus in the shared services templates to allow for graceful migration from V1 to V2 without breaking changes. After a grace period "V1" should be removed and there should be a single Nexus shared service within the codebase 

## Acceptance criteria

- [ ] Removal of ./sonatype-nexus shared servicee template
- [ ] No references/dependencies corresponding to old Nexus version
- [ ] User resources no longer accept versions of Nexus specified as a template parameter and default to the Nexus vm (V2) service endpoint

**Comment by martinpeck** [comment]
@marrobi 

Can you give your thoughts on this. We now have 2 nexus services:

- the original one, that doesn't support docker
- the new VM based on, that supports docker

At present, the VM based service is not the default (it's opt in), but it needs to become the default soon.
Additionally, we won't be updating/testing/supporting the old service.

- How do you want to message for people with existing deployments?
- What level of "migration" (if any) do you want (can't promise this will be possible, but at very least it needs documenting)
- We plan on removing the old code from the repo. Just an FYI.

**Comment by marrobi** [comment]
@martinpeck  I spoke to @jjgriff93 about this yesterday. 

Suggest we look at changing the default imminently.

Existing deployments will continue to work we don't think we need to do any migration as the old nexus can continue to exist if is already deployed. However we do need to be clear about how this affects user resource templates. We need to think about does this sort of thing go into (or linked to in) release notes moving forward?

Can we leave the legacy code a little longer - if people are deploying it from the repo and pull from upstream it could break their pipelines, so lets give it some time, how long, not sure.

**Comment by marrobi** [comment]
@jjgriff93  agree.
