### ISSUE TITLE
Block outbound connectivity

### ISSUE THREAD

**Issue by eladiw** [microsoft/AzureTRE#2033]
**Describe the bug**
Private endpoint traffic does not obey the inbound nsg rules.
As a result traffic is allowed, for example, from the TRE API over private endpoint to a ws storage account.

To mitigate this, we need to BLOCK OUTBOUND connectivity using nsg from all subnets except the RP subnet into the ws vnet
outbound traffic over private endpoints does obey the outbound nsg rules

**Steps to reproduce**

1. deploy tre
1. deploy a base ws
1. update the tre api app to create a storage container in any storage in the ws storages (which has private endpoint)
1. it will work (where it should have failed)

**Comment by tamirkamara** [comment]
Now there's a feature that NSG work for private endpoint. So the right this is in https://github.com/microsoft/AzureTRE/issues/807
