### ISSUE TITLE
Copy blobs without sas tokens

### ISSUE THREAD

**Issue by eladiw** [microsoft/AzureTRE#2034]
**Describe the bug**
Today, in the Airlock processor, we use the SAS token for the source blob in order to copy the blob.
There might be an option to copy the containers without issuing a sas token. This issue is to see if possible and fix if it is.

**Comment by tamirkamara** [comment]
It looks like this isn't possible. Despite some operations are allowed to use AD AuthN, copy between accounts doesn't work with python sdk or azure cli. The error is:

> Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
> RequestId:3ff69ae2-501e-002d-7cc1-a0e67a000000
> Time:2022-07-26T07:29:19.2951512Z
> ErrorCode:CannotVerifyCopySource

Surprisingly it DOES work when using azcopy. I've verified the identity used has no permission to get the account keys (and hence can't generate a SAS internally), and that it doesn't download the blob and re-uploads it to the destination.

**Comment by tamirkamara** [comment]
https://github.com/Azure/azure-sdk-for-python/issues/25478

**Comment by tamirkamara** [comment]
Given the SDK/service limitations mentioned in the issue above this is not possible for us currently.
