### ISSUE TITLE
Error 'Invalid option: --swaggerui-redirecturl' when running 'make auth'

### ISSUE THREAD

**Issue by stuartleeks** [microsoft/AzureTRE#2037]
Remember to label the issue with the appropriate area, and also assign it to yourself if you plan to work on the issue in the near future.

**Describe the bug**
Error `Invalid option: --swaggerui-redirecturl.` when running `make auth`

**Steps to reproduce**

1. Set up a fresh set of env files
1. Run `make auth`

**Comment by stuartleeks** [comment]
It looks like [this commit](https://github.com/microsoft/AzureTRE/commit/3744b5f623b3c3e794e319ba761ba23943ebea5d) removed/renamed the `--swagger-redirecturl` option in `aad-app-reg.sh`

**Comment by marrobi** [comment]
I think this was changed to `--tre-url`, are there references to ` --swaggerui-redirecturl` left in the repo?

If so need to be changed to the former, and remove any path after the root domain. I thought I had picked these up, apologies if missed one, maybe got lost in the merge as did test numerous times.

@damoodamoo you concur?
