### ISSUE TITLE
[airlock] Container creation and retrieval design

### ISSUE THREAD

**Issue by LizaShak** [microsoft/AzureTRE#2042]
# Container Creation 

- When researcher submits a file (import/export) and on each file status update - storage container will be created in a relevant storage account  (this is as oppose to creating all containers ahead).
- The creation of storage container will be Airlock Processor responsibility
- Airlock Processor will create relevant container upon event consumption.
- Container name will be the airlock request id 
![Untitled](https://user-images.githubusercontent.com/42377481/173770848-2f398b49-f53e-4ad4-a375-0425be6d21a6.png)

# Container Retrieval

- Container retrieval will be done through a dedicated API
- The response will contain a container url with SAS token and will allow the user to download/import the file.
-   To generate the SAS token for the relevant container: 
    1. The token generation will be done within the API app upon API request.
    2. To generate the SAS token for the container we will need the access key to the storage account
    3. To retrieve the storage account key we will use the storage management. To allow it to retrieve the account key we will need to add the API client a role assignment of [Reader and Data Access](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#reader-and-data-access) (which is the least permissions to retrieve it and has no write permissions). This role will be added as part of the terraform script.

In this solution the user will always get a valid token and we don't store tokens or keys anywhere . 

# Container Retrieval Alternatives

We have considered a few alternatives but found them less secure or less user friendly.

## Alternative 1: Store SAS keys in DB

Once the container is created by the Airlock Processor it can also generate a SAS token for it and return it in event. The API reads this event and stores the token in the cosmos db.
In this alternative we have a few downsides:
1. SAS token might be expired when the user retrieves them, in this case we will need an async process of token refresh.
2. The major downside is that we store tokens in DB which is not secure and not a good practice. 
The upside in this solution is that all the container logic is done by the Airlock Processor.

## Alternative 2: Store SAS keys in KV

Once the container is created by the Airlock Processor it can also generate a SAS token for it and store it in KV.
In this alternative  SAS token might be expired when the user retrieves them, in this case we will need an **async** process of token refresh. And the user will have to wait and do kind of polling to get the new one.

**Comment by tamirkamara** [comment]
Closing as approved.
