### ISSUE TITLE
Add code coverage to Azure TRE API unit tests and PR checks

### ISSUE THREAD

**Issue by guybartal** [microsoft/AzureTRE#2056]
**Is your feature request related to a problem? Please describe.**
Azure TRE API unit tests don't collect code coverage.

**Describe the solution you'd like**
Add code coverage to unit tests and quality gate on PR.
Provide a way to display coverage in PyCharm.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by tamirkamara** [comment]
A duplicate of #194
