### ISSUE TITLE
UI: Properties with complex types rendered as [Object]

### ISSUE THREAD

**Issue by damoodamoo** [microsoft/AzureTRE#2079]
Now some properties are real complex types rather than just strings, the properties panel needs to reflect this and iterate the object to show the real value rather than `[object]`

![image](https://user-images.githubusercontent.com/35696285/174811295-2edd26c4-f788-4978-a3b4-7b63ee33d480.png)

**Comment by damoodamoo** [comment]
^ this is in the details tab. We can hide all complex values in the details tab if we want, but if i'm looking for the details I think i'd want to see this?

**Comment by marrobi** [comment]
I can't think any reason a  researcher would want to know the redirect URLs, or many of the other fields. As an admin/dev, to debug, maybe... but they could go to cosmos.

We need a UI Schema for the forms, to sort ordering, is it possible to have a UI schema for forms, cards, and details tab?

**Comment by damoodamoo** [comment]
Yea the UI schema for the form is still to-do, we could look to extend that to include a list of props to show on the properties panel, and then use the template to drive what we see on those panels. 

The card is maybe a bit trickier due to the space available.

**Comment by marrobi** [comment]
For the card, the things that spring to mind are VM related, like CPU cores, RAM etc. (actually a single property?).
