### ISSUE TITLE
Show placeholder if no templates registered for resource type

### ISSUE THREAD

**Issue by jjgriff93** [microsoft/AzureTRE#2080]
Currently, if you have no registered templates for a resource type and go into the create resource panel for that type, it will just show a blank area. 

We should have a placeholder explaining that you need to publish and register templates for them to appear in the create menu, and can also direct users to the appropriate documentation pages for this process.

**Comment by marrobi** [comment]
Or should the new resource button just be hidden? In the case of user resources, might be there are no templates.

**Comment by jjgriff93** [comment]
That would require doing a fetch of the templates wherever the button is displayed, instead of when it is clicked to open the panel; plus I think its a bit more user friendly to explicitly show that there are no templates registered so they're not wondering if they don't have permission to create new or other reasons why the button isn't appearing

**Comment by jjgriff93** [comment]
PR for approval #2428
