### ISSUE TITLE
Need to handle reset of password for Guacamole user resources

### ISSUE THREAD

**Issue by martinpeck** [microsoft/AzureTRE#2087]
At present the VM password is created and stored in Key Vault This is likely to expire at some point in the future, or the local password may be reset by the user meaning the stored password an actual password differ.

A user needs to be able to reset their password in these scenarios.

**Comment by marrobi** [comment]
This could be a reset credentials custom action?

**Comment by jjgriff93** [comment]
@martinpeck @marrobi currently custom actions don't accept any parameters (i.e. a new password string) - I'm not aware of any reset method for a VM that doesn't mean entering a new replacement password there and then be it in CLI/PS or portal, are you aware of any? Happy to implement parameters in custom actions as a dependency, just wanted to point out the scope of this might be bigger than initially thought

**Comment by marrobi** [comment]
Can a new password not be generated and the VM and KV updated?

The password is created in the first place by TF, not by user input.

Maybe taint the secret and run an TD apply?

**Comment by jjgriff93** [comment]
Right I'm with you, yes that should work!
