### ISSUE TITLE
App packages shared service

### ISSUE THREAD

**Issue by christoferlof** [microsoft/AzureTRE#21]
Researchers will need all kinds of packages/libraries when working with data. All packages within a feed will be accessable.

Requirements:
- Support as many package feeds types as possible. 
- It should be possible to add a new package feed.
- All package feeds should be read-only, meaning publishing new package must not be possible.
- System package managers like apt-get and winget. 
- Code/SDK package mangers like PyPi, Conda, NuGet etc.

Implementation:
- #437

**Comment by marrobi** [comment]
https://www.sonatype.com/nexus/repository-oss-download can help solve some of these challenges.
