### ISSUE TITLE
UI Prompts for client app reg details when AUTO_WORKSPACE_APP_REGISTRATION=true

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#2112]
AUTO_WORKSPACE_APP_REGISTRATION=true

<img width="578" alt="image" src="https://user-images.githubusercontent.com/17089773/175533026-dfb55353-b221-407a-ab1b-c2b866184982.png">

Believe this line: ```    azure_ad_properties = read_schema('azuread.json')``` in https://github.com/marrobi/AzureTRE/blob/main/api_app/services/schema_service.py#L53

needs to be conditional.

@ross-p-smith do you agree?

**Comment by tamirkamara** [comment]
1. I don't know exactly what it's doing but looks like it validates the app somehow. If you use another guid it will still return an error: 
`Unable to get app info for app: 4509bf1c-0000-0000-0000-6bbae15fb00c`
2. It doesn't look like this param is wired to anything but the auth-setup scripts. Are we saying this is a system wide decision - either the tre is auto-aad or not?

**Comment by tamirkamara** [comment]
@marrobi, probably this will help you as it has for me:
https://github.com/marrobi/AzureTRE/blob/main/api_app/db/repositories/workspaces.py#L101

but I think we need to discuss this a bit further...

**Comment by martinpeck** [comment]
cc @ross-p-smith

**Comment by ross-p-smith** [comment]
I think that it would be nice to have conditional UI elements. We could also do the same with address_space too. Currently we are not using AUTO_WORKSPACE_APP_REGISTRATION at run time. It's used in make_auth. If we were to check this then it would prevent me from creating a workspace of each type in the same instance.

**Comment by tamirkamara** [comment]
The UI now has a default for the auto-create option and doesn't ask for the id/secret.
