### ISSUE TITLE
When registering bundles using make bundle-register, get a 500 error

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#2115]
**Describe the bug**
When using `make register-bundle` I get a 500 error. Looking at the logs this is:

```
2022-06-24T15:56:29.453684692Z raise InvalidAudienceError("Invalid audience")
2022-06-24T15:56:29.453689492Z jwt.exceptions.InvalidAudienceError: Invalid audience
```

I ran `make auth` earlier today and copied the variables into my `.env` files.

The audience in my access token is equal to my `API_CLIENT_ID`:   `"aud": "7f0e99c9-5c24-4699-9e2b-90eccc0e25ac",` This matches what is in KeyVault. 

In addition the API should return an authentication error, rather than generic 500 error.

**Comment by ross-p-smith** [comment]
@marrobi - is this the one where you had 2 variables in your .env?

**Comment by marrobi** [comment]
@ross-p-smith There were two issues, one was admin consent, one was the env vars - so my bad. 

The error returned still needs to be better.

**Comment by ross-p-smith** [comment]
@marrobi - I suggest we leave #1674 open as I know where that one is. `make register-bundle` is just calling the API. The admin consent one is #2086.

Or as a minimum - move this into Release 0.4 as that is where the duplicate is.
