### ISSUE TITLE
Unsupported param error in Gitea shared service

### ISSUE THREAD

**Issue by tamirkamara** [microsoft/AzureTRE#2137]
**Describe the bug**
1. Deployments of gitea shared service are failed on the main environment, probably the upgrade action of them (not 100% sure).
2. As a side note - not sure how the deployment succeeds if this step fails...

│ Error: Unsupported value for raw output
│
│ The -raw option only supports strings, numbers, and boolean values, but
│ output value "gitea_allowed_fqdns_list" is list of string.
│
│ Use the -json option for machine-readable representations of output values
│ that have complex types.
╵
╷
│ Error: Unsupported value for raw output
│
│ The -raw option only supports strings, numbers, and boolean values, but
│ output value "address_prefixes" is list of string.
│
│ Use the -json option for machine-readable representations of output values
│ that have complex types.
╵
Error: 2 errors occurred:
* couldn't run command /usr/bin/terraform terraform output -raw gitea_allowed_fqdns_list: exit status 1
* couldn't run command /usr/bin/terraform terraform output -raw address_prefixes: exit status 1

Error: mixin execution failed: exit status 1
Error: 1 error occurred:
* container exit code: 1, message: <nil>. fetching outputs failed: error copying outputs from container: Error: No such container:path: f658703085416a24a4cfeadde6b1480e5e0b79ad89c1c3e890aedcd46d261d6c:/cnab/app/outputs

**Steps to reproduce**
You can see errors like these but running this app insights query:
`
traces 
| where cloud_RoleName == "runner.py"
| where message has "unsupported"
| where severityLevel >1
| order by timestamp desc
`

**Comment by martinpeck** [comment]
@damoodamoo can you take a look at this please? Shout for context
