### ISSUE TITLE
Cannot delete stopped VM - "Cannot modify extensions in the VM when the VM is not running."

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#2138]
**Describe the bug**
Cannot delete a disabled/stopped VM.

**Steps to reproduce**

1. Create VM
1. Disable VM
1. Delete VM

```
Get the error: .VirtualMachineExtensionsClient#Delete: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="OperationNotAllowed" Message="Cannot modify extensions in the VM when the VM is not running.
```

**Comment by martinpeck** [comment]
This was performed via the UI
This has been seen to work previously (recently)

**Comment by martinpeck** [comment]
@tamirkamara  to take a look

**Comment by martinpeck** [comment]
Need to confirm that when you delete a VM is uses the version of the bundle that it was installed with

**Comment by marrobi** [comment]
If we added `terraform state rm module.vm.azurerm_virtual_machine_extension.init_win_vm_extension[0]` (as appropriate) as a pre step in porter think this would resolve this?

**Comment by stuartleeks** [comment]
That seems like a plan to me - we would only add this step in the `delete` action where we're going to clean up the VM anyway!

We could consider listing the terraform state and running through a grep for `.azurerm_virtual_machine_extension.` and then running the `terraform state rm` for any matches. That way we won't have to remember to update it if we rename the resource or add new extensions.
