### ISSUE TITLE
Cascade disable and delete operations

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#2152]
When a workspace is disabled all child workspace services and user resources should be disabled.

- [ ] As a Workspace Owner I want to disable a workspace service, and all child user resources get disabled.
- [ ] As a TRE Administrator I want to disable a workspace, and all workspace services get disabled.

The same should be the case for deletion.

**Comment by damoodamoo** [comment]
When we come to this we should talk about what it means to disable a resource too - since currently we're just setting a flag in Cosmos + running a patch.

**Comment by marrobi** [comment]
Discussed this and need to ensure that child resources delete/disable prior to their parent. At the moment it is understood they would attempt to operate in parallel.

Should parent, e.g. workspace service, operations, be blocked until child, e.g. user resource, operations are complete?

**Comment by damoodamoo** [comment]
I think they would need to - especially when a workspace deletes as it will delete the RG could leave other items like network connections / firewall rules etc 'orphaned' ?

**Comment by tamirkamara** [comment]
I don't think they would be orphane because either the parent resource would delete or its contained children or various action would fail (far more likely).
For example, deleting the workspace while it's services are still being deleted will fail because it will try to delete the RG which will not be empty - that is a terraform error.

**Comment by damoodamoo** [comment]
In short I think we'd have to traverse to the user resources, delete them all, then go up and delete the workspace services, then go up and delete the workspace, in order.

**Comment by marrobi** [comment]
Create a set of operations, similar to https://github.com/microsoft/AzureTRE/blob/c7da5d3bb553fd02d72cd07662e67815f86bfb05/api_app/db/repositories/operations.py#L48 ?

**Comment by anatbal** [comment]
The proposed solution for implementing a disable/delete cascade feature utilizes two key assumptions:
1. The DELETE and PATCH operations already exist for all resources, including ws, ws-service, and user resources, eliminating the need to add a new API endpoint.
2. The resources' hierarchy can be derived from the Resources container (in cosmos) in the form of a dependencies DAG.

The solution itself involves the following steps:

> 
> 1. Retrieving the dependencies graph for the required resource.
> 2. Verifying that all dependent resources are disabled before proceeding with the deletion operation. (Only for deletion step)
> 3. Constructing an operation object with steps in a specific order, based on the dependencies constraints and tree depth.
> 4. Saving the operation in cosmos and initiating the processing of the first step.
> 5. Processing the next step in the operation upon receiving confirmation of completion of the previous step.

It should be noted that the solution also supports retries.
Optional: resources on the same tree depth can be executed in parallel for added efficiency.
