### ISSUE TITLE
API errors about missing cosmos resource to update

### ISSUE THREAD

**Issue by tamirkamara** [microsoft/AzureTRE#2167]
**Describe the bug**
On June 27th the API has started to output messages like this:
Service bus message refers to resource id = 09342723-e3dd-4821-830a-f570d3602821 which does not exist

Nothing has changed in the message text or exception logging code so this is most probably something new need investigating.

Logs can be fetched from the main environment with:
```kql
traces
| where cloud_RoleName == "uvicorn"
| where message startswith "Service bus message refers to resource id"
| order by timestamp desc
```

**Comment by ross-p-smith** [comment]
This comes from this const DEPLOYMENT_STATUS_ID_NOT_FOUND when the EntityDoesNotExist in /workspaces/AzureTRE/api_app/service_bus/deployment_status_update.py

**Comment by ross-p-smith** [comment]
I've tracked this down to occurring when a multi stage pipeline creates a Guacamole Workspace Service when you use an "auto_create" workspace. An EntityDoesNotExist exception is raised within operations.get_operation_by_id. Do you have some time @damoodamoo to go through this?
