### ISSUE TITLE
Auto generated workspace app reg is missing admin consent

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#2191]
<img width="731" alt="image" src="https://user-images.githubusercontent.com/17089773/177122861-b4adc2c0-0809-4a47-ad94-93b778d299db.png">

**Comment by ross-p-smith** [comment]
Yes - this doesn't have it - if you create the workspace with the `make auth` command then it is Granted. I'm yet to see an actual side effect though as you are not required to Admin Consent these permissions.
