### ISSUE TITLE
AD app registration created when new workspace is created

### ISSUE THREAD

**Issue by christoferlof** [microsoft/AzureTRE#220]
## Description

As a TRE administrator
I want to create workspaces without providing identity provider parameters such as application id
So that I don't have to bother our cloud admin asking her to create the application registration for me first.

## Acceptance criteria

- [x] #1706
- [x] #211 
- [x] #1797
- [x] #1928
- [x] App registration deleted when the workspace is deleted (Terraform is a good option for creation/deletion)
- [ ] Documentation updated with environment variable and permissions for automatic app registration
- [x] #831
- [x] #1716

## Design 

Workspace templates must only change resources it itself creates. Changes done to management/core services such as Azure Firewall, Shared Service such as source mirror, Azure Active Directory etc. must be delegated.

Support for alternative identity providers other than Azure Active Directory for application registration must also be supported. It should be configurable which identity provider is used at TRE creation time (not part of this Story). Meaning the same identity provider will be used in all Workspaces within the same TRE instance.

Therefore, the responsible for creating application registrations is implemented into the TRE management API.

### Permissions

To be able to automatically create app registration the [Application.ReadWrite.All](https://docs.microsoft.com/en-us/graph/permissions-reference#delegated-permissions-4) permission must be granted to the TRE management API Service Principal

Azure AD is managed via the Microsoft Graph API.

### Changes to setup 

A new environment variable `auto_app_registration = [TRUE|FALSE] (default=FALSE)` indication if automatic app registration is enabled when setting up a TRE instance.
If the environment variable is set to true, then the Application.ReadWrite.All permission must be granted.

### Changes to the TRE API

Currently the following parameters are required in the REST API to create a Workspace

```JSON
{
  "workspaceType": "tre-workspace-vanilla",
  "properties": {
    "display_name": "the workspace display name",
    "description": "workspace description",
    "client_id": "9d52b04f-89cf-47b4-868a-e12be7133b36"
  }
}
```

The `app_id` should be made optional, but only if the `auto_app_registration` variable is set to TRUE.

The abstraction over identity provider is implemented in the [AccessService](https://github.com/microsoft/AzureTRE/blob/develop/management_api_app/services/access_service.py) class. This class must be extended to include an application registration method.

Incorporate and reuse as much as possible from the [manual app registration script](https://github.com/microsoft/AzureTRE/blob/develop/scripts/workspace-app-reg.py).

Use the AAD API to create the app registration ([Create application - Microsoft Graph v1.0 | Microsoft Docs](https://docs.microsoft.com/en-us/graph/api/application-post-applications?view=graph-rest-1.0&tabs=http))

**Comment by marrobi** [comment]
@Lybecker Thanks/ The bigger challenge is around how we create the app registrations and delete them. This needs to be done in a clean way otherwise we end up with lots of "orphaned" Azure AD resources.

I actually think the easiest way is for cases where we need it automatically generating we have an auth provider json schema that doesn't require an app registration ID - then the user isn't prompted. We extend the base workspace with terraform using the Azure AD TF provider to add the app registration, and using the bundle output write back mechanism write the `app_id` back into the cosmos database. We already have TF to do this in another repo.

Thoughts?

**Comment by Lybecker** [comment]
Ideally the Service Principal executing the Porter bundle executor (Resource Processor) should have as limited permissions as possible and only touch Azure resources within the Workspace. I see these benefits:

- Separation of concerns - Workspace Templates only changes _their own Azure resources_
- Security review of Workspace Templates is easier
- Workspace Templates can be reused with different Identity Providers
- Potentially all the Workspaces could be in a separate subscription. Then we contributor rights to the Resource Processor only has permissions to modify anything Workspace related.

The system should not leave orphaned Azure resources.
