### ISSUE TITLE
Clicking Go to resource after creating doesn't always go to correct resource

### ISSUE THREAD

**Issue by jjgriff93** [microsoft/AzureTRE#2210]
**Describe the bug**
When creating a VM (or other resources), in parallel to another resource either being deployed or updated (i.e. performing an action on another VM and waiting for completion), after submitting the new VM to deploy and clicking the 'Go to resource' button, if the other resource action completes or updates at the same time or just after submitting the new Vm for deployment, clicking the button will take you to that resource instead of the one you've just created.

**Comment by marrobi** [comment]
@jjgriff93 is this still an issue? I've put on the backlog, if more urgent then we can discuss.

**Comment by damoodamoo** [comment]
Feels possibly related to #2210
