### ISSUE TITLE
Unable to deploy second virtual desktop service into a workspace

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#2212]
I wanted to deploy two Guacamole services in the same workspace, this is unusual, but used to work. I now get:

> Resource Id: 40c409d6-a575-46b9-b9bb-1e30ce619038
Resource Path: /workspaces/9a0741d5-4848-4f54-8de0-9c944b20034e/workspace-services/40c409d6-a575-46b9-b9bb-1e30ce619038
Resource Version: 0
Status: deployment_failed
Action: install
Message: Multi step pipeline failed on step main
Created: Wed Jul 06 2022 13:24:54 GMT+0100 (12 minutes ago)
Updated: Wed Jul 06 2022 13:30:04 GMT+0100 (7 minutes ago)
User: Marcus Robinson

**Comment by ross-p-smith** [comment]
Just out of interest - why would you do this?

**Comment by tamirkamara** [comment]
@marrobi, I don't think we support it. At least at the TF level we have items that are at the workspace level and not the workspace service. Not sure how will that work with the KV secrets etc.
Is this a valid use-case?

**Comment by marrobi** [comment]
It used to work. There is potentially the need to expose one externally, one internally with different policies.

Everything should have the workspace service ID in, hence be unique?

**Comment by damoodamoo** [comment]
I can't think of anything from my perspective that would prevent it - if it's something we need to support then I can take a look?

**Comment by tamirkamara** [comment]
I tried it today and it worked. I think a change I did a couple of weeks ago supports this now.
