### ISSUE TITLE
[Story] Reorganize templates in repository

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#226]
## Description

As a TRE developer I want to have a straightforward repository structure so that I can develop efficiently.

## Proposal

At present we have a `/templates` and a `/workspaces` folder. This is confusing.

## Acceptance criteria

- [x] Move to the following folder structure

  `/templates`
  `/templates/core`
  `/templates/workspaces`
  `/templates/workspace_services`
  `/templates/workspace_services/[service_name]/user_resources`
  `/templates/shared_services`

- [x] Rename the `vanilla` workspace to `base` throughout as this is a prescriptive base template that is needed for services to work and should be extended for new workspace templates.

- [x] Fix links/references

**Comment by Lybecker** [comment]
We also have /devops/terraform - I found that a bit confusing when going through the quickstart.

I suggest we come up with another name than core. If we are storing shared services there, then call it that

**Comment by Lybecker** [comment]
We also have /devops/terraform - I found that a bit confusing when going through the quickstart.

I suggest we come up with another name than core. Is it the shared workspace?

**Comment by tamirkamara** [comment]
In various places we refer to core as mgmt...

**Comment by marrobi** [comment]
core and devops maybe?

**Comment by Lybecker** [comment]
We have TF/IaC files in these folders

- devops
- templates
- workspaces

It is confusing especially as we use the term Workspace Templates.

In my mind there are two logical areas:

- Infrastructure to setup the Core services (also referred to a mgmt as @tamirkamara points out)
- Workspace Templates

The folder structure should mimic this logical separation. Then we should also get rid of the `devops` folder and place it under `infrastructure`.

While we are at it, we should move the `resource_processor`, `management_api_app` and `e2e_tests` under a `src `folder

**Comment by marrobi** [comment]
@Lybecker as discussed core and management re different so don't agree with the above. There is also infrastructure throughout the repository.

As a first step lets move the templates all into one place - that was the purpose of this story. I will add some acceptance criteria, and if we need another iteration later, we can.
