### ISSUE TITLE
Error using the make auth command 

### ISSUE THREAD

**Issue by UserSck** [microsoft/AzureTRE#2260]
I have the following error:

az: error: unrecognized arguments: --only-show-errors
usage: az [-h] [--verbose] [--debug]
          [--output {json,jsonc,table,tsv,yaml,none}] [--query JMESPATH]
          {account} ...
Please run az login -t <tenant> --allow-no-subscriptions
make: *** [Makefile:428: auth] Error 1

**Comment by ross-p-smith** [comment]
What version of az cli are you using? 
Are you doing this through a devcontainer?
