### ISSUE TITLE
API endpoint to get (list) airlock requests

### ISSUE THREAD

**Issue by eladiw** [microsoft/AzureTRE#2271]
## Description

As a TRE ws owner
I want to list airlock requests in the workspace
So that I can see import/export activity

## Acceptance criteria

- [ ] A new endpoint returns a list of airlock requests in the workspace

**Comment by tanya-borisova** [comment]
Potentially, "waiting for a reviewer" is an implementation detail (a concrete filter). We may just want to get all requests that a Researcher issued. A WO could get all requests in a workspace. We probably want to provide a filter for all these cases. 

The fields that are returned would depend on the role. 

@tamirkamara  to provide more details
