### ISSUE TITLE
Airlock - Notification event should be sent by the airlock processor

### ISSUE THREAD

**Issue by eladiw** [microsoft/AzureTRE#2273]
## Description

As a TRE  Developer
I want to send the airlock notifications event from the airlock processor rather than from the TRE api
So that it will be sent from a more suitable location

## Acceptance criteria

- [ ] any recipients data should be retrieved by the airlock processor
- [ ] Sending the notification event should be initiated by the processor
- [ ] TRE api should not be aware on  these events

**Comment by LizaShak** [comment]
Decided not to move it to the Airlock processor, created different issue instead: https://github.com/microsoft/AzureTRE/issues/2457
It summarizes the decision that was made, what options were considered
