### ISSUE TITLE
Airlock - Handle malware scanning failed scans

### ISSUE THREAD

**Issue by eladiw** [microsoft/AzureTRE#2274]
## Description

As a TRE  Developer
I want to be handle malware failed scans and move the request to failed
So that the researcher knows the request failed

## Acceptance criteria

- [ ] Failed to scan for any reason should be catched by the airlock processor (e.g. password protected file / encrypted)
- [ ] move the request to failed state

**Comment by tanya-borisova** [comment]
The issue here is how to know there was a failed scan. E.g. password protected zip might cause a problem

**Comment by yuvalyaron** [comment]
Password protected zip files result in "blocked by scanner" status - we should add the output of the the scanner to the "errorMessage" field that we have in AirlockRequest (we should rename errorMessage to statusMessage to make it more generic).

File that are too big (>2GiB) are currently ignored by the scanner, this should be addressed by the malware scanner team, as we currently don't have any indication that the request is stuck.
