### ISSUE TITLE
Airlock - Add get reviews endpoint

### ISSUE THREAD

**Issue by eladiw** [microsoft/AzureTRE#2276]
## Description

As a TRE Developer
I want to add the GET reviews endpoint
So that users can ask for the given reviews and see why a request was denied/approved

## Acceptance criteria

- [ ] add missing endpoint
- [ ] all reviews / steps of a given requests are returned
- [ ] only for authorized roles
- [ ] ...

**Comment by damoodamoo** [comment]
Suggestion that this endpoint return all airlock requests "I" have access to - either waiting for my review OR requests I've submitted - is that the plan?

**Comment by tanya-borisova** [comment]
It might make sense to merge the objects in the response of requests, so that the reviews are part of a request (
Potentially not for a list, but for a GET) 
See also https://github.com/microsoft/AzureTRE/issues/2271 

@tamirkamara  to provide more details
