### ISSUE TITLE
Airlock - Add data copy event and act upon it (prepare for new data copy mechanisms)

### ISSUE THREAD

**Issue by eladiw** [microsoft/AzureTRE#2277]
## Description

As a TRE Developer
I want to add the data copy event and have the airlock processor react to it and initiate the copy of data
So that we can add more data copy mechanisms

Today, the AL processor immediatly starts to copy data when needed. instead, send a data copy event.
The AL processor will also consume this event and start the copy. Adding disable flag to not consume this event will allow other copy mechanisms to listen on this event and do something different

## Acceptance criteria

- [ ] Add data copy event
- [ ] consume this event and use the currently  used data copy mechanism (Azure Rest calls) to copy data
- [ ] add a flag to disable the consumption of this event by the AL processor
- [ ] ...

**Comment by tamirkamara** [comment]
We decided the current-internal way to copy data is enough for the scenarios we saw. Closing for now.
