### ISSUE TITLE
Unable to process request

### ISSUE THREAD

**Issue by UserSck** [microsoft/AzureTRE#2302]
Remember to label the issue with the appropriate area, and also assign it to yourself if you plan to work on the issue in the near future.

**Describe the bug**
运行make all
The following error occurs when you run the make all command
![image](https://user-images.githubusercontent.com/103118720/179503599-c46bda37-1e68-4265-b52d-a01be7de521e.png)
![image](https://user-images.githubusercontent.com/103118720/179503828-1c355917-913e-4af2-b229-47b0967da06a.png)

**Steps to reproduce**

1.I suspect that the error in the first image caused the error in the second image. After the error in the first image, make All did not terminate and then the second error occurred.

**Comment by marrobi** [comment]
Hi @UserSck, for some reason the deployment of the firewall service has failed. 

Can you check the status of the API health endpoint, as per https://microsoft.github.io/AzureTRE/tre-developers/api/#investigating-apihealth-response and report back.

Thanks.

**Comment by UserSck** [comment]
> 你好@UserSck，由于某种原因，防火墙服务的部署失败。
> 
> 您能否按照https://microsoft.github.io/AzureTRE/tre-developers/api/#investigating-apihealth-response检查 API 健康端点的状态并进行报告。
> 
> 谢谢。
I have done what you said, but I still can't access, the result of accessing this endpoint is shown below:
![image](https://user-images.githubusercontent.com/103118720/179738131-8578dead-76d8-4b6e-8053-3a0170c56d27.png)

**Comment by marrobi** [comment]
@jjgriff93  @tanya-borisova seems this is the same issue as in #2200

@UserSck can you in the Azure Portal, find an Virtual VM scale set with a name vmss-rp-porter-${TRE_ID}. Can you reimage the VMSS instance via the portal, or using the CLI as per https://docs.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest#az-vmss-reimage . Give it 5 minutes or so and try the health endpoint again.

Thanks for following this through it's an intermittent issue we have occasionally seen.

**Comment by UserSck** [comment]
> @jjgriff93 @tanya-borisova seems this is the same issue as in #2200
> 
> @UserSck can you in the Azure Portal, find an Virtual VM scale set with a name vmss-rp-porter-${TRE_ID}. Can you reimage the VMSS instance via the portal, or using the CLI as per https://docs.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest#az-vmss-reimage . Give it 5 minutes or so and try the health endpoint again.
> 
> Thanks for following this through it's an intermittent issue we have occasionally seen.

How to obtain the virtual machine instance-ID ah, I did not find where

**Comment by marrobi** [comment]
Try 1

**Comment by UserSck** [comment]
> Try 1
it shows that:


> Try 1

the result is this:
![EKHALW)TUIQ(~Q95V7SV$ O](https://user-images.githubusercontent.com/103118720/179754591-19ad93a7-f725-4a87-8a97-1e7897e7cc3b.png)

**Comment by marrobi** [comment]
Try this command to get the instance IDs - https://docs.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest#az-vmss-list-instances

**Comment by UserSck** [comment]
> Try 1

i got it, i uesd this https://docs.microsoft.com/en-US/cli/azure/vmss?view=azure-cli-latest#az-vmss-get-instance-view command

**Comment by UserSck** [comment]
> Try this command to get the instance IDs - https://docs.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest#az-vmss-list-instances

okay i got it 
Thanks!
