### ISSUE TITLE
Unable to complete - push-resource-processor-vm-porter-image - receiving Error 1

### ISSUE THREAD

**Issue by daemel** [microsoft/AzureTRE#2319]
Remember to label the issue with the appropriate area, and also assign it to yourself if you plan to work on the issue in the near future.

**Describe the bug**

Attempting to deploy with a setup using approved ID's that have Consent granted by global admin.  During the make all section of the script I receive an error 1 with no details so troubleshooting help is limited.

Checking for Docker...
»»» 🔨 Azure details from logged on user 
»»»   • Subscription: Microsoft Azure Sponsorship
»»»   • Tenant:       293da602-c0f8-49cc-9d57-3e2ac4bbaee6

Login Succeeded
The push refers to repository [trecontainerreg.azurecr.io/microsoft/azuretre/resource-processor-vm-porter]
5f70bf18a086: Layer already exists 
24406ebfacff: Layer already exists 
87d9370c8e1b: Layer already exists 
1835cb4b8ff8: Layer already exists 
a4d43621b811: Layer already exists 
eb8d0e0d7f78: Pushing [==================================================>]  392.5MB/392.5MB
c0248017b5c3: Layer already exists 
e52a9aea7366: Layer already exists 
6e4dfecff669: Layer already exists 
2e37575f9ce2: Layer already exists 
d6e05277953d: Pushing [===================>                               ]  427.9MB/1.113GB
f565f0336abc: Layer already exists 
eba06fd10755: Layer already exists 
67c8f39a5c2e: Layer already exists 
362b9397ed05: Layer already exists 
99e3b6c0b614: Layer already exists 
09ebdb357ed5: Layer already exists 
use of closed network connection
make: *** [Makefile:107: push-resource-processor-vm-porter-image] Error 1

**Steps to reproduce**

1.  Run make auth.
2.  Separately grant consent to the admin ID
3.  Run make all

**Comment by marrobi** [comment]
hi @daemel,

I've not seen this, but looks like https://github.com/docker/buildx/issues/367 . What's the internet connection like from the place doing the build? If not great I'd recommend running the commands from a cloud VM, or GiHub actions agent etc.

Let me know if get this sorted, but not sure it's something we can help, other than reducing the image size - the Azure CLI is the main culprit that we do not control.

**Comment by daemel** [comment]
Thanks Marcus, 

I have a solid 1GB here - but I will try running it from GitHub, just have to transfer my settings there.

**Comment by marrobi** [comment]
Closing this as not seen it elsewhere and seems like a network issue.
