### ISSUE TITLE
Auto install shared service names need to be formatted correctly.

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#2323]
The auto installed shared services have long names that make no sense to users:
![image](https://user-images.githubusercontent.com/17089773/180478353-1bec48be-3eea-47e3-bd87-95b2544dccde.png)

**Comment by marrobi** [comment]
In addition, the certs shared service probably does not want to be listed. Do we need a "show ito users" (as opposed to admins) boolean property?

@jjgriff93 @damoodamoo thoughts?

**Comment by marrobi** [comment]
this would be better:
<img width="185" alt="image" src="https://user-images.githubusercontent.com/17089773/180976039-3388606f-99ad-4cf4-8698-fa2538be87f2.png">

**Comment by damoodamoo** [comment]
yea we can change the display_name in the auto-install, happy to take it
