### ISSUE TITLE
Add filtering to list airlock requests API

### ISSUE THREAD

**Issue by tamirkamara** [microsoft/AzureTRE#2332]
## Description

As a user with access to a workspace
I want to list airlock requests in several filters useful for different roles and states
So that I can see requests that interests me

## Acceptance criteria
- The list endpoint support the following filters:
  - [ ] Waiting for my review (requests I have the ability to approve or reject)
  - [ ] Opened by me
  - [ ] Type (import / export)
- [ ] The API returns fields that will note if the requesting user has permissions to: approve, reject and/or cancel even if no filter is applied.

**Comment by guybartal** [comment]
@tamirkamara, what about ```submit``` action for ```draft``` requests? shouldn't the API return that as well?

**Comment by yuvalyaron** [comment]
@guybartal it's not required by the UI, but we'll add it for completeness
