### ISSUE TITLE
Retrieve workspace cost per time frame (without AuthZ)

### ISSUE THREAD

**Issue by limorl** [microsoft/AzureTRE#237]
## Description

As a Workspace Owner I want to see the Azure spend for my workspace split by calendar month, and custom time frame so I can see how much I have spent

## Acceptance critiera
 - [ ] API to retrieve spend for a single workspace, provided a workspace id and a time frame
 - [ ] API returns spend for each calendar month
 - [ ] API returns spend over custom time frame

## Notes
Related to bigger user story #88 
Suggested documentation: https://docs.microsoft.com/en-us/rest/api/cost-management/

API endpoints in management API such as:
/costs?workspace_id=1223
OR
/workspace/{workspace_id}/costs (signal workspace for Workspace Owner)

**Comment by tamirkamara** [comment]
Have been done as part of https://github.com/microsoft/AzureTRE/issues/450
