### ISSUE TITLE
Helpful Python logging

### ISSUE THREAD

**Issue by tamirkamara** [microsoft/AzureTRE#2388]
## Description

As a TRE Administrator/Developer
I want to see useful logs when errors occur in the python apps - specifically the API
So that could understand and resolve bugs

The following pattern is widely used in the api app but it doesn't help too much.
1. It doesn't include stack trace, making it hard to understand where the error came from
2. Sometimes the e isn't converted to string correctly

```python
try:
  something
except Exception as e:
  logging.error(f"Some error: {e}")
  maybe raise something
```

## Acceptance criteria

- [ ] TBD
- [ ] ...

**Comment by marrobi** [comment]
@martinpeck to flesh out issue requirements.

**Comment by martinpeck** [comment]
These two articles are well worth reviewing/reading and cover the details of how logging should be used in Python, and how exception blocks should be used:

https://guicommits.com/how-to-log-in-python-like-a-pro/
https://guicommits.com/handling-exceptions-in-python-like-a-pro/

In particular, we should be using `logger.exception` in exception blocks:

``` python
try:
    ...
except CustomException:
    logger.exception("custom message")
```

> You don't have to log the exception object. The exception function of the logger is intended to be used as-is inside except blocks. It already handles the stack trace with execution info and displays which exception caused it with its message set to ERROR level!
