### ISSUE TITLE
Terraform State error on DeployTRE Run (github actions)

### ISSUE THREAD

**Issue by daemel** [microsoft/AzureTRE#2392]
Remember to label the issue with the appropriate area, and also assign it to yourself if you plan to work on the issue in the near future.

**Describe the bug**
While running the github action "Deploy TRE" I repeatedly encounter the same issue that the Keyvault and Service Bus resources already exist and are not part of State (see Log Output below) 

**Steps to reproduce**

1.  Setup Auth (make auth)
2.  Start Deploy TRE from gitHub actions (will fail) 
      a.  set ACR name and Password in GitHub Secrets     
3.  Re-run Deploy TRE (will fail with error below)

Log output 

Changes to Outputs:
  + azure_tre_fqdn = (known after apply)
azurerm_key_vault_access_policy.deployer: Creating...
azurerm_monitor_diagnostic_setting.kv: Creating...
azurerm_monitor_diagnostic_setting.sb: Creating...
╷
│ Error: A resource with the ID "/subscriptions/***/resourceGroups/rg-***/providers/Microsoft.KeyVault/vaults/kv-***/objectId/51553684-578d-47d4-bed0-d6effee724f9" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_key_vault_access_policy" for more information.
│ 
│   with azurerm_key_vault_access_policy.deployer,
│   on keyvault.tf line 13, in resource "azurerm_key_vault_access_policy" "deployer":
│   13: resource "azurerm_key_vault_access_policy" "deployer" {
│ 
╵
╷
│ Error: A resource with the ID "/subscriptions/***/resourcegroups/rg-***/providers/microsoft.keyvault/vaults/kv-***/providers/microsoft.insights/diagnosticSettings/diagnostics-kv-***" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_monitor_diagnostic_setting" for more information.
│ 
│   with azurerm_monitor_diagnostic_setting.kv,
│   on keyvault.tf line 110, in resource "azurerm_monitor_diagnostic_setting" "kv":
│  110: resource "azurerm_monitor_diagnostic_setting" "kv" {
│ 
╵
╷
│ Error: A resource with the ID "/subscriptions/***/resourcegroups/rg-***/providers/microsoft.servicebus/namespaces/sb-***/providers/microsoft.insights/diagnosticSettings/diagnostics-sb-***" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_monitor_diagnostic_setting" for more information.
│ 
│   with azurerm_monitor_diagnostic_setting.sb,
│   on servicebus.tf line 94, in resource "azurerm_monitor_diagnostic_setting" "sb":
│   94: resource "azurerm_monitor_diagnostic_setting" "sb" {
│ 
╵
Script done, file is 1659451585-tre-core.log
Terraform Error
make: *** [Makefile:108: deploy-core] Error 1

**Comment by marrobi** [comment]
Hi @daemel , 

This looks like a deployment was done with a specific TRE_ID, and then maybe the TF state file recreated? 

The items mentioned either need deleting or importing into state or the TRE ID needs to be changed so a new state and resources are created.

If these are the only resources that already exist I'd likely go the deletion route and then run the pipeline again.

Let me know if can help.

**Comment by tamirkamara** [comment]
As was mentioned above, this looks like a run that tries to reuse the same TRE_ID while another environment is still online with the same TRE_ID.
If you can provide exact reproduce steps, please reopen this issue.

**Comment by daemel** [comment]
This was on an initial deployment, no TRE ID was in existence

**Comment by tamirkamara** [comment]
The Terraform errors suggests otherwise as it complains that the resource it is about to create already exists on Azure.
