### ISSUE TITLE
Monitor Diagnostics Settings does not support Virus Scanning and Audit settings 

### ISSUE THREAD

**Issue by daemel** [microsoft/AzureTRE#2396]
Remember to label the issue with the appropriate area, and also assign it to yourself if you plan to work on the issue in the near future.

**Describe the bug**

Experienced failures running Deploy TRE (from Github Actions) on deploying Monitor Diagnostics.  The work around was to remove the following items from ./templates/core/terraform/api-webapp.tf

Removed 

- AppServiceFileAuditLogs
- AppServiceAntivirusScanAuditLogs
- AppServiceAuditLogs

**Steps to reproduce**

1. Deploying from GitHub Action - Deploy TRE 

Log example - one for each error  

Azurerm_monitor_diagnostic_setting.webapp_api: Creating...
╷
│ Error: creating Monitor Diagnostics Setting "diag-***" for Resource "/subscriptions/***/resourceGroups/rg-***/providers/Microsoft.Web/sites/api-***": insights.DiagnosticSettingsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Category 'AppServiceFileAuditLogs' is not supported."
│ 
│   with azurerm_monitor_diagnostic_setting.webapp_api,
│   on api-webapp.tf line 141, in resource "azurerm_monitor_diagnostic_setting" "webapp_api":
│  141: resource "azurerm_monitor_diagnostic_setting" "webapp_api" {
│ 
╵

**Comment by marrobi** [comment]
@daemel believe this is a result of using an App Service Plan that is not Premium - i.e. S. These logging types are not supported in the S series. I don't believe there is much of a price difference between P vs S (and P is actually better value for money).

When we created the project S did not include network integration, hence these logging settings are included.

@tamirkamara do you concur?

**Comment by daemel** [comment]
Thanks Marcus - we are out of quota on P, but I did have quota for S.  I've been compiling notes so I can help with the documentation of this.

**Comment by marrobi** [comment]
We decided that we should be targeting premium App Service SKU, these settings could be removed (or made conditional) as don't believe we use them.
