### ISSUE TITLE
Error at Deploy main / Register Shared Bundles (shared_service, tre_workspace base)

### ISSUE THREAD

**Issue by daemel** [microsoft/AzureTRE#2408]
Remember to label the issue with the appropriate area, and also assign it to yourself if you plan to work on the issue in the near future.

**Describe the bug**
When running GitHub Actions - Deploy TRE workflow I encountered the following errors 

»»» 🧩  Registering ./templates/shared_services/gitea bundle...

╔══════════════════════════════════════╗
║          Azure TRE Makefile          ║
╚══════════════════════════════════════╝

»»» ✅ Checking pre-reqs...

Checking for Azure CLI...

Checking for Docker...

Checking for porter...
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "***",
    "id": "***",
    "isDefault": true,
    "managedByTenants": [],
    "name": "***".
    "state": "Enabled",
    "tenantId": "***",
    "user": {
      "name": "***",
      "type": "servicePrincipal"
    }
  }
]
»»» 🔨 Azure details from logged on user 
»»»   • Subscription: ***
»»»   • Tenant:       ***

Login Succeeded
API access token isn't available - automatic bundle registration not possible. Use the script output to self-register. 
See documentation for more details: https://microsoft.github.io/AzureTRE/tre-admins/registering-templates/
{
  ...
}

~~  Next Error ~~ 

»» 🧩  Registering ./templates/workspaces/base bundle...

╔══════════════════════════════════════╗
║          Azure TRE Makefile          ║
╚══════════════════════════════════════╝

»»» ✅ Checking pre-reqs...

Checking for Azure CLI...

Checking for Docker...

Checking for porter...
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "***",
    "id": "***",
    "isDefault": true,
    "managedByTenants": [],
    "name": "***",
    "state": "Enabled",
    "tenantId": "***",
    "user": {
      "name": "***",
      "type": "servicePrincipal"
    }
  }
]
»»» 🔨 Azure details from logged on user 
»»»   • Subscription: Smokejumpers External Subscription
»»»   • Tenant:       ***

Login Succeeded
API access token isn't available - automatic bundle registration not possible. Use the script output to self-register. 
See documentation for more details: https://microsoft.github.io/AzureTRE/tre-admins/registering-templates/
{
  "name": "tre-workspace-base",
...
}

**Steps to reproduce**

1.  Setup Auth (ie make auth)
2.  Setup GitHub Action Secrets 
3.  Manually trigger DeployTRE workflow

**Comment by tamirkamara** [comment]
I believe this is a result of misconfiguration of github action secrets. Please follow the updated docs.
