### ISSUE TITLE
301 Error when using devops/scripts/register_bundle_with_api.sh

### ISSUE THREAD

**Issue by daemel** [microsoft/AzureTRE#2409]
Remember to label the issue with the appropriate area, and also assign it to yourself if you plan to work on the issue in the near future.

**Describe the bug**
When trying to Register templates via the document page https://microsoft.github.io/AzureTRE/tre-admins/registering-templates/ I receive a 301 - Permanent Redirect error (see below). 

vscode ➜ .../AzureTRE/templates/workspaces/base (main) $ ../../../devops/scripts/register_bundle_with_api.sh -r *** -t workspace_service -w sonatype-nexus-vm -u *** -c -i -a a***

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9060  100   195  100  8865     15    712  0:00:13  0:00:12  0:00:01  1908

Error while registering template
HTTP/1.1 100 Continue

HTTP/1.1 301 Moved Permanently
Server: Microsoft-Azure-Application-Gateway/v2
Date: Wed, 03 Aug 2022 19:39:50 GMT
Content-Type: text/html
Content-Length: 195
Connection: keep-alive
Location: https://***.cloudapp.azure.com/api/workspace-service-templates

<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>Microsoft-Azure-Application-Gateway/v2</center>
</body>
</html>

**Steps to reproduce**

1. execute  ../../../devops/scripts/register_bundle_with_api.sh from the ./templates/workspaces/base directory using the described switches

**Comment by joalmeid** [comment]
@daemel , we're updating the documentation today regarding the bundle registration.

Do use the prefered way with the make commands. Here's an example:

```bash
make bundle-build DIR=templates/workspace_services/azureml
make bundle-publish DIR=templates/workspace_services/azureml
make bundle-register DIR=templates/workspace_services/azureml BUNDLE_TYPE=workspace_service
```
