### ISSUE TITLE
create_workspace_application.sh does not create associated secret.

### ISSUE THREAD

**Issue by chboudry** [microsoft/AzureTRE#2424]
I redeployed a tre, faced some issue with the secret of the workspace API that didn't exist,

had a look at create_workspace_applications.sh, I don't see any code taht would be able to actually create a secret?

Was expecting something like : "az ad app credential reset", but can't find it in the project files.

**Comment by marrobi** [comment]
Hi @chboudry that script accepts:

```    -r,--reset-password             Optional, switch to automatically reset the password. Default 0
```

That then calls `create_or_update_service_principal.sh` which resets and outputs the new password.

Let me know if need further help.
