### ISSUE TITLE
Verify that all TF Resources have costs tags in PR

### ISSUE THREAD

**Issue by guybartal** [microsoft/AzureTRE#2429]
## Description

As a TRE Developer
I need an automated solution which checks that all resources in Terraform has costs Tags
so that I won't miss to tag any new/updated resource

**Comment by tamirkamara** [comment]
Worth to consider doing it here: https://github.com/terraform-linters/tflint-ruleset-azurerm/issues/133

**Comment by guybartal** [comment]
contributing a rule for azurerm tflinter ruleset which verifies if all taggable resources has a tag from a list of tags which can be configured for our case to have "tre_id" while ignoring the main ACR & storage would do the trick.

**Comment by guybartal** [comment]
https://github.com/terraform-linters/tflint-ruleset-azurerm/pull/194

**Comment by guybartal** [comment]
PR got merged and released in [tflint-ruleset-azurerm v0.18.0](https://github.com/terraform-linters/tflint-ruleset-azurerm/releases/tag/v0.18.0), and requires [tflint v0.40.0](https://github.com/terraform-linters/tflint/releases/tag/v0.40.0).
waiting for a release of [superliner](https://github.com/github/super-linter) to include that version of tflint.

**Comment by marrobi** [comment]
@guybartal this is now merged and in latest release https://github.com/github/super-linter/pull/3339
