### ISSUE TITLE
Unable to download Github CLI to Docker Container via script (gh.sh)

### ISSUE THREAD

**Issue by sanjeevsidana** [microsoft/AzureTRE#2430]
Remember to label the issue with the appropriate area, and also assign it to yourself if you plan to work on the issue in the near future.

**Describe the bug**
While doing the installation of Dynamic pickup of latest github version does not work. I had to hardcode GitHub version (as shown below) in gh.sh so the curl command can download and install.

**Original** : 
curl -sSL "https://github.com/cli/cli/releases/download/v${VERSION}/gh_${VERSION}_linux_amd64.tar.gz" -o /tmp/gh.tar.gz
tar -zxvf /tmp/gh.tar.gz --strip-components 2 -C "$INSTALL_DIR" "gh_${VERSION}_linux_amd64/bin/gh" > /dev/null

**Hardcoded**:
curl -sSL "https://github.com/cli/cli/releases/download/v2.14.3/gh_2.14.3_linux_amd64.tar.gz" -o /tmp/gh.tar.gz
tar -zxvf /tmp/gh.tar.gz --strip-components 2 -C "$INSTALL_DIR" "gh_2.14.3_linux_amd64/bin/gh" > /dev/null

**Steps to reproduce**

1. Install via VSCode  and Docker Desktop on Windows.
2. follow getting started
3. open code in Remote container extension(VSCode) as it tries to load the docker container and downloads required CLI. It failed at the Github CLI download step.

**Comment by marrobi** [comment]
@sanjeevsidana is this with the code base checked out on Windows? It could be a Linux/Windows issue. Can you clone the repo on say WSL, and see if you get the same issue? 

I've added a note to the docs in this PR as a few issues have been reported. Thanks.

**Comment by sanjeevsidana** [comment]
@marrobi, yes this was cloned on windows. I will try on WSL and update.
