### ISSUE TITLE
SAS token generation UT should also check list and delete permissions

### ISSUE THREAD

**Issue by LizaShak** [microsoft/AzureTRE#2436]
**Describe the bug**
Currently Unit Tests doesn't cover list and delete permission for SAS token generation

**Comment by lyshark** [comment]
What is this

**Comment by LizaShak** [comment]
@lyshark when working with airlock requests to import/export data in the api we generate a SAS token with limited permissions to access the relevant storage account . Currently the Unit Tests didn't cover list and delete permissions check. I have added it in the related PR.
