### ISSUE TITLE
Workspace deployment updates shared firewall with required rules

### ISSUE THREAD

**Issue by christoferlof** [microsoft/AzureTRE#246]
## Description

As a TRE administrator
I want to have the firewall updated with rules required by the workspace I just deployed
So that our researchers can use the services that are part of the workspace accordingly.

## Acceptance criteria

- [x] Workspace rules added to shared firewall
- [x] Existing rules left untouched by new workspace deployment
- [x] Multiple instances of a workspace template can be deployed, all having their rules added to the firewall as needed.
- [x] Documentation created on how to add firewall rules from within a bundle

## Note on implementation

- At the moment, we will not support updates to the firewall by simultaneous workspace deployments. This is to be addressed with the Firewall shared service implementation described in #23 .

**Comment by marrobi** [comment]
@tompaana the workaround solution can be seen in [https://github.com/microsoft/AzureTRE/blob/develop/workspaces/services/innereye_deeplearning/terraform/firewall.tf](https://github.com/microsoft/AzureTRE/blob/develop/workspaces/services/innereye_deeplearning/terraform/firewall.tf) which uses this script: [https://github.com/microsoft/AzureTRE/blob/develop/workspaces/services/innereye_deeplearning/terraform/get_firewall_priorities.sh](https://github.com/microsoft/AzureTRE/blob/develop/workspaces/services/innereye_deeplearning/terraform/get_firewall_priorities.sh)
