### ISSUE TITLE
E2E fail to retrieve workspace by id

### ISSUE THREAD

**Issue by tamirkamara** [microsoft/AzureTRE#2461]
**Describe the bug**

E2E are consistently fail after #2453 
The error gist is this and can be reproduced locally by using the test (automation) account to issue the GET request.

  File "/api/./api/routes/workspaces.py", line 69, in retrieve_workspace_by_workspace_id
    user_role_assignments = get_user_role_assignments(user)
  File "/api/./api/routes/resource_helpers.py", line 67, in get_user_role_assignments
    return access_service.get_user_role_assignments(user.id)
  File "/api/./services/aad_authentication.py", line 313, in get_user_role_assignments
    raise AuthConfigValidationError(f"{strings.ACCESS_UNABLE_TO_GET_ROLE_ASSIGNMENTS_FOR_USER} {user_id}")
services.access_service.AuthConfigValidationError: Unable to get role assignments for user ade81c51-edee-4f17-ac8d-1becb3dd7352

**Comment by marrobi** [comment]
As discussed, issue is we are calling a user endpoint with a service principle token - https://github.com/microsoft/AzureTRE/blob/22545c4dca2a39cdbe0b0c0d9c944b966a497885/api_app/services/aad_authentication.py#L287
