### ISSUE TITLE
TRE Cost Management should roll up untagged resources into their parent resource group

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#2468]
If a service outside of the TRE deploys untagged resources into a workspace the costs are not accounted for. Example being Cyclecloud or Cromwell on Azure.

If resources are untagged they should be allocated to the resource group they are inside. This means if the resource group is tagged with a `workspace_id`, the workspace costs, if tagged with a `workspace_service_id` the workspace service costs, if tagged with a `user_resource`, the user resource costs.

This means querying all tagged resources and resources inside any resource groups tagged with the id. This will mean querying the resource groups to get appropriate resource groups prior to the Azure Cost Management Query.

Then using an OR query similar to:

```
{

    "type": "Usage",

    "timeframe": "Custom",

    "timePeriod": {"from":"{{TIME_FROM}}", "to": "{{TIME_TO}}" },

    "dataset": {

        "granularity": "None",

        "aggregation": {

            "totalCost": {

                "name": "Cost",

                "function": "Sum"

            }

        },

        "filter": {

            "or": [

                {

                    "dimensions": {

                        "name": "ResourceGroup",

                        "operator": "In",

                        "values": ["{{RG_NAMES}}"]

                }

                },

                {

                    "tags": {

                        "name": "{{TAG_KEY}}",

                        "operator": "In",

                        "values" : [

                            "{{TAG_VALUE}}",

                            ]

                    }

                }

            ]

        },

        "grouping": [

            {

                "type": "Tag",

            }

        ]

    }

}
```

**Comment by marrobi** [comment]
@guybartal does this align with our discussion?

**Comment by guybartal** [comment]
@marrobi 
yes, but partially correct,
are there any plans to split the user resource into a separate resource group? they are currently inside the workspace RG...

as I see it the current logic should be:

for TRE level costs we should filter by a list of resource groups names which are tagged by ```tre_id``` and list of all ```tre_workspace_id```s

for Workspace level we should filter by the resource group of the specific workspace only.

and yes it means we need to query resource groups and filter by tag name (tre_id or tre_workspace_id depends on the costs level) prior to azure cost management because API doesn't aware of the RG names).

**Comment by guybartal** [comment]
actually it won't work for tre level in a single call for cost management...
main tre cost api returns a list of workspaces costs while the cost query will return a total summary for all tre and its workspaces in a single row. 
looks like we need to call it in a loop which will be very slow response and not scalable - O(number of workspaces)

**Comment by guybartal** [comment]
adding another group by column would solve that by splitting each untagged summary into RGs:

{

    "type": "Usage",

    "timeframe": "Custom",

    "timePeriod": {"from":"{{TIME_FROM}}", "to": "{{TIME_TO}}" },

    "dataset": {

        "granularity": "None",

        "aggregation": {

            "totalCost": {

                "name": "Cost",

                "function": "Sum"

            }

        },

        "filter": {

            "or": [

                {

                    "dimensions": {

                        "name": "ResourceGroup",

                        "operator": "In",

                        "values": ["{{RG_NAMES}}"]

                }

                },

                {

                    "tags": {

                        "name": "{{TAG_KEY}}",

                        "operator": "In",

                        "values" : [

                            "{{TAG_VALUE}}",

                            ]

                    }

                }

            ]

        },

        "grouping": [

            {
                "type": "dimension",
                "name": "ResourceGroup"
            },
            {
                "type": "Tag"
            }

        ]

    }

}
