### ISSUE TITLE
Repeat Failures in Application Insights

### ISSUE THREAD

**Issue by JaimieWi** [microsoft/AzureTRE#2469]
**Describe the bug**

I have recently manually deployed the TRE a couple of times and both times noticed there are reoccurring failures in Application Insights. 
They occur every 5 minutes and show a response code of 404. 
Request.url is http://api-<tre-id>.azurewebsites.net/

**Steps to reproduce**

1. Manually deploy TRE Core
2. Go to Application Insights and check Failures

I can't see any effect on TRE use, just something to note.

**Comment by marrobi** [comment]
This is down to AlwaysOn being configured on the web app. Suggest we put a basic page in the root of the API.
