### ISSUE TITLE
📅 Merge to main 

### ISSUE THREAD

**Issue by christoferlof** [microsoft/AzureTRE#247]
Adding an issue to track the merge to main. Last thing before closing milestone.

- [x] Merge `develop` with `main`
- [x] Create `pre-release` release and tag branch with `0.1` version
- [x] Document the current development state (no end e2e test missing, limited capacity to approve PRs, comments and issues very welcommed)

**Comment by Lybecker** [comment]
Pre-release [0.2](https://github.com/microsoft/AzureTRE/releases/tag/0.2)
