### ISSUE TITLE
Deleting a workspace that has a user service is stuck on loading

### ISSUE THREAD

**Issue by yuvalyaron** [microsoft/AzureTRE#2470]
**Describe the bug**
When trying to delete a workspace that has a workspace service, the UI will show loading dialog that will load forever...
If we inspect the network using Chrome dev tools (ctrl+shift+i on Windows), we can see that the backend returns an HTTP 400 error, that says we cannot delete a workspace before deleting its workspace services.
We also cannot delete a workspace service before deleting its user services.

**Steps to reproduce**

1. create a workspace
2. create a workspace service inside that workspace
3. Optional: create a user service inside that workspace service
4. try to delete the workspace (open chrome's network tab before doing so)

**Comment by marrobi** [comment]
This work needs to be done - #2152 , but until this is complete, the UI should handle the error.
