### ISSUE TITLE
Resources with Array types have regressed to strings

### ISSUE THREAD

**Issue by damoodamoo** [microsoft/AzureTRE#2474]
Related to #2473 .

A property such as `address_prefixes` should save in Cosmos as a native array type. Instead it's being saved as a string, which is then causing issues in substitutions in pipelines.

**Comment by marrobi** [comment]
@damoodamoo Take a look at #1846 - a requirement of this will be to have multiple address prefixes for a workspace. Hence `address_prefixes` should likely be in array.

**Comment by damoodamoo** [comment]
I'm agreeing - it needs to be an array, yet it's being saved to cosmos as an encoded string - `"[\\\"github.com\\\",\\\"www.github.com\\\",\...` This was previously saving as a proper JSON array so I need to work out what's changed.
