### ISSUE TITLE
Getting wrong actions when filtering airlock requests

### ISSUE THREAD

**Issue by anatbal** [microsoft/AzureTRE#2488]
When asking for airlock requests as user with both researcher and airlock manager role, getting only part of the actions possible
![image](https://user-images.githubusercontent.com/13421451/185781775-3da944e4-06ad-4970-b155-309958a9dccd.png)

**Comment by yuvalyaron** [comment]
the allowed actions that we return are based on the current status of the request, in the attached image the status is draft, so it cannot be reviewed yet.
