### ISSUE TITLE
[Task] Document InnerEye AML workspace template

### ISSUE THREAD

**Issue by christoferlof** [microsoft/AzureTRE#249]
Story: #132 

**Description**
Documentation on resources being provisioned and networking rules being allowed.

Please include:
- An overview description of the value of the Workspace Template
- What is being created and why
- Any dependencies (e.g. builds on another Workspace Template)
- Any limitations
- Any changes to inbound and outbound firewall rules

**Comment by marrobi** [comment]
Bundles still requires documentation on resources being deployed - diagrams?
