### ISSUE TITLE
Resource history blows up document size

### ISSUE THREAD

**Issue by tamirkamara** [microsoft/AzureTRE#2491]
**Describe the bug**

Resource history is saved indefinitely along side the current resource version. This causes the document to get larger and larger overtime but CosmosDB is limited to 2MB per item.

This is happening in our CICD environment when many runs change the firewall share service until it gets too large and the API starts to output errors (from cosmos) about the document size. As a temp measure I deleted some items from the history object.

Probably best to think of a way to address this internally (either save last X versions, archive older history items elsewhere, etc.).

There was an agreement about going on and crearing a new container for archiveing older history items.
The tasks that are planned are:

- [ ] Create a new container for history
- [ ] Create history item in a new container
- [ ] Change history item schema to include also parent id 
- [ ] Change the query (but still return it as part of the resource as a list) 
- [ ] Create an API to return only history for UI usage and undo the list in the resource schema 
- [ ] Fix unit tests 
- [ ] Write migration script

**Comment by anatbal** [comment]
We decided not to change the airlock archiving mechanism
