### ISSUE TITLE
Airlock Manager can create user resources

### ISSUE THREAD

**Issue by tanya-borisova** [microsoft/AzureTRE#2499]
## Description

As an Airlock Manager
I want to have a permission to create VMs in workspaces I'm added as an Airlock Manager
So that I can create a VM and use it review an Airlock request

## Acceptance criteria

- [ ] Airlock Manager can create user resources

**Comment by tamirkamara** [comment]
We are meaning to have a roles/authorization discussion as other issues have surfaces...
but as for this issue, if an airlock manager should be able to create resources - isn't he another researcher in the workspace?

**Comment by marrobi** [comment]
@tanya-borisova, afraid I agree with @tamirkamara , this doesn't feel right.

There are scenarios where Airlock Manager should not have access to the data in the workspace, the ability to create resources means they can. 

I'd suggest making them a Workspace Researcher in the review workspace. Or c create a specific "User Resource Creator" role.

@tamirkamara I'm not sure how scopes could fix this, as I thought they are to grant a web client access to an API, not a user.

**Comment by tanya-borisova** [comment]
> There are scenarios where Airlock Manager should not have access to the data in the workspace, the ability to create resources means they can.

But why would they have access to anything if they are not a Researcher? Could you give a specific example of where this would break?

**Comment by martinpeck** [comment]
Following discussion we've close the PR and closed this issue. We will use existing mechanisms to assign users with the "airlock manager" role the rights to create resources in appropriate workspaces.

i.e. no code changes here.
