### ISSUE TITLE
In workspace view shared services do not display a connect button.

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#2552]
Users need to connect to shared services to view the shared service configuration, or external URI. The connect button appears on the Core view, but not the workspace view when a `connection_uri` is present.

**Comment by marrobi** [comment]
This is by design as shared services properties are not exposed at the workspace level. Will need to think about making an exception for `connection_uri`. Also at core level `connection_uri` isn't returned when getting the list of shared services, only by ID.

**Comment by marrobi** [comment]
@damoodamoo can you suggest a way to add `connection_uri` and `internal_connection_uri` to:

https://github.com/microsoft/AzureTRE/blob/6b025155e6607f3697c310690bbc706c0ee2636c/api_app/models/domain/restricted_resource.py#L7

Do they need to be a top level property? Thanks.

**Comment by damoodamoo** [comment]
We should just be able to add connection_uri to RestrictedProperties and it'll populate the value - happy to take this?

**Comment by marrobi** [comment]
Ah, got you, it is just the properties. If you can great, if not I can pick it up.

I've also used `internal_connection_uri` for a URI only available on the VNet in the AML service.

**Comment by lenisha** [comment]
It worked , could add PR

**Comment by marrobi** [comment]
@lenisha assigned to yourself, if you can add `internal_connection_uri` too that would be great. Let me know if need help with the PR.

**Comment by lenisha** [comment]
added
