### ISSUE TITLE
Ubuntu version hard-coded in, causes error searching for release file

### ISSUE THREAD

**Issue by JaimieWi** [microsoft/AzureTRE#2560]
**Describe the bug**
When creating a custom Linux VM I am using Ubuntu 20.04. Within the VM I get an error relating to there being no Release file. (Unfortunately I no longer have the actual error).
The fix was to edit the apt_sources_config.yml to use 20.04 instead of 18.04.

Edited line:
deb [signed-by=/etc/apt/trusted.gpg.d/microsoft.gpg] ${nexus_proxy_url}/repository/microsoft-apt/ubuntu/**20.04**/prod $RELEASE main

**Steps to reproduce**

1. Create custom Linux VM image
2. Create VM
3. Manually run the vm_config.sh file and see error looking for Release file
4. Edit the apt_sources_config.yml to use 20.04 instead of 18.04.

**Comment by marrobi** [comment]
Let's look at making this release agnostic. I'll take a look when have some time.

**Comment by SvenAelterman** [comment]
This has been addressed now with release v0.17.0
