### ISSUE TITLE
Failed to create symbolic link. Operation not supported

### ISSUE THREAD

**Issue by JaimieWi** [microsoft/AzureTRE#2561]
**Describe the bug**
Using a custom Linux VM image with Ubuntu 20.04.

This error occurs: `ln: failed to create symbolic link '/vm-shared-storage/vm-shared-storage': Operation not supported`

Fix was to add mfsymlinks to the vm_config.sh file, as per[ this link](https://docs.microsoft.com/en-us/azure/storage/files/storage-troubleshoot-linux-file-connection-problems#cannot-create-symbolic-links---ln-failed-to-create-symbolic-link-t-operation-not-supported) 

Edited line: `echo "$fileShareName -fstype=cifs,rw,dir_mode=0777,credentials=$smbCredentialFile, mfsymlinks :$smbPath" | sudo tee /etc/auto.fileshares > /dev/null`

**Comment by marrobi** [comment]
Thank Jamie, let's try this on 18.04 and see if we can add to the existing template.

**Comment by marrobi** [comment]
Closing this as will be covered in #3523
