### ISSUE TITLE
Guacamole User Resource Templates should support custom images

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#2568]
The Azure images often do not often meet researcher requirements. This means custom images need building and using. 

**Describe the solution you'd like**
The existing templates, or new templates in this repository should support custom images. The docs should also have pointers to MS docs on creating custom images.

**Comment by stuartleeks** [comment]
@marrobi - assigned this to you for comment

**Comment by marrobi** [comment]
@stuartleeks is the requirement that you want to use a different image gallery for different TRE deployments? Or make different images available from the same gallery?

In your PR you have `gallery_${var.tre_id}` which feels like a valid approach and does not need further changes in the RP code?

If there is a separate issue of making "custom" environment variables available to the resource processor (be it the gallery id) or alternatively inheriting a property from a parent resource (so input the gallery ID when deploy the workspace or workspace service) then think should treat those seperately.

**Comment by stuartleeks** [comment]
@marrobi the initial code uses the name-based convention, but the PR description is proposing to pull the Gallery ID from environment variables on the Resource Processor which would make this more flexible.

As we just discussed, I will look at how complex it would be to allow the core TRE deployment to take in custom `RP_BUNDLE_` prefixed environment variables that would be set on the Resource Processor, and then to have the Resource Processor supply those to any matching parameters that don't have values from other sources. E.g. to allow `my_param` to be satisfied by an `RP_BUNDLE_MY_PARAM` env var
