### ISSUE TITLE
Azure ML workspace service fails on deployment when ARM and Auth tenants are different

### ISSUE THREAD

**Issue by guybartal** [microsoft/AzureTRE#2591]
Azure ML workspace service fails on deployment when ARM and Auth tenants are different.

**Steps to reproduce**

1. deploy TRE with AAD_TENANT_ID != ARM_TENANT_ID
2. create a workspace
1. assign researchers to the workspace
3. deploy AML workspace service
1. it will fail on assigning data scient role for the researches

![image](https://user-images.githubusercontent.com/3179107/189820094-e2ad9c29-cc44-4ac5-b16c-9bbf4ccb25e1.png)

```
│ Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="PrincipalNotFound" Message="Principal 643e0d2b1dac4472b01fd816fe693c65 
does not exist in the directory *******. Check that you have the correct principal ID. If you are creating this principal and then immediately assigning a role, this error might be related to a replication delay. In this case, set the role assignmen
t principalType property to a value, such as ServicePrincipal, User, or Group.  See https://aka.ms/docs-principaltype"
│ 
│   with azurerm_role_assignment.app_role_members_aml_data_scientist["643e0d2b-1dac-4472-b01f-d816fe693c65"],
│   on roles.tf line 22, in resource "azurerm_role_assignment" "app_role_members_aml_data_scientist":
│   22: resource "azurerm_role_assignment" "app_role_members_aml_data_scientist" {
```
consider adding a warning in the docs that it works only if it is in the same tenant and fail fast with an error message inside ```get_app_role_members.sh``` or try to filter out irrelevant users.

**Comment by marrobi** [comment]
As AML relies on the Azure Active Directory in the tenant it is deployed into it is only possible to use Azure ML when the AAD Tenant is the same as the ARM Tenant. Hence this issue cannot be resolved.
