### ISSUE TITLE
sample.env references MGMT_RESOURCE_GROUP_NAME , github workflows reference MGMT_RESOURCE_GROUP

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#2593]
When setting up CI/CD the secret `MGMT_RESOURCE_GROUP_NAME` has been added to github secrets as per the `sample.env` file. In the workflows the name of the secret is `MGMT_RESOURCE_GROUP`.

**Comment by marrobi** [comment]
More variance in naming between workflows and env vars,

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/17089773/190346028-c4d90866-749c-438f-a6e5-93516a85dda1.png">

**Comment by tamirkamara** [comment]
Using the env files for reference on secrets setup wasn't the recommended documented way. We had a specific doc for this that is gone now...

**Comment by marrobi** [comment]
Would it not make sense for the naming of the variables to be the same? 

Could also reduce the need for duplication of documentation?

**Comment by tamirkamara** [comment]
1. Yes, it does make sense to have the same name. There're a few differences other than the one mentioned in the issue.
2. I don't think it will reduce anything. The env files are meant to be used by developers, they include settings which we don't (shouldn't) support in the pipeline.

**Comment by marrobi** [comment]
2. Could they be at the bottom of the doc, or in a seperate doc called "Developer Settings" with a clear statement these are to be used for local development?

**Comment by marrobi** [comment]
Fixed in #2655
