### ISSUE TITLE
[BUG] Tags applied by Azure Policy are being removed by terraform increasing deployment time.

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#260]
**Describe the bug**
Tags applied by Azure Policy are being removed by terraform increasing deployment time.

**Steps to reproduce**

See https://github.com/microsoft/AzureTRE/runs/2819001657?check_suite_focus=true - Deploy TRE job.

**Solution**

Ignore all tags in all TF - TRE deployment + Workspace Templates + Service Templates

**Comment by marrobi** [comment]
@christoferlof can we make sure this gets prioritized as is adding 10 minutes plus onto each run of the pipeline. Thanks.

Suggest we use an approach similar to: https://weidongzhou.wordpress.com/2018/12/13/how-to-do-tagging-efficiently-in-terraform/ . Where we specify a variable with our required common tags - such as the ones applied by policy. Tags also need to be passed into bundles.

In addition each resource needs a `tre_id` tag, and each `workspace_id` tag.

**Comment by Lybecker** [comment]
I suggest ignoring specific tags at TRE instance level using the [TF ignore feature](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/resource-tagging#ignoring-changes-to-specific-tags)

This means:

- When creating the TRE instance, the Cloud Administrator needs to specify which tags to ignore
- This value should be forwarded to the Bundle
