### ISSUE TITLE
Make an admin-vm shared service

### ISSUE THREAD

**Issue by tamirkamara** [microsoft/AzureTRE#2611]
## Description

As a TRE Administrator,
I want to install an admin-vm as a shared service
So that it will be created only when required

## Acceptance criteria

- [ ] Extract admin-vm from core infrastructure 
- [ ] Remove tools that aren't required and won't be possible to use (shared services are installed after the fw and most traffic will be blocked)
- [ ] Confirm admin tasks are still possible

**Comment by tamirkamara** [comment]
Current tools that are installed are:
1. Git
2. Azure CLI
3. JQ
4. AzureTRE OSS Clone

I couldn't find a doc that mention the jumpbox... What are the tasks those tools are needed for?
@marrobi,  @chboudry (who created the install script)

**Comment by marrobi** [comment]
Is this just the admin VM, or Bastion as well?

We used to configure Nexus by running scripts on the jumpbox, hence the need for these tools. That work is now done in the Nexus VM service install scripts.

All I ever use is a web browser to access Nexus, Gitea etc.

I'm happy with no packages for now, with the view that Nexus will be configured if want to download things. We could maybe have a variable that optionally opens up access to the Internet via the Firewall for the VM?

**Comment by chboudry** [comment]
to push it further, is the admin-vm still required ?

**Comment by tamirkamara** [comment]
I don't use that vm often. I guess it's nice to have it to do some interactions with the other parts of the core network - investigate issues, use gitea cli, etc.
Since it's no often, I think it's safe to provide a vanilla VM as a shared service for any potential need. But I'm fine with removing it altogether...

**Comment by marrobi** [comment]
Lets have a vanilla VM, as think it's useful, we can deal with software installation as and when.
