### ISSUE TITLE
make all fails on /devops/terraform/bootstrap.sh create storage account container

### ISSUE THREAD

**Issue by jonasthehobbit** [microsoft/AzureTRE#2613]
**Describe the bug**
Failed creation of storage account containers when --auth-mode login flag used in /devops/terraform/bootstrap.sh

**Steps to reproduce**

1. Fill out .env vars in /devops/terraform
2. complete .env vars in /templates/core/.env
3. ran make auth = success
4. ran make all = falure

Error message

_The request may be blocked by network rules of storage account. Please check network rule set using 'az storage account show -n accountname --query networkRuleSet'.
If you want to change the default action to apply when no rule matches, please use 'az storage account update'._

Editing bootstrap.sh and removing the --auth-mode login flag fixed the issue for me.

**Comment by marrobi** [comment]
Thanks for reporting this @jonasthehobbit . 

@tamirkamara so you think this could be associated with the changes in this PR https://github.com/microsoft/AzureTRE/pull/2607?

**Comment by jonasthehobbit** [comment]
just doing some googling... Seems related to this.

https://github.com/Azure/azure-cli/issues/13509

**Comment by jonasthehobbit** [comment]
Ok, found the issue, seems at some point I've removed my owner rights on my test subscription so I did not have relevant rights to create storage containers...

My bad!

**Comment by tamirkamara** [comment]
Ok. So can you close this issue please?

**Comment by jonasthehobbit** [comment]
RBACS incorrect on the tenant, closing.
