### ISSUE TITLE
Nexus Shared Service docs need updating for v2

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#2617]
The Nexus docs listed here - https://microsoft.github.io/AzureTRE/tre-templates/shared-services/nexus/#deploy are not appropriate for the VM based nexus deployment. 

They do not cover certificate installation and refer to running setup scripts.

**Comment by martinpeck** [comment]
@jjgriff93 are you able to take a look at this? For some reason I thought you *had* updated the docs (but I might have misremembered that).

**Comment by jjgriff93** [comment]
@martinpeck apologies for the delay! Yes I had updated it in the Quickstart but not in the template doc. There's a bit of inconsistency where configuration steps were specified for gitea in the Quickstart but not the template docs so I've addressed that in my PR as well as for Nexus
