### ISSUE TITLE
Problems with authorization in Swagger

### ISSUE THREAD

**Issue by david-salac** [microsoft/AzureTRE#2622]
When I try to authorize in Swagger (on https://xx.yy.cloudapp.azure.com/api/docs), it returns me the following error:
```
Auth error
Error: Unauthorized, error: invalid_client, description: AADSTS700025: Client is public so neither 'client_assertion' nor 'client_secret' should be presented.
Trace ID: 2173d9cc-0c11-4e26-90ed-274df3709400
Correlation ID: 62009332-0d4d-4734-a283-e32edfe34c06
Timestamp: 2022-09-20 13:54:32Z
```
Do you please have any idea how to deal with that?

**Comment by marrobi** [comment]
Are you adding something into the fields that isn't already populated? You should just be able to click `Authorize`, `client_secret` required.

![image](https://user-images.githubusercontent.com/17089773/191302189-cb221cf9-1812-4e08-a275-7e21ae3b9ab9.png)

**Comment by david-salac** [comment]
> Are you adding something into the fields that isn't already populated? You should just be able to click `Authorize`, `client_secret` required.
> 

Unfortunately, that's exactly what I tried to do (I don't even know how to add anything there nor whether it is possible).

**Comment by marrobi** [comment]
Ok, how did you set up your application registrations? Using `make auth` or manually?

**Comment by marrobi** [comment]
@david-salac please let us know if you managed to resolve the issue.

**Comment by david-salac** [comment]
Hi, yes, I used `make auth` - the thing is that it didn't generate a secret value for `SWAGGER_UI_CLIENT_ID` in the `auth.env` file (there is no `SWAGGER_UI_CLIENT_SECRET` variable - to be precise), so I had to add that secret manually (in Certificates & secrets tab). The problem is **not** solved - it still shows the same (I also generated a new 'clean' version of TRE to ensure no errors during the process might influence this issue, but it didn't help). Please, do you have any idea what to do?

**Comment by daemel** [comment]
I am experiencing the same on an install.  used make auth for the setup, swagger client ID was set (but no client secret).  Click on Auth, but keep getting the error that I do not have rights to perform any action.  Validated RBAC settings, still unable to move forward.

**Comment by marrobi** [comment]
@daemel can you post the exact error message you get back or screenshot?

There should **not** be a client secret in the authorization dialog in the Swagger, however there should be in the `auth.env` file.

**Comment by marrobi** [comment]
@david-salac you say:

>  so I had to add that secret manually (in Certificates & secrets tab)

You do not need to add a secret. Can you confirm again that a secret was not entered into the Authorize dialog and this error still appears. The only way I can get the same error is by entering a client secret (see below):
![image](https://user-images.githubusercontent.com/17089773/191558453-4b24b12c-c0b6-47d4-8e7a-b20d893150c5.png)


 Thanks.

**Comment by david-salac** [comment]
Oh dear me, you can leave that field blank ?!
Yes, now it works correctly - thank you.

**Comment by marrobi** [comment]
Yes, it uses your AD account.

Will close the issue.

**Comment by daemel** [comment]
> @daemel can you post the exact error message you get back or screenshot?
> 
> Edited: There should **not** be a client secret in the authorization dialog in the Swagger or the `auth.env`

Sorry but no - I have a limited budget so I am tearing envs down before starting a new one.  The only item I keep is auth.
