### ISSUE TITLE
Missing Start and Stop commands from User Roles document 

### ISSUE THREAD

**Issue by daemel** [microsoft/AzureTRE#2630]
Remember to label the issue with the appropriate area, and also assign it to yourself if you plan to work on the issue in the near future.

Reference: https://microsoft.github.io/AzureTRE/azure-tre-overview/user-roles/

Please add the commands for starting and stopping the TRE environment and what the impacts are ie:
- does removing the FW rules put data at risk
- how much $$ is saved by shutting down the TRE
- what items are stopped / deallocated and / or removed
- what is the impact of stopping the TRE environment, ie impacts to IP's and networking when the TRE is restarted

**Describe the bug**
The issues are 
- users are not aware of these commands (unless they read the makefile) which results un-necessary costs while users are not using the TRE environment 

TRE Start and Stop commands from the Makefile are not described in the documentation 

**Steps to reproduce**

1. go to this page... https://microsoft.github.io/AzureTRE/azure-tre-overview/user-roles/

**Comment by tamirkamara** [comment]
The commands are described in this document: https://microsoft.github.io/AzureTRE/tre-admins/start-stop/
