### ISSUE TITLE
Problem with creation of workspace app registration via script

### ISSUE THREAD

**Issue by david-salac** [microsoft/AzureTRE#2638]
I'm trying to create a basic workspace using `./devops/scripts/aad/create_workspace_application.sh` script. It always returns:
```
$ ./devops/scripts/aad/create_workspace_application.sh --name "XX" --admin-consent --ux-clientid XX --automation-clientid XX --application-admin-clientid XX

>>> OUTPUT:
ERROR: Resource '***' does not exist or one of its queried reference-property objects are not present.
```
Despite the fact that all parameters of the script are the correct Application (client) IDs (as I double-checked). Do you please know what might be wrong?

**Comment by marrobi** [comment]
I've just run this successfully. The `automation-clientid` is optional as per https://microsoft.github.io/AzureTRE/tre-admins/identities/workspace/#how-to-create

```
$ ./devops/scripts/aad/create_workspace_application.sh --name "test-ws" --admin-consent --ux-clientid "xx" --application-admin-clientid "xx"
Creating a Workspace Application in the "xx.onmicrosoft.com" Azure AD tenant.
Creating "test-ws API" app registration.
```

If you can I would recommend the automated creation of Workspace application registrations as it allows the TRE to create all the appropriate application registrations, and also assign groups to roles as per https://microsoft.github.io/AzureTRE/tre-admins/auth/#pre-requisites .

**Comment by david-salac** [comment]
Thanks for the reply. But, I did run `make auth` (before `make all`) with the default configuration of that `/templates/core/.env` file (including `AUTO_WORKSPACE_APP_REGISTRATION=true`). But generated `auth.env` file does not contain `WORKSPACE_API_CLIENT_ID` nor `WORKSPACE_API_CLIENT_SECRET`, as you can see:
```shell
APPLICATION_ADMIN_CLIENT_ID="XX"
APPLICATION_ADMIN_CLIENT_SECRET="XX"
TEST_ACCOUNT_CLIENT_ID="XX"
TEST_ACCOUNT_CLIENT_SECRET="XX"
API_CLIENT_ID="XX"
API_CLIENT_SECRET="XX"
SWAGGER_UI_CLIENT_ID="XX"
```
Is there any (other) way how to obtain those values?

**Comment by marrobi** [comment]
If `AUTO_WORKSPACE_APP_REGISTRATION=true` the app registration will be created automatically each time you deploy a workspace providing you pass `auto_create` into the application ID field.

This is described when using the UI, might be it's missing from the docs and needs to be added.

**Comment by david-salac** [comment]
1. Thank you, Marcus.
2. Yes, the documentation is very unclear.
3. For everyone that follows the QuickStart manual, in section 6 (Installing Base Workspace), subsection "Creating a base workspace", just run (in Swagger, route `/api/workspaces` method POST):
```json
{
  "templateName": "tre-workspace-base",
  "properties": {
    "display_name": "manual-from-swagger",
    "description": "workspace for team X",
    "client_id":"auto_create",
    "address_space_size": "medium"
  }
}
```
