### ISSUE TITLE
App Gateway gives 502 after TRE deployment - Open Census error

### ISSUE THREAD

**Issue by thisishusseinali** [microsoft/AzureTRE#2646]
**Describe the bug :**
> Deploy the Azure TRE and get a 502 on app gateway. 
- **The API app logs show :**
- `` WARNING:opencensus.ext.azure.common.transport:Forbidden error 403: {"itemsReceived":2,"itemsAccepted":0,"errors":[{"index":0,"statusCode":403,"message":"Component private link id does not match incoming link and has publicNetworkAccessForIngestion=Disabled"},{"index":1,"statusCode":403,"message":"Component private link id does not match incoming link and has publicNetworkAccessForIngestion=Disabled"}]}.``
> This looks like app insights private link DNS issues, maybe a race condition - need to check if the API might get deployed before the DNS zone?

**Comment by marrobi** [comment]
Duplicate #2598
