### ISSUE TITLE
Get 500 error from api when calling /link for export airlock request

### ISSUE THREAD

**Issue by jjgriff93** [microsoft/AzureTRE#2667]
**Describe the bug**
Both from the UI and the API directly I get a 500 Unable to process request error when trying to get a SAS link on a draft export airlock request. I'm authenticated as a researcher role and am able to generate links for import requests without any issues.

![image](https://user-images.githubusercontent.com/25235950/193071372-f7e180a1-f963-4b90-acfa-36c3e5cb81b9.png)

**Steps to reproduce**

1. Run the UI
1. Create an export airlock request as a researcher within a workspace
1. Press Generate on the files link field

**Comment by tanya-borisova** [comment]
In API logs I see:

```2022-10-03T10:52:00.315753103Z ERROR:root:(<urllib3.connection.HTTPSConnection object at 0x7fa6f0e4a880>, 'Connection to stalexintwsed08.blob.core.windows.net timed out. (connect timeout=20)')```

So something to do with networking for Airlock storage accounts
