### ISSUE TITLE
[BUG] Quickstart.md - make <label> fails on permissions

### ISSUE THREAD

**Issue by limorl** [microsoft/AzureTRE#267]
Remember to label the issue with the appropriate area, and also assign it to yourself if you plan to work on the issue in the near future.

**Describe the bug**
Running on Mac.
When following quickstart.md `make all` fails due to permission errors. Same when running each specific model: bootstrap, mgmt-deploy, build-api-image, etc... 

The way to workaround it to run all az and docker commands using `sudo, including `az login`.
 
**Steps to reproduce**

1. Go to quickstart.md when running from the dev container
2.  Click on `make all`
3 Hit permission errors 
4. change all az and docker commands to run as sudo.
5. `make all` works fine

**Comment by christoferlof** [comment]
@limorl is this one also resolved by PR #299 ?
