### ISSUE TITLE
Guacamole creation failed in 3rd step - "Add network firewall rules for guacamole"

### ISSUE THREAD

**Issue by dusan-ilic-mhra** [microsoft/AzureTRE#2715]
**Describe the bug**

We have successfully deployed v0.4.3 in both DEV and TEST environments. 
In DEV environment we deployed the workspace, guacamole, and VM successfully without any errors, 
but in TEST, workspace deployment was successful and Guacamole creation failed with this error in the last step:

{
  "operations": [
    {
      "id": "c83d0dbd-71d8-4118-8a02-c5b99efe9e77",
      "resourceId": "e7683927-14c0-452f-95f2-d469936eec76",
      "resourcePath": "/workspaces/9dc17d2e-6e3b-43ec-bf29-99919d543aab/workspace-services/e7683927-14c0-452f-95f2-d469936eec76",
      "resourceVersion": 0,
      "status": "deployment_failed",
      "action": "install",
      "message": "Multi step pipeline failed on step 260421b3-7308-491f-b531-e007cdc0ff46",
      "createdWhen": 1665392416.510277,
      "updatedWhen": 1665392719.765104,
      "user": {
        "id": "8f110c05-78a6-49d1-9e05-703f530a73b9",
        "name": "Dusan Ilic",
        "email": "",
        "roles": [
          "WorkspaceOwner"
        ],
        "roleAssignments": []
      },
      "steps": [
        {
          "stepId": "main",
          "stepTitle": "Main step for e7683927-14c0-452f-95f2-d469936eec76",
          "resourceId": "e7683927-14c0-452f-95f2-d469936eec76",
          "resourceTemplateName": "tre-service-guacamole",
          "resourceType": "workspace-service",
          "resourceAction": "install",
          "status": "deployed",
          "message": "e7683927-14c0-452f-95f2-d469936eec76: install action completed successfully.",
          "updatedWhen": 1665392622.373291
        },
        {
          "stepId": "12ba0dad-ea6c-4d0d-9255-d316212f5ffa",
          "stepTitle": "Add Guacamole URI as AAD redirect URI",
          "resourceId": "9dc17d2e-6e3b-43ec-bf29-99919d543aab",
          "resourceTemplateName": "tre-workspace-msl",
          "resourceType": "workspace",
          "resourceAction": "upgrade",
          "status": "updated",
          "message": "9dc17d2e-6e3b-43ec-bf29-99919d543aab: upgrade action completed successfully.",
          "updatedWhen": 1665392719.685193
        },
        {
          "stepId": "260421b3-7308-491f-b531-e007cdc0ff46",
          **"stepTitle": "Add network firewall rules for guacamole",**
          "resourceId": "115f3e59-bce2-4a25-89b0-4d029bd2f8ee",
          "resourceTemplateName": "tre-shared-service-firewall",
          "resourceType": "shared-service",
          "resourceAction": "upgrade",
          "status": "updating_failed",
          **"message": "<ValidationError: \"Additional properties are not allowed ('network_rule_collections' was unexpected)\">",**
          "updatedWhen": 1665392416.510241
        }
      ]
    }
  ]
}

We compared all templates and all versions are the same in both DEV and TEST.

**Steps to reproduce**

1. Deploy workspace
2. Deploy guacamole

Could you please advise how to solve this? 
**It is a blocker for us now.**

**Comment by marrobi** [comment]
@dusan-ilic-mhra I think this could be down to the firewall bundle version in use, and the fact it hasn't got the network_rule_collections property. Do you know what Firewall bundle version you are using?

@damoodamoo do you concur?

**Comment by marrobi** [comment]
Can you get the firewall shared service template via the API and verify it has the appropriate property. Can paste the output here. Thanks.

**Comment by marrobi** [comment]
That's all templates, we need just the firewall shared service template.

**Comment by dusan-ilic-mhra** [comment]
Here it is: 
![image](https://user-images.githubusercontent.com/104429461/194891839-7ef56a45-575a-477c-ae5d-3a09f5ba29fc.png)

And this is a response body:

{
  "id": "68a72c51-e601-4a46-b6bd-59cc3899e6ff",
  "name": "tre-shared-service-firewall",
  "title": "Firewall Shared Service",
  "description": "Provides Firewall shared service",
  "version": "0.4.3",
  "resourceType": "shared-service",
  "current": true,
  "type": "object",
  "required": [
    "display_name",
    "description"
  ],
  "properties": {
    "rule_collections": {
      "type": "array",
      "title": "rule_collections",
      "description": "",
      "default": [],
      "updateable": true,
      "items": {
        "title": "items",
        "type": "object",
        "required": [
          "name",
          "action",
          "rules"
        ],
        "properties": {
          "name": {
            "title": "name",
            "type": "string",
            "examples": [
              "my-rule"
            ],
            "pattern": "^.*$"
          },
          "priority": {
            "title": "priority",
            "type": "integer",
            "description": "Numeric priority for rule collection - leave blank for auto numbering",
            "examples": [
              110
            ]
          },
          "action": {
            "title": "action",
            "type": "string",
            "examples": [
              "Allow"
            ],
            "enum": [
              "Allow",
              "Deny"
            ]
          },
          "rules": {
            "title": "rules",
            "type": "array",
            "default": [],
            "items": {
              "title": "Items",
              "type": "object",
              "required": [
                "name"
              ],
              "properties": {
                "name": {
                  "title": "name",
                  "type": "string",
                  "examples": [
                    "rule 1"
                  ],
                  "pattern": "^.*$"
                },
                "description": {
                  "title": "description",
                  "type": "string",
                  "default": "",
                  "examples": [
                    "My rule description here"
                  ],
                  "pattern": "^.*$"
                },
                "protocols": {
                  "title": "protocols",
                  "type": "array",
                  "default": [],
                  "items": {
                    "title": "Items",
                    "type": "object",
                    "required": [
                      "port",
                      "type"
                    ],
                    "properties": {
                      "port": {
                        "title": "port",
                        "type": "string",
                        "examples": [
                          "1234"
                        ],
                        "pattern": "^.*$"
                      },
                      "type": {
                        "title": "type",
                        "type": "string",
                        "enum": [
                          "Http",
                          "Https",
                          "Mssql"
                        ],
                        "examples": [
                          "Http"
                        ]
                      }
                    }
                  }
                },
                "fqdn_tags": {
                  "title": "fqdn_tags",
                  "type": "array",
                  "default": [],
                  "items": {
                    "title": "Items",
                    "type": "string",
                    "default": "",
                    "enum": [
                      "AppServiceEnvironment",
                      "AzureBackup",
                      "AzureKubernetesService",
                      "HDInsight",
                      "MicrosoftActiveProtectionService",
                      "WindowsDiagnostics",
                      "WindowsUpdate",
                      "WindowsVirtualDesktop"
                    ],
                    "examples": [
                      "AzureKubernetesService"
                    ]
                  }
                },
                "target_fqdns": {
                  "title": "target_fqdns",
                  "type": "array",
                  "default": [],
                  "items": {
                    "title": "Items",
                    "type": "string",
                    "default": "",
                    "examples": [
                      "one.two.three.com"
                    ]
                  }
                },
                "source_addresses": {
                  "title": "Source_addresses",
                  "type": "array",
                  "default": [],
                  "items": {
                    "title": "Items",
                    "type": "string",
                    "default": "",
                    "examples": [
                      "172.196.0.0"
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "display_name": {
      "type": "string",
      "title": "Name for the shared service",
      "description": "The name of the shared service to be displayed to users",
      "updateable": true
    },
    "description": {
      "type": "string",
      "title": "Description of the shared service",
      "description": "Description of the shared service",
      "updateable": true
    },
    "overview": {
      "type": "string",
      "title": "Shared Service Overview",
      "description": "Long form description of the shared service, in markdown syntax",
      "updateable": true
    }
  },
  "actions": [],
  "customActions": [],
  "uiSchema": {},
  "additionalProperties": false,
  "system_properties": {
    "tre_id": {
      "type": "string",
      "title": "",
      "description": ""
    },
    "shared_service_id": {
      "type": "string",
      "title": "",
      "description": ""
    },
    "azure_location": {
      "type": "string",
      "title": "",
      "description": ""
    }
  }
}

**Comment by damoodamoo** [comment]
looks like you haven't got the latest firewall template installed? if you see here on `main` - there's a property called `network_rule_collections` you're missing... https://github.com/microsoft/AzureTRE/blob/239df38a2a19259897d801806fe0ad12e607e16e/templates/shared_services/firewall/template_schema.json#L169

**Comment by marrobi** [comment]
Maybe a merge issue, looks like that property is in '0.4.0'.

**Comment by dusan-ilic-mhra** [comment]
We have this one in **main** branch. We deployed this from **main** to **DEV** environment without problems, but here in **TEST** we have this issue.

This is **main** branch: 
![image](https://user-images.githubusercontent.com/104429461/195053407-aed6c3cd-0af7-4dd5-9e74-baa58962e50c.png)

We first put a version in cosmos DB manually as you can see from the screenshot above, and after that we deployed from CI.

**Comment by marrobi** [comment]
@dusan-ilic-mhra I've edit your message and deleted the history as included people's personal details.

the JSON shared here - https://github.com/microsoft/AzureTRE/issues/2715#issuecomment-1273420914 does not include `network_rule_collections` as in the JSON here - https://github.com/microsoft/AzureTRE/blob/764b0046edbb6ecaa5b8c18fc10225d44e75c940/templates/shared_services/firewall/template_schema.json

It seems that the latest version of the template has not been correctly registered in the TEST environment. Can you try registering the template again, you might need to increment the version on `porter.yaml` if it complains that it already exists. 

Then run the API call again to get the firewall shared services template, ensure that `network_rule_collections` is present in the response.

**Comment by dusan-ilic-mhra** [comment]
@marrobi 
I published and registered version 0.4.4 of tre-shared-service-firewall because it complained about the previous one. 
And, I can see now network_rule_collections in JSON here in templates:
![image](https://user-images.githubusercontent.com/104429461/195102396-921b106b-149e-44b5-9310-8a58106c9d9e.png)

Full response body:
{
  "id": "73f485e8-cfd8-4c0c-b3f2-5123dfdb8da1",
  "name": "tre-shared-service-firewall",
  "title": "Firewall Shared Service",
  "description": "Provides Firewall shared service",
  "version": "0.4.4",
  "resourceType": "shared-service",
  "current": true,
  "type": "object",
  "required": [
    "display_name",
    "description"
  ],
  "properties": {
    "rule_collections": {
      "type": "array",
      "title": "rule_collections",
      "description": "",
      "default": [],
      "updateable": true,
      "items": {
        "title": "items",
        "type": "object",
        "required": [
          "name",
          "action",
          "rules"
        ],
        "properties": {
          "name": {
            "title": "name",
            "type": "string",
            "examples": [
              "my-rule"
            ],
            "pattern": "^.*$"
          },
          "priority": {
            "title": "priority",
            "type": "integer",
            "description": "Numeric priority for rule collection - leave blank for auto numbering",
            "examples": [
              110
            ]
          },
          "action": {
            "title": "action",
            "type": "string",
            "examples": [
              "Allow"
            ],
            "enum": [
              "Allow",
              "Deny"
            ]
          },
          "rules": {
            "title": "rules",
            "type": "array",
            "default": [],
            "items": {
              "title": "Items",
              "type": "object",
              "required": [
                "name"
              ],
              "properties": {
                "name": {
                  "title": "name",
                  "type": "string",
                  "examples": [
                    "rule 1"
                  ],
                  "pattern": "^.*$"
                },
                "description": {
                  "title": "description",
                  "type": "string",
                  "default": "",
                  "examples": [
                    "My rule description here"
                  ],
                  "pattern": "^.*$"
                },
                "protocols": {
                  "title": "protocols",
                  "type": "array",
                  "default": [],
                  "items": {
                    "title": "Items",
                    "type": "object",
                    "required": [
                      "port",
                      "type"
                    ],
                    "properties": {
                      "port": {
                        "title": "port",
                        "type": "string",
                        "examples": [
                          "1234"
                        ],
                        "pattern": "^.*$"
                      },
                      "type": {
                        "title": "type",
                        "type": "string",
                        "enum": [
                          "Http",
                          "Https",
                          "Mssql"
                        ],
                        "examples": [
                          "Http"
                        ]
                      }
                    }
                  }
                },
                "fqdn_tags": {
                  "title": "fqdn_tags",
                  "type": "array",
                  "default": [],
                  "items": {
                    "title": "Items",
                    "type": "string",
                    "default": "",
                    "enum": [
                      "AppServiceEnvironment",
                      "AzureBackup",
                      "AzureKubernetesService",
                      "HDInsight",
                      "MicrosoftActiveProtectionService",
                      "WindowsDiagnostics",
                      "WindowsUpdate",
                      "WindowsVirtualDesktop"
                    ],
                    "examples": [
                      "AzureKubernetesService"
                    ]
                  }
                },
                "target_fqdns": {
                  "title": "target_fqdns",
                  "type": "array",
                  "default": [],
                  "items": {
                    "title": "Items",
                    "type": "string",
                    "default": "",
                    "examples": [
                      "one.two.three.com"
                    ]
                  }
                },
                "source_addresses": {
                  "title": "Source_addresses",
                  "type": "array",
                  "default": [],
                  "items": {
                    "title": "Items",
                    "type": "string",
                    "default": "",
                    "examples": [
                      "172.196.0.0"
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "network_rule_collections": {
      "type": "array",
      "title": "network_rule_collections",
      "description": "",
      "default": [],
      "updateable": true,
      "items": {
        "title": "items",
        "type": "object",
        "required": [
          "name",
          "action",
          "rules"
        ],
        "properties": {
          "name": {
            "title": "name",
            "type": "string",
            "examples": [
              "my-rule"
            ],
            "pattern": "^.*$"
          },
          "priority": {
            "title": "priority",
            "type": "integer",
            "description": "Numeric priority for rule collection - leave blank for auto numbering",
            "examples": [
              110
            ]
          },
          "action": {
            "title": "action",
            "type": "string",
            "examples": [
              "Allow"
            ],
            "enum": [
              "Allow",
              "Deny"
            ]
          },
          "rules": {
            "title": "rules",
            "type": "array",
            "default": [],
            "items": {
              "title": "Items",
              "type": "object",
              "required": [
                "name"
              ],
              "properties": {
                "name": {
                  "title": "name",
                  "type": "string",
                  "examples": [
                    "rule 1"
                  ],
                  "pattern": "^.{5,80}$"
                },
                "description": {
                  "title": "description",
                  "type": "string",
                  "default": "",
                  "examples": [
                    "My rule description here"
                  ],
                  "pattern": "^.*$"
                },
                "source_addresses": {
                  "title": "Source_addresses",
                  "type": "array",
                  "default": [],
                  "items": {
                    "title": "Items",
                    "type": "string",
                    "default": "",
                    "examples": [
                      "172.196.0.0"
                    ]
                  }
                },
                "source_ip_groups": {
                  "title": "Source_ip_groups",
                  "type": "array",
                  "default": [],
                  "items": {
                    "title": "Items",
                    "type": "string",
                    "default": "",
                    "examples": [
                      "some_ip_group_name"
                    ]
                  }
                },
                "destination_addresses": {
                  "title": "Destination_addresses",
                  "type": "array",
                  "default": [],
                  "items": {
                    "title": "Items",
                    "type": "string",
                    "default": "",
                    "examples": [
                      "172.196.0.0"
                    ]
                  }
                },
                "destination_ip_groups": {
                  "title": "Destination_ip_groups",
                  "type": "array",
                  "default": [],
                  "items": {
                    "title": "Items",
                    "type": "string",
                    "default": "",
                    "examples": [
                      "some_ip_group_name"
                    ]
                  }
                },
                "destination_fqdns": {
                  "title": "Destination_fqdns",
                  "type": "array",
                  "default": [],
                  "items": {
                    "title": "Items",
                    "type": "string",
                    "default": "",
                    "examples": [
                      "one.two.three.com"
                    ]
                  }
                },
                "destination_ports": {
                  "title": "Destination_ports",
                  "type": "array",
                  "default": [],
                  "items": {
                    "title": "Items",
                    "type": "string",
                    "default": "",
                    "examples": [
                      "80",
                      "443",
                      "*"
                    ]
                  }
                },
                "protocols": {
                  "title": "protocols",
                  "type": "array",
                  "default": [],
                  "items": {
                    "title": "Items",
                    "type": "string",
                    "enum": [
                      "Any",
                      "ICMP",
                      "TCP",
                      "UDP"
                    ],
                    "examples": [
                      "TCP"
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "display_name": {
      "type": "string",
      "title": "Name for the shared service",
      "description": "The name of the shared service to be displayed to users",
      "updateable": true
    },
    "description": {
      "type": "string",
      "title": "Description of the shared service",
      "description": "Description of the shared service",
      "updateable": true
    },
    "overview": {
      "type": "string",
      "title": "Shared Service Overview",
      "description": "Long form description of the shared service, in markdown syntax",
      "updateable": true
    }
  },
  "actions": [],
  "customActions": [],
  "uiSchema": {},
  "additionalProperties": false,
  "system_properties": {
    "tre_id": {
      "type": "string",
      "title": "",
      "description": ""
    },
    "shared_service_id": {
      "type": "string",
      "title": "",
      "description": ""
    },
    "azure_location": {
      "type": "string",
      "title": "",
      "description": ""
    }
  }
}

Now, I guess we need to deploy/update the existing firewall, right?
How to do that through swagger, just by running POST like this:
![image](https://user-images.githubusercontent.com/104429461/195103538-02ef54d4-eca3-48a1-a34b-ad2a1087b1b9.png)
?

Just to note, that we need to update the existing one.

**Comment by dusan-ilic-mhra** [comment]
Now we got this: 

![image](https://user-images.githubusercontent.com/104429461/195116215-93dc489f-14e5-4f89-aac3-8b353bccc773.png)

I'll try to restart the environment and deploy it again.

**Comment by dusan-ilic-mhra** [comment]
I restarted the environment and tried to deploy guacamole again, and I got the same error:
![image](https://user-images.githubusercontent.com/104429461/195148125-374ce649-36b3-4bd0-9c78-07066cd0682a.png)
Then, I tried to deploy a new workspace, I'm getting this now:
![image](https://user-images.githubusercontent.com/104429461/195148355-2c021a0a-99a2-4528-9d81-360922df331e.png)

**Comment by marrobi** [comment]
@dusan-ilic-mhra when you say restarted the environment, how do you mean? The 504 suggests the API app has an issue. Have you looked at the API status in the app gateway backend health?

If you connect to the resource processor, can you carry out `az rest` calls against `management.azure.com`?

**Comment by dusan-ilic-mhra** [comment]
I run **make tre-stop**, and then **make tre-start**.

This is what we get from the health probe:
![image](https://user-images.githubusercontent.com/104429461/195150903-cfde72db-6efd-4c58-b4f6-e956947b73b2.png)

And, backend pool for API:
![image](https://user-images.githubusercontent.com/104429461/195151115-536477cb-6025-46a1-80aa-3b4cdefdb9bc.png)

**Comment by dusan-ilic-mhra** [comment]
The same gateway configuration worked yesterday and today.

**Comment by marrobi** [comment]
I'd avoid running `make tre-start` and `make tre-stop` when troubleshooting. It's not really restarting the system, but a way to deallocate resources to save some money.

Can you try manually editing the health probe for app gateway in the portal - say increasing the timeout, hitting `Test` before you save and see what comes back.

**Comment by dusan-ilic-mhra** [comment]
The same:
![image](https://user-images.githubusercontent.com/104429461/195152772-efb2e0d5-db89-4fd3-8d5d-e514ef0a8641.png)

**Comment by dusan-ilic-mhra** [comment]
Now it's healthy without any change, odd: 

![image](https://user-images.githubusercontent.com/104429461/195155502-37d1d0f9-3d19-4aca-87da-543c13b2c3cf.png)

**Comment by dusan-ilic-mhra** [comment]
And, again unhealthy:
![image](https://user-images.githubusercontent.com/104429461/195156138-c91cf34c-5b66-4006-b861-7b8e949a2190.png)

Could you please check if is there any change or maintenance on Microsoft backbone, because we didn't change App Gateway settings?

**Comment by marrobi** [comment]
Any errors in the API app logs? Could be the API is restarting.

Actually, check your firewall is healthy. Might be one of the start/stop has caused a problem with outbound connectivity.

**Comment by dusan-ilic-mhra** [comment]
We can see these errors: 
![image](https://user-images.githubusercontent.com/104429461/195162581-39961a2d-87cc-44f9-8fbe-11a25436751b.png)
![image](https://user-images.githubusercontent.com/104429461/195163025-8fb18a91-9110-4227-9fd9-e700860201d6.png)

But, why start/stop would cause this? 
The environment is stopped every night automatically and we need to start it in the morning.

**Comment by dusan-ilic-mhra** [comment]
Again healthy:
![image](https://user-images.githubusercontent.com/104429461/195165526-38f770ef-3aa1-4c59-8595-ed3741dc2e53.png)

And, we can't see any timeout issues:
![image](https://user-images.githubusercontent.com/104429461/195165773-24602c21-4334-44d7-bc14-516080c09e52.png)

Without any change.

**Comment by dusan-ilic-mhra** [comment]
And, again: 
![image](https://user-images.githubusercontent.com/104429461/195166988-833a3d6a-4d86-4d1a-af29-900cd8b53cd1.png)

**Comment by marrobi** [comment]
It looks like an issue with the MSI token endpoint. I feel this is unrelated to the `management.azure.com` timeout at deploy time. If the timeout still appears, I suggest changing app service plan sku from say `P1v3` to `P2v3` and see if it resolves. This will force a redeploy of the web app.

Once it is stable, try the deployment, if you still get the `management.azure.com` issue, suggest jumping onto the resource processor and checking external connectivity.

**Comment by dusan-ilic-mhra** [comment]
This morning we don't have an issue. I deployed successfully a new workspace, also guacamole and VM:

As you can see new, 3rd step for guacamole succeeded after we published and registered the firewall template with an increased porter version:

{
  "operations": [
    {
      "id": "3a8c7893-2669-4837-9a24-f1edd453608b",
      "resourceId": "35d301b1-511a-4f6d-b81a-46e627bbcaf5",
      "resourcePath": "/workspaces/d91041b1-275a-4e79-9301-6df65916898e/workspace-services/35d301b1-511a-4f6d-b81a-46e627bbcaf5",
      "resourceVersion": 0,
      "status": "deployed",
      "action": "install",
      "message": "Multi step pipeline completed successfully",
      "createdWhen": 1665560308.141138,
      "updatedWhen": 1665560961.137825,
      "user": {
        "id": "8f110c05-78a6-49d1-9e05-703f530a73b9",
        "name": "Dusan Ilic",
        "email": "",
        "roles": [
          "WorkspaceOwner"
        ],
        "roleAssignments": []
      },
      "steps": [
        {
          "stepId": "main",
          "stepTitle": "Main step for 35d301b1-511a-4f6d-b81a-46e627bbcaf5",
          "resourceId": "35d301b1-511a-4f6d-b81a-46e627bbcaf5",
          "resourceTemplateName": "tre-service-guacamole",
          "resourceType": "workspace-service",
          "resourceAction": "install",
          "status": "deployed",
          "message": "35d301b1-511a-4f6d-b81a-46e627bbcaf5: install action completed successfully.",
          "updatedWhen": 1665560482.531701
        },
        {
          "stepId": "12ba0dad-ea6c-4d0d-9255-d316212f5ffa",
          "stepTitle": "Add Guacamole URI as AAD redirect URI",
          "resourceId": "d91041b1-275a-4e79-9301-6df65916898e",
          "resourceTemplateName": "tre-workspace-msl",
          "resourceType": "workspace",
          "resourceAction": "upgrade",
          "status": "updated",
          "message": "d91041b1-275a-4e79-9301-6df65916898e: upgrade action completed successfully.",
          "updatedWhen": 1665560578.571059
        },
        {
          "stepId": "260421b3-7308-491f-b531-e007cdc0ff46",
          "stepTitle": "Add network firewall rules for guacamole",
          "resourceId": "115f3e59-bce2-4a25-89b0-4d029bd2f8ee",
          "resourceTemplateName": "tre-shared-service-firewall",
          "resourceType": "shared-service",
          "resourceAction": "upgrade",
          "status": "**updated**",
          "message": "115f3e59-bce2-4a25-89b0-4d029bd2f8ee: upgrade action completed successfully.",
          "updatedWhen": 1665560961.137815
        }
      ]
    }
  ]
}

**Comment by marrobi** [comment]
Great, glad its sorted.

**Comment by dusan-ilic-mhra** [comment]
Thank you for the help.
