### ISSUE TITLE
Upgrade OAuth Proxy to 7.4.X

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#2732]
We current use oauth proxy 7.2.1, we need to upgrade to 7.3.0see

https://github.com/marrobi/AzureTRE/blob/4fa3e3dd5a08204fff1c171eabf3550713bbe80e/templates/workspace_services/guacamole/guacamole-server/docker/Dockerfile#L67

**Comment by Lakshayainani** [comment]
Can I pick this up?

**Comment by tamirkamara** [comment]
Why do we *need* to upgrade? Anything we'd like to have?

**Comment by marrobi** [comment]
There are a couple of bugs I want to see if they get resolved, and it does mention CVEs. I was going to add issues for the bugs today and links to the oauth_proxy issues.

**Comment by marrobi** [comment]
This needs to be resolved before can be upgraded. 

https://github.com/oauth2-proxy/oauth2-proxy/issues/1680

**Comment by marrobi** [comment]
Looks like resolved in 0.7.4, but might need additional properties setting - https://github.com/oauth2-proxy/oauth2-proxy/issues/1680#issuecomment-1310020120
