### ISSUE TITLE
UI for Airlock Review VM

### ISSUE THREAD

**Issue by tanya-borisova** [microsoft/AzureTRE#2738]
https://www.figma.com/file/Ncl8TJsFf2WKf3frrqTbtq/AzureTRE-OSS-UI?node-id=1293%3A27999

**Comment by jjgriff93** [comment]
Enable UI as per Figma designs:

![image](https://user-images.githubusercontent.com/25235950/196191349-01034e41-3898-454d-8907-0e3e9eb8f05d.png)
