### ISSUE TITLE
Control researcher access on workspace and VM level

### ISSUE THREAD

**Issue by dusan-ilic-mhra** [microsoft/AzureTRE#2739]
We would like to control researcher access on the workspace level and on the level of the virtual machine. 

So, we would like for the researcher to be able to see the workspace, 
and if we have e.g. 2 virtual machines in that workspace, we need to enable him to see and access a specific one of them. 

Could you please advise how we could configure this?

**Comment by tamirkamara** [comment]
@dusan-ilic-mhra the workspace enterprise application has the roles and users. A user will only see a workspace if they are assigned a role in the workspace (or defined globally as a treadmin) 
A researcher will see only VMs (user resources) they created.
Is this what you meant?

**Comment by marrobi** [comment]
Is this what you are after? To be able to create a VM as workspace owner for a user? So users don't/can't create their own VMs?

https://github.com/microsoft/AzureTRE/issues/1179

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara Related to your question:
_"A researcher will see only VMs (user resources) they created.
Is this what you meant?"_
If we have 3 VMs in the workspace, and 3 researchers, we would like to set permissions so that each of them can see only their one dedicated VM, not everyone can see and access all the VMs. That's our point.

**Comment by tamirkamara** [comment]
This is how it should work already.

**Comment by dusan-ilic-mhra** [comment]
But, in one workspace, not 3 VMs is 3 workspaces?

**Comment by tamirkamara** [comment]
Right, in a single workspace a vm is only visible for the researcher that created it.

**Comment by dusan-ilic-mhra** [comment]
We have this user TRE_TEST_USER with roles:

- Workspace Researcher - in WORKSPACE_API_CLIENT_ID
![image](https://user-images.githubusercontent.com/104429461/195817659-95cb151e-615d-49a6-80f5-d0e395bf6567.png)

- TRE Users - in API_CLIENT_ID
![image](https://user-images.githubusercontent.com/104429461/195817585-22607cd5-2cbb-4616-a0cb-4287f5edb517.png)


Workspace Owner created workspaces and VMs inside, and I'm logged in to Swagger with this user TRE_TEST_USER, 
and I see 2  workspaces created by Workspace Owner/TRE Admin:
![image](https://user-images.githubusercontent.com/104429461/195820005-7aa67efd-c47e-45b2-89e9-3611c8c7b872.png)

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara We tested, and you were right, _vm is only visible for the researcher that created it._
You can close the issue and if we experience it again we will open another one. 
Thank you.
