### ISSUE TITLE
Deployment failure due to db-migrate

### ISSUE THREAD

**Issue by t-young31** [microsoft/AzureTRE#2751]
**Describe the bug**

We've updated to v0.5.1 and are having trouble deploying the TRE. The deployment fails with

```
make: *** [/home/vscode/AzureTRE/Makefile:344: db-migrate] Error 1
HTTP/1.1 400 Bad Request
Date: Tue, 18 Oct 2022 16:52:04 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 23
Connection: keep-alive
Server: uvicorn

list index out of range
Error while migrating state store
Error: Process completed with exit code 2.
```

I've dug into this a little more and the 400 occurs at https://github.com/microsoft/AzureTRE/blob/316b9d168a05c880f4f4ae168eb2fb3e699e3085/devops/scripts/migrate_state_store.sh#L81

I'm pretty certain the secrets are right, but could be proved otherwise! 

**Steps to reproduce**

1. Run deployment pipeline https://github.com/microsoft/AzureTRE-Deployment/blob/main/.github/workflows/deploy_tre.yml 

cc: @marrobi

**Comment by tamirkamara** [comment]
@t-young31 can you access the app insights (appi*) in the environment in question and run this query to look from exceptions in the time that has happened?
```
exceptions
| order by timestamp desc
```

**Comment by t-young31** [comment]
<img width="600" alt="Screenshot 2022-10-19 at 08 39 27" src="https://user-images.githubusercontent.com/39765193/196627282-4664ec06-7050-491b-8292-5f04e45fb9e2.png">

**Comment by tamirkamara** [comment]
@t-young31 is the firewall installed in your TRE environment?

**Comment by t-young31** [comment]
hmm, it looks like the firewall has failed to deploy due to something already existing in the tf state

**Comment by tamirkamara** [comment]
@t-young31 we think there's a bug where the install action of the firewall returns an ok status despite failing. This is being fixed as part of this: https://github.com/microsoft/AzureTRE/pull/2747
CC: @stuartleeks

**Comment by t-young31** [comment]
just to close the loop on this one – once the firewall was deployed successfully the migration worked just fine. thanks for the tips!
