### ISSUE TITLE
Deployment optimisations

### ISSUE THREAD

**Issue by t-young31** [microsoft/AzureTRE#2753]
## Description

When running deployment pipelines it would be nice if 

-  the bundles that are already present aren't rebuilt and reregistered 
-  RP vm wasn't re-imaged when there aren't any changes (`module.resource_processor_vmss_porter[0].null_resource.vm_linux_reimage`)

## Acceptance criteria

- [ ] Steps in the pipeline to be skipped if they can be

**Comment by tamirkamara** [comment]
Adding something to an offline conversation we had in the team regarding:
> bundles that are already present aren't rebuilt and reregistered
This is probably not the way to save time - we had issues in the past where developers made changes to bundles and forgot to advance the version. If we'll rely on a bundle's version being registered and skip its build/publish/register flow we won't catch that. 
I think the correct behavior is find regarding how we catch these types of errors. As for the time cost of these activities I completely agree. In porter v1 there're many changes regarding how bundles are built and cache is used, I foresee that helping here.

**Comment by tamirkamara** [comment]
I think this issues described above are now as resolved as we're willing to take them:
1. Porter v1 improved build/publish time
2. Using a different TF method to decide when to reimage the vmss reduced the freq of false positives.
