### ISSUE TITLE
Upgrading TRE version docs should be more clear

### ISSUE THREAD

**Issue by LizaShak** [microsoft/AzureTRE#2760]
**Describe the bug**

We should update the docs regarding upgrading the Azure TRE version in the deployment repo. It's not as simple as:

> To upgrade AzureTRE version go to [devcontainer.json](https://github.com/microsoft/AzureTRE-Deployment/blob/main/.devcontainer/devcontainer.json) and update the OSS_VERSION param to the desired version.

1. In https://github.com/microsoft/AzureTRE-Deployment#upgrading-azuretre-version headings are a bit confusing, the "Configuration Setup" looks like a subheading of Upgrading.

2. Add steps about updating the workflows and dev container.

Use:
git remote add upstream https://github.com/microsoft/AzureTRE-Deployment
git pull upstream azuretre-v0.5.1 --allow-unrelated-histories

Then going through the merge bit by bit.

**Comment by marrobi** [comment]
The upgrading instructions should be in the docs, rather than in the deployment rep - lets keep all docs in one place and direct people to there.

**Comment by marrobi** [comment]
We are still missing the commands in the issue description which are needed to upgrade a deployment repo created from our deployment repo.
