### ISSUE TITLE
New Porter Plugin/Mixin versions break the system

### ISSUE THREAD

**Issue by tamirkamara** [microsoft/AzureTRE#2761]
**Describe the bug**

The Porter Azure plugin has recently been updated with a breaking change - they removed support in Azure Tables for state storage.
This breaks the Resource Processor if its image is being rebuilt from scratch.

**Comment by marrobi** [comment]
Running:

```
/app# porter plugins uninstall  azure
Uninstalled azure plugin
 
/app# porter plugins install azure --version v0.11.2
installed azure plugin v0.11.2 (894e361)
```

in the docker container running the resource processor resolves, also had to open firewalls rules for the RP subnet.

```
cdn.porter.sh
*.githubusercontent.com
```

A release will be created to fix this.
