### ISSUE TITLE
Uninstalling guacamole ws service doesn't remove fw rules

### ISSUE THREAD

**Issue by t-young31** [microsoft/AzureTRE#2776]
**Describe the bug**

Uninstalling a Guacamole workspace service for VMs does not remove the firewall rules. Just seems to be missing from the template:

https://github.com/microsoft/AzureTRE/blob/18d53d5cb4b2cc384eeaa6a72f31177b8a945606/templates/workspace_services/guacamole/template_schema.json#L121

Please  do close this if this is the intended behaviour, but I couldn't see why it should be!

**Steps to reproduce**

1. Create Guacamole workspace service in a TRE (with UI)
1. Delete service
1. Find that the fw rules for the deleted object are still there

**Comment by marrobi** [comment]
@t-young31 yes, looks like that is missing.

@damoodamoo  can you confirm deleting rules in pipeline should work fine?
