### ISSUE TITLE
Cannot create private AML compute

### ISSUE THREAD

**Issue by t-young31** [microsoft/AzureTRE#2780]
**Describe the bug**
When trying to create AML compute with no public IP fails with

```
Provisioning error
The subnet has a network security group (/subscriptions/xxx/resourceGroups/rg-xxx-ws-
98b8/providers/Microsoft.Network/networkSecurityGroups/nsg-ws) that is
missing the following rules below. Please add those rules or increase the
priority to allow traffic if the rules already exist. For network security group
requirements, please refer to https://docs.microsoft.com/azure/machine-
learning/how-to-secure-training-vnet?tabs=azure-studio#azure-machine.
learning-compute-clusterinstance-1.
f
"name": "Outbound Storage 445"
"properties": {
"protocol": "TCP",
"sourcePortRange": "*"
"destinationPortRange": "445"
"sourceAddressPrefix": "VirtualNetwork"
"destinationAddressPrefix": "Storage OR Internet OR Storage.uksouth",
"priority": "Higher than 4096",
"direction": "Outbound"
```

Looks like the compute is trying to access public storage(?), which is disabled https://github.com/microsoft/AzureTRE/blob/ae3efacebc864ae310aa7eb753d7d002be5aff49/templates/workspace_services/azureml/terraform/network.tf#L110 

because the service isn't exposed externally. I've had a look at https://learn.microsoft.com/en-us/azure/machine-learning/how-to-secure-workspace-vnet?tabs=pe%2Ccli#azure-storage-account and there is some storage inside the ws vnet that has a private endpoint, so I'm not really any the wiser. 

Any help would be much appreciated! 

**Steps to reproduce**

1. Deploy TRE v0.6.0
2. Create workspace with AML (not exposed publicly) and VMs (exposed publicly)
3. Log into VM
4. Go to the AML URL
5. Try to create some compute, ticking the "No public IP (preview)" checkbox

**Comment by marrobi** [comment]
@t-young31 agree. The docs say:

> (*) 445 is only required if you have a firewall between your virtual network for Azure ML and a private endpoint for your storage accounts.

So not sure why this is being requested. Will ask some questions internally and get back to you.

**Comment by marrobi** [comment]
@t-young31  I read the docs incorrectly -  it's if you have private endpoints 445 is still required. 

We can limit what that can connect to using a service endpoint policy on the subnet - https://github.com/jhirono/azureml-dlp

What I'm thinking at the moment is that a dedicated subnet for AML is created and the firewall allows outbound traffic form only that subnet, and that subnet has the endpoint policy configured.

Hopefully this will be easier longer term.

**Comment by marrobi** [comment]
This would be a prerequisite to this https://github.com/microsoft/AzureTRE/issues/1846
