### ISSUE TITLE
Airlock VM Deletion Failed

### ISSUE THREAD

**Issue by JaimieWi** [microsoft/AzureTRE#2788]
Remember to label the issue with the appropriate area, and also assign it to yourself if you plan to work on the issue in the near future.

**Describe the bug**
When going through the Airlock process, a reviewer VM should automatically delete when no longer in use. Instead, an error related to `waiting for update of Network Interface` occurred.

**Steps to reproduce**
**As a Reviewer.**
1. Review an Airlock Request, in this case it was an Export request. The VM should automatically delete. Instead an error occurred for the operation, this text file shows the message in Cosmos DB. 
[Airlock_Error_Cosmos.txt](https://github.com/microsoft/AzureTRE/files/9877772/Airlock_Error_Cosmos.txt)
2. Manually deleting the VM from Cosmos and going through the same process again was successful, so it is an intermittent error.

**Comment by tanya-borisova** [comment]
From the error logs it looks like the error was transient. Closing this but feel free to reopen if this occurs again
