### ISSUE TITLE
[BUG] Running make build-api-image fails on docker not installed

### ISSUE THREAD

**Issue by limorl** [microsoft/AzureTRE#280]
**Describe the bug**
When going over quickstart on a clean environment (on Mac). 
make bootstrap completes successfully but then `make build-api-image` fails on docker not installed.

The way to workaround it is to run the following commands manually, including docker build using sudo:
build-api-image:
	echo -e "\n\e[34m»»» 🧩 \e[96mBuilding API Image\e[0m..." \
	&& . ./devops/scripts/check_dependencies.sh \
	&& . ./devops/scripts/load_env.sh ./devops/.env \
	&& docker build -t "$${ACR_NAME}.azurecr.io/microsoft/azuretre/management-api:$${IMAGE_TAG}" ./management_api_app/

 

**Steps to reproduce**

1. run `make bootstrap` successfully
2. run `make mgmt-deploy`
2. run `make build-api-image`
3. Get the following error:
»»» ✅ Checking pre-reqs...

Checking for Azure CLI...

**Checking for Docker...
»»» **⚠️ Docker is not installed! 😥 Please go to https://docs.docker.com/engine/install/ to set it up****

4. Run the commands manually
     ./devops/scripts/check_dependencies.sh \
     ./devops/scripts/load_env.sh ./devops/.env \
     *sudo* docker build -t "$${ACR_NAME}.azurecr.io/microsoft/azuretre/management-api:$${IMAGE_TAG}"

**Comment by limorl** [comment]
None issue (missing mgmt build)

**Comment by marrobi** [comment]
@limorl  I can't replicate this, but could be my docker setup.

Can you try:

https://itprohelper.com/run-docker-without-sudo-linux/

**Comment by limorl** [comment]
PR #299 merged
