### ISSUE TITLE
Update docs to use new bundle make commands

### ISSUE THREAD

**Issue by LizaShak** [microsoft/AzureTRE#2807]
## Description

As a TRE Administrator
I want the docs to be updated and use the following `make` commands:
- workspace_bundle
- workspace_service_bundle
- shared_service_bundle
- user_resource_bundle
So that the docs updated to the latest guidance.

## Acceptance criteria

- [ ] Docs `make bundle-build/publish/register` are updated

**Comment by tanya-borisova** [comment]
Done in https://github.com/microsoft/AzureTRE/pull/2857
