### ISSUE TITLE
Gitea Shared Service fails to install in E2E

### ISSUE THREAD

**Issue by tamirkamara** [microsoft/AzureTRE#2824]
**Describe the bug**
The E2E (nightly) installs and un-installs the gitea shared service but after a few times fails to do so. The problem is with the secrets stored in KV.

│ Error: A resource with the ID "https://kv-maintre2.vault.azure.net/secrets/gitea-maintre2-administrator-password/4a970f2650f546d9959bce8ca7ca2b3c" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_key_vault_secret" for more information.
│
│ with azurerm_key_vault_secret.gitea_password,
│ on gitea-webapp.tf line 162, in resource "azurerm_key_vault_secret" "gitea_password":
│ 162: resource "azurerm_key_vault_secret" "gitea_password" {

**Comment by tanya-borisova** [comment]
I've imported that secret and tried to re-deploy on main. However I am now getting a different error:

```
╷
│ Error: keyvault.BaseClient#SetSecret: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="Conflict" Message="Secret gitea-maintre2-administrator-password is currently being recovered and cannot be re-created; retry later." InnerError={"code":"ObjectIsBeingRecovered"}
│
│ with azurerm_key_vault_secret.gitea_password,
│ on gitea-webapp.tf line 162, in resource "azurerm_key_vault_secret" "gitea_password":
│ 162: resource "azurerm_key_vault_secret" "gitea_password" {
│
╵
```

**Comment by tanya-borisova** [comment]
It is the same error as we've started getting in our PR environments recently too:

![image](https://user-images.githubusercontent.com/52954123/201173216-dc348461-2f9d-4ffa-92a6-477ff0c01253.png)

**Comment by tamirkamara** [comment]
The underlining issue is this: https://github.com/microsoft/AzureTRE/issues/2904
Closing this one.
