### ISSUE TITLE
Enable terraform step in workspace bundle upgrade

### ISSUE THREAD

**Issue by tamirkamara** [microsoft/AzureTRE#2847]
## Description

As a TRE Administrator 
I want to update workspace properties after it's initial provisioning AND those will be sent to terraform
So that the workspace infrastructure could be updated.

## Acceptance criteria

- [ ] A property sent to terraform and updates are reflected in Azure

**Comment by marrobi** [comment]
This seems to work, or could use the secret value:

```

data "azurerm_key_vault_secret" "secret" {
  count        = var.action == "install" ? 0 : 1
  name         = "mysecret"
  key_vault_id = azurerm_key_vault.kv.id
}

resource "azurerm_key_vault_secret" "secret" {
  name         = "mysecret"
  value        = var.action == "install" ? var.secret_value : data.azurerm_key_vault_secret.secret[0].value
  key_vault_id = azurerm_key_vault.kv.id
}
```

**Comment by tamirkamara** [comment]
Reopening as this is blocked by: https://github.com/microsoft/AzureTRE/issues/2913
