### ISSUE TITLE
Display a specific error on the UI when the user doesn't have a required role

### ISSUE THREAD

**Issue by tanya-borisova** [microsoft/AzureTRE#2861]
Remember to label the issue with the appropriate area, and also assign it to yourself if you plan to work on the issue in the near future.

**Describe the bug**
Currently, we only display a generic 500 page when a user doesn't have a required role, and hide a specific error message, which makes it hard to understand what the problem is. 

![image](https://user-images.githubusercontent.com/52954123/201156510-be62fdd7-774d-4c76-8fde-0016273f35a7.png)

**Steps to reproduce**

1. Remove oneself from TREUSer / TREAdmin
1. Navigate to TRE home page

**Comment by marrobi** [comment]
@damoodamoo  did you fix this today?

**Comment by marrobi** [comment]
Just tested, and is ok:


![Image](https://github.com/microsoft/AzureTRE/assets/17089773/a7144cdc-197e-4992-8b78-ae3923740ce1)
