### ISSUE TITLE
[Task] Add shared service resources to the state store

### ISSUE THREAD

**Issue by deniscep** [microsoft/AzureTRE#289]
Feature: #23  

- Modify the state store so that it can store state for the shared services (API)
- resources of type "shared_service"

Does this need a shared service API with create and update?

**Comment by jjcollinge** [comment]
@deniscep we'd need to ensure we used etag/precondition on writes to the DB to ensure concurrency is managed here. The initial shared resource documents also need adding during bootstrapping/deployment.

**Comment by damoodamoo** [comment]
Closing as covered in #1239
