### ISSUE TITLE
Airlock Import Request 504 Gateway Timeout

### ISSUE THREAD

**Issue by RIashfaqahmed** [microsoft/AzureTRE#2895]
Remember to label the issue with the appropriate area, and also assign it to yourself if you plan to work on the issue in the near future.

**Describe the bug**
While creating Import Request I get **504 Gateway Time-out** when I try to **Generate** URL

<img width="193" alt="image" src="https://user-images.githubusercontent.com/25818860/203277806-4e109839-693c-4b98-ad38-91fa560f60c5.png">

**Steps to reproduce**

1. In Workspace, Click on Airlock | New Request | Import
2. Enter **Title** & **Justification** | Create | Create
3.  Click **Generate**

**Comment by marrobi** [comment]
Is this when clicking here?
![image](https://user-images.githubusercontent.com/17089773/203286958-b6f35738-6d91-4f1e-b11e-a7e4f2d1a00e.png)

Does it happen if you retry?

**Comment by RIashfaqahmed** [comment]
> Is this when clicking here? ![image](https://user-images.githubusercontent.com/17089773/203286958-b6f35738-6d91-4f1e-b11e-a7e4f2d1a00e.png)
> 
> Does it happen if you retry?

yes

**Comment by marrobi** [comment]
@RIashfaqahmed let us know if need any help. It's not something we are seeing elsewhere so will need to get into the logs.

**Comment by RIashfaqahmed** [comment]
Hi @marrobi,

Debug was already set to True.  I tried to generate URL from from both TRE-UI and TRE-API, but same result


<img width="331" alt="image" src="https://user-images.githubusercontent.com/25818860/203529154-f36d56cc-936b-4e12-ad30-5cfa5616f63d.png">

---------------------

I ran following query in LogAnalytics instance, and got no results

```
AppTraces 
| where AppRoleName == "uvicorn"
| order by TimeGenerated desc 
```

```
No results found from the last 24 hours  
Try  selecting another time range 
```

<img width="221" alt="image" src="https://user-images.githubusercontent.com/25818860/203532136-7add8212-5136-4000-baae-10016d6894e0.png">

------------------------


I did further investigation by running a query against AppTraces and found following which might help, 
**AppTraces**


```
Message

Request URL: 'https://stalimex------.blob.core.windows.net/----------?restype=REDACTED'
Request method: 'PUT'
Request headers:
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.14.1 Python/3.8.15 (Linux-5.4.0-1089-azure-x86_64-with-glibc2.2.5)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '------------'
    'Authorization': 'REDACTED'
No body was attached to the request
```

----

**Comment by marrobi** [comment]
Do you know if any corporate Azure policies are adjusting the deployed infrastructure?

If you can mail me at marcus.robinson at microsoft.com happy to take a look given the airlock is still relatively new.

**Comment by RIashfaqahmed** [comment]
Hi @marrobi, keeping investigation continued, I ran following query
```
AppServiceHTTPLogs  
| where TimeGenerated  between (todatetime("2022-11-23 09:55:31") .. todatetime("2022-11-23 09:59:59") ) 
| order by TimeGenerated desc
```
and following result captured my attention having **SCStatus of 499 (client closed request)**, requests are timing out exactly after 60 secs of clicking **Generate** button.

```
CsMethod        GET
CsUriStem       /api/workspaces/XXXXXXXXXXXX/requests/XXXXXXXXXXXXX/link
_ResourceId     /subscriptions/XXXXXXXXXXXX/resourcegroups/rg-TRE_ID/providers/microsoft.web/sites/api-TRE_ID
CsHost          api-TRE_ID.azurewebsites.net
ScStatus        499
Result          CallerError
```

**Comment by tamirkamara** [comment]
Please try to look at the specifc API logs with the following:
```
traces
| where cloud_RoleName == "api"
| order by timestamp desc
```
Add your timestamp range and also look at the `exceptions` table (replace `traces`).

Another thing:
Examine the stalimex*** storage account -> networking:
1. Firewalls and virtual networks tab - should have "enable from all networks"
2. Private endpoint connections - should have one line

**Comment by RIashfaqahmed** [comment]
> That suggests there is some sort of issue connecting to the storage account endpoint. Let me discuss with the team and see if we can come up with some steps to investigate.
> 
> Have you stopping and starting the web app? It could be it is a DNS caching issue we need to track down.

I have restarted **api-<TRE-ID>**, but same issue. 504 Gateway Timeout

**Comment by RIashfaqahmed** [comment]
Firewall is enabled for **All Networks** with one endpoint

--------
![image](https://user-images.githubusercontent.com/25818860/203621904-93187fc0-8c65-487d-9d3f-8090c354eb18.png)

----------
![image](https://user-images.githubusercontent.com/25818860/203743557-1c601101-6956-42c1-9569-8ff980adf9bb.png)

**Comment by marrobi** [comment]
@RIashfaqahmed thank you for your time going through the issue. As discussed it seems we have a bug with the airlock if using hyphens in your `TRE_ID`.

We now have an issue to track and will report back when we have decided on an approach. Understand your current solution is going to be to redeploy without hyphens.

https://github.com/microsoft/AzureTRE/issues/2906

**Comment by RIashfaqahmed** [comment]
thanks @marrobi! we have decided to redeploy TRE without dashes (-) in TRE_ID. Since we have concluded this issue so I am going to close off this ticket.
