### ISSUE TITLE
Firewall lease unavailable  

### ISSUE THREAD

**Issue by t-young31** [microsoft/AzureTRE#2896]
**Describe the bug**
When editing multiple resources at once the firewall tf state lease can not be returned meaning a workspace modification fails with 

```
Error: \u001b[0m\u001b[0m\u001b[1mError acquiring the state lock\u001b[0m \u001b[31m│\u001b[0m \u001b[0m \u001b[31m│\u001b[0m \u001b[0m\u001b[0mError message: state blob is already locked \u001b[31m│\u001b[0m \u001b[0mLock Info: \u001b[31m│\u001b[0m \u001b[0m  ID:  ****** \u001b[31m│\u001b[0m \u001b[0m  Path:      tfstate/****-shared-service-firewall
```

Also encountered by @marrobi . Fixed by manually breaking the lease.

**Steps to reproduce**

1. Edit multiple resources

**Comment by tamirkamara** [comment]
We haven't seen this for a while so will close it for now.
