### ISSUE TITLE
Airlock - SAS URL

### ISSUE THREAD

**Issue by MoIocSidi** [microsoft/AzureTRE#2897]
Unable to access the storage account from the SAS URL generated: 

<Error>
<Code>AuthenticationFailed</Code>
<Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:8e444aa6-501e-003f-7776-fe6a83000000 Time:2022-11-22T13:26:17.0913566Z</Message>
<AuthenticationErrorDetail>Signature did not match. String to sign used was rwdl 2022-11-22T14:24:20Z /blob/stalimexcktre01/$root 6aabe3bb-05d5-41de-8281-24cadb4c710d 5b705f2e-fa01-4f0d-b5ef-5xxxxxxx 2022-11-22T13:24:20Z 2022-11-22T14:24:20Z b 2021-06-08 2021-06-08 c </AuthenticationErrorDetail>
</Error>

The user has the all the permissions required.

**Comment by marrobi** [comment]
@MoIocSidi few questions:

Can you confirm where the SAS URI is retrieved from - is it import or export?

Where are you using the SAS URI - from outside or inside of the workspace vnet?

Also how long after generating the URI did you try and use it?

**Comment by marrobi** [comment]
Ok, I've just run through the process on a deployment I have and worked fine. There is no need to modify any permissions/firewall rules.

Another stab in the dark - is the time on your computer correct?!

As this is a relatively new feature I'd like to ensure it this is not a bug, if you can drop me an email at marcus.robinson at microsoft.com I can see if we can get someone to have a closer look. Thanks.

**Comment by MoIocSidi** [comment]
@marrobi Yes the time is correct, I have just sent you an email
