### ISSUE TITLE
TRE Services - Upgrade and Documentation

### ISSUE THREAD

**Issue by JaimieWi** [microsoft/AzureTRE#2898]
The TRE resources all need to be upgraded as new versions are released. When deploying services via the deployment pipeline or via manual steps the same result can be seen and the services are not updated.

`Resource upgrade isn't currently implemented. See https://github.com/microsoft/AzureTRE/issues/141`

There are conversations currently about upgrading resources and how this should be approached (#1744) but, at the moment there is nothing in the documentation on the best approach when upgrading/ re-deploying an existing service.

For example, our Firewall is on version 0.4.0 and re-deployment causes the above error. 

     Is the best approach to deploy a second firewall and then delete the existing to ensure there is no downtime 
     for this shared service?

**Describe the bug**
Upgrading TRE services fails, mainly an issue with shared services that do not want to be deleted each time there is a new version.

The main cause of concern is lack of documentation on the topic. Best practices for re-deployment, particularly for a firewall, is required.

**Steps to reproduce**

1. Have a pre-existing TRE with shared services deployed.
2. Upgrade the porter version of one of these shared services, such as nexus.
3. run `make deploy-shared-service DIR=./AzureTRE/templates/shared_services/sonatype-nexus-vm/ BUNDLE_TYPE=shared_service PROPS="--ssl_cert_name nexus-ssl"`
4. See the above error of `Resource upgrade isn't currently implemented.`

**Comment by marrobi** [comment]
@JaimieWi at the moment the only way to upgrade is to access cosmos and update the version of the template. Then if carry out an update operation on the resource it will get the new version of the bundle.

I'm going to add a generic issue to document accessing cosmos when need to "break glass".

Hopefully we will have #1744 resolved before too long.

**Comment by JaimieWi** [comment]
@marrobi Ah ok great, thank you! I had seen that might be a solution but wasn't sure it was the best thing to do! I will start the process for updating each service now :)

**Comment by marrobi** [comment]
Added #2901 

Will close this, @JaimieWi  if need further help, let us know.
