### ISSUE TITLE
Having hyphens in storage account name breaks Airlock processor

### ISSUE THREAD

**Issue by tanya-borisova** [microsoft/AzureTRE#2906]
**Describe the bug**

If a TRE has hyphens in the name (e.g. `tanya-dev`), creation of Airlock requests will not work. 
It would fail in StatusChangedQueueTrigger as the creation of container will fail failing to reach the storage account.

**Steps to reproduce**

1. Deploy a TRE ID with a hyphen in the name
1. Try to create a Airlock request

**Comment by marrobi** [comment]
Two approaches:
1. Prevent hyphens being used in TRE ID. This might block some existing deployments.
2. Update the airlock code and add hyphens into e2e tests.

or do both?

**Comment by marrobi** [comment]
Decided in first instance will block hyphens in TRE ID in terraform validation. If we get reports that this blocks existing deployments we will discuss again.
