### ISSUE TITLE
Permission issue when creating Guacamole Workspace Service

### ISSUE THREAD

**Issue by pete-mutton-mhra** [microsoft/AzureTRE#2909]
Guacamole Workspace Service Deployment

**Describe the bug**
When deploying the Guacamole workspace service to a newly created workspace, the deployment errored at the following step:

"stepTitle": "Add Guacamole URI as AAD redirect URI"
"resourceTemplateName: "tre-workspace-msl"
"resourceType": "workspace"
"resourceAction": "upgrade"
"status": "updating_failed"
"message" : ..."ERROR: Insufficient privileges to complete the operation"

We resolved the issue by running the following command as an AAD GA to add the 'tre_dev Application Admin" and "TRE_DEV-workspace API" as owners of the App Registration:

AzureTRE/devops/scripts/aad/create_workspace_application.sh --name "TRE_DEV - workmiguel1" --admin-consent --ux-clientid "xxx" --automation-clientid "xxx" --application-admin-clientid "xxx"

What AAD role do we need to give the developer to ensure the workspace service deployment works without having to resort to using a GA enabled account?

**Comment by tamirkamara** [comment]
@pete-mutton-mhra I assume this is a new workspace AAD application and that you initially didn't use the `AzureTRE/devops/scripts/aad/create_workspace_application.sh` to create it.
Is that right?

**Comment by tamirkamara** [comment]
I think we have discussed this offline.
