### ISSUE TITLE
Creating base workspace is not working on a new TRE environment

### ISSUE THREAD

**Issue by anatbal** [microsoft/AzureTRE#2915]
When creating a new TRE environment from scratch by make all, and trying to deploy a base workspace to it, it fails.
1. First, it fails with an API error:
![image](https://user-images.githubusercontent.com/13421451/204253988-460a1228-5a21-4701-af06-4472130a7c99.png)
 2.  However, if you manage to skip this validation step, this will occur once you deploy the workspace base template:
![image](https://user-images.githubusercontent.com/13421451/204254516-8e4abba9-6afd-4e4e-a90a-f2b0e4747ab1.png)

**Comment by marrobi** [comment]
This is the issue with the unit test that got through, let me find the line in PR that fixes it.

**Comment by marrobi** [comment]
@anatbal this is the fix:

https://github.com/microsoft/AzureTRE/blob/e3578a02e19a74310f28e99491681855510f13ac/api_app/db/repositories/workspaces.py#L70-L73

**Comment by anatbal** [comment]
@marrobi 
Also, I noticed that if I manage to have a ws already in the cosmosdb, creating a second, different workspace is also failing.  I am just not sure if it is related to this or perhaps a different thing

**Comment by marrobi** [comment]
I think it's likely the same issue, the v0.7.0 will fail.

**Comment by tamirkamara** [comment]
@LizaShak might be trying to do a quick fix just on this issue.
