### ISSUE TITLE
Add storage explorer link and az cli command to Airlock UI request storage link section

### ISSUE THREAD

**Issue by jjgriff93** [microsoft/AzureTRE#2916]
**Is your feature request related to a problem? Please describe.**
A couple of users (i.e #2897) have tried to use the SAS URL directly in a web browser as there isn't much guidance in the UI on what a SAS URL is and how to use it (i.e. pasting it into Azure Storage explorer or using the az cli).

**Describe the solution you'd like**
Instead of expecting all users to have reviewed the documentation, we should make it clearer in the UI by offering drop-down options for not just the raw SAS URL, but a storage Explorer web link and an az cli command - giving users options out of the box on how to consume the SAS URL.

**Comment by tamirkamara** [comment]
FYI storage explorer direct link doesn't support SAS so that isn't a possibility.

**Comment by marrobi** [comment]
@yuvalyaron as discussed can you verify the appropriateness of when the SAS URI/cli command appears at each stage for researcher and airlock manager. For example it should not appear to a research once submitted.

**Comment by yuvalyaron** [comment]
@marrobi 
it turns out that it's a quite more complex as we have some unexpected behaviors in that area,
I've created #3187 to address them.
In the meanwhile, as part of this issue, I made the section to appear only for draft and approved requests.
