### ISSUE TITLE
Add option to disable Swagger UI

### ISSUE THREAD

**Issue by chboudry** [microsoft/AzureTRE#2925]
Customer would like to make swagger API docs less accessible to ordinary users.

**Comment by marrobi** [comment]
Suggest with either disable by env var, or put auth in front.

**Comment by yuvalyaron** [comment]
@marrobi 
Should it be set to off by default? If the default configuration aims to production environments, then it should be off by default in my opinion.

**Comment by marrobi** [comment]
Hmm, quite possibly. As long as its clearly documented.

Maybe the sample env file has it enabled so local deployments have it enabled? Or could we show an error saying SWAGGER_ENABLED needs to be set to true to access Swagger?

**Comment by yuvalyaron** [comment]
Sounds good, I'll do both of them 👍
