### ISSUE TITLE
Enable AUTH on /workspaceTemplates

### ISSUE THREAD

**Issue by TessFerrandez** [microsoft/AzureTRE#293]
## Description

As a AzureTRE Admin
I want to restrict access to the templates registration and retrieval
So that I don't get random workspace templates

## Acceptance critiera

TBD - need to figure out who should have access to what

**Comment by marrobi** [comment]
@TessFerrandez what's the status of this? Thanks.

**Comment by TessFerrandez** [comment]
This can be closed!
