### ISSUE TITLE
Unable to build CNAB invocation image: requires BuildKit

### ISSUE THREAD

**Issue by JaimieWi** [microsoft/AzureTRE#2962]
In our DevOps CICD pipeline a new error has occurred for `make bundle-build bundle-publish` of certain bundles. The ones that did not fail are: Guacamole, AzureML, Gitea, MLflow, AdminVM, Firewall, Shared Gitea.

All others failed with the same error:
```
[2022-12-13T11:39:20.118Z]  ---> Using cache
 ---> 4feb4e9fcfba
Step 13/22 : RUN --mount=type=cache,target=/var/cache/apt --mount=type=cache,target=/var/lib/apt 	apt-get update && apt-get install -y apt-transport-https lsb-release gnupg curl

[2022-12-13T11:39:20.144Z] Error: unable to build CNAB invocation image: failed to stream docker build output: the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled

[2022-12-13T11:39:20.144Z] make: *** [/home/vscode/AzureTRE/Makefile:179: bundle-build] Error 1

[2022-12-13T11:39:50.147Z] Failed!
```
For the full output see this file: [buildkiterror.txt](https://github.com/microsoft/AzureTRE/files/10218149/buildkit.txt)

**Describe the bug**
This error occurs when merging a PR to main. The PR was for a small typo in VM sizes so would have no effect.

**Steps to reproduce**
1. Create a PR to make a small change. This pipeline is successful.
2. Complete the PR to merge to main, this error occurs for certain bundles.
3. Choosing `Run new` to rerun the pipeline causes the same bundles to have the error.

**Comment by marrobi** [comment]
@JaimieWi is this using your own pipelines rather than the GitHub actions. Within the GitHub actions workflows that are part of this and the deployment repo I believe DOCKER_BUILDKIT is enabled for all operations:

https://github.com/microsoft/AzureTRE/search?q=DOCKER_BUILDKIT

**Comment by JaimieWi** [comment]
This is within the Azure DevOps pipeline that we had previously set up. I have tried re-running and the same bundles fail. I have also pointed to a more recent commit and see the same failures.
<img width="290" alt="Screenshot 2022-12-15 at 10 00 51" src="https://user-images.githubusercontent.com/92854957/207830184-d7c7c4ba-002d-4a93-bf46-00a2df42a81e.png">


I can see Docker BuilKit is enabled for GitHub actions, we don't seem to have it enabled for our pipelines. The only reference to it is in our devcontainer.json. 
```
"mounts": [
    // Keep command history
    "type=volume,source=tre-bashhistory,target=/home/vscode/commandhistory",
    // Mounts the login details from the host machine to azcli works in the container
    "type=bind,source=${env:HOME}${env:USERPROFILE}/.azure,target=/home/vscode/.azure",
    // Mount docker socket for docker builds
    "type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock"
  ],
  "remoteUser": "vscode",
  "containerEnv": {
    "DOCKER_BUILDKIT": "1"
  },
  ```
Do we need to enable it?

**Comment by marrobi** [comment]
It's likely worth a try, as it's this `--mount` https://github.com/microsoft/AzureTRE/blob/885813aa0b99a62e31bb694d186a7b2e514f71a5/.github/actions/devcontainer_run_command/action.yml#L128 that seems to be your issue, and `DOCKER_BUILDKIT` is set to 1 as part of the same command.

**Comment by JaimieWi** [comment]
The `docker run --rm --mount` command is not being called in our [pipeline.yml](https://github.com/microsoft/AzureTRE/files/10236403/azure_pipelines.txt). I can see multiple references to DOCKER_BUILDKIT across your GitHub Actions pipeline. 

At the moment we are faking dev container mounts (first mentioned line:66 of pipeline.yml file above), could this be having an effect on this whole process?
- How would we make use of BuildKit in our pipeline yaml? 
- Would it require modification to the stages in our pipeline?

**Comment by JaimieWi** [comment]
Hi @marrobi, we managed to fix the issue!

It turns out it was due to our .devcontainer folder being out of date. The Dockerfile, devconatiner.json and porter.sh file all needed to be updated. I hadn't thought of that as the error led me in the wrong direction! I believe it could be due to the way Porter was being referenced. Thanks for your help! I'll close the issue now :)
