### ISSUE TITLE
Terraform error during initial deployment

### ISSUE THREAD

**Issue by ukct** [microsoft/AzureTRE#2966]
**Describe the bug**
The deployment process fails when doing an initial deployment into an empty subscription in a dedicated tenant, whilst following https://microsoft.github.io/AzureTRE/tre-admins/setup-instructions/ 

The Deploy main / Deploy TRE / Deploy TRE Core process fails after about 30 mins with the following errors. There are no other errors before this point. 

```
│ Error: A resource with the ID "/subscriptions/***/resourceGroups/rg-***/providers/Microsoft.KeyVault/vaults/kv-***/objectId/ee6cc934-35c8-4a57-bb80-5d0fb4b69cc1" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_key_vault_access_policy" for more information.
│ 
│   with azurerm_key_vault_access_policy.deployer,
│   on keyvault.tf line 13, in resource "azurerm_key_vault_access_policy" "deployer":
│   13: resource "azurerm_key_vault_access_policy" "deployer" ***
│ 
╵
╷
│ Error: A resource with the ID "/subscriptions/***/resourcegroups/rg-***/providers/microsoft.keyvault/vaults/kv-***/providers/microsoft.insights/diagnosticSettings/diagnostics-kv-***" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_monitor_diagnostic_setting" for more information.
│ 
│   with azurerm_monitor_diagnostic_setting.kv,
│   on keyvault.tf line 115, in resource "azurerm_monitor_diagnostic_setting" "kv":
│  115: resource "azurerm_monitor_diagnostic_setting" "kv" ***
│
│ Error: A resource with the ID "/subscriptions/***/resourcegroups/rg-***/providers/microsoft.servicebus/namespaces/sb-***/providers/microsoft.insights/diagnosticSettings/diagnostics-sb-***" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_monitor_diagnostic_setting" for more information.
│ 
│   with azurerm_monitor_diagnostic_setting.sb,
│   on servicebus.tf line 95, in resource "azurerm_monitor_diagnostic_setting" "sb":
│   95: resource "azurerm_monitor_diagnostic_setting" "sb" ***
│ 
╵
╷
│ Error: A resource with the ID "/subscriptions/***/resourceGroups/rg-***/providers/Microsoft.OperationalInsights/workspaces/log-***/linkedStorageAccounts/ingestion" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_log_analytics_linked_storage_account" for more information.
│ 
│   with module.azure_monitor.azurerm_log_analytics_linked_storage_account.workspace_storage_ingestion,
│   on azure-monitor/azure-monitor.tf line 29, in resource "azurerm_log_analytics_linked_storage_account" "workspace_storage_ingestion":
│   29: resource "azurerm_log_analytics_linked_storage_account" "workspace_storage_ingestion" ***
│ 
╵
╷
│ Error: A resource with the ID "/subscriptions/***/resourceGroups/rg-***/providers/Microsoft.OperationalInsights/workspaces/log-***/linkedStorageAccounts/customlogs" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_log_analytics_linked_storage_account" for more information.
│ 
│   with module.azure_monitor.azurerm_log_analytics_linked_storage_account.workspace_storage_customlogs,
│   on azure-monitor/azure-monitor.tf line 41, in resource "azurerm_log_analytics_linked_storage_account" "workspace_storage_customlogs":
│   41: resource "azurerm_log_analytics_linked_storage_account" "workspace_storage_customlogs" ***
│ 
╵
```

**Steps to reproduce**

1. Start with an empty subscription, and no app registrations in AAD. 
1. Deploy AzureTre-Deployment template into new repository
1. Create service principal (https://microsoft.github.io/AzureTRE/tre-admins/setup-instructions/cicd-pre-deployment-steps/)
1. Setup auth configuration (https://microsoft.github.io/AzureTRE/tre-admins/setup-instructions/setup-auth-entities/)
1. Populate environment variables in new repository as listed (https://microsoft.github.io/AzureTRE/tre-admins/setup-instructions/cicd-pre-deployment-steps/)
1. Run 'Deploy Azure TRE' github action

or, at step 5, continue to work within devcontainer and run 'make all' (as described in https://microsoft.github.io/AzureTRE/tre-admins/setup-instructions/manual-deployment/). This will then result in the same set of errors.

**Comment by marrobi** [comment]
Hi @ukct this tends to occur when you deploy with the same TRE_ID as has been used previously. The diagnostic settings are stored within Azure Monitor at the subscription level, so deleting resource groups will not remove them.

Did you have a previous deployment with the same TRE_ID Also did you use the `make tre-destroy` command to delete?

**Comment by marrobi** [comment]
Hi @ukct , did you manage to get sorted? Thanks.

**Comment by anon57121** [comment]
Yes, thanks very much for the tip. Changing TRE_ID was successful and everything's run through as expected and I'm able to successfully create workspaces etc. 

```make tre-destroy``` was failing with a permission error on key vault, but that may be due an earlier error so will need to test that in with a clean deployment. 

Is there a way of accessing subscription level diagnostic settings, that's not something I'm familiar with.  ```az monitor diagnostic-settings subscription``` wasn't showing anything.

**Comment by marrobi** [comment]
Looks like we do it here by getting the resources then searching for the settings:

https://github.com/microsoft/AzureTRE/blob/main/devops/scripts/destroy_env_no_terraform.sh#L88

Will close this issue, feel free to open another one if the destroy command doesn't work. Thanks.
