### ISSUE TITLE
[BUG] Key Vault script in tre-deploy target fails due to missing environment variable

### ISSUE THREAD

**Issue by tompaana** [microsoft/AzureTRE#297]
`/devops/scripts/set_contributor_sp_secrets.sh` is run as part of the `tre-deploy` target in Makefile. If run **manually**, the script will fail, because `TRE_ID` environment variable is not defined. The Makefile target loads environment variables from .env files, but injects `TF_VAR_` prefix so although TRE ID is in the environment variables, it has a name the script is not expecting.

**A** solution is to also use `load_env.sh` to process the `/templates/core/.env` file in `tre-deploy` target.

**Comment by limorl** [comment]
@tompaana  I'll update the makefile and test so will add the line in bold:

tre-deploy:
	echo -e "\n\e[34m»»» 🧩 \e[96mDeploying TRE\e[0m..." \
	&& . ./devops/scripts/check_dependencies.sh nodocker \
	**&& . ./devops/scripts/load_env.sh ./templates/core/.env \**
	&& . ./devops/scripts/load_terraform_env.sh ./devops/.env \
	&& . ./devops/scripts/load_terraform_env.sh ./templates/core/.env \
	&& cd ./templates/core/terraform/ && ./deploy.sh \
	&& cd ../../../ && ./devops/scripts/set_contributor_sp_secrets.sh

**Comment by limorl** [comment]
The variables are loaded correctly but the script fails on this line and actually crashes my terminal:
az keyvault secret set --name deployment-processor-azure-client-id --vault-name $key_vault_name --value $CONTRIBUTOR_SP_CLIENT_ID

**Comment by christoferlof** [comment]
When I add the above two calls to load the required env variables, I'm instead seeing auth issues and Terraform terminates.
Given the error message, it seems additional env variables are picked up but also a change in behaviour - probably because of the existence of the ARM_ variables? ARM_TENANT_ID should be optional according to the quickstart.

```plaintext
│ Error: Failed to get existing workspaces: Error retrieving keys for Storage Account "<storage-account-name>": azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/<id>/resourceGroups/<rg>/providers/Microsoft.Storage/storageAccounts/<account name>/listKeys?api-version=2021-01-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"AADSTS900023: Specified tenant identifier '__change_me__' is neither a valid DNS name, nor a valid external domain.\r\nTrace ID: c0a1f46b-f8f1-43ae-8e9d-2f5b40cc7900\r\nCorrelation ID: ee34bec3-077a-4233-a00e-e0aba47c0e26\r\nTimestamp: 2021-06-18 13:49:32Z","error_codes":[900023],"timestamp":"2021-06-18 13:49:32Z","trace_id":"c0a1f46b-f8f1-43ae-8e9d-2f5b40cc7900","correlation_id":"ee34bec3-077a-4233-a00e-e0aba47c0e26","error_uri":"https://login.microsoftonline.com/error?code=900023"} Endpoint https://login.microsoftonline.com/__CHANGE_ME__/oauth2/token?api-version=1.0
```

**Comment by limorl** [comment]
@christoferlof the variabes are correct, I think there was an issue with Key Vault.
Can you try to replace the variables in the script in real values and run it without loading the env?
I have a hunch that you will see the same behavior... I don;t think it is related.
