### ISSUE TITLE
Creating Workspace from ML Template

### ISSUE THREAD

**Issue by ibeddows74** [microsoft/AzureTRE#2971]
Newly deployed TRE 

Attempting to create a New Workspace based on the ML Template and we get a failure in deploying with the following message in the Operations tab:

Resource Id
: 76fa45e8-c08e-4e2f-916c-0dab34e57a77
Resource Path
: /workspaces/942a3510-9cd8-469f-968b-555451d72e6d/workspace-services/76fa45e8-c08e-4e2f-916c-0dab34e57a77
Resource Version
: 0
Status
: deployment_failed
Action
: install
Message
: Multi step pipeline failed on step main
Created
: Tue Dec 13 2022 15:53:37 GMT+0000 (2 days ago)
Updated
: Tue Dec 13 2022 15:56:32 GMT+0000 (2 days ago)
User
: Ian Beddows (AZ Admin)

Can anybody advise?

Thanks

**Comment by marrobi** [comment]
Hi @ibeddows74 there has a been a breaking change with the AML API and terraform. We will a have in fixed in the next release, likely early January,  but in the meantime you need to create your own custom version of the bundle, and replace the `azapi` definition in main.tf in the AML bundle with:

```
resource "azurerm_machine_learning_workspace" "aml_workspace" {
  name                          = local.workspace_name
  resource_group_name           = data.azurerm_resource_group.ws.name
  location                      = data.azurerm_resource_group.ws.location
  application_insights_id       = azurerm_application_insights.ai.id
  container_registry_id         = azurerm_container_registry.acr.id
  friendly_name                 = var.display_name
  description                   = var.description
  high_business_impact          = true
  key_vault_id                  = data.azurerm_key_vault.ws.id
  public_network_access_enabled = var.is_exposed_externally ? true : false
  storage_account_id            = azurerm_storage_account.aml.id

 

  identity {
    type = "SystemAssigned"
  }
} 
```

also increase the  azurerm  provider version to `version = "=3.32.0"`
