### ISSUE TITLE
Unable registering firewall bundle

### ISSUE THREAD

**Issue by dusan-ilic-mhra** [microsoft/AzureTRE#2982]
**Describe the bug**

We are upgrading the OSS version to v0.7.0 in our repository. 
When we executed 'make all', it failed in the last step of registering the firewall with this error:
![image](https://user-images.githubusercontent.com/104429461/209240233-e5dedd9d-690c-4024-9ac8-8d40f0530f58.png)

Could you please help with this because it is a blocker for us currently?

**Steps to reproduce**

1. run 'make bundle-register DIR=AzureTRE/templates/shared_services/firewall/ BUNDLE_TYPE=shared_service'

**Comment by dusan-ilic-mhra** [comment]
I found a way to install TRE CLI (cli/README.md)

I also saw this comment: 

_## Installation
Currently, installation has only been tested within the dev container_.

But, how register and installing a firewall will work when we use CI to deploy?

**Comment by tamirkamara** [comment]
@dusan-ilic-mhra the TRE CLI is being installed via the devcontainer automatically. Are you sure you've updated your copy with the latest one coming from the 0.7.0 release?

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara, yes, I updated with the 0.7.0 release, but it hasn't been installed automatically. I needed to install it manually:
'make install-cli'

**Comment by tamirkamara** [comment]
@dusan-ilic-mhra can you share your devcontainer's dockerfile (either in email or gist)?

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara you can close this issue, we solved it by adding this block in Dockerfile:

# Install tre-cli
COPY ./cli /tmp/cli
WORKDIR /tmp/cli
RUN make install-cli && echo -e "\n# Set up tre completion\nsource <(_TRE_COMPLETE=bash_source tre)" >> ~/.bashrc

and adding **cli** folder in the root of our repo. 

Thanks for the help.

**Comment by tamirkamara** [comment]
@dusan-ilic-mhra you shouldn't copy the cli folder, the lines you've added into your docker file aren't accurate. Please review the selected ones here: https://github.com/microsoft/AzureTRE-Deployment/blob/main/.devcontainer/Dockerfile#L104-L106

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara From this link, I see that the repo is AzureTRE-Deployment.
But, from AzureTRE repo, you have this:

![image](https://user-images.githubusercontent.com/104429461/211820872-60615705-f889-40e9-b0be-43bada4841fe.png)

https://github.com/microsoft/AzureTRE/blob/main/.devcontainer/Dockerfile

However, it works now, after we added these lines and put **cli** folder in the root of our repository.

**Comment by tamirkamara** [comment]
The AzureTRE-Deployment repo is an example of how a customer repo should look like and work (much like your own private repo in the internal org).
Copying the cli folder means that you won't get updates automatically when we update the version in the OSS repo. 
I suggest you remove your copy of the cli folder and try the lines in the link I sent.

**Comment by dusan-ilic-mhra** [comment]
OK, I will do it. Thanks for the explanation @tamirkamara

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara The change you mentioned is applied. Everything is ok. You can close the issue. Thank you.
