### ISSUE TITLE
Deploy management failed - AZURE_CREDENTIALS set as GitHub secret

### ISSUE THREAD

**Issue by dusan-ilic-mhra** [microsoft/AzureTRE#2984]
**Describe the bug**

We upgraded the OSS version to 0.7.0 and now we are facing this issue when we deploy using CI:

![image](https://user-images.githubusercontent.com/104429461/209239729-7b5b67ca-f30c-4673-8b79-e1681ccf3ae9.png)

I reviewed this PR:
https://github.com/microsoft/AzureTRE/pull/2654

and created AZURE_CREDENTIALS as a GitHub secret in the mentioned format:

{
  "clientId": "xxx",
  "clientSecret": "xxx",
  "tenantId": "xxx",
  "subscriptionId": "xxx",
"resourceManagerEndpointUrl": "management.azure.com"
}

**Steps to reproduce**

1. Run Deploy Azure TRE workflow

Do I miss something? Could you please help us because this is currently a blocker for us?

**Comment by tamirkamara** [comment]
@dusan-ilic-mhra please verify that the format & values corrosponds to the example given [here](https://github.com/marketplace/actions/azure-login#configure-deployment-credentials).
I think you should try the change the _resourceManagerEndpointUrl_

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara Where I can find resourceManagerEndpointUrl?

**Comment by dusan-ilic-mhra** [comment]
Following your comment to take a look at this link https://github.com/marketplace/actions/azure-login#configure-deployment-credentials

I run a command for the existing App Reg: 

az ad sp create-for-rbac --name "**App_Reg_Name**" --role contributor --scopes /subscriptions/**Subscription_ID**/resourceGroups/**management_rg_name** --sdk-auth

and I’ve got this output:

{
  "clientId": "xxxxxxxxxxxxxxxxxxxx",
  "clientSecret": "xxxxxxxxxxxxxxxxxxxx",
  "subscriptionId": "xxxxxxxxxxxxxxxxxxxx",
  "tenantId": "xxxxxxxxxxxxxxxxxxxx",
  "activeDirectoryEndpointUrl": "xxxxxxxxxxxxxxxxxxxx",
  "resourceManagerEndpointUrl": "https://management.azure.com/",
  "activeDirectoryGraphResourceId": "xxxxxxxxxxxxxxxxxxxx",
  "sqlManagementEndpointUrl": "xxxxxxxxxxxxxxxxxxxx",
  "galleryEndpointUrl": "xxxxxxxxxxxxxxxxxxxx",
  "managementEndpointUrl": "xxxxxxxxxxxxxxxxxxxx"
}

I put this output in as AZURE_CREDENTIALS in GitHub secrets and still getting this error:
![image](https://user-images.githubusercontent.com/104429461/211349729-9b139d86-a3af-4242-b7b3-9e090a15695f.png)

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara  You can close this issue as we solved it by adding new secrets:
MGMT_RESOURCE_GROUP_NAME
MGMT_STORAGE_ACCOUNT_NAME
As their name has been changed in the new version.
