### ISSUE TITLE
[BUG] Workspace template registration doesn't check for actual in ACR

### ISSUE THREAD

**Issue by deniscep** [microsoft/AzureTRE#303]
**Describe the bug**
When a template is registered via API, the link to ACR is not established or verified. Once the deployment is run against the workspace, it fails on no existing image in ACR.

We should probably check does the image exists in ACR before submitting a run to processor, letting the user know that the template is registered but it doesn't have a corelated image.

**Steps to reproduce**

1. Register a workspace_template via API for a specific name and version
2. Delete that version tag from ACR
3. Create a workspace deployment via POST.

**Comment by marrobi** [comment]
Fixed in #525
