### ISSUE TITLE
Airlock requests don't include user's email

### ISSUE THREAD

**Issue by migldasilva** [microsoft/AzureTRE#3087]
When creating an Airlock request, user's email is not included. It negatively impact on Airlock Notifications. 

User backed is Azure AD and authorization/authentication is working properly. 

The following output shows the API response for request creation.

```
{
  "airlockRequest": {
    "id": "eb6ecce0-13d5-4991-9ffa-6874bffe07ed",
    "resourceVersion": 0,
    "createdBy": {
      "id": "a2661996-9af0-4acb-XXXX-XXXXXXXXXXXX",
      "name": "Juan Perez",
      "email": "",
      "roles": [
        "AirlockManager",
        "WorkspaceResearcher",
        "WorkspaceOwner"
      ],
      "roleAssignments": []
    },
    "createdWhen": 1673949947.981732,
    "updatedBy": {
      "id": "a2661996-9af0-4acb-XXXX-XXXXXXXXXXXX",
      "name": "Juan Perez",
      "email": "",
      "roles": [
        "AirlockManager",
        "WorkspaceResearcher",
        "WorkspaceOwner"
      ],
      "roleAssignments": []
    },
    "updatedWhen": 1673949948.327619,
    "history": [],
    "workspaceId": "40e5d597-b754-4c43-8e73-18177548a927",
    "type": "import",
    "files": [],
    "title": "Test 1 - import",
    "businessJustification": "Test 1 - import",
    "statusMessage": null,
    "reviews": [],
    "_etag": null,
    "reviewUserResources": {},
    "status": "draft"
  },
  "allowedUserActions": [
    "cancel",
    "submit"
  ]
}
```

Data transfer during Airlock request creation, and Airlock request submission are working fine. I can track the file being copied from one storage account to the other.

**Comment by LizaShak** [comment]
Hi @migldasilva,
Thank you for contacting us :) 
The airlock notifications sources the emails recipients from the MSGraph, we ask it to give us a list of emails for all users with role assignments. Then for example when an airlock request is submitted all the users with airlock manager role assignment will get a notification to review the request.
The emails in the airlock request itself shouldn't affect the notification. 
Is it an issue with a specific user not getting notifications? Are there users that do get notified?

**Comment by migldasilva** [comment]
Thank @LizaShak. After deeply reviewing the Logic App output, it was clear that the email is there!

I'm closing this question.
