### ISSUE TITLE
Isolate Workspaces into individual subscriptions 

### ISSUE THREAD

**Issue by v-smahaj** [microsoft/AzureTRE#3097]
As an IT admin, I want each workspace deployed into their own subscription so that research teams can manage their own subscriptions, improve security isolation, billing isolation, and overcome subscription resource limitations.

**Comment by marrobi** [comment]
Closing as duplicate of https://github.com/microsoft/AzureTRE/issues/1073

Please discuss on the existing issue. Thanks.
