### ISSUE TITLE
Research Azure CAF and Azure Blueprints

### ISSUE THREAD

**Issue by deniscep** [microsoft/AzureTRE#31]
- What are [Azure Landing Zones](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/) and [Azure Blueprints](https://docs.microsoft.com/en-us/azure/governance/blueprints/overview)?
- Which features are they providing?
- Any patterns we reuse?

**Comment by christoferlof** [comment]
The **Microsoft Cloud Adoption Framework for Azure** (CAF) is a collection of guidance and tools to help organizations adopt Azure.

> The Cloud Adoption Framework is a collection of documentation, implementation guidance, best practices, and tools that are proven guidance from Microsoft designed to accelerate your cloud adoption journey.  
-- [Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/)

**Landing zones** is a concept in CAF.

Landing zones are pre-provisioned segments of a cloud environments in which teams can develop and deliver their applications in a compliant manner.

CAF as such doesn't require a specific toolset or langugage for the infrastructure code defining the landing zones.

> Azure landing zones are the output of a multisubscription Azure environment that accounts for scale, security, governance, networking, and identity. Azure landing zones enable application migrations and greenfield development at enterprise-scale in Azure. These zones consider all platform resources that are required to support the customer's application portfolio and don't differentiate between infrastructure as a service or platform as a service.  
-- [What is an Azure landing zone?](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/)

The landing zones [examples in the CAF documentation](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/migrate-landing-zone) are implemented as Azure Blueprints, which make use of ARM Templates. (More on that below).

Some organizations prefer Terraform over ARM based deployments. The organizations who want to follow the concept of Landing zones and also want a prescriptive way of how to implement them using Terraform should have a look at [Cloud Adoption Framework for Azure landing zones on Terraform](https://github.com/Azure/caf-terraform-landingzones)

Azure Blueprints is a way to bundle resource definitions (ARM Templates), policy assignments and RBAC assignments. Blueprints are published in Azure as a resource and available to users to create their environments (or landing zones) from.

> Azure Blueprints enables cloud architects and central information technology groups to define a repeatable set of Azure resources that implements and adheres to an organization's standards, patterns, and requirements. Azure Blueprints makes it possible for development teams to rapidly build and stand up new environments with trust they're building within organizational compliance with a set of built-in components, such as networking, to speed up development and delivery.  
-- [What is Azure Blueprints?](https://docs.microsoft.com/en-us/azure/governance/blueprints/overview)

There are several [Blueprint samples](https://docs.microsoft.com/en-us/azure/governance/blueprints/samples/) created for various compliance needs such as ISO 27001, HIPAA HITRUST 9.2, DoD, to name a few.
