### ISSUE TITLE
Allow users to upgrade resources through the UI

### ISSUE THREAD

**Issue by guybartal** [microsoft/AzureTRE#3118]
## Description

As a TRE Administrator/TRE Workspace Owner/Researcher 
I want to be able to upgrade resources that have been deployed through the UI,
so that I can easily keep them up-to-date and take advantage of new features and bug fixes. 

## Acceptance criteria
- [ ] List the versions that we can upgrade to when we GET a resource
- [ ] Allow users to choose the version they want to upgrade to within the resource card, based on their role.

**Comment by marrobi** [comment]
@guybartal moved onto the feature roadmap. Would be useful, but not sure its an immediate priority.

**Comment by yuvalyaron** [comment]
For now, we will not let users upgrade to major versions through the UI, since it might break the resource so we should not make it too accessible.
