### ISSUE TITLE
make db-migrate is not working

### ISSUE THREAD

**Issue by dusan-ilic-mhra** [microsoft/AzureTRE#3121]
**Describe the bug**
We upgraded TRE CORE to v0.7.0 and in the release notes we saw this:

[0.7.0](https://github.com/microsoft/AzureTRE/releases/tag/v0.7.0)
BREAKING CHANGES & MIGRATIONS:

The airlock request object has changed. Make sure you have ran the db migration step after deploying the new API image and UI (which runs automatically in make all/make tre-deploy but can be manually invoked with **make db-migrate**) so that existing requests in your DB are migrated to the new model.

We executed **make db-migrate** command and we got this output:
![image](https://user-images.githubusercontent.com/104429461/214551277-5e6673b3-f477-4d62-bb6e-6c34cb7dcea3.png)

But, still we have an issue when we want to review Airlock requests:

![image](https://user-images.githubusercontent.com/104429461/214551517-0d7aff4f-e3c3-4c64-bb33-36a2d6fffb51.png)

**Steps to reproduce**

1. Run **make db-migrate** on TEST environment
2. Log in to swagger for workspace and run GET /api/workspaces/{workspace_id}/requests from the airlock section

**Comment by tamirkamara** [comment]
@dusan-ilic-mhra is the problem with pre-exiting requests that were opened before the upgrade? 
Or, have you opened a new request after the upgrade and fail on it?

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara It's the problem with pre-existing requests that were opened before the upgrade.

**Comment by tamirkamara** [comment]
@dusan-ilic-mhra Which TRE OSS version have these been created in?

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara 0.4.3
