### ISSUE TITLE
Provide ability to copy URL to access an internally accessible resource.

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#3122]
As a researcher I can click on a connect button to access a TRE resource. If a resource is only available internally I cannot click connect. I do however need to be able to copy the URI. I cannot do this at present. The AML service shows a button that doesn't work, others there is no button.

Reproduce:
- Workspace with VMs and AML with no public access
- Login as Workspace Researcher (not owner)
- Access AML

Notes:
At present we have `connection_uri` and `internal_connection_uri`. We also have `is_exposed_externally`. Using a combination of these fields the appropriate behaviour should occur. If accessible, a button to click, if not a button to copy URI to the clipboard.

**Comment by guybartal** [comment]
remove `internal_connection_uri` and always use `connection_uri`, and in the UI render the button according to the `is_exposed_externally` input parameter (copy button the `connection_uri` to clipboard /link).
