### ISSUE TITLE
Allow TRE workspace owners manage permissions for researches and data engineers using the Unity Catalog in Azure Databricks workspace service

### ISSUE THREAD

**Issue by guybartal** [microsoft/AzureTRE#3145]
## Description

As a TRE Workspace owner 
I want to be able to give Researches and Data Engineers access to their data stored in the workspace storage
So that they can analyze it and write back as needed

## Acceptance criteria

- [ ] TRE Workspace owner can give researchers permissions to their data stored in the workspace storage account using Unity Catalog
- [ ] TRE Researchers able to access their data stored in the workspace storage.

**Comment by guybartal** [comment]
this may help:
[Deploying pre-requisite resources and enabling Unity Catalog](https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/unity-catalog-azure)

**Comment by tamirkamara** [comment]
Workspace users usually get full access to everything in the workspace, there're almost no permissions enforced inside the workspace. So what is the angle for this story/product to be used in a workspace?

**Comment by guybartal** [comment]
If all researchers and data engineers should have access to the whole data inside the workspace then Unity Catalog might be an overkill for this scenario, and simply mounting the shared workspace storage would be sufficient.
