### ISSUE TITLE
Firewall Logs do not appear after upgrade to Firewall Policies.

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#3155]
After upgrading to the unreleased 0.9.0 where the Firewall is upgraded, I no longer see any Firewall logs. 

@guybartal @tamirkamara can you confirm if you have logs in your deployments?

**Comment by marrobi** [comment]
If I tick all boxes, then it works, but future updates to firewall give:

`Diagnostic setting does not support mix of log category and log category group.`

**Comment by guybartal** [comment]
I don't see any logs in my environment, I'll check again after turning on all boxes.

**Comment by guybartal** [comment]
After setting all boxes I see FW logs in `AzureDiagnostics`.

**Comment by marrobi** [comment]
Marcus to verify.

**Comment by marrobi** [comment]
Confirmed still an issue.

Classic logs give:

![Image](https://user-images.githubusercontent.com/17089773/221208828-dd783700-4e75-4fc5-94cd-c5a5a0f89fd5.png)

Resource specific logs give:

![Image](https://user-images.githubusercontent.com/17089773/221209050-b5f9539b-bc92-4b05-83c8-3de2bca12246.png)

**Comment by tamirkamara** [comment]
The reason is that it's a preview feature that needs to be turned on for the entire subscriptions.
For now I think the best solution would be to revert the change and go back to the old log options.
https://learn.microsoft.com/en-us/azure/firewall/firewall-structured-logs
