### ISSUE TITLE
Review Data folder in Airlock Import Review VM Empty

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#3181]
When provisioning a VM to review import data the data is not in the review folder.

**Comment by yuvalyaron** [comment]
Resolved by #3215.
The storage account of Airlock's "import in progress" (stalimip) has 2 private endpoints, one to enable airlocks flow, and the other for the review VM. These 2 endpoints used the same private DNS zone, which caused the DNS entry to be overwritten when one of them was deployed/removed.

In this particular case, the DNS entry had the value of the first endpoint, causing the review VM to resolve to the wrong private endpoint IP.
