### ISSUE TITLE
Custom domain name + supplied certificate for API / UI

### ISSUE THREAD

**Issue by damoodamoo** [microsoft/AzureTRE#3209]
Currently the TRE UI / API is accessed via `https://tre-id.location.cloudapp.azure.com` - but some customers need to offer a more branded and custom URL and associated certificate, such as `https://companytre.net` . 

A custom domain name and key vault location of the certificate should be optionally passed in at deploy time and the terraform should configure the app gateway appropriately. 

**Out of scope**:
- Certificate rolling / renewal - the cert will be 'externally' managed, and only referenced from the TRE. When a certificate is updated or changed, the reference will be updated and a TRE deploy will need to run to reconfigure.

**Comment by tamirkamara** [comment]
@damoodamoo I believe we had an issue similar to this which we had closed as we viewed the custom domain name, dns (cname) and respective certificate to be managed outside the TRE. We have also confirmed such a configuration works and easily configured.

**Comment by damoodamoo** [comment]
would the configuration not be overwritten on the next deploy, if was not part of the terraform?

**Comment by tamirkamara** [comment]
The only relevant configuration managed by terraform is the certificate appgw uses, but currently defined to ignore changes. So no, everything will be left as is.

**Comment by damoodamoo** [comment]
With the UI fix, we have implemented this outside of the TRE - was just important to make sure the certificate is named `cert-primary` to avoid TF updating it on the next deploy.
