### ISSUE TITLE
Attempt to upgrade from 0.6.3 to 1.0.0 denied. major version upgrade is not allowed

### ISSUE THREAD

**Issue by dusan-ilic-mhra** [microsoft/AzureTRE#3218]
**Describe the bug**

After the upgrade to version 0.8.0 we got this error when we executed **_make all_** in the developers' environment:

![image](https://user-images.githubusercontent.com/104429461/218443690-b523904e-fff4-4719-9f1a-5044ce48ab8f.png)

What will be the easiest way to upgrade Firewall to the major version as we saw that major version updates are blocked:
https://github.com/microsoft/AzureTRE/pull/2908
?

**Steps to reproduce**

1. Run **make all** command after upgrading to v0.8.0

**Comment by tamirkamara** [comment]
@dusan-ilic-mhra are you sure you're using 0.8.0 release? I'm asking since firewall version 1.0.0 was only part of the 0.9.0 release. 
Please review the release notes for this version. It includes a step-by-step of what is needed.
https://github.com/microsoft/AzureTRE/releases/tag/v0.9.0

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara you can see here that 1.0.0 is in v0.8.0:

![image](https://user-images.githubusercontent.com/104429461/218685553-cdc5a081-b448-4658-b4e7-577216cdbe76.png)

I will review the link you sent.

**Comment by tamirkamara** [comment]
The right property is `version`

**Comment by tamirkamara** [comment]
@dusan-ilic-mhra there's a mismatch here. I think you might be using a later version of the TRE OSS and not 0.8.0

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara yes, you are right. 
We created a tag in our OSS repo after version 0.8.0, so, some changes have been included from 0.9.0. 

Probably we will need to do an upgrade to 0.9.0.
We will take a look.

Thank you.

**Comment by tamirkamara** [comment]
Closing this for now.
