### ISSUE TITLE
Upgrade to the v0.9.0

### ISSUE THREAD

**Issue by dusan-ilic-mhra** [microsoft/AzureTRE#3238]
**Describe the bug**
We are doing an upgrade from v0.7.0 to v0.9.0 and when we execute **make tre-deploy** we get this error:

![image](https://user-images.githubusercontent.com/104429461/220378138-01d7cd5d-a097-4f74-98ea-cb2e4e22755f.png)

Could you please advise?

**Steps to reproduce**

1. **make tre-deploy** in order to deploy changes from v0.9.0 on the environment which has 0.7.0

**Comment by tamirkamara** [comment]
This is a timeout between terraform and Azure which we have limited control over.
Try to rerun the command please.

**Comment by dusan-ilic-mhra** [comment]
I've got this now, after re-run:
![image](https://user-images.githubusercontent.com/104429461/220383424-854c1883-d343-479f-bc2e-be6d3ca2afab.png)

**Comment by dusan-ilic-mhra** [comment]
I've got this now:
![image](https://user-images.githubusercontent.com/104429461/220385776-77c5ecab-2a71-44a5-bd13-dbff83d18922.png)

**Comment by tamirkamara** [comment]
All these errors indicate an issue with the communication between the machine running the deployment and Azure, or an issue with Azure itself. Give it some time, maybe close vscode and try again.

**Comment by dusan-ilic-mhra** [comment]
I'm still getting the same issues: 
![image](https://user-images.githubusercontent.com/104429461/220470838-4317ec3c-da7c-4118-8d0c-a9433652ae6f.png)

**Comment by marrobi** [comment]
Are you on a VPN maybe? Can you try on a different Internet connection, maybe tethered to a mobile phone.

**Comment by dusan-ilic-mhra** [comment]
@marrobi, @tamirkamara 

I switched to a mobile hotspot without VPN and this is still creating: 
![image](https://user-images.githubusercontent.com/104429461/220611730-85bdc0a2-a065-4e59-a246-0c094909a7e5.png)

I don't think this is related to the network from where I'm executing **make tre-deploy**

**Comment by dusan-ilic-mhra** [comment]
still creating: 

![image](https://user-images.githubusercontent.com/104429461/220617655-47c0822f-3919-4bc5-b428-a6886d16063e.png)

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara @marrobi 
And, we got the same error:

![image](https://user-images.githubusercontent.com/104429461/220620569-4c6f1e44-2f61-4b7a-943e-6e91920566e9.png)

We can see that the Private Endpoint **pe-cosmos-mongo-dusan07dev** has been created together with the network interface:

![image](https://user-images.githubusercontent.com/104429461/220621086-24823829-96d6-457a-a290-22f00898e8ec.png)

If I re-run **make tre-deploy** I will get the error that Private Endpoint already exists. 
I tried a couple of times to delete it and to run **make tre-deploy** but it is the same outcome.

Could you please advise?

**Comment by tamirkamara** [comment]
Unfortunately, sometimes there're Azure problems and this is one of those times.
Try to delete the relevant private endpoint and run the deployment again.

**Comment by dusan-ilic-mhra** [comment]
I did that more than 10 times.

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara 

I deleted the private endpoint and restarted vmss:

![image](https://user-images.githubusercontent.com/104429461/220627022-8cf984d3-d5c7-4ff3-9960-82b330d05957.png)

I will re-run **make tre-deploy** again.

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara 

It's still the same behavior:
![image](https://user-images.githubusercontent.com/104429461/220630908-effec721-47e2-4475-970c-d006dc9ba2e8.png)

**Comment by dusan-ilic-mhra** [comment]
Still the same:
![image](https://user-images.githubusercontent.com/104429461/220639408-3e7becfa-72ff-49b6-a39c-aeaf1ac531c7.png)

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara 

Failed again:
![image](https://user-images.githubusercontent.com/104429461/220667467-92da50ed-cfa4-49e0-95b7-c1a5d34b329c.png)

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara 

We tried also from another workstation.
And, it's failing there also. These are 2 **make tre-deploy** attempts:

![image](https://user-images.githubusercontent.com/104429461/220675730-ec406927-10de-4259-8a6a-b101917e20b1.png)
![image](https://user-images.githubusercontent.com/104429461/220675940-6795a08b-a27c-49ea-8d83-9e2379f29cab.png)

**Comment by mvalijipa** [comment]
We tried running the **make tre-deploy** today as well and we are getting the same error, even after deleting everything and starting again. 
![image](https://user-images.githubusercontent.com/107870922/220704009-5403b170-7255-4704-9231-3b1dcd2d8e57.png)

**Comment by tamirkamara** [comment]
If you rerun as is, without deleting anything from Azure do you get a terraform error saying the resource already exists?

**Comment by dusan-ilic-mhra** [comment]
Yes:
![image](https://user-images.githubusercontent.com/104429461/220854147-e6467d4f-2aee-4317-b4cd-788f3f99fae5.png)

**Comment by tamirkamara** [comment]
> Yes: ![image](https://user-images.githubusercontent.com/104429461/220854147-e6467d4f-2aee-4317-b4cd-788f3f99fae5.png)

I don't know why it happens but it looks like a networking thing (even the other examples from ciprian about the keyvault).
Does it also happen for a whole new tre_id?
We can try to overcome the issue by doing the import Terraform suggests. For that please edit core/terraform/import.sh and change the command on line 17 to look similar to this:
```
terraform import azurerm_private_endpoint.mongo <REPLACE_WITH_RESOURCE_ID>
```
The resource ID should be the one listed in your image /subscriptions/.../privateEndpoints/pe-cosmos-mongo-... (use the full path copied from the Terraform error.
then run `make terraform-import DIR=/core`
If successful, try the deploy command again.

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara 

_Does it also happen for a whole new tre_id?_ 
Ciprian's example is for new tre_id. 
He created the environment from scratch, and in my environment, I'm trying to do an upgrade.

I'll try what you suggested and I will send you feedback.

**Comment by marrobi** [comment]
I'm 90% sure the context deadline exceeded issues are down to some DNS/networking configuration. Are you running from corporate machines with any DNS/VPN configured? 

(the import is the next step, but wouldn't be surprised if you get that context deadline exceeded error again)

**Comment by dusan-ilic-mhra** [comment]
@marrobi 
I'm running from my local machine and I don't have anything configured related to DNS and I'm not using VPN.

However, I'll try what @tamirkamara wrote.

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara 

So, this is done:

![image](https://user-images.githubusercontent.com/104429461/220864446-c24702eb-1137-4ee5-94aa-28cb65ffc8e8.png)

I will now re-run **make tre-deploy**.

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara 

We don't have any more errors related to the creation of pe-cosmos-mongo-dusan07dev.

Now, we got this: 
![image](https://user-images.githubusercontent.com/104429461/220875143-9779861c-42ec-4a3b-aae4-4b3b42f64ea9.png)


But, I think I will need to do what you wrote on the issue - https://github.com/microsoft/AzureTRE/issues/3218

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara 

From what you wrote on the issue - https://github.com/microsoft/AzureTRE/issues/3218

I did the first 2 steps marked yellow:

![image](https://user-images.githubusercontent.com/104429461/220877863-67c80ab6-224a-4c0e-bbc7-abb345d7ac7d.png)

Now, I have a problem accessing swagger: 

![image](https://user-images.githubusercontent.com/104429461/220878037-a20ccc61-1411-411d-ae26-cab4e97d7e90.png)

And, we have this error logged in the App Service:

![image](https://user-images.githubusercontent.com/104429461/220878244-0fe37200-7ff6-4821-9e32-c5df2af8260a.png)

We have opened an issue for this error but for another action - https://github.com/microsoft/AzureTRE/issues/3240

What we can do now?

**Comment by marrobi** [comment]
This is a 502 error, it looks like the API is returning 200 on the `ping` endpoint. So think App Gateway is to blame.

Can you try the steps here - https://github.com/microsoft/AzureTRE/issues/2879#issuecomment-1426023210

Interested if its a similar issue.

**Comment by dusan-ilic-mhra** [comment]
This is what we have:

![image](https://user-images.githubusercontent.com/104429461/220892831-eeb081db-07c2-447a-bb99-53c6c69fe18e.png)

![image](https://user-images.githubusercontent.com/104429461/220893012-d24bb7ee-3ae0-4325-a7c5-2b42bcf0a1dc.png)

**Comment by dusan-ilic-mhra** [comment]
And, I don't have this image in ACR:

![image](https://user-images.githubusercontent.com/104429461/220893777-8e8e182b-781f-4a8a-92e6-8ccc883eb851.png)

![image](https://user-images.githubusercontent.com/104429461/220893835-99779c8d-70dd-4a12-bb88-f4f80215f098.png)

**Comment by tamirkamara** [comment]
@dusan-ilic-mhra running just `make tre-deploy` isn't enough...
please run `make all` to make sure all components are actually in place. This will automatically include `make images` that will push the new images.

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara This is after make all:

![image](https://user-images.githubusercontent.com/104429461/220925919-4018e287-6def-4e64-966d-961048542c04.png)

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara 

I run **make all** again and I got this:

![image](https://user-images.githubusercontent.com/104429461/220931707-7eae0da5-b9cb-4907-b576-82b4d8a61b1b.png)

I will continue now with this step: 
_Issue a patch API request to force-update the firewall to its new version._
from here: https://github.com/microsoft/AzureTRE/releases/tag/v0.9.0

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara

It's still in "status": "awaiting_update":
![image](https://user-images.githubusercontent.com/104429461/220937743-556685aa-a883-4f1f-a286-0bed9937f951.png)

Do I need to restart VMSS maybe?

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara 

I restarted VMSS but this is still in "status": "awaiting_update":

![image](https://user-images.githubusercontent.com/104429461/221013426-769d2a55-d49d-4ca2-bd9d-47244593d41d.png)

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara, @marrobi 

This is still in **_awaiting_update_** status:

![image](https://user-images.githubusercontent.com/104429461/221129555-0753cc49-de4b-467d-b8ce-4a05180e3ff2.png)

But, this is strange because I can see that the firewall is updated somehow to version 1.0.0:

![image](https://user-images.githubusercontent.com/104429461/221129836-64cd395c-98c4-4646-8c84-594691f64212.png)

And also, I see that **tre-shared-service-firewall image** is deployed with v1.0.0:

![image](https://user-images.githubusercontent.com/104429461/221130093-14c26507-44e7-4366-b0a1-36b9d1026c70.png)

But, **tre-shared-service-firewall-installer** image is still with version v0.6.3:

![image](https://user-images.githubusercontent.com/104429461/221130565-4241f437-d70f-4848-8f2a-3413b5ac738c.png)

What we should do now?

**Comment by marrobi** [comment]
@dusan-ilic-mhra I think can ignore the container image differences, I don't have the installer images, think this might be a change since Porter v1.0:
![image](https://user-images.githubusercontent.com/17089773/221191482-8bc8b091-e98b-4e15-84b7-54c82ce32098.png)

Is the TRE up and health as per https://microsoft.github.io/AzureTRE/v0.9.0/tre-developers/api/#investigating-apihealth-response ?

**Comment by marrobi** [comment]
@dusan-ilic-mhra https://microsoft.github.io/AzureTRE/v0.9.0/troubleshooting-faq/troubleshooting-rp/

**Comment by javos79** [comment]
I found that the dev container version needs to be updated, but I'm missing the documentation on how to update an existing installation.

According to this error, my assumption of running "make tre-depoy" was correct - but only an assumption.

I would please you provide a link to the docs, if it exists

**Comment by marrobi** [comment]
@javos79 @dusan-ilic-mhra I've added some notes on upgrades here - https://github.com/microsoft/AzureTRE/pull/3262  Let me know if this information would have helped with the upgrade process.

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara @marrobi 

We still have "context deadline exceeded" issues. We succeeded just once to upgrade the environment.

We also tried with the current version we are using 0.7.0 and with 0.9.0 and we are getting these errors in both versions for the different resource types. 

With this behavior, currently, we are blocked to progress anything because we can't create an environment.

Because we get these errors in v0.7.0 and v0.9.0, do you know if this is some change on Azure itself because it recently started to happen? Before, we didn't have this behavior.

**Comment by marrobi** [comment]
Nothing has changed here, this is typically down to local machine or networking configuration.

We hit similar issues when on the Microsoft corporate network where they override some of the private link DNS zones. 

Have you tried using a CI/CD pipeline with cloud hosted build agents or via codespaces?

**Comment by dusan-ilic-mhra** [comment]
Yes:
![image](https://user-images.githubusercontent.com/104429461/222747353-e230f538-e6f2-41f8-be11-866d3cede6d9.png)

**Comment by marrobi** [comment]
@dusan-ilic-mhra is this a generic GitHub hosted agent or a private agent?

Feels like a terraform bug of some sort. Although unusual that its a network security group which doesn't include private link functionality.

This article may help:
https://support.hashicorp.com/hc/en-us/articles/4404634420755-Why-am-I-seeing-context-deadline-exceeded-errors

**Comment by marrobi** [comment]
Also suggest opening an issue here - https://github.com/hashicorp/terraform-provider-azurerm/issues

I wonder if its something specific to your subscription that is blocking the requests - something like DDoS protection as we've not seen this on any other deployment.

Can you try getting the Terraform debug logs?

https://developer.hashicorp.com/terraform/internals/debugging
