### ISSUE TITLE
create new workspace_service error

### ISSUE THREAD

**Issue by pselmani** [microsoft/AzureTRE#3248]
Hi,

I've done a successful make bundle-build\publish\register on a workspace_service, it's a simple storage account

When I try to deploy azure resource out of that, it gives me the below error

Status
: deployment_failed
Action
: install
Message
: 50908537-74e8-4300-813f-0da35e0eecdb: Error message: Unable to find image 'trect07acr.azurecr.io/tre-workspace-service-psstorage2@sha256:9155f076c02e49731c396ce3c2d2257fd1227c966d572345eeb8d090bbf7c733' locally [31m[31m╷[0m[0m [31m│[0m [0m[1m[31mError: [0m[0m[1mFailed to get existing workspaces: Error retrieving keys for Storage Account "{{ bundle.parameters.tfstate_storage_account_name }}": storage.AccountsClient#ListKeys: Invalid input: autorest/validation: validation failed: parameter=resourceGroupName constraint=Pattern value="{{ bundle.parameters.tfstate_resource_group_name }}" details: value doesn't match pattern ^[-\w\._\(\)]+$[0m [31m│[0m [0m [31m│[0m [0m[0m [31m╵[0m[0m [0m[0m Error: could not init terraform, exit status 1 1 error occurred: * mixin execution failed: package command failed /cnab/app/cnab/app/mixins/terraform/runtimes/terraform-runtime install [31m[31m╷[0m[0m [31m│[0m [0m[1m[31mError: [0m[0m[1mFailed to get existing workspaces: Error retrieving keys for Storage Account "{{ bundle.parameters.tfstate_storage_account_name }}": storage.AccountsClient#ListKeys: Invalid input: autorest/validation: validation failed: parameter=resourceGroupName constraint=Pattern value="{{ bundle.parameters.tfstate_resource_group_name }}" details: value doesn't match pattern ^[-\w\._\(\)]+$[0m [31m│[0m [0m [31m│[0m [0m[0m [31m╵[0m[0m [0m[0m Error: could not init terraform, exit status 1 1 error occurred: * mixin execution failed: package command failed /cnab/app/cnab/app/mixins/terraform/runtimes/terraform-runtime install [31m[31m╷[0m[0m [31m│[0m [0m[1m[31mError: [0m[0m[1mFailed to get existing workspaces: Error retrieving keys for Storage Account "{{ bundle.parameters.tfstate_storage_account_name }}": storage.AccountsClient#ListKeys: Invalid input: autorest/validation: validation failed: parameter=resourceGroupName constraint=Pattern value="{{ bundle.parameters.tfstate_resource_group_name }}" details: value doesn't match pattern ^[-\w\._\(\)]+$[0m [31m│[0m [0m [31m│[0m [0m[0m [31m╵[0m[0m [0m[0m Error: could not init terraform, exit status 1 2 errors occurred: * container exit code: 1, message: <nil> * required output internal_connection_uri is missing and has no default ; Command executed: az login --identity -u 7500626c-b78a-49c5-bd19-2e9a47807d08 && az acr login --name trect07acr && porter install "50908537-74e8-4300-813f-0da35e0eecdb" --reference trect07acr.azurecr.io/tre-workspace-service-psstorage2:v0.1.1 --param arm_use_msi="true" --param id="50908537-74e8-4300-813f-0da35e0eecdb" --param mgmt_acr_name="trect07acr" --param mgmt_resource_group_name="trect071-rg" --param tfstate_container_name="tfstate" --param tfstate_resource_group_name="trect071-rg" --param tfstate_storage_account_name="trect07store" --param tre_id="trect071ci" --param workspace_id="a3384f46-c377-44d8-95f8-de5d5d01a7c7" --allow-docker-host-access --force --credential-set arm_auth --credential-set aad_auth

Happy to share my code
Any ideas?

**Comment by marrobi** [comment]
This is the error: `Invalid input: autorest/validation: validation failed: parameter=resourceGroupName constraint=Pattern value="{{ bundle.parameters.tfstate_resource_group_name }}"

You are using a Porter v0.x bundle format, but the TRE is using Porter v1.x. In the changelog it notes updating bundles to Porter v1 format.

The `{{` notation is no longer valid, see:
https://github.com/microsoft/AzureTRE/blob/main/templates/workspaces/base/porter.yaml

For the v1 equivalent. 

Will close the issue, as sure this is the problem.
