### ISSUE TITLE
Teerraform issue when using Github CI/CD

### ISSUE THREAD

**Issue by slawpast** [microsoft/AzureTRE#3250]
When running Deploy Azure TRE job, I am getting following errors. I tried to remove listed resources, and run again, also simply restarting the job (few times), error still exists

![image](https://user-images.githubusercontent.com/107872721/221159535-3e347167-208e-4522-a315-35ead74186f6.png)

**Comment by marrobi** [comment]
It looks like you have tried to deploy using a `TRE_ID` that has been used before and resources still exist - either outside of the resource group or in a soft deleted state.

The resources listed either need to be deleted from Azure or imported into your terraform state.

If this is a development deployment with no workspaces I suggest changing your `TRE_ID` to ensure resources are created that do not already exist.

**Comment by mvalijipa** [comment]
Yes we tried using the same `TRE_ID` after deleting the previous resources using make `tre-destroy`.

Since we are using the CICD route, is there a way of handling these imports into the Terraform State if we would like to continue using the same `TRE_ID` .

**Comment by marrobi** [comment]
Yes, set up your local deployment repo dev container with the same settings in the config.yaml as your CI secrets:

Edit `AzureTRE/core/terraform/import.sh` and change the command on line 17 to look similar to this:

`-c "terraform import module.appgateway.azurerm_key_vault_certificate.tlscert https://kv-xxxx.vault.azure.net/certificates/letsencrypt/dce717bf2fa242ad8c9900f4317d0591"`

(can do multi line commands with `&& \`)

Using the module names and paths copied from the Terraform error.

Then run make terraform-import DIR=AzureTRE/core

When all imported run the deploy command again.

**Comment by mvalijipa** [comment]
Prefect. Thank you. 

Would I have to run the command manually using `make tre-deploy` or could I just rerun my devOps actions for deployment.

**Comment by marrobi** [comment]
You need to run ` make terraform-import DIR=AzureTRE/core`

We haven't a actions pipeline for this.

**Comment by mvalijipa** [comment]
Okay understood. Will keep this in mind for next time. Thank you.
