### ISSUE TITLE
Authentication has not yet been provisioned for this resource

### ISSUE THREAD

**Issue by slawpast** [microsoft/AzureTRE#3253]
Error appears during a workspace creation via TRE ui:

We also are not able to access the workspace after it was deployed.

![image](https://user-images.githubusercontent.com/107872721/221553373-25e33638-6557-44a9-981f-e5ffccb1f13b.png)

**[UPDATE]:** this was resolved after running `make letsencrypt` manually. 
However, because we deployed using CI/CD we were excepting letsencrypt to run as a part of devops pipeline.

**Comment by marrobi** [comment]
@slawpast not sure this is an error - what you see is a status notification as to why you cannot yet access the workspace. You just need to wait until the workspace has been deployed.

Lets Encrypt should not affect this. As different customers manage their certificates in different way's Lets Encrypt is not part of the default deployment pipelines.

If the workspace deployment failed, what was the error? This can be retrieved by the following swagger endpoint:
![image](https://user-images.githubusercontent.com/17089773/221600227-1a681d91-4c7b-41a1-aef1-92145c07719b.png)

#2363 is to track making this available in the UI.

**Comment by slawpast** [comment]
Thank you Marcus for your response.
We have redeployed the environment, and this issue is gone.
