### ISSUE TITLE
Overlapping address space on workspace creation

### ISSUE THREAD

**Issue by javos79** [microsoft/AzureTRE#3255]
Based on this error message when creating a couple of TRE workspaces based on a template. When you don't specify a custom address space, TRE will create the address based on the size you have specified. Unfortunately, it has not been checked if the address space was already set for another workspace:

Hence this:

```
Message="Cannot create or update peering /subscriptions/*******/resourceGroups/rg-****tredev2-ws-071f/providers/Microsoft.Network/virtualNetworks/vnet-****tredev2-ws-071f/virtualNetworkPeerings/ws-core-peer-****tredev2-ws-071f.

Virtual networks /subscriptions/*******/resourceGroups/rg-****tredev2-ws-071f/providers/Microsoft.Network/virtualNetworks/vnet-****tredev2-ws-071f and /subscriptions/*******/resourceGroups/rg-****tredev2/providers/Microsoft.Network/virtualNetworks/vnet-****tredev2 
cannot be peered because address space of the first virtual network overlaps with address space of virtual network 
/subscriptions/*******/resourceGroups/rg-****tredev2-ws-e2f1/providers/Microsoft.Network/virtualNetworks/vnet-****tredev2-ws-e2f1 already peered with the second virtual network. Overlapping address prefixes: 10.1.7.0/24.
```

There should be a checking mechanism for this in the workspace upon creation

Maybe this is related: https://github.com/microsoft/AzureTRE/issues/2986 but in our case we perform this sequentially, whereas the ticket mentioned performs workspace creation in parallel

**Comment by tamirkamara** [comment]
Have you made any manual action on your environment like:
1. Delete workspace Resource Groups by other means than the TRE system (like via the azure portal)
2. Delete any items from the CosmosDB
?

**Comment by marrobi** [comment]
@javos79 any update on this? Thanks.
