### ISSUE TITLE
Manual cleanup necessary after failed deployment

### ISSUE THREAD

**Issue by javos79** [microsoft/AzureTRE#3256]
After a failed workspace deployment, we are unable to delete this workspace. 
Reason: We are also not able to disable the workspace because it runs into an error

We encountered several error messages. We assume it depends on the stage where the deployment failed
```
Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code=\"AuthorizationFailure\" Message=\"This request is not authorized to perform this operation
```
and also 
```
Error context message = ERROR: Unsupported or invalid query filter clause specified for property 'identifierUris' of resource 'Application'. 
```

Because of this error we have to result into deleting all related resources (resource group, tfstate, storage, permissions, ...) by ourselves manually and also removing the workspace item manually from cosmos database.

<img width="164" alt="image" src="https://user-images.githubusercontent.com/46265242/221562798-2ab78167-3d85-4dbf-8910-f097ff788ac9.png">

**Comment by tamirkamara** [comment]
I understand that disable failed, but have you tried to ask for its deletion anyway (sometimes that would work just fine)?

**Comment by tim-allen-ck** [comment]
not seen for a while, closing. Please reopen if problem persists.
