### ISSUE TITLE
[GOV] Add support for US Gov cloud in porter azure plugin

### ISSUE THREAD

**Issue by LizaShak** [microsoft/AzureTRE#3284]
## Description

As a Azure TRE Developer
I want the porter azure plugin to support vaultUrl
So that I can use KV which are not on public cloud.

Link to issue in the plugin repo: https://github.com/getporter/azure-plugins/issues/57

Technical notes:
- Patch solution for reference: https://github.com/getporter/azure-plugins/compare/main...LizaShak:azure-plugins:main
- I understood their approach is to pass vaultUrl as additional param, and use it if it is passed. Please verify with Caroline.
-  See Developer Tasks in : https://github.com/getporter/porter/blob/main/CONTRIBUTING.md to see how to build the plugin and test it. 

## Acceptance criteria
- [x]  A fixing PR is merged on the repo: https://github.com/getporter/azure-plugins
- [x]   azure plugin is able to connect and get secrets from KeyVault in US Gov cloud
- [x]   azure plugin is able to connect and get secrets from KeyVault in public cloud

**Comment by anatbal** [comment]
https://github.com/getporter/azure-plugins/pull/60
Waiting for Carolyn's review
