### ISSUE TITLE
[GOV]  Authority passed to services should be dynamically sourced

### ISSUE THREAD

**Issue by LizaShak** [microsoft/AzureTRE#3287]
## Description

As a Azure TRE Developer
I want to eliminate the hardcoded `login.microsoftonline.com`  passed as authority
So that I can deploy our solution in multiple clouds

Technical notes:
- Search for all the places where `login.microsoftonline.com` is passed as authority/issuer
- Think of a design how to source it dynamically or with a config that easy to change when deployed on another cloud

## Acceptance criteria

- [ ] login.microsoftonline.com is sourced  based on the target cloud type

**Comment by tamirkamara** [comment]
Is this the same Authority that corresponds to one in which the workspace app was create in?
