### ISSUE TITLE
Azure TRE firewall rule not visible/not created

### ISSUE THREAD

**Issue by slawpast** [microsoft/AzureTRE#3302]
As a TRE admin I have added frewall.tf file under <i>AzureTRE/templates/workspaces/base/terrafrom/ </i> folder with the following content:
```
locals { 
  service_id = "970b"
  workspace_id = substr(var.tre_resource_id, -4, -1)
  allowed_urls                     = ["#####.blob.core.windows.net/","*google.com"]
  service_resource_name_suffix    = "${var.tre_id}-ws-${local.workspace_id}-svc-${local.service_id}"
}

data "azurerm_firewall" "fw" {
  name                = "fw-${var.tre_id}"
  resource_group_name = "rg-${var.tre_id}"
}

data "azurerm_virtual_network" "ws" {
    name                = "vnet-${var.tre_id}-ws-${local.workspace_id}"
    resource_group_name = azurerm_resource_group.ws.name
}

resource "null_resource" "az_login" {
  provisioner "local-exec" {
    command = "az login --identity -u '${var.arm_client_id}'"
  }

  triggers = {
    timestamp = timestamp()
  }
}

data "external" "rule_priorities" {
  program = ["bash", "-c", "./get_firewall_priorities.sh"]

  query = {
    firewall_name       = data.azurerm_firewall.fw.name
    resource_group_name = data.azurerm_firewall.fw.resource_group_name
    service_resource_name_suffix = local.service_resource_name_suffix
  }
  depends_on = [
    null_resource.az_login
  ]
}

resource "azurerm_firewall_application_rule_collection" "apprulecollection" {
  name                = "arc-${local.service_resource_name_suffix}"
  azure_firewall_name = data.azurerm_firewall.fw.name
  resource_group_name = data.azurerm_firewall.fw.resource_group_name
  priority            = data.external.rule_priorities.result.application_rule_priority
  action              = "Allow"

  rule {
    name = "allowRulesTest"

    source_addresses = data.azurerm_virtual_network.ws.address_space

    target_fqdns = local.allowed_urls

    protocol {
      port = "443"
      type = "Https"
    }
    protocol {
      port = "80"
      type = "Http"
    }
  }
}
```

The workspace was re-built using make <b>workspace_bundle BUNDLE=base </b>command

We cannot see this rule anywhere within firewall policy Rule Connections.
We cannot connect to google in a virtual desktop, power shell results in Request timed out

![image](https://user-images.githubusercontent.com/107872721/222758972-7c466323-027e-4251-9acf-cf2bdb25f8da.png)

The excersise was to access azure AD from the virtual machine.

**Comment by marrobi** [comment]
@slawpast what you have done "should" work, however, can I suggest you take a look at the Guacamole workspace service for an example of how firewall rules can be added to the Firewall shared service - https://github.com/microsoft/AzureTRE/blob/4ccc6536558c545f5c49c1db81359477c9672d93/templates/workspace_services/guacamole/template_schema.json#L78

This ensures the rules get added to the shared service state, and avoids the challenge around priorities and rules being overwritten.

The `get_firewall_priorities.sh` script was depreciated a long time ago. Apologies, it looks like the docs need an update. https://microsoft.github.io/AzureTRE/v0.9.0/tre-workspace-authors/firewall-rules/

Try that approach and if you have an issue let us know and we can reopen the issue. I am going to create a bug for the docs.

**Comment by marrobi** [comment]
Added a bug https://github.com/microsoft/AzureTRE/issues/3315

**Comment by marrobi** [comment]
@slawpast this link explain template schema with an example around firewall rules - https://microsoft.github.io/AzureTRE/v0.9.0/tre-templates/pipeline-templates/pipeline-schema/ . We will the get the firewall rules documentation updated.

**Comment by slawpast** [comment]
@marrobi 
We have modified template schema as per your advice:
**/templates/workspace_services/guacamole/template_schema.json**

<img width="976" alt="image" src="https://user-images.githubusercontent.com/107872721/223101706-0c83113e-e242-44e4-8901-200152b54a7d.png">

After changes we made following steps:

1. Re-deployed guacamole workspace service 
`make workspace_service_bundle BUNDLE=guacamole`
2. Created a new workspace service.
3. Created a new virtual machine.

The issues still persists:
<img width="976" alt="image" src="https://user-images.githubusercontent.com/107872721/223104987-ac0ccb4c-df15-48a4-88a6-4996cd5b2225.png">

**Comment by marrobi** [comment]
You are putting a FQDN - `google.com` into a network rule collection. FQDN can only be used on application rule collections. 

An example can be found here - https://github.com/microsoft/AzureTRE/blob/d167dae861b212b4c5e8217203ee3651915358ff/templates/workspace_services/azureml/template_schema.json#L188

**Comment by slawpast** [comment]
Thank you @marrobi for your response. We have added the following rule to 
**/templates/workspace_services/guacamole/template_schema.json**

<img width="782" alt="image" src="https://user-images.githubusercontent.com/107872721/223138543-ad1f4ff0-7e5e-47f4-8957-e9063e522243.png">

The rule has been added:
![image](https://user-images.githubusercontent.com/107872721/223139876-46a819c1-1548-45f3-85eb-d8463a3be49e.png)

However, we still cannot connect to the url

![image](https://user-images.githubusercontent.com/107872721/223140140-973320cf-c0cf-4424-bb7a-e523e1b70e1a.png)

**Comment by marrobi** [comment]
Does ping work over port 443 or 80? I suggest you try an http request. 

Also verify your VM's IP is in the source range.

**Comment by marrobi** [comment]
You will need to create an additional output that contains the IP address range you require.

You can see in the AML bundle we reference the entire workspace address space, rather than just the web app address range:

https://github.com/microsoft/AzureTRE/blob/4ccc6536558c545f5c49c1db81359477c9672d93/templates/workspace_services/azureml/terraform/outputs.tf#L21

https://github.com/microsoft/AzureTRE/blob/4ccc6536558c545f5c49c1db81359477c9672d93/templates/workspace_services/azureml/porter.yaml#L147

https://github.com/microsoft/AzureTRE/blob/4ccc6536558c545f5c49c1db81359477c9672d93/templates/workspace_services/azureml/template_schema.json#L141

**Comment by slawpast** [comment]
Great. Thank you @marrobi.
