### ISSUE TITLE
[GOV]  Hardcoded servicebus url should be dynamically sourced

### ISSUE THREAD

**Issue by LizaShak** [microsoft/AzureTRE#3306]
## Description

As a Azure TRE Developer
I want the hardcoded `.servicebus.windows.net` to be sourced dynamically
So that our code is easier to maintain.

## Acceptance criteria

- [ ] service bus url  is dynamically set

**Comment by tamirkamara** [comment]
Waiting for https://github.com/hashicorp/terraform-provider-azurerm/pull/20790

**Comment by tamirkamara** [comment]
This now waits for the next provider version (3.47) to be released
