### ISSUE TITLE
Airlock API authentication failed using Postman

### ISSUE THREAD

**Issue by mvalijipa** [microsoft/AzureTRE#3324]
I am trying to use Airlock APIs to automatically create requests and upload data to the airlock containers and ultimately the workspace. Might align with the following ticket: https://github.com/microsoft/AzureTRE/issues/2304 

I am trying to use the APIs from https://microsoft.github.io/AzureTRE/v0.9.0/azure-tre-overview/airlock/ in Postman to test out the basics. However, I am facing a few issues with getting the correct scope to make the Outh2 work. 

**Error messaged received:**
![image](https://user-images.githubusercontent.com/107870922/223450121-6de539f6-9b38-4d9f-8832-4a4df2013d52.png)

**Here are the settings from postman:**

Authorization URL: https://login.microsoftonline.com/3b3d872b-1521-4140-bab8-43a0db479eef/oauth2/v2.0/authorize
Token URL: https://login.microsoftonline.com/3b3d872b-1521-4140-bab8-43a0db479eef/oauth2/v2.0/token

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/107870922/223450431-e96ba68c-644a-46d2-a22c-1bb4a5069c7e.png">

**Comment by marrobi** [comment]
The scope you are using is set to `null`. 

You can find the scope either by using the Swagger docs, when click Authorize it lists the scope.

Or view the application registration in Azure AD and can see the scopes listed:

![image](https://user-images.githubusercontent.com/17089773/223667335-3a8e05c8-1075-488c-bd5b-1fcc26739291.png)

**Comment by mvalijipa** [comment]
@marrobi thank you for that. I managed to get the scopes from application registration in Azure AD as mentioned. 

I was also required to setup some authentication configurations to get the callbacks uris to work. Here is the setup:
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/107870922/223699374-f421828a-27dc-4970-9e14-7a3672a4fa06.png">

Once setup I was able to successfully login as part of the authentication process. However, I am still receiving the following error in postman:
<img width="1480" alt="image" src="https://user-images.githubusercontent.com/107870922/223699755-e75aaaf9-eca2-4ecb-875a-7d4db78b29f9.png">

Am I required to do some additional configurations?

**Comment by marrobi** [comment]
Looks like you have something on the end of your token URI - %0A ?

**Comment by mvalijipa** [comment]
@marrobi that is right, I think there was an 'enter' after the token URI. Amended that now but still get another error:
<img width="1480" alt="image" src="https://user-images.githubusercontent.com/107870922/223702121-a4824aa8-a787-42e5-8af5-cac817af6147.png">

I think it might be due to the client secret. Currently I have the client secret as blank same as the Swagger docs.
<img width="816" alt="image" src="https://user-images.githubusercontent.com/107870922/223702837-05f18096-8161-46a6-946f-d64ee3ee0304.png">

**Comment by marrobi** [comment]
I'm afraid I can't give you any more in depth support around postman as it's outside of the scope of the Azure TR project.

You need to get a token for a client app and use that to call the backend API. This is the equivalent of the TRE UI or Swagger docs calling the UI.

I suggest you read: https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview

And: https://dev.to/425show/calling-an-azure-ad-secured-api-with-postman-22co

**Comment by mvalijipa** [comment]
Okay no problem. I thought it might have been an issue with how I was trying to execute the API request and not postman. 

I will have a read through the docs provided and see if I am able resolve the issue.
