### ISSUE TITLE
TRE UI does not update when an action on a VM completes

### ISSUE THREAD

**Issue by anastasiakuzn** [microsoft/AzureTRE#3353]
For example, trying to **stop** a machine. The UI did not appear to register the request.

![CleanShot 2023-02-14 at 14 00 46](https://user-images.githubusercontent.com/1080268/218760919-1a15cad3-1720-4dde-afe3-438cc2a0fa8b.png)

then this only after refresh ....

![CleanShot 2023-02-14 at 14 02 44](https://user-images.githubusercontent.com/1080268/218761158-fa870b29-7476-4f7f-9690-85b3082235b1.png)

The same happened when I tried to deploy a new machine. The little blue spinner just told me the process was  pending, until I refreshed the browser page.

**Comment by martinpeck** [comment]
I believe I've worked out what's going on here.

This does not reproduce if you are a TREAdmin. Users who see this do not have admin access.
Users have multiple bearer tokens when using the TRE UI:
1. a bearer token for general access to the TRE
1. a bearer token specifically for accessing resources in a given workspace

By looking at the browser dev tools, and inspecting the bearer token for a user seeing this issue, I can see that the token being presented for these updates is the first token (the general access token) and so the user is presenting as a `TREUser`...

``` json
"roles": [
    "TREUser"
  ],
```

The UI makes calls to the API to get updates for the workspace. The URL it calls is...
 
`https://mrictretest.uksouth.cloudapp.azure.com/api/workspaces/<workspace-id>`

This API route is only callable by users in the following roles...

```
["TREAdmin", "WorkspaceOwner", "WorkspaceResearcher", "AirlockManager"]
```

and so, the API call returns an HTTP 403 and this is why the UI doesn't update.
