### ISSUE TITLE
Generate OMOP dataset (in postgre)

### ISSUE THREAD

**Issue by itye-msft** [microsoft/AzureTRE#3356]
- Generate two synthetic datasets (1k patients) using Synthea as CSV files
- Download vocabularies from Athena
- Using Hades and ETLSyntheaBuilder OHDSI R Package:
  - Create OMOP CDM schema on PostgrSQL
  - Create Synthea schema on PostgrSQL
  - Load Synthea data to PostgreSQL
  - Load vocabulary data to PostgreSQL
  - Generate events data on PostgreSQL
- Using Archilles R Package generate results schema and data on PostgreSQL

DoD
Atlas is configured to a new CDM source on Azure database for PostgreSQL

**Comment by guybartal** [comment]
opened by mistake in this repo, closing
