### ISSUE TITLE
Use versioned environment configuration module 

### ISSUE THREAD

**Issue by LizaShak** [microsoft/AzureTRE#3382]
## Description

As a Azure TRE Developer
I want to use a specific version of [terraform-azurerm-environment-configuration](https://github.com/microsoft/terraform-azurerm-environment-configuration) module
So that i am sure that the module is stable

**Comment by tamirkamara** [comment]
@LizaShak Isn't this done?

**Comment by LizaShak** [comment]
@Yes it is... Closing it
