### ISSUE TITLE
Deployment custom user resource bundle failed in Github Actions

### ISSUE THREAD

**Issue by slawpast** [microsoft/AzureTRE#3386]
As a TREAdmin I want to deploy custom GPU virtual machine, it fails during GitHub actions deployment with the following error:

`    Usage: /home/vscode/AzureTRE//devops/scripts/register_bundle_with_api.sh [-c --current] [-i --insecure]

    Options:
        -r, --acr-name                Azure Container Registry Name
        -t, --bundle-type             Bundle type: workspace, workspace_service, user_resource or shared_service
        -w, --workspace-service-name  The template name of the user resource (if registering a user_resource)
        -c, --current                 Make this the currently deployed version of this template
        -v, --verify                  Verify registration with the API
        --dry-run                     Don't submit the template to the API, just output the payload`

However, it works on a local machine, when running on Docker from Visual Studio Code with a custom make command: **user_resource_bundle_custom**

**Steps to reproduce**

1. Copy **guacamole-azure-windowsvm** folder into our repository
3. Rename it to **guacamole-azure-windowsvm- gpu** 
4. Modify template_schema.json to include new os_image:
![image](https://user-images.githubusercontent.com/107872721/228774821-90f540f0-0bb1-4e2e-b964-b1a21c2b9ba0.png)
5. Modify porter.yaml to include new option.
![image](https://user-images.githubusercontent.com/107872721/228775119-ffdf7e89-7655-4369-b477-1fdfbf8c7f84.png)

6. Insert extra bundles into **deploy_tre_reusable.yml** file:
![image](https://user-images.githubusercontent.com/107872721/228775936-c08747da-f8fa-4baf-85d0-e6e328d9537e.png)

![image](https://user-images.githubusercontent.com/107872721/228775697-728bb737-5481-4fd1-83ea-a88818509b32.png)

7. Modify **Makefile**
![image](https://user-images.githubusercontent.com/107872721/228776679-bef9a4fd-74f6-4962-b8e4-6260d9d27006.png)

**Comment by marrobi** [comment]
Looks like you are missing WORKSPACE_SERVICE_NAME - maybe add to line 607 - can see others on 600, 603 etc.

**Comment by slawpast** [comment]
Thank you @marrobi we did not spot that, we are testing it now, once successful, I will close the issue.
