### ISSUE TITLE
Explore: Using Azure Information Protect with Azure Machine Learning

### ISSUE THREAD

**Issue by Lybecker** [microsoft/AzureTRE#34]
The TRE secures the data by not allowing data transfer in or out of the closed VNET. With [Azure Information Protect] (https://docs.microsoft.com/en-us/azure/information-protection/what-is-information-protection), data can classified, protected and access governed by an AAD identity, to enhance security and minimize the risk of data leakage. E.g. if data left the TRE users will still not be able to read the content.

For Azure Machine Learning to be able to process/read data, it must be able to act as the identity of a user with permissions to read the data. This feature is in private preview: https://github.com/MayMSFT/identity-based-data-access/

Is this feature mature for TRE?

**Comment by marrobi** [comment]
Closing this as it's an AML feature than TRE feature. If find there is a requirement down the line for an AML TRE service supporting this we can reopen.
