### ISSUE TITLE
Mount persistent drive to Bundle for state keeping

### ISSUE THREAD

**Issue by Lybecker** [microsoft/AzureTRE#343]
**Is your feature request related to a problem? Please describe**

An enhancement to make the Resource Processor IoC tool agnostic and allowing the Workspace Bundle to keep its own state.

Currently the Bundle when executed is passed an Azure Storage Account as a parameter `TERRAFORM_STATE_CONTAINER_NAME`, `tfstate_storage_account_name` and `tfstate_resource_group_name`, which as the name states is intended for the Bundle to keep the Terraform backend state.
This solution is Terraform specific and is not agnostic for other IoC solutions.

**Describe the solution you'd like**

For every execution, the Resource Processor should mount an Azure Storage Account container. It should be the same container for the same Bundle + Workspace. This will allow the Bundle to keep state of any kind and we can remove the Terraform specific paramenter.

**Comment by marrobi** [comment]
As we are running on a VMSS and can run output commands on the same machine that does the deployment not sure this is needed. The IaC tooling will need to managed it's own state - but we can make `MGMT_RESOURCE_GROUP_NAME` and `MGMT_STORAGE_ACCOUNT_NAME`  variables available as environment variables to be used as required.
