### ISSUE TITLE
Untyped Terraform variables cause issues

### ISSUE THREAD

**Issue by tamirkamara** [microsoft/AzureTRE#3432]
**Describe the bug**

Many templates use terraform input variables without defining their type which makes them string ones. This can cause problems with other types like bool are used in comparisons. 

A bool_var is defined in porter.yaml as bool.
```hcl
var.bool_var == false
```
This translates to something like `False == false` which makes the condition result in a **false** despite the logical expectation for **true**.

- [ ] #3657

**Steps to reproduce**

1. Install a Guacamole service without exposing it externally - be sure the uncheck the box.
1. This should have resulted in the web-app having a private endpoint, which is doesn't.

**Comment by marrobi** [comment]
There is an additional aspect to this, even when it is typed the output is returned as a string back into cosmos.
