### ISSUE TITLE
guacamole-azure-linuxvm user service initializes Terraform with the same backend key as the Windows VM

### ISSUE THREAD

**Issue by SvenAelterman** [microsoft/AzureTRE#3434]
**Describe the bug**

I don't know if this is a real issue. But if it's meant to be generic, perhaps the OS could be removed from the `key` value?

**Steps to reproduce**

See this line of code: https://github.com/microsoft/AzureTRE/blob/d90d4929a6e6d5531fb3f1272c10af252e2c844d/templates/workspace_services/guacamole/user_resources/guacamole-azure-linuxvm/terraform/deploy.sh#L16

**Comment by tamirkamara** [comment]
Thank you for this.
This might be an issue for a developer running terraform commands directly. There's no issue with the bundle.
