### ISSUE TITLE
Document Azure services used and cost running an Azure TRE instance

### ISSUE THREAD

**Issue by Lybecker** [microsoft/AzureTRE#344]
## Description

As an Azure Administrator
I want to understand what is provisioned when setting up a TRE instance
So that I can estimate the Azure cost

## Acceptance criteria

- [x] Description of Azure services used for a TRE instance (core)
- [x] Description of Azure services used for Vanilla workspace instance

**Comment by CrimsonCabbageBob** [comment]
Would be great to have this considered as this is a need emerging for some of our customers.

Many thanks

Phil
