### ISSUE TITLE
[Task] API to use Managed Identity to authenticate against Cosmos DB

### ISSUE THREAD

**Issue by Lybecker** [microsoft/AzureTRE#345]
**Is your feature request related to a problem?

Currently the API use an API key `STATE_STORE_KEY` to authenticate against Cosmos DB. The API uses Managed Identity to authenticate against Azure Service Bus.

**Describe the solution you'd like

Using the same simplified access pattern to authenticate from the API to Azure resource.

Note: looks like Cosmos data-plane doesn't really support managed identity (in Python at least) but there might be a way to do this:
https://github.com/MicrosoftDocs/azure-docs/issues/29762
https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/tutorial-linux-vm-access-cosmos-db

**Comment by tamirkamara** [comment]
This is the best I came up with:
```python
from azure.cosmos import CosmosClient
from azure.mgmt.cosmosdb import CosmosDBManagementClient
from azure.identity import DefaultAzureCredential

subscription_id = "..."
resource_group = "..."
account_name = "..."

credential = DefaultAzureCredential()
dbmgmt = CosmosDBManagementClient(credential, subscription_id, f"https://management.azure.com")
keys = dbmgmt.database_accounts.list_keys(resource_group, account_name)

client = CosmosClient(url="...", credential=keys.primary_master_key)
```

**Comment by marrobi** [comment]
This is now possible in the SDK without using a master key, I will reopen and submit a PR
