### ISSUE TITLE
Buildx Error

### ISSUE THREAD

**Issue by MoIocSidi** [microsoft/AzureTRE#3452]
## Description

In my Azure TRE deployment I am trying to run the make all command and Get an error I have not seen before, This environment was working before, I ran the destroy command to tear it down, rebuilding isnt working.

## Code
Make all

![2023-04-21 10_58_41-Trecicd  Dev Container_ AzureTRE-Deployment  - Visual Studio Code](https://user-images.githubusercontent.com/111135644/233610298-bf727441-22c4-414d-b1ae-959d4ca207d5.png)

**Comment by marrobi** [comment]
Please try rebuilding your dev container without cache using:

![image](https://user-images.githubusercontent.com/17089773/233610578-42661b32-a1a2-4cb5-a068-cf64188c73b3.png)

**Comment by marrobi** [comment]
Or this could actually be an issue with the docker configuration on your host machine, rather than the dev container.

**Comment by MoIocSidi** [comment]
Thanks Marcus, I appear to be getting the same error

**Comment by marrobi** [comment]
Ok, that suggests it 's an issue with your Docker configuration rather than Azure TRE.

You could try reinstalling buildx: https://docs.docker.com/build/install-buildx/

If that does not work, suggest creating an issue on the Docker buildx repo: https://github.com/docker/buildx

**Comment by marrobi** [comment]
Closing this as isn't an issue with Azure TRE, but with docker configuration.
