### ISSUE TITLE
Deploy Core Error

### ISSUE THREAD

**Issue by MoSidiIC** [microsoft/AzureTRE#3458]
Please advise on the error below?
![Deploy Core](https://user-images.githubusercontent.com/131386615/234576617-feac98e4-cac5-4a04-ba55-978c0b0e8285.PNG)

**Comment by MoSidiIC** [comment]
@LizaShak kindly advise?

**Comment by tamirkamara** [comment]
@MoSidiIC which TRE version is this?

**Comment by tamirkamara** [comment]
If it's 0.10, then we have a bug there that is fixed and pending for the next release. https://github.com/microsoft/AzureTRE/pull/3444

In the meantime, add a new github environment variable `RP_BUNDLE_VALUES` with a value of `{}`.

**Comment by MoSidiIC** [comment]
Thanks

**Comment by tamirkamara** [comment]
This is now released. Please use 0.11.0 going forward.
