### ISSUE TITLE
Deploying Shared Sevices Errror

### ISSUE THREAD

**Issue by MoSidiIC** [microsoft/AzureTRE#3459]
Receiving the error below during deployment:

Calling /health endpoint...
*** ⚠️ API _not_ healthy ***
Unhealthy services:
[
  ***
    "service": "Cosmos DB",
    "status": "Not OK",
    "message": "State Store endpoint is not responding"
  ***,
  ***
    "service": "Resource Processor",
    "status": "Not OK",
    "message": "Unspecified error"
  ***
]
make: *** [/home/vscode/AzureTRE/Makefile:369: api-healthcheck] Error ***
Error: Process completed with exit code 2.

Please advise?

**Comment by MoSidiIC** [comment]
@LizaShak Please advise? Thanks for the help earlier, the deployment is almost complete , just this final hurdle

**Comment by MoSidiIC** [comment]
@marrobi Any advice would be appreciated

**Comment by marrobi** [comment]
https://microsoft.github.io/AzureTRE/v0.10.0/troubleshooting-faq/troubleshooting-rp/

**Comment by MoSidiIC** [comment]
looks like its running, I will update it and rerun the job

**Comment by MoSidiIC** [comment]
@marrobi Inching forward , after restarting the resource processor it went a step further, but is balking at a missing firewall instance, im not sure when and where that should have nee created as everything else is successful :


 **mTerraform has been successfully initialized!
Using TEST_ACCOUNT_CLIENT_ID to get token via client credential flow
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
***00   ***89    0     0  ***00   ***89      0    926 --:--:-- --:--:-- --:--:--   92***
***00  ***420  ***00  ***23***  ***00   ***89   2829    434 --:--:-- --:--:-- --:--:--  3256
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
***00   ***25  ***00   ***25    0     0    ***73      0 --:--:-- --:--:-- --:--:--   ***72
***00   ***25  ***00   ***25    0     0    ***73      0 --:--:-- --:--:-- --:--:--   ***72
HTTP/***.*** 400 Bad Request
Date: Wed, 26 Apr 2023 ***6:34:33 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: ***25
Connection: keep-alive
Server: uvicorn

Expecting to have an instance of Firewall (template name tre-shared-service-firewall) deployed in a successful TRE deployment
Error while migrating state store
make: *** [/home/vscode/AzureTRE/Makefile:375: db-migrate] Error ***
Error: Process completed with exit code 2.

**Comment by tamirkamara** [comment]
@MoSidiIC have you tried to rerun the workflow from the start?

**Comment by MoSidiIC** [comment]
@tamirkamara Yes I have done that a few times now

**Comment by MoSidiIC** [comment]
@LizaShak @marrobi  Any advice would be much appreciated

**Comment by MoSidiIC** [comment]
@tamirkamara @marrobi @LizaShak Strangely in the step above the deployment
![Firewall](https://user-images.githubusercontent.com/131386615/234828003-3494fbd6-ceb2-4fb0-a6d5-ec026d107fbe.PNG)
 has happened successfully:

**Comment by LizaShak** [comment]
@MoSidiIC Is it deployed successfully?( To validate it is deployed successfully - go to the UI and then shared services, there should be an instance of firewall, in successful state it should be in status deployed and have no errors in the operations tab)

**Comment by MoSidiIC** [comment]
@LizaShak @marrobi Please see below:
![image](https://user-images.githubusercontent.com/131386615/234850147-55103266-9119-411e-96d3-537fec8bcfd1.png)

**Comment by tamirkamara** [comment]
Although I don't think we'd seen this before, it might be a failure on the cloud side. What is the `Provisioning state` of the firewall in the respective resource group?

**Comment by MoSidiIC** [comment]
is there any value is deleting it out of the cosmos DB and rerunning the workflow?

**Comment by tamirkamara** [comment]
Why Cosmos?
I'd start with removing the firewall through the TRE UI and then reinstall it.

**Comment by tamirkamara** [comment]
Can you try to reinstall the firewall from the UI too?

**Comment by MoSidiIC** [comment]
deployment successful from the UI, re running the workflow to see where it fails now

**Comment by MoSidiIC** [comment]
@tamirkamara Workflow completed successfully, deleting the fw and redeploying it from the TRE UI appears to have resolved worked around whatever was causing the issue.
