### ISSUE TITLE
Shared Service Config

### ISSUE THREAD

**Issue by MoSidiIC** [microsoft/AzureTRE#3460]
When running make shared_service_bundle BUNDLE=certs

I get the following:

rror building docker image: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: frontend grpc server closed unexpectedly
unable to build CNAB invocation image: error building docker image: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: frontend grpc server closed unexpectedly
unable to build CNAB invocation image: error building docker image: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: frontend grpc server closed unexpectedly
make[1]: *** [/home/vscode/AzureTRE/Makefile:183: bundle-build] Error 1
make[1]: Leaving directory '/workspaces/ImperialTRE'
make: *** [/home/vscode/AzureTRE/Makefile:280: shared_service_bundle] Error 2

I am assuming this is because the workspace version is no 0.3.2

Could I kindly have some guidance on how I confirm the worskpace version and how I update the version so i can create the shared service bundle.

**Comment by MoSidiIC** [comment]
@tamirkamara Any insights would be appreciated

**Comment by marrobi** [comment]
This looks like a docker issue again. Does it happen if you repeat the command?

Search online for "docker frontend grpc server closed unexpectedly" for some suggestions.

**Comment by MoSidiIC** [comment]
I double check and docker appears fine, repeated the command and it worked after a few tries. I will put this down to a local issue at my end.
