### ISSUE TITLE
Error during deployment - resources already exists

### ISSUE THREAD

**Issue by tljjvogten** [microsoft/AzureTRE#3485]
Even when deploying a fresh instance of the TRE in a new resource group, we get the following errors. The error below is an example, but it seems that all resources linked to the created keyvault are already existing. If anyone could direct me in the correct direction, that would be great. Thanks.

│ Error: A resource with the ID "/subscriptions/bd93f7fb-7335-4271-89ea-df14014b3fee/resourceGroups/rg-tretuedilab/providers/Microsoft.KeyVault/vaults/kv-tretuedilab/objectId/bd0f70a7-cadc-4fc0-ab98-6d5e417362c2" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_key_vault_access_policy" for more information.
│ 
│   with azurerm_key_vault_access_policy.deployer,
│   on keyvault.tf line 13, in resource "azurerm_key_vault_access_policy" "deployer":
│   13: resource "azurerm_key_vault_access_policy" "deployer" {
│ 
╵

**Comment by marrobi** [comment]
Hi @tljjvogten . Have you previously deployed Azure TRE with the same `TRE_ID`? Key Vault purge protection means Key Vault resources are left behind in a soft deleted state.

The easiest resolution would be to use a new `TRE_ID` and ensure your local terraform state is removed.

Alternatively you can import the soft deleted resources into state, but adding import commands to this script - https://github.com/microsoft/AzureTRE/blob/main/core/terraform/import.sh .

@tamirkamara can you just confirm I'm correct in my thinking above, the provider config below covers secrets, but not access policies?

```
provider "azurerm" {
  features {
    key_vault {
      # Don't purge on destroy (this would fail due to purge protection being enabled on keyvault)
      purge_soft_delete_on_destroy               = false
      purge_soft_deleted_secrets_on_destroy      = false
      purge_soft_deleted_certificates_on_destroy = false
      purge_soft_deleted_keys_on_destroy         = false
      # When recreating an environment, recover any previously soft deleted secrets - set to true by default
      recover_soft_deleted_key_vaults   = true
      recover_soft_deleted_secrets      = true
      recover_soft_deleted_certificates = true
      recover_soft_deleted_keys         = true
    }
  }
}
```

**Comment by tljjvogten** [comment]
I've redeployed the TRE with a different TRE ID, which I confirm works now. Thanks for the info, much appreciated.
