### ISSUE TITLE
CICD fails to deploy a new AzureTRE - TF says resources already exist

### ISSUE THREAD

**Issue by azuretresussex** [microsoft/AzureTRE#3493]
**Describe the bug**
CICD fails to deploy a new AzureTRE with the following error. 

│ Error: A resource with the ID "/subscriptions/***/resourceGroups/rg-***/providers/Microsoft.KeyVault/vaults/kv-***/objectId/f3b48d15-b55f-429d-90c7-609bb968cb91" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_key_vault_access_policy" for more information.
│ 
│   with azurerm_key_vault_access_policy.deployer,
│   on keyvault.tf line 13, in resource "azurerm_key_vault_access_policy" "deployer":
│   13: resource "azurerm_key_vault_access_policy" "deployer" ***
│ 
╵
╷
│ Error: A resource with the ID "/subscriptions/***/resourceGroups/rg-***/providers/Microsoft.KeyVault/vaults/kv-***|diagnostics-kv-***" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_monitor_diagnostic_setting" for more information.
│ 
│   with azurerm_monitor_diagnostic_setting.kv,
│   on keyvault.tf line 115, in resource "azurerm_monitor_diagnostic_setting" "kv":
│  115: resource "azurerm_monitor_diagnostic_setting" "kv" ***
│ 
╵
╷
│ Error: A resource with the ID "/subscriptions/***/resourceGroups/rg-***/providers/Microsoft.ServiceBus/namespaces/sb-***|diagnostics-sb-***" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_monitor_diagnostic_setting" for more information.
│ 
│   with azurerm_monitor_diagnostic_setting.sb,
│   on servicebus.tf line 95, in resource "azurerm_monitor_diagnostic_setting" "sb":
│   95: resource "azurerm_monitor_diagnostic_setting" "sb" ***
│ 
╵
╷
│ Error: A resource with the ID "/subscriptions/***/resourceGroups/rg-***/providers/Microsoft.Network/privateEndpoints/pe-file-***" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_private_endpoint" for more information.
│ 
│   with azurerm_private_endpoint.filepe,
│   on storage.tf line 39, in resource "azurerm_private_endpoint" "filepe":
│   39: resource "azurerm_private_endpoint" "filepe" ***
│ 
╵
╷
│ Error: A resource with the ID "/subscriptions/***/resourceGroups/rg-***/providers/Microsoft.OperationalInsights/workspaces/log-***/linkedStorageAccounts/Ingestion" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_log_analytics_linked_storage_account" for more information.
│ 
│   with module.azure_monitor.azurerm_log_analytics_linked_storage_account.workspace_storage_ingestion,
│   on azure-monitor/azure-monitor.tf line 34, in resource "azurerm_log_analytics_linked_storage_account" "workspace_storage_ingestion":
│   34: resource "azurerm_log_analytics_linked_storage_account" "workspace_storage_ingestion" ***
│ 
╵
╷
│ Error: A resource with the ID "/subscriptions/***/resourceGroups/rg-***/providers/Microsoft.OperationalInsights/workspaces/log-***/linkedStorageAccounts/CustomLogs" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_log_analytics_linked_storage_account" for more information.
│ 
│   with module.azure_monitor.azurerm_log_analytics_linked_storage_account.workspace_storage_customlogs,
│   on azure-monitor/azure-monitor.tf line 41, in resource "azurerm_log_analytics_linked_storage_account" "workspace_storage_customlogs":
│   41: resource "azurerm_log_analytics_linked_storage_account" "workspace_storage_customlogs" ***
│ 
╵
Script done.
Terraform Error
make: *** [/home/vscode/AzureTRE/Makefile:106: deploy-core] Error 1
Error: Process completed with exit code 2.

**Steps to reproduce**

1. Follow steps for a new AzureTRE deployment.
2. Run deploy_tre.yml, if it fails...
3. Delete the management and TRE resource groups
4. Re-run deploy_tre.yml

Perhaps an issue with stale state or pre-existing resources not being deleted in a timely fashion? I have reproduced this 3 times today, so it wasn't a one-off.

**Comment by marrobi** [comment]
Can you take a look at https://github.com/microsoft/AzureTRE/issues/3485 , and see if its the same issue. Thanks.

**Comment by azuretresussex** [comment]
Hi @marrobi - thanks - looks like it could be the same issue, yes.
I'll try a different TRE_ID and report back.

**Comment by azuretresussex** [comment]
A new TRE_ID looks like a good, if partial, workaround. (I think it would be better to be able to reuse the TRE_ID value though, rather than having to have a new one after each failed deployment - as it forms part of the URI for the TRE.)

I received a different error unfortunately.

<img width="708" alt="image" src="https://github.com/microsoft/AzureTRE/assets/132447702/48e74601-eef4-4a10-839f-871aff75f562">

I re-reployed the failed part of the workflow and received this error.

<img width="712" alt="image" src="https://github.com/microsoft/AzureTRE/assets/132447702/321b99d8-83f6-4abd-afcd-8b350683c9da">

**Comment by marrobi** [comment]
Not having much luck!

https://github.com/microsoft/AzureTRE/issues/3433

Deleted the resource and rerun.

@tamirkamara any ideas on how we can fix this permanently?
