### ISSUE TITLE
Creation of new Workspace fails in newly deployed TRE

### ISSUE THREAD

**Issue by azuretresussex** [microsoft/AzureTRE#3494]
**Describe the bug**
Creation of a new Workspace in a newly deployed TRE fails with the following error. Have reproduced with two different workspaces.

<img width="920" alt="image" src="https://github.com/microsoft/AzureTRE/assets/132447702/995989d2-f387-43be-ae74-b077e218e584">

Tried updating the workspace, that failed too.
<img width="350" alt="image" src="https://github.com/microsoft/AzureTRE/assets/132447702/ad0dfe7d-a9d5-4f30-89c1-5588b57015ea">

**Steps to reproduce**

1. Create a new Workspace in the UI with the following config.
<img width="618" alt="image" src="https://github.com/microsoft/AzureTRE/assets/132447702/a9d26a2e-e4b1-4444-afcb-d8341860adfc">

Is there a way to troubleshoot the deployment of the Workspace?

**Comment by marrobi** [comment]
What is `AUTO_WORKSPACE_GROUP_CREATION` set to?

https://microsoft.github.io/AzureTRE/v0.11.0/tre-admins/auth/

As you have ticked the create AAD groups box, this var needs to be true when running `make auth` for the correct permissions to be granted. 

There is a PR open to remove this box when this variable is set to false.

**Comment by azuretresussex** [comment]
That config item was false.

I added Group.ReadWrite.All to the Application Admin app registration, retried the workspace update in the portal and it failed again. 
<img width="1011" alt="image" src="https://github.com/microsoft/AzureTRE/assets/132447702/1a776670-e590-4ebc-8424-8579401dd242">

I unchecked the Create AAD Groups checkbox, in the Update a workspace modal/flyout  and it updated fine.
<img width="614" alt="image" src="https://github.com/microsoft/AzureTRE/assets/132447702/256275f3-4a88-4692-859e-ba64295eaade">

I can live with creating any required AAD Groups manually for now, but are the above App Registration permissions as they should be for creating a new workspace?

**Comment by marrobi** [comment]
The one your have added says delegated, think it should be application.

But it's the correct permission added.

**Comment by azuretresussex** [comment]
My mistake. 

I added Group.ReadWrite.All with Type=Application and was able to create a new workspace with the AAD groups checkbox checked.

<img width="538" alt="image" src="https://github.com/microsoft/AzureTRE/assets/132447702/fc441988-8a12-4ea1-bbba-f2fb289d3145">

Many thanks, again! :-)
