### ISSUE TITLE
DevContainer does not build unless you have az cli installed on your host machine

### ISSUE THREAD

**Issue by ross-p-smith** [microsoft/AzureTRE#3496]
TRE expects you to have az cli installed on your host and fails if you dont as it tries to bind mount your .azure folder. Why do I have to have az cli on the host - the point of a devcontainer is a self contained environment. Remove the mount in the devcontainer.json or add the Pre-requisite to the docs

**Steps to reproduce**

1. Don't have az cli installed on your host machine
1. Clone and open the project in a DevContainer and it will fail

```bash
invalid mount config for type "bind": bind source path does not exist: /home/<USER>/.azure
```

**Comment by tamirkamara** [comment]
I have tried this on a fresh VM: Win11, WSL, Docker, VSCode, no AZ insight and everything worked well.
Perhaps you've had another issue?

**Comment by tamirkamara** [comment]
Closing as stale.
