### ISSUE TITLE
Explore: Using RDP directly without Guacamole

### ISSUE THREAD

**Issue by Lybecker** [microsoft/AzureTRE#35]
Investigate if RDP meets the requirements for Virtual Desktop Service #18. Accessing af VM in the closed VNET behind an Azure Firewall.

Benefits of using RDP:

- Faster user experience
- Graphics acceleration
- Disabled screen capture
- Known and secure technology
- Supports both Windows and Linux
- No need to manage Guacamole + TomCat server

Acceptance criteria:

- [ ] Great Linux support for RDP
- [ ] Disable copy&past for both Linux and Windows (Normally it is handled via Group policies)
- [ ] Disable download and possibly upload of data/files
- [ ] Make use of [JIT access](https://docs.microsoft.com/en-us/azure/security-center/just-in-time-explained) via Azure Firewall

**Comment by Lybecker** [comment]
@jjcollinge applying the [VM best practices](https://www.microsoft.com/security/blog/2020/10/07/best-practices-for-defending-azure-virtual-machines/) and [JIT access](https://docs.microsoft.com/en-us/azure/security-center/just-in-time-explained)

**Comment by jjcollinge** [comment]
Ah ok, so the VM will have a public IP but just be secured as best it can be at that level?

**Comment by Lybecker** [comment]
That is the thinking.

**Comment by marrobi** [comment]
Closing as two RDP options going forward will be Guacamole (as a catch all solution) or Azure Virtual Desktop.
