### ISSUE TITLE
Sonatype Nexus VM not successfully deployed

### ISSUE THREAD

**Issue by craddm** [microsoft/AzureTRE#3500]
On a new deployment of version 0.11, Nexus Sonatype deployment seems to be failing. Although it successfully deploys, Nexus is not actually running. This also means no Linux VMs work. The failure seems to be during the cloud-init stage. I've attached the full serial console log.

Below are a couple of excerpts where errors are apparent

[nexus-dshtre.72a4ba77-37dd-44da-8d42-9018494b9e71.serialconsole.txt](https://github.com/microsoft/AzureTRE/files/11488466/nexus-dshtre.72a4ba77-37dd-44da-8d42-9018494b9e71.serialconsole.txt)

> [  210.617967] cloud-init[2411]: Unable to find image 'sonatype/nexus3:latest' locally
[  210.755479] cloud-init[2411]: docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": EOF.
[  210.759958] cloud-init[2411]: See 'docker run --help'.
[  210.762566] cloud-init[2411]: Checking for Nexus admin password file...
[[0;32m  OK  [0m] Created slice Slice for Azure VM Agent and Extensions.
[[0;32m  OK  [0m] Created slice azure-walinuxagent.slice.
[[0;32m  OK  [0m] Created slice Slice for Azure VM Agent Periodic Log Collector.
[[0;32m  OK  [0m] Started /usr/bin/python3 -u bin/WALâ€¦t-2.9.0.4-py2.7.egg -collect-logs.
[  511.116364] cloud-init[2411]: ERROR - Timeout while waiting for nexus-data/admin.password to be created
[[0;32m  OK  [0m] Started Daemon for generating UUIDs.
[  517.697345] cloud-init[2411]: ERROR: EOF occurred in violation of protocol (_ssl.c:997)
[  517.701094] cloud-init[2411]: Certificate verification failed. This typically happens when using Azure CLI behind a proxy that intercepts traffic with a self-signed certificate. Please add this certificate to the trusted CA bundle. More info: https://docs.microsoft.com/cli/azure/use-cli-effectively#work-behind-a-proxy.
[  517.949307] cloud-init[2411]: Checking for ./nexus_repos_config directory...
[  517.952699] cloud-init[2411]: Found config file: /tmp/nexus_repos_config/almalinux_proxy_conf.json. Sending to Nexus...
[  517.974724] cloud-init[2411]: Response received from Nexus: 000
...
> [  822.116884] cloud-init[2411]: ERROR - Timeout while trying to configure almalinux
[  822.121311] cloud-init[2411]: Cloud-init v. 23.1.2-0ubuntu0~18.04.1 running 'modules:final' at Tue, 16 May 2023 13:06:12 +0000. Up 71.44 seconds.
[  822.121394] cloud-init[2411]: 2023-05-16 13:18:43,678 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
[  822.129298] cloud-init[2411]: 2023-05-16 13:18:43,685 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
ci-info: no authorized SSH keys fingerprints found for user adminuser.

**Steps to reproduce**

1. Deploy a Nexus Sonatype shared service.

**Comment by craddm** [comment]
> @craddm maybe you can retry this?

I tried redeploying it, also logged in to the VM and ran cloud-init manually - no improvement.

> Should see the KeyVault extension...

Nothing there!

(I actually misspoke, it's not a totally new deployment exactly - I recently updated it from v0.9.0 - not sure if that has any bearing on the issue)

**Comment by marrobi** [comment]
@craddm can you follow the steps here:

https://microsoft.github.io/AzureTRE/unreleased/troubleshooting-faq/cloud-init/

Get the cloud init logs, and try rerunning cloud init.

Also can you confirm what version of the nexus bundle you are using? It's in the porter.yaml file, or TRE portal.

Finally, can you get the KeyVault extension logs off the VM:

`cd /var/log/azure/Microsoft.Azure.KeyVault.KeyVaultForLinux/`

Then get the contents of the akvvm_service_**.log files.

Thanks for your help.

**Comment by craddm** [comment]
> @craddm can you follow the steps here:
> 
> https://microsoft.github.io/AzureTRE/unreleased/troubleshooting-faq/cloud-init/
> 
> Get the cloud init logs, and try rerunning cloud init.
> 
> Also can you confirm what version of the nexus bundle you are using? It's in the porter.yaml file, or TRE portal.
> 
> Finally, can you get the KeyVault extension logs off the VM:
> 
> `cd /var/log/azure/Microsoft.Azure.KeyVault.KeyVaultForLinux/`
> 
> Then get the contents of the akvvm_service_**.log files.
> 
> Thanks for your help.

Ok, scratch all that - when I did the update, I didn't update the Nexus bundle. It was still on 2.3.0. Updated it to 2.5.0 and now everything is fine. Thanks for the help!
