### ISSUE TITLE
Cannot connect to Guacamole share service or an user resource (linux and windows vms)

### ISSUE THREAD

**Issue by slawpast** [microsoft/AzureTRE#3511]
As a workspace admin, I tried to open windows vm, It asks for a guacamole user name and a password.
The issue started, after upgrading to the latest version.
1. Run make tre-destroy
2. Add following environment variables: LOCATION, CORE_ADDRESS_SPACE (as default is different no), TRE_ADDRESS_SPACE, ENABLE_SWAGGER
3. Run github actions 
4. Create certs, nexus and admin shared services (I had to use different certification name here - nexus-certs, as it was failing using nexus-ssl, and I was not able to purge it)
5. Create guacamole workspace service.
6. Create windows vm.
7. connect to windows vm - asking for guacamole username and password.
8. Go back to share services, and connect to guacamole - asking for an username and password.

![image](https://github.com/microsoft/AzureTRE/assets/107872721/a93dbdbe-e290-4255-831b-073146d8050c)

If I go to Azure Portal and login to the windows vm using bastion and credentials from a key vault - login is successful

EDIT:
The issue seems to be related to the user modified workspace service, with the following steps:
1. copy the whole folder guacamole folder from AzureTRE to our repo.
2. rename it to guacamole-firewall-opened.
3. modify porter.yaml file (line3: name, line 4: version 0.9.1)
<img width="828" alt="porter" src="https://github.com/microsoft/AzureTRE/assets/107872721/dfa75a95-4eed-4796-abd7-990134448e9d">

4. modify template_schema.json:
 - line 5: title
 - and line 6: description
 - add rule collections (from line 111) to enable extra firewall rules)
 
<img width="828" alt="template" src="https://github.com/microsoft/AzureTRE/assets/107872721/ec6f4d5f-8922-4f0e-94e3-739921c1703c">

6. modify parameters.json (line 5: name to match porter.yaml).
<img width="828" alt="parameters" src="https://github.com/microsoft/AzureTRE/assets/107872721/8fce8127-e103-49d3-898b-0ee81bf02cbf">

7. modify deploy_tre_reusable to deploy new `guacamole-firewall-opened` workspace service. (sections 
    - publish_bundles, 
    - register_bundles,  
    - register_user_reosurces_bundles
    - 
<img width="954" alt="TRE1" src="https://github.com/microsoft/AzureTRE/assets/107872721/1f4b44c2-bcec-4f1c-bc42-f84b1506563c">

<img width="954" alt="TRE2" src="https://github.com/microsoft/AzureTRE/assets/107872721/77431966-d458-44a2-8bca-a7497629c273">
<img width="954" alt="tre3" src="https://github.com/microsoft/AzureTRE/assets/107872721/19a95d87-7982-48ec-b57a-dd60ca2b7371">

**Comment by marrobi** [comment]
That looks like an OpenID Connect issue. Can you do a full diff of your workspace services vs https://github.com/microsoft/AzureTRE/tree/main/templates/workspace_services/guacamole

@LizaShak @tamirkamara can you think of anything in the Gov cloud work that might have affected this?

**Comment by slawpast** [comment]
Thanks, actually I have re-run the actions (as they are) removed old and created new base workspace, problem disappeared. It can be closed now.
