### ISSUE TITLE
Databricks workspace service fails to deploy with DNS error

### ISSUE THREAD

**Issue by SvenAelterman** [microsoft/AzureTRE#3515]
Remember to label the issue with the appropriate area, and also assign it to yourself if you plan to work on the issue in the near future.

**Describe the bug**

Unable to deploy an instance of the default `databricks` workspace service. The error messages in the Operations logs are verbose but this is the first message:

`looking up A records for "": lookup : no such host`

**Steps to reproduce**

1. Deploy TRE 0.11
1. Deploy a new base workspace
1. Register default databricks workspace service bundle
1. Attempt to deploy the databricks service to the workspace.

**Comment by marrobi** [comment]
Have you deployed the Databricks authentication shared service? 

Is listed as prerequisite here - https://microsoft.github.io/AzureTRE/v0.11.0/tre-templates/workspace-services/databricks/

Not sure if that's the cause, but is needed.

**Comment by SvenAelterman** [comment]
@marrobi I didn't deploy the Databricks auth service. I deployed it now, have an instance of the shared service running. I redeployed the workspace service, but creation in a workspace is still failing with the same DNS error message.

**Comment by marrobi** [comment]
Can you share the full logs. Email or teams is fine if don't want to share here.

Thanks.

**Comment by marrobi** [comment]
@SvenAelterman created a PR here - https://github.com/microsoft/AzureTRE/issues/3515

Are you able to test this change, as I don't have an East US deployment at present.

**Comment by SvenAelterman** [comment]
@marrobi  Will try ASAP. Thanks.

**Comment by SvenAelterman** [comment]
@marrobi Should the version number of the Databricks template not be increased?

**Comment by marrobi** [comment]
good catch, feel free to add it to the PR review :)

**Comment by marrobi** [comment]
@SvenAelterman fixed.
