### ISSUE TITLE
Github Actions - running action does not uninstall custom user resources.

### ISSUE THREAD

**Issue by slawpast** [microsoft/AzureTRE#3516]
As a TRE developer I deployed custom user resource (to have GPU enabled machine), and a custom shared service (to have Guacamole service with some firewall rules added). Later on decided to remove them, however they are still available and deployable in a TRE workspace.

**Describe the bug**

**Steps to reproduce**

1. Copy the guacamole folder from the AzureTRE repo and paste into our cloned repo.
2. Update name, version, and firewall settings.
3. Copy the windows vm and update the version, name, and images settings.
4. modify deploy_tre_reusable in below sections:
   - publish_bundles,
   - register_bundles,
   - register_user_reosurces_bundles
5. Run Deploy Azure TRE action.
5. New resources are in place:
![image](https://github.com/microsoft/AzureTRE/assets/107872721/e8b46d32-9952-40ec-bfbe-d709776deffc)

6. Remove custom copied folders.
7. Remove lines from deploy_tre_reusable, reversing to the original one.
8. Run Deploy Azure TRE action.
9.  The resources are still in place:
![image](https://github.com/microsoft/AzureTRE/assets/107872721/2da2925d-1bf6-43ad-9f28-541a88d5dfd7)

10. Running bundle-uninstall returned an error, however I do not a copy of it now.

**Comment by marrobi** [comment]
Once registered templates are registered, not running register command will not remove them.

There isn't currently an API to remove templates, but will create a feature request to address this.

If you do need to remove templates they can be removes in cosmos, but ensure they aren't in use elsewhere - https://microsoft.github.io/AzureTRE/v0.11.0/troubleshooting-faq/manually-editing-resources/

**Comment by slawpast** [comment]
> Once registered templates are registered, not running register command will not remove them.
> 
> There isn't currently an API to remove templates, but will create a feature request to address this. #3517
> 
> If you do need to remove templates they can be removes in cosmos, but ensure they aren't in use elsewhere - https://microsoft.github.io/AzureTRE/v0.11.0/troubleshooting-faq/manually-editing-resources/

Thank you for your advice. I have found editing cosmos items quick and easy this problem solution.
