### ISSUE TITLE
Azure Database for MySQL single server is on the retirement path

### ISSUE THREAD

**Issue by ciprianmaf** [microsoft/AzureTRE#3540]
Hello,

as the "Azure Database for MySQL single server" is on the [retirement path](https://go.microsoft.com/fwlink/?linkid=2216041), please update to "Azure Database for MySQL - Flexible Server".

Thank you!

Regards,

Ciprian Maftei
NTT DATA

**Comment by marrobi** [comment]
@ciprianmaf thanks, if this is an issue for yourselves, maybe you could look at doing a PR to update the terraform?

**Comment by migldasilva** [comment]
@marrobi I have advanced in this issue. So far I was able to move to MySQL Flexible Server for Gitea Shared service and Gitea Workspace service. Flexible Server requires a dedicated VNet, so I had to change TRE's Core for Gitea Shared service, and the workspace definition, for Gitea Workspace service.

I would be able to create a PR in a couple of days.

**Comment by tamirkamara** [comment]
@migldasilva thank you for having a look at this.
Changes in the core network can be disruptive for existing deployments and need to be done carefully.
Azure MySQL flexible server is about to receive support for private endpoints which will make it far easier to be integrated into an exiting framework. Let us give Microsoft the summer to release it and then revisit (single server isn't going away anytime soon). wdyt?

**Comment by migldasilva** [comment]
@tamirkamara Perfect. Let's wait. On the other hand, I've been testing the changes in core, so that everything keeps working. The main idea is to use one of the free subnets declared in [core/terraform/network/locals.tf](../blob/main/core/terraform/network/locals.tf).

**Comment by tamirkamara** [comment]
@migldasilva apparently it's available already: https://learn.microsoft.com/en-us/azure/mysql/flexible-server/concepts-networking-private-link

**Comment by SvenAelterman** [comment]
This has some new urgency, as in a few days, the creation of new MySQL DB Single Servers will be [blocked](https://learn.microsoft.com/en-us/azure/mysql/single-server/whats-happening-to-mysql-single-server#:~:text=Azure%20CLI%20beginning%20March%2019%2C%202024).

@tamirkamara, @marrobi

**Comment by marrobi** [comment]
We discussed this and plan of action for anything using MySQL single server should be:

1. Update the bundles with new major version numbers so new deployments can succeed
2. Document manual migration approach and if deemed appropriate automate. 
3. Move on to Postgres for MLflow (or retire MLflow entirely as used in Azure ML?)

**Comment by nasaldrops** [comment]
Any feedback on the Compute size name? Looking at General Purpose.

azurerm_mysql_server has sku_name  "GP_Gen5_2"

azurerm_mysql_flexible_server dopesn't have that option, so these are the GP ones available (see image)

![image](https://github.com/microsoft/AzureTRE/assets/1178018/ca0e6a85-0981-48a2-b35b-2caceb850cfd)

**Comment by marrobi** [comment]
> Any feedback on the Compute size name? Looking at General Purpose.
> 
> `azurerm_mysql_server` has sku_name "GP_Gen5_2"
> 
> `azurerm_mysql_flexible_server` doesn't have that option, so these are the GP ones available (see image)
> 
> ![image](https://private-user-images.githubusercontent.com/1178018/312515183-ca0e6a85-0981-48a2-b35b-2caceb850cfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTgyMzIsIm5iZiI6MTcxMDQxNzkzMiwicGF0aCI6Ii8xMTc4MDE4LzMxMjUxNTE4My1jYTBlNmE4NS0wOTgxLTQ4YTItYjM1Yi0yY2FjZWI4NTBjZmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMTIwNTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDQ0N2ExMDljODdkYjQxNWI2OWQ3MDRlZjg2ZjRlNTU3YjcxYWU4MDAxNjlhMjYyYWVkYTc3ZTkyNDE2ZDM0MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cPU9c6Uxa3q4w-HyCiS3ILq_Sfkl3ub6RokGSRUUUbM)

Ideally they would be options in the bundle, defaulting to the lowest burstable spec maybe? The CPU usage for TRE use cases is typically very low.
