### ISSUE TITLE
Databricks workspace service UDR file missing entries for some regions.

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#3566]
The file 

https://github.com/microsoft/AzureTRE/blob/main/templates/workspace_services/databricks/terraform/databricks-udr.json

Is missing entries for some regions, they need copying over from:

https://learn.microsoft.com/en-gb/azure/databricks/resources/supported-regions

**Comment by lordlinus** [comment]
updated eastus2 and created PR - https://github.com/microsoft/AzureTRE/pull/3568/commits/9efce6d7398b116e0aa7f967d1d334c8dae4a753

**Comment by nayeem01** [comment]
@marrobi is it still open?

**Comment by marrobi** [comment]
Yes. Please feel free to add them.
