### ISSUE TITLE
devcontainer deployment issue

### ISSUE THREAD

**Issue by danwhite-ck** [microsoft/AzureTRE#3570]
Devcontainer will not startup 

Dockerfile-with-features:111
--------------------
 109 |     # Install tre-cli
 110 |     WORKDIR /"${AZURETRE_HOME}"/cli
 111 | >>> RUN make install-cli && echo -e "\n# Set up tre completion\nsource <(_TRE_COMPLETE=bash_source tre)" >> ~/.bashrc
 112 |     
 113 |     # Build x86-64 docker images by default
--------------------
ERROR: failed to solve: process "/bin/bash -o pipefail -c make install-cli && echo -e \"\\n# Set up tre completion\\nsource <(_TRE_COMPLETE=bash_source tre)\" >> ~/.bashrc" did not complete successfully: exit code: 2

**Comment by marrobi** [comment]
Hi @danwhite-ck . Are there any other logs? The above error doesn't provide enough information. Thanks.

**Comment by marrobi** [comment]
Is it the same as this issue? I will look to do a PR to resolve.

https://github.com/microsoft/AzureTRE-Deployment/issues/75

**Comment by danwhite-ck** [comment]
Yes - Thanks - The solution in there fixed my issue by editing the .sh file.
