### ISSUE TITLE
Error on opening repo in a codespace or locally in devcontainer

### ISSUE THREAD

**Issue by slawpast** [microsoft/AzureTRE#3579]
The error happens on building devcontainer, related to run `make  install-cli `
Please note, that we did not make any updates to repo, just started with a new docker installation and previously was running fine

`#28 8.066   self.initialize_options()
microsoft/AzureTRE#28 8.069 error: cryptography 41.0.1 is installed but cryptography<41,>=0.6 is required by {'msal'}
microsoft/AzureTRE#28 8.099 	
2023-06-02 11:44:19.259Z: microsoft/AzureTRE#28 ERROR: executor failed running [/bin/bash -o pipefail -c make install-cli && echo -e "\n# Set up tre completion\nsource <(_TRE_COMPLETE=bash_source tre)" >> ~/.bashrc]: exit code: 2`

I have also attached the full log:

[creation.log](https://github.com/microsoft/AzureTRE/files/11635306/creation.log)

Steps to reproduce:

1. Clone repo https://github.com/microsoft/AzureTRE-Deployment in 
2. open in visual studio code
3. Reopen in container - fails
Or:
2. Open in codespace - the same error.

**Comment by marrobi** [comment]
Transferring as fix needs to happen in Azure TRE repo.
