### ISSUE TITLE
Explore: VM sign-in options

### ISSUE THREAD

**Issue by Lybecker** [microsoft/AzureTRE#36]
Can we use AAD identities directly to sign-in to a VM?

Benefits

- Less complexity compared to the current Guacamole implementation, where the Researcher credentials are mapped to VM credentials stored in Key Vault.
- The Researcher will be accessing other resources like storage as their own identity making auditing and permission management simpler.

Tasks:

- [x] [Log in to a Linux virtual machine in Azure using Azure Active Directory authentication](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/login-using-aad)
- [x] [Sign in to Windows virtual machine in Azure using Azure Active Directory authentication](https://docs.microsoft.com/en-us/azure/active-directory/devices/howto-vm-sign-in-azure-ad-windows)

**Comment by jjcollinge** [comment]
This looks like a neat alternative if you're ok to use preview and can live without NSGs.

**Comment by marrobi** [comment]
Closing as sign in options will be defined on a per customer basis. Initially implementation will use mapped credentials as this is the default catch all for Windows and Linux when users are not members of the local AAD.
