### ISSUE TITLE
Airlock Import Workspace deployment fails with network/private endpoint issues

### ISSUE THREAD

**Issue by SvenAelterman** [microsoft/AzureTRE#3616]
**Describe the bug**

This appears to be the same issue that exists with the base workspace (PR #3581).

**Steps to reproduce**

It does not appear possible to consistently reproduce this issue.

**Comment by marrobi** [comment]
Closing as required fix are in base workspace and need to be included in airlock as covered in https://github.com/microsoft/AzureTRE/issues/3617
