### ISSUE TITLE
"Airlock Import Review" and "unrestricted" workspace templates have hardcoded references to TRE versions (0.9.0 and 0.8.0)

### ISSUE THREAD

**Issue by SvenAelterman** [microsoft/AzureTRE#3617]
**Describe the bug**

In line 12 of the Dockerfile.tmpl for the airlock-import-review workspace bundle, the Azure TRE version is hardcoded to 0.9.0.

See https://github.com/microsoft/AzureTRE/blob/8d31b90b1504132a276385da470b204f567a855a/templates/workspaces/airlock-import-review/Dockerfile.tmpl#L12C15-L12C15 

It seems this would be problematic because changes to the base workspace bundle won't make it to the airlock import review workspace. This is especially relevant with PR #3581

**Comment by SvenAelterman** [comment]
I see another challenge with the particular approach of downloading the base workspace files from GitHub. It means that any bug fixes to the base template won't apply to the airlock import review template until a new tag is created.

Would it not be simpler to copy the base workspace files from the local machine?

**Comment by SvenAelterman** [comment]
I just realized that the unrestricted template has a hardcoded reference also.

**Comment by marrobi** [comment]
For now lets update the references, but should look at copying files into the directories and porter dependencies which have progressed since we first did this work.

- [ ] Investigate alternative ways to handle dependency on base workspace in the airlock and unrestricted workspaces.
