### ISSUE TITLE
When Guacamole VM fails to build correctly the first time, the Connect button or command doesn't appear after a successful update

### ISSUE THREAD

**Issue by SvenAelterman** [microsoft/AzureTRE#3618]
**Describe the bug**

I attempted to create a VM with a custom template. The VM creation failed because a required subscription-level resource provider feature wasn't registered yet.

I registered the feature (EncryptionAtHost) and updated the VM. The VM update was reported as successful, but the connect button is not showing on the card in the Guacamole service. Neither is the Connect command in the VM detail page.

**Steps to reproduce**

1. Customize a VM template to enable encryption at host. Ensure the feature is not registered at the subscription level. (Or make any other modification to the VM template that is valid but will cause a deployment failure due to some environment factor, like policy.)
1. Deploy a VM with the custom template.
1. The VM creation will fail, but the VM will have a card.
1. Fix the issue that caused the failure.
1. Update the VM.
1. VM update is successful, but the VM card shows like this:  
  ![image](https://github.com/microsoft/AzureTRE/assets/17446043/ae83b454-997e-45b6-a012-8cd63e05b5c7)

**Comment by marrobi** [comment]
Can you check if the VM has a `connection_uri` and `is_exposed_externally` set in properties?

These are outputs from the deployment and if they don't exist the card will not show.

**Comment by marrobi** [comment]
I mean do the outputs exist on the details tab? They are what makes the button appear.

I expect the initial failure meant the output wasn't created.

**Comment by SvenAelterman** [comment]
I misunderstood. I already deleted that VM, so I can't check that anymore (unless the document still exists in Cosmos?)

**Comment by marrobi** [comment]
Closing this, if it reoccurs we can reopen.
