### ISSUE TITLE
Update "Azure AD" references to "Entra ID"

### ISSUE THREAD

**Issue by SvenAelterman** [microsoft/AzureTRE#3650]
## Description

As a TRE Administrator
I want to see documentation that reflects the current name of the service
So that the project is up-to-date

## Acceptance criteria

- [ ] Documentation all updated
- [ ] Microsoft Entra Workforce tenant used rather than Azure AD Tenant
- [ ] Code files containing comments updated

**Comment by marrobi** [comment]
Example:
![image](https://github.com/microsoft/AzureTRE/assets/17089773/f6750a53-b96d-4a54-b2c0-daa13098f26b)

**Comment by wojciechcloudkubed** [comment]
What would be a proper naming convention now? From [official source ](https://www.microsoft.com/en-us/security/business/identity-access/microsoft-entra-id) it says _Azure Active Directory is now Microsoft Entra ID_ so after the update would it be

- "to be enabled in the _Microsoft Entra Workforce_ application"

or 

- "to be enabled in the _Microsoft Entra Workforce **ID**_ application"

**Comment by marrobi** [comment]
I believe so. @SvenAelterman thoughts?
