### ISSUE TITLE
Changing docker file permissions breaks docker outside the container

### ISSUE THREAD

**Issue by SJaffa** [microsoft/AzureTRE#3673]
https://github.com/microsoft/AzureTRE/blob/c3f144f9593230cfb3a43a2b789dff800f5d25bc/devops/scripts/set_docker_sock_permission.sh#L7

This line changes the group of the `docker.sock` file _outside of the container_ (from `docker` to `citrixlog`). This means that I can't run docker outside the container anymore as my normal user isn't part of that group, so opening any new devcontainers or running `docker ps` fails with a permissions error (it works if I use `sudo`).

I think the reason it changes the group from `docker` to `citrixlog` is because the group number for docker inside the container is 1001 and that's the group number for `citrixlog` outside the container.

Is there a way to stop this acting on my normal system file outside the container and only affect the `/var/run/docker.sock` file _inside_ the container?

I'm using Ubuntu 20.04 and Docker version 24.0.5, build ced0996

**Comment by marrobi** [comment]
@SJaffa hmm, the file is mounted in, as docker is running on your host machine so can't be edited just in the container.

What happens if you comment out the line specified above in the script? I've not hit the issue personally and it was added a fair while ago and the comment says it's specific to mac OS and codespaces.

This feels like more of a generic "How do I run docker inside a dev container without having to use sudo on mac OS and codespaces" question. Rather than TRE specific.

@stuartleeks shot in the dark, any ideas? Thanks.

**Comment by SJaffa** [comment]
If I comment that line out (or just stop it running that script entirely when it does `make all`) then nothing else seems to break but I am having some other Docker issues so not sure if that is related or not at the moment. When I fix my other issue I'll check if this was related or not.

**Comment by marrobi** [comment]
Actually, I've just replicated it on my machine, WSL:

```
➜  ~ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

I only upgraded last week, not noticed it before. I can confirm docker group ID in WSL is different to that in the container.

**Comment by marrobi** [comment]
I can confirm if I stop that script running I see no adverse affects, and docker permissions do not get broken.

**Comment by SJaffa** [comment]
Yep just solved my other devcontainer/docker issue and it was unrelated, so I think removing this script is fine for me, but is there a way to stop this breaking things for anyone else on Linux? Or a different way to fix the original macOS/codespaces problem?

**Comment by marrobi** [comment]
Have verified that the script is needed on codespaces. 

The only solution I can think of at present is to parse something from say `docker info` to only run the command in certain scenarios.

**Comment by marrobi** [comment]
In code spaces, we can check for:

`CODESPACES=true`

Actually, we could just run `docker ps` and check the exit code.

```
if ! docker ps > /dev/null 2>&1; then
  echo "docker ps failed, setting docker.sock permissions"
  sudo chgrp docker /var/run/docker.sock
  sudo chmod g+rw /var/run/docker.sock
fi
```
