### ISSUE TITLE
Nexus shared service Update dialog doesn't populate SSL cert name

### ISSUE THREAD

**Issue by SvenAelterman** [microsoft/AzureTRE#3697]
**Describe the bug**
When trying to update the Nexus shared service, the cert name text box is blank and disabled.

Clicking Submit results in an error message.

**Steps to reproduce**

1. Deploy Nexus.
1. Click **Update**.
1. Click **Submit**.

**Comment by marrobi** [comment]
@SvenAelterman found an issue - https://github.com/microsoft/AzureTRE/issues/3716

**Comment by marrobi** [comment]
Fixed in https://github.com/microsoft/AzureTRE/pull/3717

**Comment by marrobi** [comment]
Closing this as duplicate of #3717
