### ISSUE TITLE
Unrestricted workspace fails to deploy

### ISSUE THREAD

**Issue by basitrehman531997** [microsoft/AzureTRE#3700]
When I create a workspace or workspace service, it shows a deployment failure, and I also get the error message "Error retrieving workspace: Unable to decode or validate token."

401 Error: Unable to decode or validate token at

Operation Failed
upgrade for test2 completed with status updating_failed

but this issue create that time when a run the following command for unrestricted workspace 
make workspace_bundle BUNDLE=unrestricted 

also create more workspace application which delete later when the above error get

**Steps to reproduce**

1.crate workspace form tre portal 
2.enable air lock 
3.create AAD group
4.assign all permission and role us e this link https://microsoft.github.io/AzureTRE/v0.14.1/tre-admins/identities/application_admin/

**Comment by marrobi** [comment]
@basitrehman531997 can you confirm the value you have for `auto_workspace_app_registration` in your `config.yaml`?

Thanks.

**Comment by brehmanepicsoft** [comment]
yes auto_workspace_app_registration: true and  auto_workspace_group_creation: true both are true

**Comment by marrobi** [comment]
Can you use the swagger API - `/api/docs` to get the operation logs for the workspace? It should provide more details.

**Comment by brehmanepicsoft** [comment]
i have no experience about tre can you explain me how can we access operation logs from api docs
thanks

**Comment by brehmanepicsoft** [comment]
oh iuse to access api_docs 
use the following url https://<azure_tre_fqdn>/api/workspaces/<workspace_id>/docs
but it gets the following message 
Unable to process request

**Comment by marrobi** [comment]
That's the workspace API, rather than the core API.

This could be the same issue as #3701 - the unrestricted and airlock review templates need updating.

**Comment by brehmanepicsoft** [comment]
i changes v of tre in unrestricted and airlock review run make all .but got same error like that 
<img width="679" alt="operation failed" src="https://github.com/microsoft/AzureTRE/assets/142625590/d363746f-2ec4-444c-b31e-266c5f4a7367">

**Comment by marrobi** [comment]
> <img alt="api" width="839" src="https://user-images.githubusercontent.com/142625590/265738618-d5a36335-5575-42bd-8375-42b9af9d0947.png">
> "I have four workspaces. Is it necessary for each workspace to have its own dedicated workspace?" @marrobi

Yes, each workspace requires its own app registration as many workspace services rely on a unique client/application ID for managing authentication, and roles need to eb different for each workspace.

Re the deployment issues, can you get the operation logs for the workspaces?

I will try to reproduce this today.

**Comment by marrobi** [comment]
Working on this here - https://github.com/microsoft/AzureTRE/issues/3702

**Comment by marrobi** [comment]
I've replicated this issue and it is fixed (and added into the tests for future) here - https://github.com/microsoft/AzureTRE/pull/3704

Issue is a setting has been depreciated on Azure and the templates needed updating.
