### ISSUE TITLE
should be enable internet access in base workspace 

### ISSUE THREAD

**Issue by brehmanepicsoft** [microsoft/AzureTRE#3707]
1.in base workspace 
2.we have guacamole service on this service we have 3 vm windows 10, window server,linux vm but all vms can not access internet service 
3.is any option which allow internet on these vm 
  

**Azure TRE release version (e.g. v0.14.0 or main):**

**Deployed Azure TRE components - click the (i) in the UI:**

**Comment by marrobi** [comment]
The `unrestricted` workspace shows how this can be done.
