### ISSUE TITLE
Cannot build bundles after `make setup-local-debugging`

### ISSUE THREAD

**Issue by basitrehman531997** [microsoft/AzureTRE#3711]
when i run make all 
tre produce this kind of error 

note   :  this type of error produce after run command >>> make setup-local-debugging
  

Runtime image build section isn't specified. Exiting...
could not render config file because ${secret.porter-db-connection-string} could not be resolved: rpc error: code = Unknown desc = could not get secret porter-db-connection-string: keyvault.BaseClient#GetSecret: Failure sending request: StatusCode=0 -- Original Error: Get "https://.vault.azure.net/secrets/porter-db-connection-string/?api-version=7.0": dial tcp: lookup .vault.azure.net: no such host
make[1]: *** [Makefile:189: bundle-build] Error 1
make[1]: Leaving directory '/workspaces/AzureTRE'
make: *** [Makefile:305: firewall-install] Error 2

**Azure TRE release version (e.g. v0.14.0 or main):**

**Deployed Azure TRE components - click the (i) in the UI:**

**Comment by marrobi** [comment]
This looks like a transient connectivity issue. 

`dial tcp: lookup .vault.azure.net: no such host`

Did it succeed after a second run?

**Comment by marrobi** [comment]
I think I know the issue, `make setup-local-debugging` creates this file - `/home/vscode/.porter/config.yaml`, to allow the resoure processor to be debugged. 

This affects future commands that interact with porter but aren't configured with the RP environment variables.

If run `rm ~/.porter/config.yaml` the issue goes away.

One to look at when have time.
