### ISSUE TITLE
Unable to deploy OHDSI Atlas Workspace Service

### ISSUE THREAD

**Issue by dusan-ilic-mhra** [microsoft/AzureTRE#3712]
**Describe the bug**

We successfully deployed the MSL workspace (copy of the base workspace) without any error.
When the MSL workspace is deployed we can see that subnet WebAppsSubnet is created under the workspace VNET.
After, that we initiated the deployment of OHDSI Atlas Workspace Service.
We tried many times in different newly created workspaces but we are getting the following terraform error:

"An operation on the Virtual Network has failed. Details: {\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"ReferencedResourceNotProvisioned\\\",\\r\\n    \\\"message\\\": \\\"Cannot proceed with operation because resource /subscriptions/*******/resourceGroups/rg-cprdtest-ws-****/providers/Microsoft.Network/virtualNetworks/vnet-cprdtest-ws-****/subnets/WebAppsSubnet used by resource WebAppsSubnet is not in Succeeded state. Resource is in Updating state and the last operation that updated/is updating the resource is PutSubnetOperation.

**Steps to reproduce**

1. Deploy MSL workspace - successful
2. Deploy OHDSI Atlas Workspace Service - not successful

**Azure TRE release version (e.g. v0.14.0 or main):**

v.0.9.0

Yesterday, this worked without any issues, but today we are not able to deploy the OHDSI Atlas Workspace Service.
We didn't have any related changes.

Could you please help us with this?

BR, 
Dusan

**Comment by marrobi** [comment]
Looks to me like a dependency issue. I would make any operations that impact that subnet - such as private endpoint creation occur in a serial fashion.

@tamirkamara thoughts?

**Comment by dusan-ilic-mhra** [comment]
Hi @marrobi, @tamirkamara,

We raised an Azure support request yesterday and we got this:
![image](https://github.com/microsoft/AzureTRE/assets/104429461/2c9281e1-5404-406f-95ca-ac7c58b5dee6)

After that, we tried last evening and this morning and Atlas WS Service has been deployed without issues. 

So, this was probably some Azure backbone-related issues.

I think you can close an issue.
