### ISSUE TITLE
Unable to create import/export Airlock requests

### ISSUE THREAD

**Issue by dusan-ilic-mhra** [microsoft/AzureTRE#3713]
**Describe the bug**
We are not able to create import/export Airlock requests, and we are getting Error: Internal Server Error.
You can see the attached full log from api related to this action.
[api-app-log.txt](https://github.com/microsoft/AzureTRE/files/12661616/api-app-log.txt)

**Steps to reproduce**

1. Authorize to Swagger as a Researcher role user
2. Try to create import or export airlock request

**Azure TRE release version (e.g. v0.14.0 or main):**
v0.9.0

**Comment by dusan-ilic-mhra** [comment]
@marrobi, @tamirkamara,

Just to put a bit more clarification:

- The user has been assigned as a Workspace Researcher app role
- The user has an email address in AAD
- Email Microsoft Graph API permission has been granted on the App Registration for the workspace

And, we still have the same problem (you can see the log).

**Comment by marrobi** [comment]
This is the code that gets the users:

https://github.com/microsoft/AzureTRE/blob/2bd71a0b4b30bae3a5030276fe417ecd46713e19/api_app/services/aad_authentication.py#L243-L249

So as you suggest, leads to think is an issue with missing roles or emails.

It might be worth adding some debug outputs into the Python to track what is happening in this scenario.

**Comment by dusan-ilic-mhra** [comment]
@marrobi 

Could you please help us with how to do that and what is needed in order to have DEBUG logs?

**Comment by dusan-ilic-mhra** [comment]
@marrobi 
You can close this issue as we reloved it by creating a new App Registration.
