### ISSUE TITLE
deployment_failed custom windows vm from image 

### ISSUE THREAD

**Issue by basitrehman531997** [microsoft/AzureTRE#3720]
deployment_failed vm:

<img width="239" alt="deployment_failed" src="https://github.com/microsoft/AzureTRE/assets/76579245/4d56f301-b0ff-4bce-84bd-a002fb33fae5">

operations :

 Error message: [31m╷[0m[0m [31m│[0m [0m[1m[31mError: [0m[0m[1mCode="VMExtensionProvisioningError" Message="VM has reported a failure when processing extension 'windowsvmaf02-vmextension' (publisher 'Microsoft.Compute' and type 'CustomScriptExtension'). Error message: \"Command execution finished, but failed because it returned a non-zero exit code of: '1'. The command had an error output of: 'conda : The term 'conda' is not recognized as the name of a cmdlet, function, script file, or operable program. Check \r\nthe spelling of the name, or if a path was included, verify that the path is correct and try again.\r\nAt C:\\azuredata\\configure.ps1:32 ch...' For more information, check the instance view by executing Get-AzVmssVm or Get-AzVm (https://aka.ms/GetAzVm). These commands can be executed using CloudShell (https://aka.ms/CloudShell)\". More information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot.
 
<img width="932" alt="operations" src="https://github.com/microsoft/AzureTRE/assets/76579245/bcf09cc4-9f1c-4749-ae53-2351bc6cd713">

steps:
create image:
1:create vm in azure portal login successfully using rdp.
2:create image using capture method .place image in compute gallery which image name is :   windows10image
3:create vm from image which is successfully login using rdp
create custom template:
1.copy  guacamole-azure-windpwsvm rename name to guacamole-azure-windpwsvm-gpu

<img width="303" alt="gpupic" src="https://github.com/microsoft/AzureTRE/assets/76579245/c1c01bc4-62f9-4098-a4b9-2f336807da74">

2.make changes in  guacamole-azure-windpwsvm-gpu porter.ymal

<img width="660" alt="portlyml1" src="https://github.com/microsoft/AzureTRE/assets/76579245/41ad2137-503a-41e0-9fa6-b05420d9adbc">

define default value compute gallery 

<img width="871" alt="mainportl" src="https://github.com/microsoft/AzureTRE/assets/76579245/41445b32-cfc7-4bb2-823f-0316867ef823">

3.make chnages in  template_schema.json

<img width="932" alt="gpujson" src="https://github.com/microsoft/AzureTRE/assets/76579245/ca68fa4c-d6ec-4a35-b76c-190bb06e3c21">

4.make chnages in .github/workflows/deploy_tre_resuable.yml

<img width="969" alt="workflow2" src="https://github.com/microsoft/AzureTRE/assets/76579245/bfb2dc74-d9be-49b5-a2c9-c28667c14f08">

<img width="804" alt="workflow" src="https://github.com/microsoft/AzureTRE/assets/76579245/14aa0112-b650-49f2-8564-7f95be671655">

5.make chnages in config.yaml

<img width="966" alt="config2" src="https://github.com/microsoft/AzureTRE/assets/76579245/4ea47ca4-4c8a-4042-abf5-ce4afd825442">

**Azure TRE release version (e.g. v0.14.0 or main):**

**Deployed Azure TRE components - click the (i) in the UI:**

**Comment by marrobi** [comment]
@basitrehman531997  looks like your base VM image has not got conda installed.

You can see here:
https://github.com/microsoft/AzureTRE/blob/0f12981a51eadfd51ac14734e23da977ddf0f1ec/templates/workspace_services/guacamole/user_resources/guacamole-azure-windowsvm/porter.yaml#L24-L37

that we only configure conda on the DSVM as it has conda preinstalled. If you want to run the conda configuration you will need to have conda installed on your VM image.

I will close the case, but feel free to reopen if you do have conda installed on your VM image.
