### ISSUE TITLE
Workspace costs do not show in UI for a TRE User who is a workspace owner.

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#3721]
Log into the TRE with a user that isn't a TRE Admin, but is a Workspace Owner, they will not see the costs.

This is the TRE level token is being evaluated, not workspace level.

**Comment by marrobi** [comment]
Why does this:

https://github.com/microsoft/AzureTRE/blob/35a73a2f31cb7775faec8c551732291575bf34cb/ui/app/src/components/shared/SecuredByRole.tsx#L18

Only check one set of roles, not combined?

**Comment by jjgriff93** [comment]
Yeah this is problematic for cases where you want to check for roles in either context. A quick fix for the workspace costs is to add another SecuredByRole element for the non-workspace context with the same element in it. A better fix would be for the component to accept two properties:

```tsx
<SecuredByRole allowedAppRoles={['a', 'b']} allowedWorkspaceRoles={['a']} element={
   <div></div>
}/>
```

**Comment by marrobi** [comment]
The issue is on the root dashboard, the workspace context does not exist. Other than also pass the workspace ID and get the roles, any ideas?
