### ISSUE TITLE
airlock function runtime version & container creation fail

### ISSUE THREAD

**Issue by brehmanepicsoft** [microsoft/AzureTRE#3725]
when i create request for import request its show error that type:
""Error submitting airlock request
Unable to process request
500
""
runtime version show only --- in airlock function app
enable_airlock_malware_scanning is also set to false 

action :
after every day i delete airlock function because has runtime version error 
runtime version show only ---
when i delete and redeploy new function it show runtime version

but after redeployment of function app the request submitted but container creation fail  

tre version :v0.14.1

**Comment by marrobi** [comment]
Believe this is what see on this run here - https://github.com/microsoft/AzureTRE/actions/runs/6276011634/job/17045724446

@martinpeck @tamirkamara any pointers as to how can start tracking this down?

**Comment by marrobi** [comment]
I've run 50 requests through the airlock using a script without issue so @brehmanepicsoft we need to have additional logs from the API to understand why you get a 500 error.

Set debug to true as per https://microsoft.github.io/AzureTRE/v0.14.1/troubleshooting-faq/debug-api/

And when you have a failure check the logs as per - https://microsoft.github.io/AzureTRE/v0.14.1/troubleshooting-faq/app-insights-logs/

**Comment by marrobi** [comment]
Closing as had no response.
