### ISSUE TITLE
Review VMs not setup when reviewing airlock request

### ISSUE THREAD

**Issue by brehmanepicsoft** [microsoft/AzureTRE#3726]
when request come to me and i click on review button it show me vm are not set up 

also when i click on review request it show 
<img width="857" alt="airlock" src="https://github.com/microsoft/AzureTRE/assets/142625590/efae18da-1fff-4e58-9c7b-e1eee99da583">

not show review vm create button  
<img width="855" alt="airlock_2" src="https://github.com/microsoft/AzureTRE/assets/142625590/1356fc91-d69b-43ed-be62-3d03db96895c">

**Azure TRE release version v0.14.1

**Comment by marrobi** [comment]
As per the error you need to set up review VMs for the workspace as per https://microsoft.github.io/AzureTRE/v0.14.1/tre-admins/configure-airlock-review/#configuring-airlock-vm-for-research-workspace

Can you confirm you have done this? Thanks.

**Comment by brehmanepicsoft** [comment]
thanks  .but i get error about ReviewData folder show empty @marrobi

**Comment by marrobi** [comment]
Is that a separate issue/error to the one this issue is for? Have you got past the error above?

**Comment by brehmanepicsoft** [comment]
Do I need to create an Airlock Import Workspace for reviewing data if I only have one workspace, which is the base? Will deploying the Airlock Import Workspace resolve the issue?

**Comment by brehmanepicsoft** [comment]
yes i resolve the issue above .

**Comment by brehmanepicsoft** [comment]
when i resolve the review vm creation error i get anther error  when i access ReviewData it show empty folder

**Comment by marrobi** [comment]
Please check https://microsoft.github.io/AzureTRE/v0.15.2/troubleshooting-faq/airlock-troubleshooting/#files-do-not-appear-in-review-data-folder-on-the-vm and get back to us if this is not the issue.
