### ISSUE TITLE
fail deployment of airlock review workspace 

### ISSUE THREAD

**Issue by brehmanepicsoft** [microsoft/AzureTRE#3729]
i want to create two workspace one is base workspace and the other is airlock review import .nut the airlock review import give me error fail deployment .
i chnage ARG AZURE_TRE_VERSION="0.12.0" to 0.14.0 and make tre_deploy but same error get 
<img width="958" alt="airlock workspace" src="https://github.com/microsoft/AzureTRE/assets/142625590/d17ea0b8-15a6-4731-9b6a-3ceea13b1789">

<img width="833" alt="application api" src="https://github.com/microsoft/AzureTRE/assets/142625590/44319cb8-5210-4b9a-8a60-64518f07a9ff">

I use different workspace api for every workspace 

**Azure TRE release version (e.g. v0.14.1 or main):**

**Deployed Azure TRE components - click the (i) in the UI:**

**Comment by marrobi** [comment]
What version of the airlock template are you using? Have you published the latest bundles?

**Comment by marrobi** [comment]
Closing as no response, please reopen if still an issue.
