### ISSUE TITLE
why we need stop and start azure function app for review to request

### ISSUE THREAD

**Issue by brehmanepicsoft** [microsoft/AzureTRE#3730]
when i create airlock request it goes to fail .when i stop and start the azure function app it start work and my new request goes to review section .its not a good  sign for researcher .and also researcher have no access of portal . 

**Azure TRE release version (e.g. v0.14.1 or main):**

**Deployed Azure TRE components - click the (i) in the UI:**

**Comment by marrobi** [comment]
Hello,

You have created 5 issues around the airlock:

![image](https://github.com/microsoft/AzureTRE/assets/17089773/a24f073e-3b6f-4877-8f3b-b835a40a8e97)

None have any detailed logs which makes it very hard to troubleshoot. **Could I ask you to consolidate these to a single issue** and try and provide some logs from the API or Function app which are stored in log analytics as per the docs.

I will look to do set up some automated load tests for the airlock to see if I can replicate the issues you report.

Apologies if this isn't working as expected.
