### ISSUE TITLE
How we could restrict upload of some specific file extension types while using Airlock

### ISSUE THREAD

**Issue by dusan-ilic-mhra** [microsoft/AzureTRE#3736]
## Description

We would like to restrict the upload of some specific file extension types while using Airlock (e.g. .exe, .dll, .msi)

## Steps

1. Create an airlock import request 
2. Upload file .exe or .dll or .msi

**Comment by marrobi** [comment]
Hi @dusan-ilic-mhra , this seems like a feature request, is it something you are considering developing and contributing to the project? Either way, users can always rename file prior to and after import. Or even put them in a zip archive.

It might also be worth looking at the malware scanning.

**Comment by dusan-ilic-mhra** [comment]
Hi @marrobi, probably we will need to work on this. 
For the time being, you can close the issue and when we have some solution in place we will contribute to the project.

**Comment by marrobi** [comment]
Ok, I will close for now, as I don't see it as something that adds immediate value - as the user can just rename the files.
