### ISSUE TITLE
Guacamole Linux VM cloud-init config file contains hardcoded Ubuntu version

### ISSUE THREAD

**Issue by SvenAelterman** [microsoft/AzureTRE#3773]
**Describe the bug**

In apt_sources_config.yml, the entry for the Microsoft package manager contains a hardcoded Ubuntu version `18.04` but a `$RELEASE` placeholder. When combined and written to sources.list, this results in impossible combinations, such as `.../18.04/prod focal..` (where focal is the name of Ubuntu 20)

This means that a single bundle cannot be used for multiple Ubuntu releases, and certainly not for multiple Linux distributions.

**Steps to reproduce**

1. Update template_schema.json and porter.yaml for a recent Linux version.
1. Publish the bundle.
1. Attempt to deploy a Linux VM with the newer image.

Result: apt-get fails during cloud-init, leaving the VM inaccessible from Guacamole.

**Azure TRE release version (e.g. v0.14.0 or main):** v0.15.2

**Comment by tim-allen-ck** [comment]
Looking at fixing this with #3893
