### ISSUE TITLE
Registering new shared service throws 500 error

### ISSUE THREAD

**Issue by tim-allen-ck** [microsoft/AzureTRE#3774]
Trying to register a new shared_service bundle I've created throws 500 error.
Building and publishing the bundle all work fine and the bundle is added to the ACR. 
Registering with API has the same effect as the pipeline. 
```
Registering template...
***
  "status_code": 500,
  "body": "Unable to process request"
***
make: *** [/home/vscode/AzureTRE/Makefile:268: bundle-register] Error 2
```
The terraform code for the bundle is pretty basic and passes the validation, the bundle accepts no input properties other than the basic name and description.

**Azure TRE release version v0.14.0+ **

**Comment by marrobi** [comment]
Can you enable debug logging and check the API logs. https://microsoft.github.io/AzureTRE/v0.15.2/troubleshooting-faq/debug-api/

It is likely that the JSON template schema does not validate against the pydantic model. If you can paste the schema here we can see if anything jumps out.

**Comment by tim-allen-ck** [comment]
> Can you enable debug logging and check the API logs. https://microsoft.github.io/AzureTRE/v0.15.2/troubleshooting-faq/debug-api/
> 
> It is likely that the JSON template schema does not validate against the pydantic model. If you can paste the schema here we can see if anything jumps out.

I enabled debug=true but didn't get anything useful out of the logs.

**Comment by marrobi** [comment]
Just tried and can see in the logs:

  ```
  File "/workspaces/marrobi-azure-tre/api_app/./db/repositories/resource_templates.py", line 162, in create_and_validate_template
    created_template = await self.create_template(template_input, resource_type, workspace_service_template_name)
  File "/workspaces/marrobi-azure-tre/api_app/./db/repositories/resource_templates.py", line 117, in create_template
    "required": template_input.json_schema["required"],
KeyError: 'required'
```

You are missing required in your json schema.

```
   "required": [],
```

The error should maybe handled in a better way. Line 117 could become:

```
            "required": template_input.json_schema["required"],
```

could become:

```
            "required": template_input.json_schema["required"] if "required" in template_input.json_schema else [],
```

Or a try/except returning "Invalid JSON schema"

**Comment by tim-allen-ck** [comment]
Hi Marcus, yes that looks like its fixed it thank you. 
Do we need to add something into the documentation about this or add a task to alter the error handling?

**Comment by marrobi** [comment]
The error handling should be nicer. You are the first person to hit this so not a priority, but if you feel like doing a PR, would be welcome.
