### ISSUE TITLE
GitHub Action Deploy TRE fails on first run at ACR login step

### ISSUE THREAD

**Issue by jonnyry** [microsoft/AzureTRE#3778]
**Describe the bug**

GitHub Action Deploy Azure TRE fails on first run at the [2nd ACR Login step](https://github.com/microsoft/AzureTRE/blob/6d589c49d6d647633109c70ee4636415b1ac17a8/.github/workflows/deploy_tre_reusable.yml#L247) with error `$ec numeric argument required`.

![first-run](https://github.com/microsoft/AzureTRE/assets/7916532/4bdf3050-cfc9-4fd5-b530-1605a6f635a5)

On subsequent runs it passes, as the 2nd ACR Login step is not executed, due to the [1st ACR Login step](https://github.com/microsoft/AzureTRE/blob/6d589c49d6d647633109c70ee4636415b1ac17a8/.github/workflows/deploy_tre_reusable.yml#L201) passing:

![second-run](https://github.com/microsoft/AzureTRE/assets/7916532/6a8e0ba8-2e04-4daf-9ab4-f89a3418325b)

**Steps to reproduce**

1.  Deploy the TRE using the "Deploy Azure TRE" GitHub Action for the first time (/to an empty Azure environment).
2.  Observe the error above on first run.
3.  Run a second time and observe the error does not occur.

**Azure TRE release version (e.g. v0.14.0 or main)**

main (v0.15.2)

**Comment by marrobi** [comment]
I believe this is this fix in the deployment repo - https://github.com/microsoft/AzureTRE-Deployment/pull/74/files#diff-5a2b3ccde8a4255fb43032fe938e96b572e2bee154824cab96b2027cb6a405c9R222 - need to make sure its applied everywhere needed.

**Comment by jonnyry** [comment]
Great, I'll rerun once merged.

**Comment by jonnyry** [comment]
@marrobi is there an upcoming release due that will include the fix in the PR above?

**Comment by marrobi** [comment]
Is it blocking you? Does a second run work? It's not something I've hit and deployed multiple PRs this week that cover this piece of code.

Are you using the deployment repo - if so it's a template - so you can just make the pipeline fix yourself until we do get this resolved.

**Comment by jonnyry** [comment]
No, it's not blocking - the second run is fine :-)

I was really asking the question to understand from a more general perspective how external PRs are handled by the core team and if there is release schedule / roadmap you're working to.

**Comment by marrobi** [comment]
So security and blocking bug fixes are prioritised. Then this board should give a general idea as to what is being worked on - https://github.com/orgs/microsoft/projects/559 - albeit priorities may change. We aim to do a release  month, or more frequently if required.

There is no core team working on a roadmap. Features/enhancements are only done when working directly with customers or based on PRs from external parties. This may change in the future but is the current situation.

Hope that helps.

**Comment by marrobi** [comment]
@nasaldrops @jonnyry I'm trying to work out the difference between the two approaches. I ask GitHub Copilot(!)...

---
Compare the following bash:
```
          for i in {1..3}; do
            az acr login --name "${{ secrets.CI_CACHE_ACR_NAME }}" && ec=0 && break || ec=\$? && sleep 10
          done
          # shellcheck disable=SC2242
          (exit ${ec})
```

with 

```
          for i in {1..3}; do
            az acr login --name "${{ secrets.CI_CACHE_ACR_NAME }}" && ec=0 && break || ec="$?" && sleep 10
          done
          # shellcheck disable=SC2242
          (exit "$ec")
```
---

After some explanation is says:

> In this specific context, both scripts will behave the same way as exit codes are integers and do not contain spaces or special characters. However, the second script follows better bash scripting practices.

So #3861 wins ;-) (and doesn't have linting issues). I'll get it merged unless anybody raises an issue. @nasaldrops are we good to close #3853? Thanks.

**Comment by jonnyry** [comment]
Thanks for merging @marrobi
