### ISSUE TITLE
Upgrading base and Airlock import review workspaces fails

### ISSUE THREAD

**Issue by SvenAelterman** [microsoft/AzureTRE#3781]
**Describe the bug**

Upgrading a base workspace from 1.1.0 to 1.5.0 and an Airlock import review workspace from 0.8.2 to 0.12.15 fail with the same errors. New deployments of the same versions succeed.

Error message (extracted relevant text, full below):

hashicorp/null: could not connect to registry.terraform.io: failed to request discovery document: Get "https://registry.terraform.io/.well-known/terraform.json": EOF Error: could not init terraform, exit status 1

**Azure TRE release version (e.g. v0.14.0 or main):** v0.15.2

**Deployed Azure TRE components - click the (i) in the UI:** 
UI Version:
0.5.15
API Version:
0.15.17

**Full error message:**

8112f919-2fd0-4a73-8420-ea46dfc809f8: Error message: [31m[31m╷[0m[0m [31m│[0m [0m[1m[31mError: [0m[0m[1mFailed to query available provider packages[0m [31m│[0m [0m [31m│[0m [0m[0mCould not retrieve the list of available versions for provider [31m│[0m [0mhashicorp/null: could not connect to registry.terraform.io: failed to [31m│[0m [0mrequest discovery document: Get [31m│[0m [0m"https://registry.terraform.io/.well-known/terraform.json": EOF [31m╵[0m[0m [0m[0m Error: could not init terraform, exit status 1 1 error occurred: * mixin execution failed: package command failed /cnab/app/cnab/app/mixins/terraform/runtimes/terraform-runtime upgrade [31m[31m╷[0m[0m [31m│[0m [0m[1m[31mError: [0m[0m[1mFailed to query available provider packages[0m [31m│[0m [0m [31m│[0m [0m[0mCould not retrieve the list of available versions for provider [31m│[0m [0mhashicorp/null: could not connect to registry.terraform.io: failed to [31m│[0m [0mrequest discovery document: Get [31m│[0m [0m"https://registry.terraform.io/.well-known/terraform.json": EOF [31m╵[0m[0m [0m[0m Error: could not init terraform, exit status 1 1 error occurred: * mixin execution failed: package command failed /cnab/app/cnab/app/mixins/terraform/runtimes/terraform-runtime upgrade [31m[31m╷[0m[0m [31m│[0m [0m[1m[31mError: [0m[0m[1mFailed to query available provider packages[0m [31m│[0m [0m [31m│[0m [0m[0mCould not retrieve the list of available versions for provider [31m│[0m [0mhashicorp/null: could not connect to registry.terraform.io: failed to [31m│[0m [0mrequest discovery document: Get [31m│[0m [0m"https://registry.terraform.io/.well-known/terraform.json": EOF [31m╵[0m[0m [0m[0m Error: could not init terraform, exit status 1 2 errors occurred: * container exit code: 1, message: <nil> * required output app_role_id_workspace_owner is missing and has no default ; Command executed: az cloud set --name AzureCloud && az login --identity -u 2adf0178-8e06-47c3-81fb-80b3c94529ac && az acr login --name actredemocreastus01 && porter upgrade "8112f919-2fd0-4a73-8420-ea46dfc809f8" --reference actredemocreastus01.azurecr.io/tre-workspace-airlock-import-review:v0.12.15 --param aad_redirect_uris="W3sibmFtZSI6ICJlZGIwMTI1NS1jYzQyLTRjNTctYjNmMi1iZjJhZWJlNmUyZWEiLCAidmFsdWUiOiAiaHR0cHM6Ly9ndWFjYW1vbGUtYWN0cmVkZW1vMDEtd3MtMDlmOC1zdmMtZTJlYS5henVyZXdlYnNpdGVzLm5ldC9vYXV0aDIvY2FsbGJhY2sifV0=" --param address_spaces="WyIxMC41MS41LjAvMjQiXQ==" --param app_role_id_workspace_airlock_manager="e6e4c304-d286-905d-a03c-277d1ae90891" --param app_role_id_workspace_owner="c6905c47-c0cb-feb6-86e0-40be92a7772e" --param app_role_id_workspace_researcher="5b8a80ca-2b28-6301-15b8-25cc8387d821" --param app_service_plan_sku="S1" --param arm_environment="public" --param arm_use_msi="true" --param azure_environment="AzureCloud" --param azure_location="eastus" --param client_id="3675b9f3-d5fb-4230-949c-1e94ba18b740" --param create_aad_groups="True" --param id="8112f919-2fd0-4a73-8420-ea46dfc809f8" --param register_aad_application="True" --param scope_id="api://actredemo01-ws-09f8" --param sp_id="5ac32ebd-724b-4389-a73e-151eda7154ca" --param tfstate_container_name="tfstate" --param tfstate_resource_group_name="actre-demo-rg-eastus-01" --param tfstate_storage_account_name="actredemosteus01" --param tre_id="actredemo01" --param workspace_owner_object_id="2f439cdc-dfa9-4130-a49d-c363fe380ad1" --force --credential-set arm_auth --credential-set aad_auth

**Comment by SvenAelterman** [comment]
This might have been due to a very old template to deploy the existing workspaces. However, it could be that customers would run into this as well.

**Comment by tim-allen-ck** [comment]
Looks like a transit connectivity issue, closing now now.
