### ISSUE TITLE
Service Bus Premium SKU?

### ISSUE THREAD

**Issue by jonnyry** [microsoft/AzureTRE#3782]
Could the Service Bus SKU be reduced to Standard in order to reduce running costs?  Are there any tradeoffs in doing so?

[Cost between the Standard and Premium SKU in UK South](https://azure.microsoft.com/en-gb/pricing/details/service-bus/):
  - Standard £8.10/mo (up to 13M ops)
  - Premium £557.72/mo (unlimited ops)

Given it's not possible to suspend or stop the Service Bus (without deleting it) wanting to find out whether the Premium SKU is necessary.

**Comment by marrobi** [comment]
It's used as it is VNet integrated so there are no public endpoints. Agree the cost differential can be a challenge. 

See: https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-premium-messaging#network-security

Standard could be used if IP filtering is sufficient (would need a consistent outbound IP from the resource processor) https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-ip-filtering . 

The majority of use cases require no public endpoints to be exposed, hence premium is required. It would be nice to have the option but requires development.

Thought about deleting the service bus as part of `make-tre-stop`, then on start running `make deploy-core` to recreate, but that is hacky.

**Comment by jonnyry** [comment]
I see - not so straightforward!  I guess that its also not possible (or even desirable) to temporarily downgrade the SKU when stopping the service and upgrade when starting.

**Comment by marrobi** [comment]
No, not possible unfortunately.

**Comment by jonnyry** [comment]
Thanks for the ideas @marrobi .  Will close this off as a question - though it's something we're continuing to consider.

**Comment by marrobi** [comment]
The easiest way would be to delete this resource and allow it to be recreated, try:

```
az resource delete --ids /subscriptions/####################/resourceGroups/rg-mytre/providers/Microsoft.ServiceBus/namespaces/sb-mytre|diagnostics-sb-mytre
```

If that doesn't work use the portal (see https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/create-diagnostic-settings?tabs=portal ) to find the diagnostic setting and delete it. They are part of Azure Monitor, so deleting the service bus does not delete the diagnostic setting, but then terraform tries to recreate it with the service bus.
