### ISSUE TITLE
Applying Windows / Linux VM updates

### ISSUE THREAD

**Issue by jonnyry** [microsoft/AzureTRE#3788]
Are there mechanisms for applying Windows and Linux OS updates to VMs on a restricted workspace?

I can see on linux that APT has been pointed to the Nexus package mirror allowing updates that have been loaded into it:

![image](https://github.com/microsoft/AzureTRE/assets/7916532/ce470227-10b8-4a35-92ec-229594d5a5a4)

However Windows Update won't connect - I'm not sure if there's a different mechanism being used to apply updates from the package mirror?

**Comment by marrobi** [comment]
HI @jonnyry, customers handle update in a variety of ways. 

Some use WSUS, others open up rules in the firewall - https://learn.microsoft.com/en-us/troubleshoot/windows-client/deployment/windows-update-issues-troubleshooting?toc=%2Fwindows%2Fdeployment%2Ftoc.json&bc=%2Fwindows%2Fdeployment%2Fbreadcrumb%2Ftoc.json#issues-related-to-httpproxy

We could do with doing an investigation and adding some documentation around Azure Update Manager: 
https://learn.microsoft.com/en-us/azure/update-manager/overview?tabs=azure-vms
