### ISSUE TITLE
"Error: making Read request on Azure KeyVault Secret" during deployment via GH Action

### ISSUE THREAD

**Issue by jonnyry** [microsoft/AzureTRE#3789]
**Describe the bug**

KeyVault read request failures during the main TRE deploy step (when re-deploying on top of existing deployed TRE), such as the one shown below.

```
Error: making Read request on Azure KeyVault Secret porter-db-connection-string: keyvault.BaseClient#GetSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Client address is not authorized and caller is not a trusted service.\r\nClient address: ***********\r\nCaller: appid=***;oid=*****;iss=[https://sts.windows.net/***/\r\nVault:](https://sts.windows.net/***//r/nVault:) kv-***;location=*****" InnerError=***"code":"ForbiddenByFirewall"***
│ 
│   with azurerm_servicebus_namespace_network_rule_set.servicebus_network_rule_set,
│   with azurerm_key_vault_secret.cosmos_mongo_connstr,
│   on cosmos_mongo.tf line 94, in resource "azurerm_key_vault_secret" "cosmos_mongo_connstr":
│   94: resource "azurerm_key_vault_secret" "cosmos_mongo_connstr" ***
```

![image](https://github.com/microsoft/AzureTRE/assets/7916532/c773eb43-6af1-460a-998f-84e95f915502)

**Steps to reproduce**

1. Deploy the TRE to clean environment.
2. Re-deploy the TRE
3. Witness above error

**Azure TRE release version (e.g. v0.14.0 or main):**
0.15.2

**Comment by marrobi** [comment]
Hmm, the KeyVault has public endpoint enabled I believe  (one maybe to review - but  GitHub agents would have to be on a VNet), looks like your hasn't. Can you check the KeyVault network setting, has a policy maybe enabled it?

**Comment by jonnyry** [comment]
KeyVault is set like this:

![image](https://github.com/microsoft/AzureTRE/assets/7916532/0acf2c5a-2f0e-4ebd-b046-9143390e3f6b)

I don't see a `public_network_access` setting in the terraform code:

https://github.com/microsoft/AzureTRE/blob/d5cd77b3efc3f4b764385987274e199df77ca65d/core/terraform/keyvault.tf

When you say GitHub agents would have to be on a VNet - do you mean something [like this](https://docs.github.com/en/enterprise-cloud@latest/admin/configuration/configuring-private-networking-for-hosted-compute-products/about-using-github-hosted-runners-in-your-azure-virtual-network)?

We're just using the out of the box GitHub Actions - not using self hosted runners.  Should be deploying with self hosted runners?

**Comment by marrobi** [comment]
This is what I see on our deployments:

![image](https://github.com/microsoft/AzureTRE/assets/17089773/72e57406-08de-4305-bbb2-a857ac950be8)

I expect you have a policy on the subscription that is changing the network setting.

**Comment by jonnyry** [comment]
Just doing a deploy to a clean environment to make sure nothing has come along and changed that setting.

I'll report back.

**Comment by jonnyry** [comment]
OK after a fresh deploy, I also now have a publicly accessible KeyVault:

![Capture](https://github.com/microsoft/AzureTRE/assets/7916532/4f2584e3-2000-4921-a6d6-02947defabd9)

Either I've changed it inadvertantly, or something else has - I'll keep an eye on it over the next few days.

Just on a broader point - I know one the main arch principles of the TRE is to have all network traffic running over private vnets, except for user accessible endpoints - having the KV publicly accessible seems to go against the principal, unless there's something I'm missing

**Comment by marrobi** [comment]
Ideally, and adhering to zero trust, they would be on a VNet, but  thismakes it very hard for people to get started with the solution. As the endpoints they secrets are for are on private networks, even if the KeyVault was breached they would be of little use. 

Should somebody have the time a solution such as https://github.com/UCLH-Foundry/Azure-Bootstrap would be useful to be integrated. This peers build agents to the TRE VNet and removes the need for public endpoints.

Could have a deployment parameter, `local_deploy` or similar which if true has these endpoints exposed, if not are closed.

**Comment by jonnyry** [comment]
OK thanks for clarifying.

Was my assertion that the TRE uses private VNETs for all traffic generally correct, except for this exception (and user accessible endpoints - bastion, app gateway etc)?

Are there other components that have public endpoints (for pragmatic reasons)?

**Comment by marrobi** [comment]
Yes, anything where is a risk of data/PII being exposed is inside a virtual network.

This isn't possible for say the airlock import storage account - as how else can a user get data in.

The ACR has a public endpoint, again so they can be built by a build agent and uploaded, as does the terraform state storage account. Ideally the build agent should be on a private network along with these resources.

**Comment by jonnyry** [comment]
Ok thanks, that's useful to know.

I'll close this issue down as I've done several deployments since and the network setting has matched your deployment, and had no problems since.
