### ISSUE TITLE
Release v0.16.0

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#3790]
Need to do this release so the airlock fixes are available.

**Comment by jonnyry** [comment]
Hi @marrobi any chance of this release being made available in microsoft/AzureTRE-Deployment?

I did attempt to re-point myself, but it looks like some of the elements in .devcontainer / .github require upgrading.

**Comment by marrobi** [comment]
I will try find time tis week as things are quietening down. 

You should just be able to update any amended lines in the dev container and copy over the yarn.local file that has been edited.

If need a hand let me know, you could even do a PR to the deployment repo ;)

(see point 4 at https://microsoft.github.io/AzureTRE/latest/tre-developers/release/ )

**Comment by marrobi** [comment]
@jonnyry https://github.com/microsoft/AzureTRE-Deployment/pull/96

Can you give it a test maybe? Thanks.

**Comment by jonnyry** [comment]
@marrobi yes will do, sorry for the delay - christmas got in the way!

**Comment by jonnyry** [comment]
@marrobi 

Just done a diff on the `.github` & `.devcontainer` folders between:

https://github.com/microsoft/AzureTRE/tree/v0.16.0
https://github.com/microsoft/AzureTRE-Deployment/tree/9178aa3db9b93555b4ac2a6ff20b0754fa43750a

There's a difference in the Porter version in the `.devcontainer` that looks like it needs bringing across.  Not sure about `pip` - I assume this is not needed on the Deployment version?

![image](https://github.com/microsoft/AzureTRE/assets/7916532/23a209de-7e54-4e5b-887b-fed56f6e08cb)

**Comment by jonnyry** [comment]
There were some differences in the GitHub folder - linters & minor differences to some of the GitHub Actions, though I couldn't see anything that looked critical (IMO).

**Comment by jonnyry** [comment]
@marrobi I've submitted a PR to microsoft/AzureTRE-Deployment in order to upgrade the Porter version

**Comment by marrobi** [comment]
@jonnyry thanks, merged.
