### ISSUE TITLE
MySQL: There is no (longer a?) 6 GB memory option

### ISSUE THREAD

**Issue by SvenAelterman** [microsoft/AzureTRE#3794]
**Describe the bug**
The MySQL workspace service template defines four SKUs: 2, 4, 6, and 8 CPUs. This is mapped to `GP_Gen5_X` in TF, where `X` is the number of cores. However, there is no SKU `GP_Gen5_6` (or at least not anymore). The valid SKUs for a General Purpose Gen 5 MySQL single server are GP_Gen5_2, GP_Gen5_4, GP_Gen5_8, GP_Gen5_16, GP_Gen5_32, and GP_Gen5_64.

Ref: https://learn.microsoft.com/azure/mysql/single-server/concepts-pricing-tiers

**Steps to reproduce**

1. Attempt to deploy a `GP | 5GB 6vCores` SKU from TRE.
1. Deployment fails with 

    Error message: expected sku_name to be one of [B_Gen4_1 B_Gen4_2 B_Gen5_1 B_Gen5_2 GP_Gen4_2 GP_Gen4_4 GP_Gen4_8 GP_Gen4_16 GP_Gen4_32 GP_Gen5_2 GP_Gen5_4 GP_Gen5_8 GP_Gen5_16 GP_Gen5_32 GP_Gen5_64 MO_Gen5_2 MO_Gen5_4 MO_Gen5_8 MO_Gen5_16 MO_Gen5_32], got GP_Gen5_6

**Azure TRE release version (e.g. v0.14.0 or main):** v0.15.2

**Comment by tim-allen-ck** [comment]
Hi @SvenAelterman this has been fixed with the release of v0.17.0 with transition to the flexible server resource.
```  
sql_sku = {
    "B | 4GB 2vCores"   = { value = "B_Standard_B2s" },
    "GP | 8GB 2vCores"  = { value = "GP_Standard_D2ds_v4" },
    "BC | 16GB 2vCores" = { value = "MO_Standard_E2ds_v4" }
  }
```

**Comment by tim-allen-ck** [comment]
@SvenAelterman is this good to be closed?

**Comment by SvenAelterman** [comment]
@tim-allen-ck I will be upgrading my TRE to 0.17.0 sometime today probably, I will test again then.

**Comment by tim-allen-ck** [comment]
Closing Issue
