### ISSUE TITLE
bundle-build target doesn't work without setting DOCKER_CONTEXT=default for porter

### ISSUE THREAD

**Issue by TonyWildish** [microsoft/AzureTRE#3801]
Remember to label the issue with the appropriate area, and also assign it to yourself if you plan to work on the issue in the near future.

**Describe the bug**
Running make on a Mac terminal session, the bundle-build target fails because porter doesn't have the correct Docker context. Setting DOCKER_CONTEXT=DEFAULT on the command line before executing porter fixes this:

```
@@ -186,14 +196,18 @@ lint-docs:
# check-params is called at the end since it needs the bundle image,
# so we build it first and then run the check.
bundle-build:
        $(call target_title, "Building ${DIR} bundle with Porter") \
        && . ${MAKEFILE_DIR}/devops/scripts/check_dependencies.sh porter,env \
        && . ${MAKEFILE_DIR}/devops/scripts/set_docker_sock_permission.sh \
        && cd ${DIR} \
        && if [ -d terraform ]; then terraform -chdir=terraform init -backend=false; terraform -chdir=terraform validate; fi \
        && FULL_IMAGE_NAME_PREFIX=${FULL_IMAGE_NAME_PREFIX} IMAGE_NAME_PREFIX=${IMAGE_NAME_PREFIX} \
                ${MAKEFILE_DIR}/devops/scripts/bundle_runtime_image_build.sh \
-       && porter build \
+       && DOCKER_CONTEXT=default porter build \
          $(MAKE) bundle-check-params
```

This might be Mac-specific, but the fix is generic, so including it won't hurt.

**Steps to reproduce**

1. Install AzureTRE git repo on a Mac
1. Run through the build procedure, wait for it to get to the bundle-build target

**Azure TRE release version (e.g. v0.14.0 or main):**
main

**Deployed Azure TRE components - click the (i) in the UI:**
none, didn't get that far.

**Comment by TonyWildish** [comment]
No, I'm running from the Terminal, not in the devcontainer.

I realise that puts me out on a limb in terms of deployment, but since the fix is generic, I thought it might be worth mentioning.

**Comment by marrobi** [comment]
As per https://microsoft.github.io/AzureTRE/v0.15.2/tre-admins/setup-instructions/deployment-repo/#clone-the-azure-tre-deployment-git-repository - all steps need to be run inside the dev container. 

We are aware of other platform specific issues, such as Windows, and often conflicting (as in change it for one, breaks another), so by using the dev container we can support a workflow that works across operating systems.

Hope that helps. I'll close the issue.
