### ISSUE TITLE
building Docker images which require pip to install psutils fails unless gcc is installed

### ISSUE THREAD

**Issue by TonyWildish** [microsoft/AzureTRE#3802]
Remember to label the issue with the appropriate area, and also assign it to yourself if you plan to work on the issue in the near future.

**Describe the bug**
Building the Docker images for `api_app/Dockerfile` or `resource_processor/vmss_porter/Dockerfile` fails at the 'pip install' step due to gcc and python3-dev not being installed in the image.

In both cases, adding `RUN apt-get update -y && apt-get install -y gcc python3-dev` before the pip install command is enough to fix the problem.

N.B. This is on a Mac with a manual installation from the terminal, but I don't believe that is responsible for the problem since it occurs inside the container being built.

**Steps to reproduce**

1. clone AzureTRE repository
1. follow manual build procedure
1. when it reaches the stage to build either of these Docker images, it fails with a pip message that psutils cannot be built because of gcc and python3-dev being absent

**Azure TRE release version (e.g. v0.14.0 or main):**
main

**Deployed Azure TRE components - click the (i) in the UI:**
none, didn't get that far

**Comment by marrobi** [comment]
@TonyWildish Can you confirm that you running inside the dev container? Thanks.

**Comment by TonyWildish** [comment]
no, running from the Terminal command line on a Mac.

**Comment by marrobi** [comment]
Can you test within the dev container? As per the other thread, it's extremely hard to support multiple platforms, hence the dev container resolves most of these challenges.

**Comment by TonyWildish** [comment]
can do, I'll get back to you.

**Comment by marrobi** [comment]
Hi @TonyWildish did this work in the dev container? Thanks.

**Comment by TonyWildish-BH** [comment]
Hi Marcus, yes, it does work in the devcontainer.

**Comment by marrobi** [comment]
Ok, closing as the supported route is via dev container. Thanks.
