### ISSUE TITLE
File ownership error building TRE CLI in devcontainer

### ISSUE THREAD

**Issue by TonyWildish** [microsoft/AzureTRE#3804]
Remember to label the issue with the appropriate area, and also assign it to yourself if you plan to work on the issue in the near future.

**Describe the bug**

Building the Devcontainer requires installing the TRE CLI, which is copied to `/tmp/cli`, then built in-place (lines 107+). This doesn't work unless the COPY command explicitly sets the ownership correctly, with `COPY --chown=vscode ...`

Again, I'm running on a Mac, but since I need to build the devcontainer to be able to use it, I consider this worth fixing.

**Steps to reproduce**

1. clone AzureTRE repository on a Mac
1. build devcontainer: `docker build -t devcontainer -f .devcontainer/Dockerfile .`

**Azure TRE release version (e.g. v0.14.0 or main):**
main

**Deployed Azure TRE components - click the (i) in the UI:**
none

**Comment by TonyWildish** [comment]
No, I'm building manually, not with VSCode.

**Comment by TonyWildish** [comment]
I'm sure it works in VSCode, I just thought it would be useful for it to work outside that too, since it's a non-specific change.

**Comment by marrobi** [comment]
We only have a limited amount of resource and hence can't "support" workflows that don't align with the way we test and hence document how to deploy and work with the project. Although you say it's not specific - without fully testing each change on each platform (and every developers specific environment) nothing is certain. This is why we use devcontainers  and have documentation with clear step by step instructions. 

If there are issue as a result of the following the documentation (there are likely issues in the docs as with most docs), then happy to discuss and look at a resolution. Thanks.
