### ISSUE TITLE
Azure Open AI deployability as a workspace service within Azure TRE

### ISSUE THREAD

**Issue by andrewsoltan** [microsoft/AzureTRE#3810]
Requesting ability to deploy the Azure OpenAI service as a service (e.g. as a workspace service) within an Azure TRE workspace, including secure networking within the TRE boundary

**Comment by marrobi** [comment]
@SvenAelterman was any progress made by your team in finding resource to do this? I know it was on a list somewhere.

If not @andrewsoltan  have you people who could build this out with our assistance? What's the timescales you need this within?

**Comment by andrewsoltan** [comment]
Thanks all- we would be hoping to use this for a project funded by the MSR Accelerating Foundation models research grant (https://www.microsoft.com/en-us/research/collaboration/accelerating-foundation-models-research/phase-ii/ ) with an end date of end-Jan 2024, but appreciate that's quite tight!
Including @JaimieWi too for info

**Comment by SvenAelterman** [comment]
This did not make it in our scope, unfortunately.

**Comment by marrobi** [comment]
@JaimieWi if I make a start on something are you able to test and refine so we can hopefully get it merged into the project?

**Comment by SvenAelterman** [comment]
I would be happy to participate too. I don't have the availability to do the whole thing, but happy to test and review and help with design.

**Comment by JaimieWi** [comment]
@marrobi Yes, very happy to help where I can

**Comment by marrobi** [comment]
Ok, I've made a start here - https://github.com/microsoft/AzureTRE/pull/3812

I can't test myself due to subscription limits - I have no OpenAI capacity where I have my TRE deployed (and I'm currently travelling), but hopefully enough for @JaimieWi and @SvenAelterman to give it a test and feedback.

**Comment by martysharkey** [comment]
@marrobi did this get completed?

**Comment by marrobi** [comment]
@martysharkey  I'm not sure if it got tested/used by @JaimieWi ?

It needs picking up at some point in the future, testing and merging into the repo.

**Comment by JaimieWi** [comment]
Hi @marrobi @martysharkey Apologies, we didn't get time to work on this and the team had to move onto other projects. I'm not sure when/if we'll be able to pick it up.

**Comment by martysharkey** [comment]
thanks both.

**Comment by wenjia-knight** [comment]
Hi @marrobi Happy to pick this one up with my colleagues @michael-fielding if testing/using is still needed?

**Comment by marrobi** [comment]
Yes, that would be great if you can pick up the existing draft PR.

**Comment by martysharkey** [comment]
Thats great news @wenjia-knight. I've just sent you a linkedin connection request. It would be amazing if you could join my Azure TRE User Group and pop a little post in telling the users that you are working on this now. 🥰 https://www.linkedin.com/groups/12867690

**Comment by JaimieWi** [comment]
> @martysharkey I'm not sure if it got tested/used by @JaimieWi ?
> 
> It needs picking up at some point in the future, testing and merging into the repo.

Apologies, I was not able to progress with this. Thank you very much @wenjia-knight !

**Comment by harryy94** [comment]
Hi. I work with @wenjia-knight and @michael-fielding at Hippo. Just to update you all, we have been looking at this and have built upon @marrobi's original PR to get a deployable Open AI Workspace Service. We are still doing some testing but welcome any comments on that PR in the meantime. Thanks.

**Comment by marrobi** [comment]
@harryy94 great to see! Will have a look through and look to test. 

@damoodamoo @anatbal might be can use this for the hack as per - https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/azure-ai-search-integration-with-fabric-onelake-now-in-preview/ba-p/4136672

**Comment by harryy94** [comment]
Hi. We've done a load more testing and are happy with it. I've pushed additional changes to tidy things up (like adding some documentation and bumping up version numbers) using another older PR as a guide. Please let me know if you have any feedback :)
