### ISSUE TITLE
Getting Airlock SAS URL into workspace VM

### ISSUE THREAD

**Issue by jonnyry** [microsoft/AzureTRE#3813]
In my Azure TRE deployment I am trying to find a user friendly way to get an Airlock SAS URL into a workspace VM in order to download import data / upload export data, *when copy/paste is disabled on the VM*.

Just wondering if there is a method I haven't discovered or whether other people have found a neat solution to this?

**Comment by marrobi** [comment]
Most customers allow paste in, but not out, as the Guacamole clipboard is limited to quite a small amount, and significantly hinders researcher productivity if blocked.

We did discuss making the UI and API available inside the workspace ( https://github.com/microsoft/AzureTRE/issues/1812 ) but given the above has never been prioritised.

**Comment by jonnyry** [comment]
Linked to #2402
