### ISSUE TITLE
Issue Post-Deployment: Access Denied - Error in Resource Retrieval - Missing Roles ['TREUser', 'TREAdmin'] for Workspace Access

### ISSUE THREAD

**Issue by BiologyGeek** [microsoft/AzureTRE#3835]
Hi team,

* Immediately following deployment and login, I encountered this red error message:
```
Access Denied
Error retrieving resources
The user is missing a required role: ['TREUser', 'TREAdmin']
Attempted resource: workspaces
```
![2024-01-31_203209](https://github.com/microsoft/AzureTRE/assets/157970993/be8efee2-aa92-4017-ad85-c2b57b458d99)

* The steps I took for deployment include:
  1. Accessed a new and empty Azure account.
  2. Activated a pay-as-you-go subscription.
  3. Created a new Tenant using Microsoft Entra ID to enable the use of 'Dedicated Tenant' benefits over the 'Default Directory'. This helps automate some AD Tenant Admin tasks. I was presented with two options: 'Microsoft Entra Workforce tenant' and 'Azure AD B2C'. I chose 'Azure AD B2C'.
  4. Started the dev container, completed the 'config.yaml' file with the required parameters, and then ran these commands:
```
$ az login --use-device-code
$ make auth
$ make all
```
Additional Information: The process failed twice at the firewall configuration step, displaying a lengthy error message. The last three lines of the message were as follows:
```
make[1]: *** [Makefile:298: ***deploy-shared-service] Error 1
make[1]: Leaving directory '/home/vscode/AzureTRE'
make: *** [Makefile:305: firewall-install] Error 2
```
But it succeeded on the third attempt, displaying the FQDN and other expected outputs.

Then continue with:
 ```
$ make letsencrypt
$ curl https://<MY azure_tre_fqdn Was Here>/api/health
```
The API call result was 'ok' for all three items.

For reference, I used the manual deployment method as detailed here:
https://microsoft.github.io/AzureTRE/v0.16.0/tre-admins/setup-instructions/manual-deployment/

* After open FQDN and logging in and encountering the error message, I consulted the following documentation:
  - Introduction - Azure TRE
    https://microsoft.github.io/AzureTRE/v0.16.0/tre-admins/auth/

  In the Azure Portal, under my new Directory Tenant in the 'App registrations' section, I found these four items:
  (Azure Portal --> (Switch to) my new Directory Tenant --> App registrations)
  - mytreid API
  - mytreid Application Admin
  - mytreid Automation Admin
  - mytreid UX

  Further, in the 'Users' section under 'Assigned roles' for my main user, I expected to see 'TREUser' and 'TREAdmin' roles as per the documentation. However, they were not present. I then assigned the following roles to the account:
  (Azure Portal --> my new Directory Tenant --> Microsoft Entra ID --> Users --> (Select) my main user -->  Assigned roles --> Add assignments)
  - Application Administrator
  - Application Developer
  - Cloud Application Administrator
  - Directory Readers
  - Directory Writers
  - Network Administrator

  Note: Prior to adding these, the account already had the 'Global Administrator' role.

  Unfortunately, the issue persists.

My question is, considering I used a 'Dedicated Tenant', why weren't the 'TREUser' and 'TREAdmin' permissions automatically assigned to my main user (the only user in the Tenant)? Did I overlook something in the process?

Thanks!

**Comment by marrobi** [comment]
Ok, first of all I'm not sure an Azure AD B2C (business to consumer) Tenant will work. It seems the naming in the portal may have changed. "Entra Workforce Tenant" must be what a traditional Azure AD tenant is. Apologies - this is new.

Tagging this issue as we should fix this in the docs: https://github.com/microsoft/AzureTRE/issues/3650

If you proceed with B2C then afraid it's unchartered territory and expect will hit issues when authenticating with Azure resources as B2C identities cannot be assigned to azure resources. I suggest trying again with "Entra Workforce Tenant".

As far ass the application role, TREAdmin, this does need assigning manually as per:

https://microsoft.github.io/AzureTRE/latest/tre-admins/setup-instructions/setup-auth-entities/#add-admin-user. It's not done automatically as some users don't what the team deploying to have access to the application itself. We have a feature on the backlog to enable this here - https://github.com/microsoft/AzureTRE/issues/3241.

Sorry that you hit an issue and we will look to get the docs updated.

**Comment by BiologyGeek** [comment]
Thank you @marrobi 

By following your advice on redeploying and assigning roles manually, the problem has been resolved.

![2024-02-02_062624](https://github.com/microsoft/AzureTRE/assets/157970993/597ddc3f-65c8-44bf-84b5-536356e2bb10)
