### ISSUE TITLE
Creating a Export Review VM fails with "EntityDoesNotExist"

### ISSUE THREAD

**Issue by james-annages** [microsoft/AzureTRE#3850]
**Describe the bug**
When trying to create a export review VM it thoughs the error "Error creating review resource" 
When looking in the Logs it shows this: 
```
Failed to retrieve Airlock Review configuration for workspace <workspace ID for Airlock review workspace>
Traceback (most recent call last):
  File "/api/api/routes/airlock.py", line 136, in create_review_user_resource
    updated_resource, operation = await create_review_vm(airlock_request, user, workspace, user_resource_repo, workspace_service_repo, operation_repo, airlock_request_repo, resource_template_repo, resource_history_repo)
  File "/api/services/airlock.py", line 198, in create_review_vm
    user_resource, operation = await _deploy_vm(airlock_request, user, workspace, review_workspace_id, review_workspace_service_id, user_resource_template_name, user_resource_repo, workspace_service_repo, operation_repo, resource_template_repo, resource_history_repo)
  File "/api/services/airlock.py", line 220, in _deploy_vm
    workspace_service = await workspace_service_repo.get_workspace_service_by_id(workspace_id=review_workspace_id, service_id=review_workspace_service_id)
  File "/api/db/repositories/workspace_services.py", line 55, in get_workspace_service_by_id
    raise EntityDoesNotExist
db.errors.EntityDoesNotExist

```
**Azure TRE release version (e.g. v0.14.0 or main):**
v0.16.0
**Deployed Azure TRE components - click the (i) in the UI:**
UI: 0.5.17
API: 0.16.9
Cosmos DB: OK
Service Bus: OK
Resource Processor: OK

**Comment by marrobi** [comment]
Hi @james-annages,

It sounds like the Export Workspace Service ID as described here: https://microsoft.github.io/AzureTRE/latest/tre-admins/configure-airlock-review/#configuring-airlock-vm-for-research-workspace

Cannot be found. Typically this is the ID of the Apache Guacamole Service in the workspace you are doing the export from.

Let me know if this helps.

**Comment by james-annages** [comment]
Hello, @marrobi 
thanks for the suggestion, 
However, they are all the same. 
Config from the Airlock settings in the workspace
![Screenshot 2024-02-12 152139](https://github.com/microsoft/AzureTRE/assets/45330941/535336c2-e9b0-45d6-8fca-b6d633c58747)
The settings in the DB for that workspace
![Screenshot 2024-02-12 152404](https://github.com/microsoft/AzureTRE/assets/45330941/5c7ae647-96ca-4228-82ad-c60e827b617d)
Settings from the Workspace services for the Apache Guacamole services that I want to use for exports (they are all in the same work space.
![Screenshot 2024-02-12 152613](https://github.com/microsoft/AzureTRE/assets/45330941/5d26251d-2229-4604-ae18-f45ce643efb3)

**Comment by marrobi** [comment]
That is odd. The query that is failing is:

```
SELECT * FROM c WHERE c.resourceType = "{ResourceType.WorkspaceService}" AND c.workspaceId = "workspace_id}"' AND c.id = "{service_id}"
```

(from ```  File "/api/db/repositories/workspace_services.py", line 55, in get_workspace_service_by_id```)

In the Resources collection. You could always try the query in CosmosDB wit the values substituted in.

Is the request definitely being created from the workspace starting 6b...? My only other guess is is there some hidden characters somehow introduced via copy/paste...

**Comment by james-annages** [comment]
Sorry just seen there is some incorect information in the bug report, 
the call in coming from the workspace that has submitted the airlock request.

**Comment by james-annages** [comment]
Hello, sorry for the confution. 
ID of the Airlock requeting enviroment: bc0c7799
ID of the workspace where the guacamole service is located: 6b5a6866
ID of the guacamole service for the export: 9596936c

when running the query from the ID of the where the Airlock request was submitted:
![Screenshot 2024-02-12 170640](https://github.com/microsoft/AzureTRE/assets/45330941/cfe92425-7a87-4816-9300-f318aba33d86)
I get no results

when running the query from the ID of the where the Airlock review workspace is located: 
![Screenshot 2024-02-12 170536](https://github.com/microsoft/AzureTRE/assets/45330941/fde3d48e-4753-4eb4-8df5-fabc4196312f)
i also go no results.

**Comment by marrobi** [comment]
It's c.id not c.service_id, see my example above.

**Comment by james-annages** [comment]
re tried the query with the requested information, when we try and use the ID for the workspace that submitted the airlock request we don't get any responses. 
when I submit the query with the ID for the airlock review workspace
![Screenshot 2024-02-13 145520](https://github.com/microsoft/AzureTRE/assets/45330941/ef8ae09f-bcf4-41d1-886b-6c4a6723370b)

**Comment by marrobi** [comment]
Ok, for EXPORT the Guacamole service needs to be in the workspace that you are exporting from. The data must not leave that workspace until reviewed, hence that's where the VM needs to be to review it.

The "airlock IMPORT review" workspace is only for imports.

As per: https://microsoft.github.io/AzureTRE/latest/tre-admins/configure-airlock-review/#configuring-airlock-vm-for-research-workspace 

"For Export Review Workspace Service ID, use the GUID of the Workspace Service deployed into the **Research Workspace from step 4.**"

Deploy the Guacamole Workspace Service into the workspace you are exporting from, update the ID, and you should be good.

**Comment by marrobi** [comment]
@james-annages did you get this resolved? Thanks.

**Comment by james-annages** [comment]
Hello it did. Sorry ment to update this.
