### ISSUE TITLE
Storage account name collisions are becoming too likely

### ISSUE THREAD

**Issue by SvenAelterman** [microsoft/AzureTRE#3862]
**Describe the bug**
With only 4 hexadecimal digits to create uniqueness, storage account names are seeing increasing collisions.

**Steps to reproduce**

1. Create workspace is a luck of the draw.

**Azure TRE release version (e.g. v0.14.0 or main):** any

**Deployed Azure TRE components - click the (i) in the UI:** n/a

> Backwards compatibility is going to be a significant issue to work around for existing workspaces and possibly (third-party) code that has a dependency on the current naming structure.

Additional entropy can be added by including the TRE ID in the storage account name:

`stgws<tre_id>ws<ws_short_id>`

This would be maximally 5 + 12 + 2 + 4 = 23 characters, which is within the limits of storage account names (24 characters).

This method would avoid adding randomness to ensure that services that need to leverage the storage account can deterministically create the name.

**Comment by SvenAelterman** [comment]
Thought: if randomness should be added instead of the TRE ID, then perhaps a tag can be used to identity the storage account for what it is. But I am not sure if TF could retrieve an existing resource by type + tag name/value pair. I know Bicep couldn't do it.

**Comment by marrobi** [comment]
Reopening https://github.com/microsoft/AzureTRE/issues/2893, was closed in error.

**Comment by marrobi** [comment]
Closing as duplicate, lets discuss in the other issue.
