### ISSUE TITLE
Databricks control plane IPs are changing 2024-05-30

### ISSUE THREAD

**Issue by SvenAelterman** [microsoft/AzureTRE#3901]
**Describe the bug**

Databricks control plane IPs in the json file need to be updated following today's announcement that they are changing effective May 30, 2024.

List: https://learn.microsoft.com/en-us/azure/databricks/resources/supported-regions#--inbound-to-azure-databricks-control-plane

**Azure TRE release version (e.g. v0.14.0 or main):** N/A

**Deployed Azure TRE components - click the (i) in the UI:** N/A

**Comment by tim-allen-ck** [comment]
This the databricks-udr.json file will need updating
templates/workspace_services/databricks/terraform/databricks-udr.json

**Comment by tim-allen-ck** [comment]
@SvenAelterman could you clarify which ips need changing? Or is it all locations?

**Comment by SvenAelterman** [comment]
@tim-allen-ck I don't know, I haven't compared.
