### ISSUE TITLE
Enable Workspace owners to create Airlock requests and remove need for email

### ISSUE THREAD

**Issue by SvenAelterman** [microsoft/AzureTRE#3904]
**Describe the bug**

When creating a new airlock request, the airlock seems to expect at least one member of the Workspace Researchers role with an email address assigned.

Besides the odd requirement for this (considering bug #3506), having only Workspace Owners should be supported too.

**Steps to reproduce**

1. Create a workspace with airlock enabled.
1. Assign Workspace Owner with an email address populated.
1. Try to create an Airlock request.

**Azure TRE release version (e.g. v0.14.0 or main):** v0.16.0

**Deployed Azure TRE components - click the (i) in the UI:**
- UI: 0.5.17
- API: 0.16.9

**Comment by marrobi** [comment]
Agree, Workspace Owners should be supported, and the requirement for email made optional.
