### ISSUE TITLE
Docs not rebuilt for v0.17.0

### ISSUE THREAD

**Issue by SvenAelterman** [microsoft/AzureTRE#3905]
**Describe the bug**

The documentation at shows version 16 as the lastest: https://microsoft.github.io/AzureTRE/latest/

**Comment by tim-allen-ck** [comment]
Hi @SvenAelterman, the doc pipeline failed to run when the latest release published.
This PR [#3898](https://github.com/microsoft/AzureTRE/pull/3898) should fix the error in the next release.
The pipeline is setup to run manually to build the release docs. Is this something we should do?

**Comment by SvenAelterman** [comment]
I am not sure, actually. I've never published a release myself.

@marrobi?

**Comment by marrobi** [comment]
It was the auto one that runs on release fails, and can't rerun without unpublishing the release. I suggest we just wait until the next release as don't think will be far away.

**Comment by tim-allen-ck** [comment]
This has been fixed with the new release
