### ISSUE TITLE
Isuue with "make letsencrypt": `Error creating new order :: too many certificates already issued for "eastus.cloudapp.azure.com". Retry after 2024-04-25T20:00:00Z:`

### ISSUE THREAD

**Issue by BiologyGeek** [microsoft/AzureTRE#3908]
Hello team,

**Describe the bug**
When attempting to run `make letsencrypt` after initial deployment, the following error message is displayed:
```kusto
Waiting for network rule to take effect
Created network rule on storage account
Checking for index.html file in storage account
index.html already present
Saving debug log to /workspaces/AzureTRE-Deployment/letsencrypt/logs/letsencrypt.log
Account registered.
Requesting a certificate for mytre.eastus.cloudapp.azure.com
An unexpected error occurred:
Error creating new order :: too many certificates already issued for "eastus.cloudapp.azure.com". Retry after 2024-04-25T20:00:00Z: see https://letsencrypt.org/docs/rate-limits/
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /workspaces/AzureTRE-Deployment/letsencrypt/logs/letsencrypt.log or re-run Certbot with -v for more details.
make: *** [/home/vscode/AzureTRE/Makefile:119: letsencrypt] Error 1
```

`Error creating new order :: too many certificates already issued for "eastus.cloudapp.azure.com". Retry after 2024-04-25T20:00:00Z:`

**Steps to reproduce**

1. Run `make letsencrypt`  for an instance deployed in the East US region.

**Azure TRE release version:** 0.17

-----

**Question:** Before addressing this issue programmatically, is there a way to resolve it manually?

**Comment by tim-allen-ck** [comment]
> Thanks you @tim-allen-ck, The Let's Encrypt documentation you provided states:
> 
> > The main limit is Certificates per Registered Domain (50 per week). A registered domain is, generally speaking, the part of the domain you purchased from your domain name registrar. **For instance, in the name [www.example.com](http://www.example.com), the registered domain is example.com. `In new.blog.example.co.uk, the registered domain is example.co.uk`**.
> 
> Based on this document, I believe 'azure.com' is considered the Registered Domain to which rate limits are applied, not 'eastus.cloudapp.azure.com'. Is my understanding correct? In this case, if I deploy in another region, would 'azure.com' still be the Registered Domain, with only a component like 'eastus' being replaced in this URL: eastus.cloudapp.azure.com?

Ahh yes sorry @BiologyGeek, you're right the Registered domain is azure.com. Yes it will still be the registered domain if deploying to a new region.

**Comment by tim-allen-ck** [comment]
@BiologyGeek to get round the issue for now try added in `--test-cert` here [file](https://github.com/microsoft/AzureTRE/blob/cb59c99233575b096207e6afc288af9da7ee0256/core/terraform/scripts/letsencrypt.sh#L107) to use Lets Encrypt staging which has higher limits.

**Comment by tim-allen-ck** [comment]
#1540

**Comment by tim-allen-ck** [comment]
ahh that message from the nexus is from the cert shared service.

**Comment by marrobi** [comment]
Just a heads up, the staging certs aren't trusted by default, so if don't want warnings need to add the root cert to the trusted store on the browser. It's fine for development, but for production, best using a custom domain name on the app gateway(s).

**Comment by marrobi** [comment]
It's something we need do some more work on as part of #1540.

As you can see here - https://github.com/microsoft/AzureTRE/blob/cb59c99233575b096207e6afc288af9da7ee0256/core/terraform/appgateway/certificate.tf#L15C1-L64C2 a certificate called letsencrypt is created in KeyKault. You can replace that with a cert for your DNS name, and point a custom domain name to the App Gateway public IP.

I'll have to have a think about Nexus, as it's not something I've personally done.

**Comment by tim-allen-ck** [comment]
Closing, will be looked at in #1540
