### ISSUE TITLE
Dockerize the Resource Processor function

### ISSUE THREAD

**Issue by Lybecker** [microsoft/AzureTRE#391]
The Resource Processor is hosted in an Azure Function, but not in a Docker container.

The CNAB container and the Management API are both Dockerized. To standardize by having all processes in Docker container, the Resource Processor should be dockerize too. 

[Steps to create host an Azure Function in a Docker container](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image?tabs=bash%2Cportal&pivots=programming-language-python)

Docker container hosting for Azure Functions requires a Premium hosting plan. We are already using a Premium hosting plan for VNET integration, so it will introduce no cost of running TRE.

**Comment by marrobi** [comment]
VMSS resource processor uses docker,
