### ISSUE TITLE
Cost API "too many requests"

### ISSUE THREAD

**Issue by Danny-Cooke-CK** [microsoft/AzureTRE#3929]
While using the TRE, it will occasionally / frequently output a message banner at the top of the screen advising too many requests have been issues to the cost API service. 

![image](https://github.com/microsoft/AzureTRE/assets/136708214/f515b669-3b84-45f2-b5f1-046b2f3b2a1e)

It happens during just normal use of the TRE and can be quite annoying. 

Navigating back to the TRE home page, putting your mouse in the address bar and hitting enter normally resolves the issue for a while but it will always come back

**Comment by jonnyry** [comment]
Also frequently see this message!

**Comment by TonyWildish-BH** [comment]
me too. It makes no sense that we're being throttled like this, surely the TRE can't be making calls that often?

It would also be nice if the red 'X' were active, so I could close the error message and get rid of it.

**Comment by marrobi** [comment]
@tim-allen-ck can we get this temp fix merged? I'm seeing lots of requests to costs, think is an issue with the UI somewhere refreshing the data too frequently.
