### ISSUE TITLE
Migrate GitHub CI subscription

### ISSUE THREAD

**Issue by PoojanumN** [microsoft/AzureTRE#3934]
This feature request involves transitioning the Azure subscription details used within GitHub for a specific project. The current credentials need to be updated to align with a new subscription plan. The key action items include updating GitHub secrets with new API client IDs and secrets, as well as the Azure credentials. This update is necessary to ensure continuous integration and deployment processes function smoothly with the new Azure subscription.

The tasks will involve:

- Verifying existing GitHub secrets and replacing them with the new subscription details.
- Coordinating with team members to handle the changes during a scheduled call to avoid any disruptions.
- Running tests to confirm that the new settings are functioning correctly within the GitHub Actions workflows.
- A temporary environment will be used for testing, which will be spun up and torn down per pull request to ensure that the changes do not affect ongoing operations. This task should also consider updating the documentation and removing any outdated or unused variables from the workflows.

The aim is to achieve a seamless transition with minimal disruption to ongoing development activities. This will require collaborative efforts and clear communication among all stakeholders involved.

**Comment by Danny-Cooke-CK** [comment]
in progress. the Blank PR has triggered tests

**Comment by Danny-Cooke-CK** [comment]
i have managed to get most of the TRE deployed via a PR but im currently experiencing Timeout's 

https://github.com/microsoft/AzureTRE/actions/runs/9128975870/job/25106235076

will leave it for a while and then try again

**Comment by tim-allen-ck** [comment]
Subscription has been moved, pipeline is working in CK Sub
