### ISSUE TITLE
Key Vaults should use RBAC instead of access policies for access control

### ISSUE THREAD

**Issue by SvenAelterman** [microsoft/AzureTRE#4000]
## Description

As a TRE Administrator
I want to use the recommended configurations for Azure resources
So that feature deprecations, etc. won't affect a production environment

## Acceptance criteria

- [ ] Key Vaults deployed by TRE use Azure RBAC for access control
- [ ] A migration path is documented for existing TRE instances

**Comment by SvenAelterman** [comment]
@marrobi @jonnyry When will this be published to a new release?

**Comment by marrobi** [comment]
We will look to get a release done in the next week or two.
