### ISSUE TITLE
Core deployment errors - Error: reading blob properties for Storage Account

### ISSUE THREAD

**Issue by jonnyry** [microsoft/AzureTRE#4004]
Deploying a fresh TRE from 2 commits behind main (1ffb09baf37f4599adfd65b4259fdda7564da408)...

Experienced storage account failures on two seperate deployments:

![Capture](https://github.com/microsoft/AzureTRE/assets/7916532/b5df5b40-4872-4500-8498-b3e2c844f6e7)

![Capture3](https://github.com/microsoft/AzureTRE/assets/7916532/add3195b-69f8-4fab-b663-5d7081712e61)

**Comment by tim-allen-ck** [comment]
could be an issue with the terraform providers?

**Comment by jonnyry** [comment]
Just pulled your tf provider update and giving it a try now.

**Comment by jonnyry** [comment]
Reployed fine with the tf provider update - I'll close this off.

**Comment by jonnyry** [comment]
Unfortuntely just happened again on the latest codebase (including the tf provider update):

![image](https://github.com/microsoft/AzureTRE/assets/7916532/07d4e6df-a1f7-4660-8755-2fc030b31e8b)

**Comment by tim-allen-ck** [comment]
how weird, and the storage account doesn't exist in the portal?

**Comment by jonnyry** [comment]
I have already destroyed that environment already, but I've just seen it happen again and I've checked and the storage account does exist:

![image](https://github.com/microsoft/AzureTRE/assets/7916532/d2592af7-e6fc-4ccc-8b4d-222823df4ec0)

![image](https://github.com/microsoft/AzureTRE/assets/7916532/7234cb74-c806-4ef6-91e9-29acedc1a7af)

**Comment by jonnyry** [comment]
Looks like it could be this:  https://github.com/hashicorp/terraform-provider-azurerm/issues/22992

**Comment by jonnyry** [comment]
And for the issue to be resolved, wait for the following PR:  https://github.com/hashicorp/terraform-provider-azurerm/pull/26218

**Comment by jonnyry** [comment]
still occurring on almost every deployment:

![image](https://github.com/microsoft/AzureTRE/assets/7916532/88a73537-c3d9-4e8b-8219-0c043a4ba1a0)

**Comment by marrobi** [comment]
Are you using the same TRE ID between deployments? Wonder if some sort of DNS caching going on?

**Comment by jonnyry** [comment]
I am yes.  I think it is to do with DNS caching.

However not sure why the issue has only started occuring this week, as been reusing TRE IDs for a long time.

**Comment by marrobi** [comment]
Are these jobs running on a github agent? Is it a GitHub hosted one or an agent you manage?

**Comment by jonnyry** [comment]
Just a standard GitHub Actions Runner - not one that we manage.

**Comment by marrobi** [comment]
Hmm, we never really deploy, destroy, and deploy with the same ID. Wonder if you left it a couple of days before reusing the same  ID.

Might be need to create an issue in the Terraform provider repository/wait for the one you mentioned, not sure its an Azure TRE issue, or something we are going to be able to resolve.

**Comment by jonnyry** [comment]
It's intermittent - I think it does depend on how long it was since the last deploy.

Curiously for the issue I was having this morning, I deleted the storage account that was causing the 404, re-ran the build and it completed sucessfully.

I'll hopefully manage to work around it for now and keep an eye on release of the terraform PR above.

**Comment by jonnyry** [comment]
Strangely not seen it for a couple of weeks - it went away by itself.  If it reoccurs, I'll try bumping the terraform azurerm version.

**Comment by marrobi** [comment]
Going to close this given not senit again.

**Comment by jonnyry** [comment]
This has occured 6 times in the last week - when attempting to deploy a TRE instance using the same name as that of a recently deleted TRE instace.

Going to try bumping TF provider in the core from v3.112.0 to v3.117.0 (incorporating a [fix for this issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/22992)) to see if it helps.

**Comment by jonnyry** [comment]
OK two deployments using v3.117.0 have succeeded.
