### ISSUE TITLE
Documentation does not render ending emoji Properly

### ISSUE THREAD

**Issue by Sweetdevil144** [microsoft/AzureTRE#4027]
Remember to label the issue with the appropriate area, and also assign it to yourself if you plan to work on the issue in the near future.

**Describe the bug**

_Documentation errors are as follow :_

The like line of the Contributing to `AzureTRE docs` are rendered as follow : `Thanks! :heart: :heart: :heart:` when I visit it from my Brave and Safari browser.

**Steps to reproduce**

1. Visit the webpage at [https://microsoft.github.io/AzureTRE/latest/contributing/](https://microsoft.github.io/AzureTRE/latest/contributing/)
2. Navigate to the bottom of page at the end of `How to Contribute to our Documentation` section
3. Observe the last line

**Azure TRE release version (e.g. v0.14.0 or main):**

**Deployed Azure TRE components - click the (i) in the UI:**

**Comment by tim-allen-ck** [comment]
good spot.
It looks like there is a markdown extension missing from the mkdocs.yml
https://github.com/microsoft/AzureTRE/blob/9d0bf319e5eed1b5ae4ec055917adc98ce6651da/mkdocs.yml#L33-L45

[for reference](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/)
