### ISSUE TITLE
Resource processor function app not deployed as part of Quickstart

### ISSUE THREAD

**Issue by christoferlof** [microsoft/AzureTRE#403]
When following the steps in the quickstart, you'll end up with a AzTRE instance without the resource processor function app deployed - preventing bundles from being deployed.

There is a `deploy-processor-function` target in the [Makefile](https://github.com/microsoft/AzureTRE/blob/develop/Makefile#L67), but it is not called from `tre-deploy` nor mentioned in quickstart.

**Comment by limorl** [comment]
merged #405
