### ISSUE TITLE
Can't connect to workspace Linux VM via Guacamole - cloud-init failure

### ISSUE THREAD

**Issue by jonnyry** [microsoft/AzureTRE#4039]
Can't connect to workspace Linux VM via Guacamole.

Azure TRE version - 0.18.0
Linux VM image - Ubuntu 22.04 LTS

Looking at the logs on the machine, cloud-init has failed:

![image](https://github.com/user-attachments/assets/11f875e4-8d63-4a99-89ce-d45d4ba3acae)

I am not running the nexus package manager on this TRE.

Is running Nexus a pre-req for running Linux VMs?

**Comment by tim-allen-ck** [comment]
Hey, yes nexus is now a pre-req for all vms in Guacamole

**Comment by jonnyry** [comment]
Is this since the Ubuntu 22.04 upgrade?

Is there any way we can enforce the pre-req?... e.g. prevent install of Linux VMs without Nexus being installed.  Or install nexus if it isn't.

If not, a documentation update would be useful.

**Comment by tim-allen-ck** [comment]
not sure about forced pre-req, but that wopuld be ideal. The linux vm docs have already been updated.

**Comment by jonnyry** [comment]
Ah I apologise - I was looking at an old version :-(

**Comment by jonnyry** [comment]
As way of an update, I can confirm that adding the nexus package mirror, then re-running the cloud-init scripts resolved the issue and I can now connect.

https://microsoft.github.io/AzureTRE/unreleased/troubleshooting-faq/cloud-init/
