### ISSUE TITLE
View users who are assigned roles within a workspace

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#4049]
TRE Admins and all workspace users should be able to retrieve which users are assigned to a workspace.

This can be done by adding an additional route to `workspaces_shared_router`, for example: `/api/workspaces/{workspace_id}/users/`.

The MS Graph API should be used to retrieve roles from the Enterprise Application. This can be done using the call described here - https://learn.microsoft.com/en-us/graph/api/serviceprincipal-list-approleassignedto?view=graph-rest-1.0&tabs=http , `GET /servicePrincipals(appId='{appId}')/appRoleAssignedTo`

This needs to appear in the Workspace Swagger docs under a section Users.

The API response should return a list of users, including their name (principalDisplayName), email (derived from another graph call using principalId), and the app roles assigned to the user.

The user interface needs a new section on the left hand menu under Airlock, called Users. This should display a list of users including their  name, email and role(s).

**Comment by tim-allen-ck** [comment]
Would be good to get this for the main TRE too, not just a workspace

**Comment by marrobi** [comment]
![image](https://github.com/user-attachments/assets/8746dc0c-3b1f-4104-a842-334b14f61159)

Thoughts? Should it be Users or Members? On the left menu, or maybe somewhere else.

@jonnyry @TonyWildish-BH @tim-allen-ck thoughts? 

I will try do a PR, as code is written, and people can test and comment as feel fit.

**Comment by TonyWildish-BH** [comment]
this looks useful, yes. It's a little confusing to put it under 'shared services', since it's not a service, just config information. Is it easy to add an extra section on the left, 'config', where this can go?

Eventually, we may want to implement further features, such as allowing the Workspace Owner to allow/disallow certain workspace service templates, and this would then be a great place to put it.

**Comment by marrobi** [comment]
Ah, it's not actually under shared services, that's the React component being confusing...
![image](https://github.com/user-attachments/assets/47cf5546-a158-4d67-9394-0a581162df0b)

But agree, a section called *Configuration* or *Administration*. Wording is another discussion.

**Comment by tim-allen-ck** [comment]
> Thoughts? Should it be Users or Members? On the left menu, or maybe somewhere else.
> 
> @jonnyry @TonyWildish-BH @tim-allen-ck thoughts?
> 
> I will try do a PR, as code is written, and people can test and comment as feel fit.

Users makes sense, but looks good. Is this just to view the users or configure them as well?

**Comment by marrobi** [comment]
This PR is to view, we could add configuration options. I just wanted something interesting to give a go with Copilot Workspaces. Was probably 50% AI...

**Comment by jonnyry** [comment]
> ![image](https://private-user-images.githubusercontent.com/17089773/355083269-8746dc0c-3b1f-4104-a842-334b14f61159.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4OTU0MTUsIm5iZiI6MTcyMjg5NTExNSwicGF0aCI6Ii8xNzA4OTc3My8zNTUwODMyNjktODc0NmRjMGMtM2IxZi00MTA0LWE4NDItMzM0YjE0ZjYxMTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDIxNTgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMzQ2YWQ1MmE2ZDdlNWQ2NGMyZDdlNTk3ZTczNGQxMDY3OWQ5NDM1MjU1Zjk2Zjc2ZTBkODAxZGFhNDZkZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DeH4IEySSSwWYAP8FQ7AgEB8xJnzpb-N9TV8xtSq8J0)
> 
> Thoughts? Should it be Users or Members? On the left menu, or maybe somewhere else.
> 
> @jonnyry @TonyWildish-BH @tim-allen-ck thoughts?
> 
> I will try do a PR, as code is written, and people can test and comment as feel fit.

This would be handy for us. I think users is marginally clearer.

**Comment by marrobi** [comment]
Draft PR above, welcome anybody who is able to test with larger numbers of users/groups than I have in my demo environment.

@TonyWildish-BH if/when we get more admin/config settings we can create a separate section.
