### ISSUE TITLE
Azure Storage Explorer won't run on Linux VM unless .NET is updated

### ISSUE THREAD

**Issue by TonyWildish-BH** [microsoft/AzureTRE#4067]
**Describe the bug**

Azure Storage Explorer doesn't run on the new Ubuntu 22.04 image out of the box. It gives an error message stating that .NET SDK 8.0 is needed, but the installed version is 7.0.

This is easy to fix on the VM by uninstalling `dotnet-sdk-7.0` and replacing it with `dotnet-sdk-8.0`, then the Storage Explorer runs correctly.

Updating `templates/workspace_services/guacamole/user_resources/guacamole-azure-linuxvm/vm_config.sh`, line 61, and rebuilding the template fixes this at source.

**Steps to reproduce**

1. Deploy the current HEAD (commit e84e62516d29142f00554e0a5fe173b587b6cfe1)
2. Deploy a workspace, then Guacamole, then a Linux VM. 
3. Attempt to start the Azure Storage Explorer, wait for the error message

**Azure TRE release version (e.g. v0.14.0 or main):**
current HEAD

**Deployed Azure TRE components - click the (i) in the UI:**

**Comment by tim-allen-ck** [comment]
I'll raise a PR for this now @TonyWildish-BH
