### ISSUE TITLE
Log Analytics deprecated in favour of Azure Monitor agent?

### ISSUE THREAD

**Issue by TonyWildish-BH** [microsoft/AzureTRE#4076]
I received an email from Microsoft recently warning me that Log Analytics is deprecated, and that we should switch to the Azure Monitor agent by August 31st - mail shown below. It looks like all the VMs in the TRE are using Log Analytics, so two questions:

1) is this known already, and are there any plans to do anything about it?
2) what are the consequences of _not_ migrating? Will it simply mean we lose monitoring, or will the VMs fail to deploy, blocking our use of the TRE?

mail as follows:

----------------------------------

### Start using the Azure Monitor agent instead of the Log Analytics agent before 31 August 2024

_**You're receiving this email because you use the Log Analytics agent to monitor your virtual machines (VMs) or servers.**_

On 31 August 2024, we'll retire the Log Analytics agent that you use in Azure Monitor. Before that date, you'll need to start using the Azure Monitor agent to monitor your VMs and servers in Azure. The Azure Monitor agent provides new features and capabilities, including:

- Centralized configuration for multiple VMs.
- Data limits and filters at the source.
- Multiple destinations for data from a single agent.

### Required action

Follow the [migration instructions](https://learn.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration) to start using the Azure Monitor agent to monitor your VMs and servers before 31 August 2024.

**Comment by Danny-Cooke-CK** [comment]
Hi Tony, Thanks for this.  i was unaware of this too but it seems the initial announcement was https://azure.microsoft.com/en-gb/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/.

The azure TRE uses azure monitor already so i would imagine this has already been taken care of but let me confirm. I suspect you got that email because your tenant or subscription has VM's in there created but not from the TRE?

**Comment by tim-allen-ck** [comment]
Hi @TonyWildish-BH as @akolensky said, it doesn't appear the TRE is using the LA Agents so I'm closing the ticket.
