### ISSUE TITLE
What's the meaning of 'updateable' in a template schema?

### ISSUE THREAD

**Issue by TonyWildish-BH** [microsoft/AzureTRE#4086]
I'm trying to update the Guacamole template to permanently disable the ability to copy data out via the clipboard. I've set the appropriate parameter to `updateable: false`, and rebuilt the image.

I've verified that it's built and pushed correctly by pulling it down from the ACR to a different machine, entering the container, and verifying that the `template_schema.json` in use is the correct one.

When I go to deploy the service, I still see that I can check or uncheck that checkbox, there's nothing preventing me from updating the field.

Is that expected behaviour, or is there something else I should be doing?

I've trawled through the codebase, and the only place where I see `updateable: false` in use is in the SAS URL for an airlock request. That field is indeed not updateable, so it looks like it's working there.

**Comment by marrobi** [comment]
It means the field cannot be updated after initial deployment. Soo if it is initial deployment rather than an update the behaviour is by design.

What you actually want to do is hard code the configuration? In which case you should remove the field from the schema completely and ensure the default is as you require.

**Comment by TonyWildish-BH** [comment]
got it, thanks!

**Comment by TonyWildish-BH** [comment]
hmm, I've tried removing the fields from the schema, and I've verified that I really have removed them fully and rebuilt the templates correctly, but the UI persists in displaying the fields. Do I need to rebuild the UI as well?

**Comment by marrobi** [comment]
Have you increased the version of the template and reregistered?

**Comment by TonyWildish-BH** [comment]
Ah, I was replacing the template in-place, I don't like bumping version numbers during development, it can lead to an awful lot of versions.

I've just destroyed/re-built my TRE, and the menu correctly shows only the options I want. If I mess with it again, I'll bump the version as you recommend, so we can close this one now, thanks.
