### ISSUE TITLE
How do I debug a firewall deploy which fails with an empty error message?

### ISSUE THREAD

**Issue by TonyWildish-BH** [microsoft/AzureTRE#4088]
I'm deploying a TRE, and it fails on the firewall installation. The error message, below, is not very helpful in this case.

The firewall itself did get deployed, I can see it in the portal. So I don't know what it's objecting to here, and I don't know how to debug this. Does anyone have any suggestions?

```
azurerm_firewall.fw: Still creating... [6m10s elapsed]
azurerm_firewall.fw: Still creating... [6m20s elapsed]
╷
│ Error: waiting for creation/update of Firewall: (Azure Firewall Name "fw-sdetw15" / Resource Group "rg-sdetw15"): Code="InternalServerError" Message=
"An error occurred." Details=[]
│ 
│   with azurerm_firewall.fw,
│   on firewall.tf line 30, in resource "azurerm_firewall" "fw":
│   30: resource "azurerm_firewall" "fw" {
│ 

error running command /cnab/app/terraform /usr/bin/terraform apply -auto-approve -input=false -var api_driven_network_rule_collections_b64=W10= -var ap
i_driven_rule_collections_b64=W10= -var firewall_sku=Standard -var microsoft_graph_fqdn=graph.microsoft.com -var tre_id=sdetw15 -var tre_resource_id=77
bc4038-e223-4500-aeb0-ccf44f2c2e41: exit status 1
Error: error running command /cnab/app/terraform /usr/bin/terraform apply -auto-approve -input=false -var api_driven_network_rule_collections_b64=W10= 
-var api_driven_rule_collections_b64=W10= -var firewall_sku=Standard -var microsoft_graph_fqdn=graph.microsoft.com -var tre_id=sdetw15 -var tre_resourc
e_id=77bc4038-e223-4500-aeb0-ccf44f2c2e41: exit status 1
1 error occurred:
* mixin execution failed: package command failed /cnab/app/cnab/app/mixins/terraform/runtimes/terraform-runtime install
╷
│ Error: waiting for creation/update of Firewall: (Azure Firewall Name "fw-sdetw15" / Resource Group "rg-sdetw15"): Code="InternalServerError" Message=
"An error occurred." Details=[]
│ 
│   with azurerm_firewall.fw,
│   on firewall.tf line 30, in resource "azurerm_firewall" "fw":
│   30: resource "azurerm_firewall" "fw" {
│
```

**Comment by tim-allen-ck** [comment]
Looks like the terraform api just timed out. What does the resource say when you login into the tre?

**Comment by TonyWildish-BH** [comment]
it shows that error message, and that it's not ready.

**Comment by tim-allen-ck** [comment]
Is there a error message in the tre on the shared service?

**Comment by TonyWildish-BH** [comment]
that's the error message that comes up in the container running in the resource processor, and is then shown in the firewall service in the TRE. They're the same in this case.

**Comment by marrobi** [comment]
What happens if you run an update on the firewall? I expect it will recover. 

Looks like a transient issue on the deployment of the Firewall. If you want to get to the root cause you would have to look at the firewall activity logs and potentially open a support case.

**Comment by TonyWildish-BH** [comment]
I didn't find anything in the firewall activity logs, they were empty.

I destroyed the TRE and redeployed from scratch (new tre_id), and it got past that point, so I guess it was transient. I'll close this ticket, thanks for the help.
