### ISSUE TITLE
Airlock notifier is broken?

### ISSUE THREAD

**Issue by TonyWildish-BH** [microsoft/AzureTRE#4089]
**Describe the bug**
I'm deploying a fresh TRE, and am setting up the Airlock Notifier shared service. This no longer works, the Logic App workflow is corrupt somehow. The actual deployment from the TRE goes through without error, but the Logic App is showing errors.

From what I can tell, it looks like something has changed behind the scenes and the message trigger is no longer correct. See screenshots below.

I've deployed several TREs for development over the last few months, but this is only the second time I try to get the Airlock Notifier working, I haven't used it in my other development environments, only in our Alpha release to uses about 3 months ago. So something could have changed anytime in the last 3 months or so.

**Steps to reproduce**

1. Deploy a fresh TRE
2. Deploy the Airlock Notifier shared service
3. Look at the Logic App to see that it's broken.

**Azure TRE release version (e.g. v0.14.0 or main):**
latest code as of 2 weeks ago, unmodified.

**Deployed Azure TRE components - click the (i) in the UI:**
UI Version:   0.5.27
API Version: 0.18.11

note the error message, plus the runtime version is showing an error
<img width="1350" alt="airlock-runtime" src="https://github.com/user-attachments/assets/13d1c6a0-6bcd-4486-8983-ef256a310f46">

inspecting the workflow, the trigger looks broken...
<img width="1290" alt="airlock-trigger" src="https://github.com/user-attachments/assets/7698f386-0314-4d1f-95a2-8c2bc8940a5d">

**Comment by tim-allen-ck** [comment]
Hi Tony what version number of the notifier are you deploying?

**Comment by TonyWildish-BH** [comment]
0.12.16

**Comment by tim-allen-ck** [comment]
Okay, thanks, I'll deploy that version and try to reproduce.

**Comment by TonyWildish-BH** [comment]
in `airlock_notifier.tf`, set `WEBSITE_NODE_DEFAULT_VERSION` to `~18`, and set `version` to `~4` for the `logic_app` resource.
