### ISSUE TITLE
Git permission issue in Dev Container?

### ISSUE THREAD

**Issue by jonnyry** [microsoft/AzureTRE#4090]
Recently built a fresh Dev Container in VS Code (on Windows) and now seeing the following error when trying to use Git CLI from within the container:

![image](https://github.com/user-attachments/assets/b02f2dbb-5955-4cdd-a72a-ad8878097816)

I have manually added an exception, but just wanted to raise it as I've not seen it before when building the Azure TRE Dev Container, and wondered whether anyone else had seen it?

---

This provides a bit of background on Dev Containers & the error in git...

https://www.kenmuse.com/blog/avoiding-dubious-ownership-in-dev-containers/

**Comment by marrobi** [comment]
@tim-allen-ck hit it last week I think. Didn't consider that it would be a Dev Container issue.

**Comment by tim-allen-ck** [comment]
me either, I assumed it was me

**Comment by jonnyry** [comment]
Glad it's not just me :-)

Wonder if its worth sticking the following in `devcontainer.json` as per that kenmuse.com link above?

```
"postStartCommand": "git config --global --add safe.directory ${containerWorkspaceFolder}",
```

**Comment by a-illarionov** [comment]
a quick workaround is using "sudo -s" running it again and then running the rest in parts...

**Comment by jonnyry** [comment]
No longer occuring with a freshly built container on the current version of main.
