### ISSUE TITLE
Workspace creation blocked due to Azure API depreciation.

### ISSUE THREAD

**Issue by TonyWildish-BH** [microsoft/AzureTRE#4095]
**Describe the bug**
I created a workspace for a user on September 10th. The user was unable to allocate time to use it until this week, so I disabled the workspace on the 10th, to reduce costs a bit.

Today, I tried to re-enable that workspace, and it fails. The message in the Operations tab is from Terraform, about being unable to register a Resource Provider:

```
Error message: Error ensuring Resource Providers are registered.
Terraform automatically attempts to register the Resource Providers it supports to
ensure it's able to provision resources.
If you don't have permission to register Resource Providers you may wish to use the
"skip_provider_registration" flag in the Provider block to disable this functionality.

Please note that if you opt out of Resource Provider Registration and Terraform tries
to provision a resource from a Resource Provider which is unregistered, then the errors
may appear misleading - for example:

> API version 2019-XX-XX was not found for Microsoft.Foo

Could indicate either that the Resource Provider "Microsoft.Foo" requires registration,
but this could also indicate that this Azure Region doesn't support this API version.

More information on the "skip_provider_registration" flag can be found here
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#skip_provider_registration

Original Error: determining which Required Resource Providers require registration: the required Resource Provider "Microsoft.TimeSeriesInsights" wasn't returned from the Azure API

with provider["registry.terraform.io/hashicorp/azurerm"],
on providers.tf line 20, in provider "azurerm":
20: provider "azurerm"

error running command /cnab/app/terraform /usr/bin/terraform apply -auto-approve -input=false -var
```

**Steps to reproduce**

1. Create a workspace
2. Disable it
3. Wait two weeks (not sure how important that part is)
4. (Try to) re-enable the workspace

**Azure TRE release version (e.g. v0.14.0 or main):**
main, as of August 12th.

**Deployed Azure TRE components - click the (i) in the UI:**
UI Version: 0.5.27
API Version: 0.18.11

**Comment by marrobi** [comment]
Can you check that the provider Microsoft.TimeSeriesInsights is registered in your subscription, and which API versions are available?

https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-providers-and-types#register-resource-provider

**Comment by TonyWildish-BH** [comment]
Microsoft.TimeSeriesInsights is not visible in the list of resource providers, whether registered or not.

**Comment by marrobi** [comment]
See: https://github.com/hashicorp/terraform-provider-azurerm/issues/27466

Can you try updating the provider version please.

**Comment by jonnyry** [comment]
Hi @TonyWildish-BH @marrobi 

Yes I've just seen this when creating a new workspace

**Comment by RPal111** [comment]
The error means that Terraform is trying to use a resource provider called Microsoft.TimeSeriesInsights, but it isn't registered in your Azure subscription. Terraform usually registers resource providers automatically, but sometimes this fails because of permission issues or other problems.

See this ; https://learn.microsoft.com/en-us/azure/azure-resource-manager/troubleshooting/error-register-resource-provider

**Comment by Danny-Cooke-CK** [comment]
Hi tony. We've also had the same issue today. We tried to deploy a new TRE and the pipeline failed with the same issue. I have raised a ticket with MS as the provider has disappeared and i can't reenable it 

│ Error: Error ensuring Resource Providers are registered.
│ 
│ Terraform automatically attempts to register the Resource Providers it supports to
│ ensure it's able to provision resources.
│ 
│ If you don't have permission to register Resource Providers you may wish to use the
│ "skip_provider_registration" flag in the Provider block to disable this functionality.
│ 
│ Please note that if you opt out of Resource Provider Registration and Terraform tries
│ to provision a resource from a Resource Provider which is unregistered, then the errors
│ may appear misleading - for example:
│ 
│ > API version 2019-XX-XX was not found for Microsoft.Foo
│ 
│ Could indicate either that the Resource Provider "Microsoft.Foo" requires registration,
│ but this could also indicate that this Azure Region doesn't support this API version.
│ 
│ More information on the "skip_provider_registration" flag can be found here:
│ https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#skip_provider_registration
│ 
│ Original Error: determining which Required Resource Providers require registration: the required Resource Provider **"Microsoft.TimeSeriesInsights"** wasn't returned from the Azure API
│ 
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on main.tf line 33, in provider "azurerm":
│   33: provider "azurerm" ***
│ 
╵
Releasing state lock. This may take a few moments...
make: *** [/home/vscode/AzureTRE/Makefile:110: deploy-core] Error 1

**Comment by Danny-Cooke-CK** [comment]
https://azure.microsoft.com/en-us/updates/we-re-retiring-azure-time-series-insights-on-7-july-2024-transition-to-azure-data-explorer/#:~:text=Microsoft%27s%20leadership%20emphasizing%20priority%20on%20security%20has%20decided,Insights%20will%20stop%20functioning%20and%20will%20be%20inaccessible

**Comment by jonnyry** [comment]
Upping the azurerm provider version in the base workspace appears to work (as evidenced by other people in https://github.com/hashicorp/terraform-provider-azurerm/issues/27466).  See fix here:  https://github.com/nwsde/nwsde-azuretre/tree/jr/upstream-main/65-update-tf-providers

However I now get the following error when deploying a base workspace, which appears to be related to the recent Open AI change:

![image](https://github.com/user-attachments/assets/7748ba4d-4c05-4739-bdb0-cfb4511cd701)

**Comment by marrobi** [comment]
@jonnyry the OpenAI PR requires a core update. So `make deploy-core` at minimum?

**Comment by jonnyry** [comment]
> @jonnyry the OpenAI PR requires a core update. So `make deploy-core` at minimum.

Ah yes - I've removed that from my comment as I realised I was deploying the latest base workspace against a slightly older TRE.  Just re-testing now.

**Comment by JaimieWi** [comment]
Could this change be applied across all bundles with the older versions? The error is also seen on user resource and workspace service deployments. 

Tests done:
Deploying Guacamole workspace service or any new VMs fails with the same error.

**Comment by TonyWildish-BH** [comment]
there's quite a range of values specified in various places:

```
> grep --after-context=2 -h 'azurerm =' $(find core templates -name providers.tf) | grep version | awk -F\" '{ p
rint $2 }' | sort | uniq
3.37.0
=3.108.0
=3.37.0
=3.40.0
=3.53.0
=3.57.0
=3.58.0
=3.73.0
>= 3.8.0
>=3.33.0
```

**Comment by jonnyry** [comment]
Also the PR above is to the `base` workspace only - https://github.com/microsoft/AzureTRE/pull/4096

`airlock-import-review` and `unrestricted` workspaces both pull a pinnned version of the `base` workspace code from GitHub and so will use an older version, until a new Azure TRE release is created, the version number updated here:

https://github.com/microsoft/AzureTRE/blob/7dd1915ca4a350ebc6c34282078965a127d058b0/templates/workspaces/airlock-import-review/Dockerfile.tmpl#L17

https://github.com/microsoft/AzureTRE/blob/7dd1915ca4a350ebc6c34282078965a127d058b0/templates/workspaces/unrestricted/Dockerfile.tmpl#L17

**Comment by jonnyry** [comment]
@tim-allen-ck #4096 fixes the Terraform issue for the base workspace.

But as @JaimieWi mentions above the issue exists on other templates since each pins its own version of the azurerm providier, e.g. Guacamole:

![image](https://github.com/user-attachments/assets/5a8013cf-b242-4f10-9801-31add1b04801)

**Comment by Danny-Cooke-CK** [comment]
Regarding this case. All the providers need updating and then the lock files where appropriate. 
Working on it now as a priority

**Comment by TonyWildish-BH** [comment]
@Danny-Cooke-CK, thanks for prioritising this. When you test the fix, will you be testing only fresh installations, or will you test upgrades to existing installations?

[The new error message I'm getting](https://github.com/microsoft/AzureTRE/issues/4095#issuecomment-2371596260) probably won't show up on a fresh install, but we need to upgrade. It seems from Hashicorp that the problem is linked to [strict case-sensitive matching where there used to be case insensitive matching](https://github.com/hashicorp/terraform-provider-azurerm/issues/22138).

**Comment by marrobi** [comment]
@TonyWildish-BH the case issues occurs on fresh installs too, @jonnyry accounted for it in his PR to fix workspaces - https://github.com/nwsde/nwsde-azuretre/blob/e4d9a07a040079639903baeee03b7aadf9283c36/templates/workspaces/base/terraform/azure-monitor/azure-monitor.tf#L139

**Comment by TonyWildish-BH** [comment]
thanks @marrobi, I'd missed that line, and that does fix it for me.

**Comment by jonnyry** [comment]
> Regarding this case. All the providers need updating and then the lock files where appropriate. Working on it now as a priority

@Danny-Cooke-CK thanks.  Also note the unrestricted and airlock-import-review workspace also have the same problem, but the fix is different - see https://github.com/microsoft/AzureTRE/issues/4095#issuecomment-2371464915 above.

**Comment by Danny-Cooke-CK** [comment]
> > Regarding this case. All the providers need updating and then the lock files where appropriate. Working on it now as a priority
> 
> @Danny-Cooke-CK thanks. Also note the unrestricted and airlock-import-review workspace templates also have the same problem, but the fix is different - see [#4095 (comment)](https://github.com/microsoft/AzureTRE/issues/4095#issuecomment-2371464915) above.

Thanks @jonnyry i was just about to create a PR and saw this comment !! cheers i'll make that update too

**Comment by Danny-Cooke-CK** [comment]
PR to fix this raised https://github.com/microsoft/AzureTRE/pull/4097

**Comment by TonyWildish-BH** [comment]
@Danny-Cooke-CK ,thanks for the fast work.

I see the PR completely removes `config.sample.yaml`, is that intentional?

<img width="886" alt="Screenshot 2024-09-26 at 8 43 49 AM" src="https://github.com/user-attachments/assets/30086bc8-b59a-4d58-a0cb-4c1ad5436d41">

**Comment by Danny-Cooke-CK** [comment]
> @Danny-Cooke-CK ,thanks for the fast work.
> 
> I see the PR completely removes `config.sample.yaml`, is that intentional?
> 
> <img alt="Screenshot 2024-09-26 at 8 43 49 AM" width="886" src="https://private-user-images.githubusercontent.com/153200306/371035591-30086bc8-b59a-4d58-a0cb-4c1ad5436d41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzcwMDEsIm5iZiI6MTcyNzMzNjcwMSwicGF0aCI6Ii8xNTMyMDAzMDYvMzcxMDM1NTkxLTMwMDg2YmM4LWI1OWEtNGQ1OC1hMGNiLTRjMWFkNTQzNmQ0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwNzQ1MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTRkYTUzZTcxOTY2MWY1YTU3YzlhNTUzNDViMGZkYzc2ZTE1ZDc1MDVlNWIwZTU5OWI4YjRlZDMwNjI4ODhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9DDmC5HeS6CPFHX33WZol6G4-YmGjzfV19RnOUSY4DU">

thanks tony. well spotted

**Comment by marrobi** [comment]
@TonyWildish-BH you seem to have linked a PR to close this issue from your fork of the project?

**Comment by TonyWildish-BH** [comment]
@Danny-Cooke-CK, just a question since you're on it:

I see that the version specs still vary: `3.112.0`, `=3.112.0`,  `>=3.112.0`. Is it feasible to have them all identical, or will that break something, now or in the future? It would be nice for them to be consistent if that's possible.

**Comment by TonyWildish-BH** [comment]
> @TonyWildish-BH you seem to have linked a PR to close this issue from your fork of the project?

not intentionally, that's just a partial fix for the bits I care about right now. Updated to remove the link, thanks for calling that out.
