### ISSUE TITLE
Unify CI/CD pipeline and quickstart

### ISSUE THREAD

**Issue by Lybecker** [microsoft/AzureTRE#410]
## Description

As a TRE developer
I want to deploy TRE 
So that there is only one way to deploy

## Acceptance criteria

- [ ] Quickstart documentation updated
- [x] CI/CD pipeline uses devcontainer
- [ ] CI/CD pipeline and quickstart is using the same scripts and follows the same steps

**Comment by ross-p-smith** [comment]
@marrobi and @tamirkamara  - I think we can close this one. The local build / CI-CD are not going to benefit from this very generic story.

**Comment by marrobi** [comment]
@ross-p-smith agree, done.
