### ISSUE TITLE
Unable to delete vm's

### ISSUE THREAD

**Issue by james-annages** [microsoft/AzureTRE#4109]
**Describe the bug**
We are unable to remove vm's from the Apache Guacamole service. 

**Steps to reproduce**

1. deploy a VM in Apache Guacamole. 
2. Disable the VM. 
3. Try to delete the VM

**Azure TRE release version (e.g. v0.14.0 or main):**
v0.19.1 we updated from v0.16.0

**Deployed Azure TRE components - click the (i) in the UI:**
![Image](https://github.com/user-attachments/assets/3920a363-efdb-474c-9737-a852eb14775b)

**Comment by marrobi** [comment]
Did you upgrade in one jump up or go though the versions?

Is there an error logged on the operations tab?

**Comment by james-annages** [comment]
went up in steps. 
this was a custom user resource.
Error message: uninstalling bundle couldn't run command /cnab/app ./delete_vm_extensions.sh rg-*****-mgmt ********* tfstate 7*****e1-e657-****-****-************: fork/exec ./delete_vm_extensions.sh: permission denied 

i have got it working again after copying the new default windows resource and modifying it as needed.

**Comment by marrobi** [comment]
Ok, closing this if you are sorted, let us know if need further help.
