### ISSUE TITLE
Github build validation fails on missing tags when it shouldn't

### ISSUE THREAD

**Issue by tamirkamara** [microsoft/AzureTRE#4117]
**Describe the bug**
We enforce tags for Azure resources at different levels of the solution and our build validation should take that under advisement but it doesn't... Is requires `tre_workspace_id` tag on a `devops` level resource which isn't reasonable.

**Comment by jonnyry** [comment]
Hi @tamirkamara 

Is this the same as/ related to the linting issues on my recent PR https://github.com/microsoft/AzureTRE/pull/4116#issuecomment-2454358909?

Was wondering whether I should attempt to fix the lint issue, or whether the /devops path should be excluded from that lint condition?

Thanks

**Comment by tamirkamara** [comment]
Hi @jonnyry, 
Yes, this is the source of your issue too. There's a PR in flight that once merged will (hopefully) solve the issue in your PR.

**Comment by jonnyry** [comment]
Ah great thanks :-)
