### ISSUE TITLE
Depreciation of ML Flow and InnerEye bundles.

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#4127]
I propose that we remove the ML Flow and InnerEye workspace services from the repo.

ML Flow functionality is now available in Azure ML: https://learn.microsoft.com/en-us/azure/machine-learning/concept-mlflow?view=azureml-api-2

InnerEye repository is no longer maintained: https://github.com/microsoft/InnerEye-DeepLearning

Neither bundles have been updated in a long while, and we are unsure of functionality. If users require the bundles in the future I suggest maintaining custom bundles.

We will leave this issue for 2 weeks, then look to remove before the next release.

**Comment by Danny-Cooke-CK** [comment]
is it worth instead keeping the bundles there but removing their deployment from the pipelines? just for short term?

**Comment by marrobi** [comment]
> > is it worth instead keeping the bundles there but removing their deployment from the pipelines? just for short term?
> 
> The code will still be available in previous commits

And releases.
