### ISSUE TITLE
Resource processor terraform cannot connect to blob state container

### ISSUE THREAD

**Issue by TonyWildish-BH** [microsoft/AzureTRE#4137]
## Description

We have (had!) a working TRE, with users and workspaces all up and running, until about a week ago. Then, coinciding exactly with our Entra ID P2 license expiring, our TRE broke. Every attempt to create/disable/delete a workspace or workspace service fails with the message "This request is not authorized to perform this operation" (see below).

I'm trying to understand how the loss of license could cause this, or if something else is responsible, and I'm coming up empty-handed. Does anyone have any suggestions?

Extra information, in case useful:
* The P2 license was functional at the time the TRE was deployed.
* We have done nothing to the codebase or configuration that should affect the behaviour in this manner. No changes to the way service principles are created/used, nor to the app registrations, or anything at the Azure level.
* The TRE CLI can still list/show workspaces & services, but has the same error when creating/disabling/deleting anything.

![Image](https://github.com/user-attachments/assets/13d61aaa-4eb3-43f8-8673-d4b944ff7d75)

**Comment by marrobi** [comment]
This doesn't look like a licensing issue.

A search of the error online returns: 

https://stackoverflow.com/questions/77388978/failed-to-get-existing-workspaces-containers-clientlistblobs-code-containern

> The error message you're encountering indicates that the specified container does not exist in the specified storage account. There is no issue with permissions, as being a contributor should be sufficient to upload a file to Azure Blob storage

It's a terraform state issue. Does the tfstate container exist in your mgmt resource group? Has the resource processor msi got access to the account? Any new network restrictions on the storage account?
