### ISSUE TITLE
Does `test-extended` always fail?

### ISSUE THREAD

**Issue by tamirkamara** [microsoft/AzureTRE#4176]
**Describe the bug**

Did anyone see test-extended actually succeed recently?

The process that stops a CI environment after 2 hours of in activity (either commit or comment) is not enough to cover the time it takes to run all tests not to mention if a deploy is also included. I think the first attempt is highly likely to fail (always) which is on its own a waste of time, it might be that following attempts are also likely to fail.

What do you think?

**Comment by tamirkamara** [comment]
I think it's an exception. This run took just under 3 hours.
The clean envs works runs every 2 hours and looks on envs not update the past 2 hours, and so the example run was at risk of being stopped. Are we will to bring the time to 3 hours?

**Comment by marrobi** [comment]
@tim-allen-ck ?

**Comment by tim-allen-ck** [comment]
> [@tim-allen-ck](https://github.com/tim-allen-ck) ?

I'd maybe say change it to 4 hours just to be safe?

**Comment by tamirkamara** [comment]
Even better, so 4 hours TTL and workflow will run every 1 hour which could give 5 hours total under unique conditions.
