### ISSUE TITLE
[Story] Verify minimum set of firewall rules required for Azure ML

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#418]
Story: #350

**Description**
A set of firewall rules that enable Azure ML to function are deployed as part of the Azure ML bundle:

```
URLs:

- graph.windows.net
- ml.azure.com
- login.microsoftonline.com
- aadcdn.msftauth.net
- graph.microsoft.com
- management.azure.com
- viennaglobal.azurecr.io (Azure ML preview features)

Service Tags:

- Storage.`{AzureRegion}`
- AzureContainerRegistry
```

ref:
https://github.com/microsoft/AzureTRE/blob/ab01fa4bd8f8a3834591f41d515c7e000e0b4a51/workspaces/services/azureml/terraform/locals.tf#L10-L11

We do not believe all these are still required. Remove those that are no longer needed and replace those that can be done with [Service Tags](https://docs.microsoft.com/en-us/azure/virtual-network/service-tags-overview) wherever possible.

Tasks:
- [x] #598
- [x] #600
- [x] #651
- [x] #599
- [x] #601
- [x] #838

**Comment by marrobi** [comment]
Do along with #584 ?

**Comment by Lybecker** [comment]
Closing this one calls for a celebration :)
