### ISSUE TITLE
Shared filesystem doesn't support Unix soft links

### ISSUE THREAD

**Issue by TonyWildish-BH** [microsoft/AzureTRE#4180]
The shared filesystem doesn't support soft links in a Unix VM. This greatly restricts the usefulness of the storage.

For example, we've been advising people to install software on the shared storage, so they can avoid customising the actual VMs, so they can destroy and create VMs as needed on a daily basis. A lot of our researchers use `conda`, and installing a basic conda environment will almost inevitably pull in `OpenSSL`, which creates a soft-link between certificate files.

**Steps to reproduce**
1. Create a workspace with shared storage.
2. Create a Linux VM in that workspace, log in to it.
3. Create a conda environment:
`conda create -p /path/to/shared-storage/my/env openssl`

This fails with `[Errno 95] Operation not supported: 'cacert.pem' -> '/shared-storage/conda/predict/ssl/cert.pem`.

Or, simpler:
```
cd /path/to/shared-storage
touch a
ln -s a b
ln: failed to create symbolic link 'b': Permission denied
```

This is only one example, there are lots of tools out there that make use of soft links.

I don't know if there's a filesystem that supports soft links and is still mountable on Windows, one that could be easily implemented in Azure? If not, it would be worth considering supporting a Linux-only shared filesystem in addition to the workspace-wide shared filesystem. This would allow maximum flexibility.

The only workaround we have is to tell people to write installation scripts for the tools they want to install, and to put them on the shared storage. Then, at least, when a new machine is booted, they can run the scripts and reproduce their environment. That's not ideal.

**Comment by jonnyry** [comment]
Have you looked at the NFS mount option for Azure Files?

https://learn.microsoft.com/en-us/azure/storage/files/storage-files-quick-create-use-linux

I don't know what the Windows support is like though.

**Comment by TonyWildish-BH** [comment]
I've not looked into that, no. Can someone with more Windows expertise than me comment on what effect it might have on Windows machines if we switched the mount point to NFS?

One thing that would allow us to do is to start using Unix-level file permissions on the files. I had a request for that from a user just yesterday, asking how multiple users on a project can safely share the shared storage. That comes with its own issues, of course.

**Comment by marrobi** [comment]
I don't believe NFS requires credentials which has caused challenges in the past.  https://learn.microsoft.com/en-us/azure/storage/files/storage-files-how-to-mount-nfs-shares#step-2-configure-network-security

We've been here before, but never found a good cross platform file system. Blobfuse2 on top of Blob is another option, but just for Linux.

**Comment by ljtill** [comment]
We should be able to fix this with `mfsymlinks` and updating the mount ownership, it can be added to the autofs configuration.

Add `uid=1000,gid=1000,mfsymlinks` to the `echo` statement.

https://github.com/microsoft/AzureTRE/blob/cb42226abedf993eb600d92211fd1503508eb292/templates/workspace_services/guacamole/user_resources/guacamole-azure-linuxvm/terraform/vm_config.sh#L126

**Comment by marrobi** [comment]
I've tested this and seems to work great. Thanks @ljtill .
