### ISSUE TITLE
Ability to customise UI header and footer text

### ISSUE THREAD

**Issue by jonnyry** [microsoft/AzureTRE#4201]
As a TRE administrator I would like to be able to customise the header and footer text in the TRE portal via deployment variables so that I can display organisational and environment specific information.

**Comment by tim-allen-ck** [comment]
Would be good to have a configurable logo too.

**Comment by marrobi** [comment]
@jonnyry is this similar to this one? https://github.com/microsoft/AzureTRE/issues/3809

**Comment by marrobi** [comment]
And this one https://github.com/microsoft/AzureTRE/issues/2851

**Comment by jonnyry** [comment]
> And this one [#2851](https://github.com/microsoft/AzureTRE/issues/2851)

It's a duplicate of this one, will close.
