### ISSUE TITLE
Ability to choose size of Sonatype Nexus VM

### ISSUE THREAD

**Issue by tim-p-allen** [microsoft/AzureTRE#4209]
## Description

As a TRE Administrator I want to be able to choose the size of the Nexus VM I want to deploy.
This is either an input field or dropdown list of recommended sizes

## Acceptance criteria

- [ ] VM size is configurable on creation

**Comment by marrobi** [comment]
Think we should offer:

Standard_B2ms
RAM: 8 GB
vCPUs: 2

Standard_B4ms
RAM: 16 GB
vCPUs: 4
D Series

Standard_D2s_v3
RAM: 8 GB
vCPUs: 2

Standard_D4s_v3
RAM: 16 GB
vCPUs: 4

The B series should say "Burstable", and the default should be Standard_B2ms
