### ISSUE TITLE
[Task] Subnet as a parameter for POST /workspace

### ISSUE THREAD

**Issue by Lybecker** [microsoft/AzureTRE#423]
**Description**
Currently the subnet for a new Workspace is hardcoded, but it should be forwarded as a parameter in the API

https://github.com/microsoft/AzureTRE/blob/d80eab210191058597270b85663ee8b4b961ad68/management_api_app/db/repositories/workspaces.py#L116-L121

**Comment by marrobi** [comment]
@Lybecker @sachinkundu this isn't actually a bug, if pass an address space in the payload it works, if no address space, then this is the default.

#52 still stands.
