### ISSUE TITLE
[STORY] Write a DEBUGGING guide

### ISSUE THREAD

**Issue by sachinkundu** [microsoft/AzureTRE#425]
When infrastructure deployment does not work or when the workspace creation fails we should be able find out clearly how to find the problem and possibly a list of known mitigations. The mitigation guide could be the TROUBLESHOOTING guide.

## Acceptance Criteria
- [x] #636
- [x] #637
- [x] #638

**Comment by marrobi** [comment]
@sachinkundu is this still relevant - does it need re writing for the new processor?

**Comment by TessFerrandez** [comment]
@adishachar is someone working on this (since you moved to in progress)? If so I suggest assigning the story to a person so we know who is working on it
