### ISSUE TITLE
Create sample workspace bundle

### ISSUE THREAD

**Issue by christoferlof** [microsoft/AzureTRE#43]
A really simple workspace bundle that is quick to deploy and can be used for development and validate the architecture against.

- [x] Contains a VNET, RG

**Comment by marrobi** [comment]
I've pushed a very basic workspace template to https://github.com/microsoft/AzureTRE/tree/issues/43/basic_templates. I've taken from past project and removed many resources for now.

Includes:
![image](https://user-images.githubusercontent.com/17089773/117064659-5e70b180-ad1e-11eb-9319-4f699fe94ff1.png)

Also includes shared services network, which is peered, and log analytics, as this is a dependency.

- Will need some tidying, what naming conventions are we following?
- As we have no firewall, is no route table.
- No NSGs on shared services

Hopefully a useful (if not perfect) start.
