### ISSUE TITLE
Documentation refined and restructured

### ISSUE THREAD

**Issue by Lybecker** [microsoft/AzureTRE#431]
The Azure TRE needs to have **a better structure** and should have the following content added:

- [x] An overview of what Azure TRE is and what are its benefits
- [x] A guide for cloud administrators to provision
- [x] A guide to provision new workspaces
- [x] A guide for developers to setup the development environment
- [x] A guide where to find what and what is the content in each folder
- [x] Architectural overview with description of each component
- [x] Network diagram with rules, boundaries, ingress/egress

Related task:

- [x] #378 Add instruction to set auth related vars in Quickstart

**Comment by ktakeda1** [comment]
Please could we add higher-level documentation for business decision-makers? Happy to help with those, could include researcher user stories

**Comment by Lybecker** [comment]
Of cause... I will need some help :)

**Comment by Lybecker** [comment]
@ktakeda1 I've added a section for business decision makers here: https://github.com/microsoft/AzureTRE/tree/docs/docs#business-decision-makers

If you don't mind, then either post it here or a PR.
