### ISSUE TITLE
[BUG] Workspaces require the management ACR name to deploy child bundles

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#440]
**Describe the bug**
When deploying a workspace such as `workspaces/azureml_devtestlabs` that requires `acr_name` deployment fails.

Two issues:
1. The API should validate the parameter and say it cannot be found as is marked as required
2. The API should inject this parameter as it is system provided

**Steps to reproduce**
1. Publish  `workspaces/azureml_devtestlabs` bundle
1. Deploy the bundle via the create workspace API with a payload without acr_name:

```
{
  "displayName": "My workspace",
  "description": "workspace for team X",
  "workspaceType": "tre-workspace-azureml-devtestlabs",
  "parameters": {
"address_space": "192.168.11.0/24"},
  "authConfig": {
    "provider": "AAD",
    "data": {
      "app_id": "xxxx"
    }
  }
}
```

**Comment by marrobi** [comment]
#420 should come first.

**Comment by marrobi** [comment]
@sachinkundu assigning to you as part of #420

**Comment by sachinkundu** [comment]
The API should inject this parameter as it is system provided

I'll convert this to another issue. Closing this one.
