### ISSUE TITLE
Lock down public endpoints on service bus

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#441]
## Description

As a Cloud Administrator
I want no public access to the service bus
So that the solution attack surface is reduced

## Acceptance criteria

- [ ] Service bus cannot be connected to other than via the private endpoint
- [ ] Workspaces still deploy successfully

**Comment by jjcollinge** [comment]
AFAIK service bus private endpoint requires premium SKU $$$ - we've made it optional and use the service bus firewall settings to restrict it to our CIDR to work around this for those who need to keep cost down.

**Comment by marrobi** [comment]
Having spoken to a few people, given the usual spend on the solution - from a workspace compute perspective - the additional cost isn't a major issue at present so will stick with premium for now.
