### ISSUE TITLE
Cost Reporting

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#450]
Administrators, PMs and Researchers need to have a clear view on spend and know when hitting budget limits.

## Description

- As a TRE Administrator I want to see the Azure spend for each workspace by custom time frame so that I can understand how much I have spent.

- As a Workspace Owner I want to see the Azure spend for my workspace by custom time frame so I can see how much I have spent

- As a Workspace Owner I want to see the Azure spend for my workspace split by workspace service

- As a Workspace Owner I want to be notified when my workspace has hit its budget limit

**Acceptance Criteria**
- [x] API endpoint can retrieve spend for all workspaces 
- [x] API endpoint can retrieve spend for a single workspace
- [x] API endpoint can returns spend split by workspace service
- [x] API endpoint can return spend over custom time frame

**[Feature Design](https://github.com/microsoft/AzureTRE/issues/450#issuecomment-1114263557)**

## Implementation

- [x] #1901
- [x] #1902
- [x] #2129

**Comment by lenisha** [comment]
would it be possible also to measure how much % workspace used from core shared services and split costs for them ?

**Comment by yorkecp** [comment]
Looking at the API calls I think there needs to be the inclusion of one to return the cost of the costs of the TRE Core. This would be useful from the point of view of service providers so that they can easily see the costs.

In the Workspace related calls we need to make sure we return detailed information about the breakdown as there may need to be subsequent filtering depending on any reserved instance provision within the environment.

**Comment by joalmeid** [comment]
Here it follows a reviewed set on goals and a suggestions for user stories:

## Main Goals:
Provide general cost reporting capability to a TRE instance
TRE Admins, TRE Users/Researchers need to have a clear view on TRE spending costs and on budget limits
TRE Workspace users need to have a clear view on Workspace spending costs and on budget limits
TRE users should be able get alerts around costs and budget limits.

## Draft user stories:

As a TRE Admin, 
I want to be able to query the total azure spend 
So that I understand my overall research costs within this TRE instance
	- TRE admin can access the costs endpoint for all TRE instance
	- TRE admin gets total azure spend discriminated by workspace 
	- TRE admin gets total azure spend discriminated by shared service
	- TRE admin gets total azure spend for TRE Core
	- TRE admin must be able to specify custom time frame, being default calendar month

As a TRE Admin or a Workspace Owner
I want to see the Azure spend for a workspace
so that I can understand how much I have spent.
	- Workspace Owner can access the costs endpoint for a workspace he owns
	- TRE Admin can access the costs endpoint for any workspace
	- TRE Admin/Workspace Owner gets total azure spend discriminated by user resources
	- TRE Admin/Workspace Owner gets total azure spend discriminated by workspace shared services
	- TRE Admin/Workspace Owner must be able to specify custom time frame, being default calendar month

As a TRE Admin/Workspace Owner
I want to set budget limit
so that I get notified with an alert when my workspace has it its budget limit
	- Workspace Owner can set a budget limit for a workspace he owns
	- TRE Admin can set a budget limit for any workspace 
	- TRE Admin/Workspace Owner get a proper alert notification when my workspace has it its budget limit

## Implementation
Besides the provided suggestions, if implemented in the `TRE API`, it will allways depend on the billing info available in Azure REST APIs. At the moment there are few possibilities to investigate:
- https://docs.microsoft.com/en-us/rest/api/cost-management/query/usage#timeframetype
- https://docs.microsoft.com/en-us/rest/api/consumption/usage-details/list#customerusagedetailslist-modern

**Comment by joalmeid** [comment]
## Related
- #417

**Comment by guybartal** [comment]
## Design Considerations

Azure REST API provides two types of Cost APIs, Azure Cost Management API and Azure Consumption API.

The [Azure Cost Management API](https://docs.microsoft.com/en-us/rest/api/cost-management/) provide the ability to explore cost and usage data via multidimensional analysis, where creating customized filters and expressions allow you to answer consumption-related questions for your Azure resources. These APIs are currently available for Azure Enterprise customers.

The [Azure Consumption API](https://docs.microsoft.com/en-us/rest/api/consumption/) give you programmatic access to cost and usage data for your Azure resources. These APIs currently only support Enterprise Enrollments and Web Direct Subscriptions (with a few exceptions). The APIs are continually updated to support other types of Azure subscriptions.
Currently doesn't support internal, CSP and sponsored subscription types.

Azure TRE currently deploys workspace services and user resources inside the same resource group per workspace.

Azure TRE API is aware of TRE entity types (workspace, workspace service, user resource), underling azure resources are visible only for resource processor.

Azure Cost Management API supports querying with different types of filtering, aggregation and grouping capabilities and different timeframes:

* Grouping by - Tag or Dimention (valid values for Dimention: 'ResourceGroup','ResourceGroupName','ResourceLocation','ConsumedService','ResourceType','ResourceId','MeterId','BillingMonth','MeterCategory','MeterSubcategory','Meter','AccountName','DepartmentName','SubscriptionId','SubscriptionName','ServiceName','ServiceTier','EnrollmentAccountName','BillingAccountId','ResourceGuid','BillingPeriod','InvoiceNumber','ChargeType','PublisherType','ReservationId','ReservationName','Frequency','PartNumber','CostAllocationRuleName','MarkupRuleName','PricingModel','BenefitId','BenefitName')

* Filter by - any Tag in array of values or any Dimention (same as above). note: when filtering by Tag, not all Azure Resources are supported in Cost Management (see [list of supported resources](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/tag-support#microsoftmachinelearningservices)).

* Aggregation  - valid values: 'UsageQuantity','PreTaxCost','Cost','CostUSD','PreTaxCostUSD'

* Timeframe - Valid values:  BillingMonthToDate, Custom (from-to dates), MonthToDate, TheLastBillingMonth, TheLastMonth, WeekToDate

## Design Options

|  	| Option 1 	| Option 2 	| Option 3 	| Option 4 	|
|---	|---	|---	|---	|---	|
| Description 	| Group by resource group 	| Group by Workspace / Workspace Service / User Resource Tags 	| Group by Resource IDs 	| Combine option 2 and 3<br>tag resources, fetch resource ids<br>then group by resource ids 	|
| Pros 	| Easy to implement 	| Decouple TRE modules 	| Supported by all resource types 	| * Decouple TRE modules<br>* Supports all resource types 	|
| Cons 	| * Supports only workspace level<br>* Couple with resource processor internal implementation 	| * Not all azure resources supports tagging in Azure Cost management API<br>* Complex - need to add tags for every resource 	| * very complex - need to return resource ID from resoruce processor and store in cosmos 	| * Complex - need to add tags for every resource 	|

Option 4 is the prefered option.

## Tagging resources upon creation

Cost report API will rely on Azure tagging to be able to generate cost report for core, shared, workspace, workspace services and user resources.
When creating each one of the above we need to make sure that underling Azure resources are taged with the corresponding tag:

* Core Services - each core service will have a tag named "tre_core_service" with a value of the TRE ID to descriminate all core services per TRE instance
* Shared Services - each core service will have a tag named "shared_service_id" with a value of the shared service id to descriminate each and every shared service
* Workspace Services - each workspace service will have:
  * "workspace_id" with a value of the workspace id to descriminate each resource by workspace level
  * "workspace_service_id" with a value of the workspace service id to descriminate each resource by workspace service level
* User Resource - each user resource will have the following tags:
  * "workspace_id" with a value of the workspace id to descriminate each resource by workspace level
  * "workspace_service_id" with a value of the workspace service id to descriminate each resource by workspace service level
  * "user_resource_id" with a value of the user resource id to descriminate each resource by user resource level


## TRE Admin Cost Reporting - overall cost report
### Description
Get overall cost report for TRE instance (core services), per shared services and per workspace

### Authorization
Only TRE Admin can call this url, others will get unauthorized

### Input
POST /costs
Payload:
```json
{
    "timeframe":"BillingMonthToDate|Custom|MonthToDate|TheLastBillingMonth|TheLastMonth|WeekToDate",
    "timePeriod": {"from":"MM/DD/YYYY","to":"MM/DD/YYYY"}, // only for "Custom" timeframe, up to 1 year timespan
    "granularity":"Daily|None" // None will summarize for the timefame
}
```

### Output
```json
{
    "coreServices": [
        {"date":"", "cost":"", "currency":""} // date will return only for Daily granularity
        ],
    "sharedServices": [ {
        "sharedServiceId":"",
        "costs": [
            {"date":"", "cost":"", "currency":""} // date will return only for Daily granularity
            ]
        }],
    "workspaces": [ {
        "workspaceId":"", 
        "costs":[
            {"date":"", "cost":"", "currency":""} // date will return only for Daily granularity
            ]}
        ]
}
```

### sequence diagram

![image](https://user-images.githubusercontent.com/3179107/162829915-6a38c206-cc6f-4a70-be9d-071683bf9ae9.png)

### Get resource ids by tag

```
https://management.azure.com/subscriptions/{{subscriptionId}}/resources?api-version=2021-04-01&$filter=tagName eq 'workspace_id' and tagValue eq 'e67c8bf9-442f-406b-b40c-e482f190c1f1'
```

### Cost management API payload

```
POST https://management.azure.com/subscriptions/{{subscriptionId}}/providers/Microsoft.CostManagement/query?api-version=2021-10-01&$expand=properties/data
```

Payload:
```json
{
    "type": "Usage",
    "timeframe": "Custom", // can be also BillingMonthToDate|MonthToDate|TheLastBillingMonth|TheLastMonth|WeekToDate according to input
    "timePeriod": {
        "from": "MM/DD/YYYY",
        "to": "MM/DD/YYYY"
    },
    "dataset": {
        "granularity": "Daily",
        "aggregation": {
            "totalCost": {
                "name": "Cost",
                "function": "Sum"
            }
        },
        "filter": {
            "dimensions": {
                "name": "ResourceId",
                "operator": "In",
                "values": [
                    /// List of Azure resource ids as strings
                ]
            }
        }
    }
}

```

Output example:

```json
{
    "id": "subscriptions/xxxx/providers/Microsoft.CostManagement/query/yyyy",
    "name": "yyy",
    "type": "Microsoft.CostManagement/query",
    "location": null,
    "sku": null,
    "eTag": null,
    "properties": {
        "nextLink": null,
        "columns": [
            {
                "name": "Cost",
                "type": "Number"
            },
            {
                "name": "UsageDate",
                "type": "Number"
            },
            {
                "name": "Currency",
                "type": "String"
            }
        ],
        "rows": [
            [
                0.00032930107526881738,
                20211208,
                "USD"
            ],
            [
                0.0011290322580645167,
                20211209,
                "USD"
            ],
            [
                0.0011290322580645167,
                20211210,
                "USD"
            ],
        ]
    }
}
```

## TRE Admin / Workspace Owner Cost Reporting - specific workspace cost report
### Description
Get overall cost report for a specific workspace

### Authorization
Only TRE Admin and the workspace owner can call this url, others will get unauthorized

### Input
POST /workspace/{workspace_id}/costs
Payload:
```json
{
    "timeframe":"BillingMonthToDate|Custom|MonthToDate|TheLastBillingMonth|TheLastMonth|WeekToDate",
    "timePeriod": {"from":"MM/DD/YYYY","to":"MM/DD/YYYY"}, // only for "Custom" timeframe, up to 1 year timespan
    "granularity":"Daily|None" // None will summarize for the timefame
}
```

### Output
```json
{
    "sharedServices": [ {
      "sharedServiceId":"",
      "costs": [
          {"date":"", "cost":"", "currency":""} // date will return only for Daily granularity
          ]
      }],
    "workspace": {
      "workspaceId":"", 
      "workspaceServices":[{
        "workspaceServiceId":"",
          "costs":[{"date":"", "cost":"", "currency":""}], // date will return only for Daily granularity
          "userResources":[{
            "userResourceId": "",
            "costs":[{"date":"", "cost":"", "currency":""}], // date will return only for Daily granularity
          }]
        }]
      }
}
```

### Sequence diagram

![image](https://user-images.githubusercontent.com/3179107/162830050-ab671a53-18d0-4709-94fc-3ca8d5a3542c.png)

**Comment by eladiw** [comment]
@guybartal  does option 3 means you get a cost report per resource? is that what group by resource id means?
and option 3 means the same but instead of asking for the cost of these resource ids, you ask for the tags?

if so, I think that getting the resource cost is too fine grained, I think that the ws service or ws user resource level is better.

**Comment by guybartal** [comment]
> @guybartal does option 3 means you get a cost report per resource? is that what group by resource id means? and option 3 means the same but instead of asking for the cost of these resource ids, you ask for the tags?
> 
> if so, I think that getting the resource cost is too fine grained, I think that the ws service or ws user resource level is better.

Thanks for rasing this @eladiw, I changed "Group by" to "Filter By", it was a typo. I meant that the cost will be daily / total for a period and get filtered by a set of resources, it doen't make sense to group by a resource.

**Comment by eladiw** [comment]
looks good. I like the fact you dont assume to keep track of the resource ids, and ask them from the management api

**Comment by guybartal** [comment]
## Status
- [ ] Draft
- [x] Proposed
- [ ] Accepted
- [ ] Deprecated

## Design Considerations

Azure REST API provides two types of Cost APIs, Azure Cost Management API and Azure Consumption API.

The [Azure Cost Management API](https://docs.microsoft.com/en-us/rest/api/cost-management/) provide the ability to explore cost and usage data via multidimensional analysis, where creating customized filters and expressions allow you to answer consumption-related questions for your Azure resources. These APIs are currently available for Azure Enterprise customers.

The [Azure Consumption API](https://docs.microsoft.com/en-us/rest/api/consumption/) give you programmatic access to cost and usage data for your Azure resources. These APIs currently only support Enterprise Enrollments and Web Direct Subscriptions (with a few exceptions). The APIs are continually updated to support other types of Azure subscriptions.
Currently doesn't support internal, CSP and sponsored subscription types.

Azure TRE currently deploys workspace services and user resources inside the same resource group per workspace.

Azure TRE API is aware of TRE entity types (workspace, workspace service, user resource), underling azure resources are visible only for resource processor.

Azure Cost Management API supports querying with different types of filtering, aggregation and grouping capabilities and different timeframes:

* Grouping by - Tag or Dimention (valid values for Dimention: 'ResourceGroup','ResourceGroupName','ResourceLocation','ConsumedService','ResourceType','ResourceId','MeterId','BillingMonth','MeterCategory','MeterSubcategory','Meter','AccountName','DepartmentName','SubscriptionId','SubscriptionName','ServiceName','ServiceTier','EnrollmentAccountName','BillingAccountId','ResourceGuid','BillingPeriod','InvoiceNumber','ChargeType','PublisherType','ReservationId','ReservationName','Frequency','PartNumber','CostAllocationRuleName','MarkupRuleName','PricingModel','BenefitId','BenefitName')

* Filter by - any Tag in array of values or any Dimention (same as above). note: when filtering by Tag, not all Azure Resources are supported in Cost Management (see [list of supported resources](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/tag-support#microsoftmachinelearningservices)).

* Aggregation  - valid values: 'UsageQuantity','PreTaxCost','Cost','CostUSD','PreTaxCostUSD'

* Timeframe - Valid values:  BillingMonthToDate, Custom (from-to dates), MonthToDate, TheLastBillingMonth, TheLastMonth, WeekToDate

Cost Management API requiers "Billing Reader" Role Assignment to be called.

Consumption API (Usage Details)
- doesn't supports cost aggregation but only list of usage
- doesn't supports start and end date but only per scope of billing
- filtering by tags and resource groups will get deprecated.

## Design Options

|  	| Option 1 	| Option 2 	| Option 3 	|
|---	|---	|---	|---	|
| Description 	| Group by resource group 	| Group by Workspace / Workspace Service / User Resource Tags 	| Filter by Resource IDs 	|
| Pros 	| Easy to implement 	| Decouple TRE modules 	| Supported by all resource types 	|
| Cons 	| * Supports only workspace level<br>* Couple with resource processor internal implementation 	| * Not all azure resources supports tagging in Azure Cost management API<br>* Complex - need to add tags for every resource, developer might miss tags when authoring new template 	| * very complex - need to return resource ID from resoruce processor and store in cosmos 	|

Option 2 is the prefered option.

## Tagging resources upon creation

Cost report API will rely on Azure tagging to be able to generate cost report for core, shared, workspace, workspace services and user resources.
When creating each one of the above we need to make sure that underling Azure resources are taged with the corresponding tag:

* Core Services - each core service will have a tag named "tre_core_service" with a value of the TRE ID to descriminate all core services per TRE instance
* Shared Services - each core service will have a tag named "shared_service_id" with a value of the shared service id to descriminate each and every shared service
* Workspace Services - each workspace service will have:
  * "workspace_id" with a value of the workspace id to descriminate each resource by workspace level
  * "workspace_service_id" with a value of the workspace service id to descriminate each resource by workspace service level
* User Resource - each user resource will have the following tags:
  * "workspace_id" with a value of the workspace id to descriminate each resource by workspace level
  * "workspace_service_id" with a value of the workspace service id to descriminate each resource by workspace service level
  * "user_resource_id" with a value of the user resource id to descriminate each resource by user resource level


## TRE Admin Cost Reporting - overall cost report
### Description
Get overall cost report for TRE instance (core services), per shared services and per workspace

### Authorization
Only TRE Admin can call this url, others will get unauthorized

### Input
GET /costs?from=MM/DD/YYYY&to=MM/DD/YYYY

Parameters:
* from, to - time period, up to 1 year timespan


### Output
```json
{
    "coreServices": [
        {"date":"", "cost":"", "currency":""} 
        ],
    "sharedServices": [ {
        "id":"shared service id",
        "name":"shared service name",
        "costs": [
            {"date":"", "cost":"", "currency":""} 
            ]
        }],
    "workspaces": [ {
        "id": "workspace id",
        "name": "workspace name", 
        "costs":[
            {"date":"", "cost":"", "currency":""} 
            ]}
        ]
}

```

### sequence diagram

![image](https://user-images.githubusercontent.com/3179107/166151856-469897ff-ea26-42ee-9e9f-9d635e3d3d46.png)



### Cost management API payload

API will return a flat result of all cost with every tag combination which exists on the filtered resources by the provided tag, meaning that a resource which has tre_id, tre_workspace_id, and tre_workspace_service_id will get be summerized in all three tags.

```
@SUBSCRIPTION = FILL_YOUR_SUBSCRIPTION_ID

@COST_API_URI = https://management.azure.com/subscriptions/{{SUBSCRIPTION}}/providers/Microsoft.CostManagement
@COST_API_VERSION = 2021-10-01
@TRE_ID = FILL_TRE_ID
@TIME_FROM = MM/DD/YYYY
@TIME_TO = MM/DD/YYYY

POST {{COST_API_URI}}/query?api-version={{COST_API_VERSION}}&$expand=properties/data
Authorization: {{$aadToken $aadV2TenantId}}
Content-Type: application/json
```

Payload:
```json
{
    "type": "Usage",
    "timeframe": "Custom", // can be also BillingMonthToDate|MonthToDate|TheLastBillingMonth|TheLastMonth|WeekToDate according to input
    "timePeriod": {
        "from": "{{TIME_FROM}}",
        "to": "{{TIME_TO}}"
    },
    "dataset": {
        "granularity": "Daily", // can be also "None" for total costs
        "aggregation": {
            "totalCost": {
                "name": "Cost",
                "function": "Sum"
            }
        },
        "filter": {
            "tags": {
            "name": "tre_id",
            "operator": "In",
            "values" : [
                "{{TRE_ID}}",
                ]
            }
        },
        "grouping": [
            {
                "type": "Tag",
            }
        ]
    }
}

```

Output example:

```json
{
  "id": "subscriptions/xxx/providers/Microsoft.CostManagement/query/xxx",
  "name": "e79b86b0-cc54-494c-9d8f-30b66e03aaff",
  "type": "Microsoft.CostManagement/query",
  "location": null,
  "sku": null,
  "eTag": null,
  "properties": {
    "nextLink": null,
    "columns": [
      {
        "name": "Cost",
        "type": "Number"
      },
      {
        "name": "UsageDate",
        "type": "Number"
      },
      {
        "name": "Tag",
        "type": "String"
      },
      {
        "name": "Currency",
        "type": "String"
      }
    ],
    "rows": [
      [
        0.000580800064177395,
        20220406,
        "\"tre_id\":\"yyy\"",
        "GBP"
      ],
      [
        2.1554252199539997E-05,
        20220407,
        "\"tre_id\":\"yyy\"",
        "GBP"
      ],
      [
        0.0,
        20220408,
        "\"tre_id\":\"yyy\"",
        "GBP"
      ],
      [
        0.0,
        20220409,
        "\"tre_id\":\"yyy\"",
        "GBP"
      ],
      [
        0.0,
        20220410,
        "\"tre_id\":\"yyy\"",
        "GBP"
      ]
    ]
  }
}
```

## TRE Admin / Workspace Owner Cost Reporting - specific workspace cost report
### Description
Get overall cost report for a specific workspace

### Authorization
Only TRE Admin and the workspace owner can call this url, others will get unauthorized

### Input
GET /workspace/{workspace_id}/costs?from=MM/DD/YYYY&to=MM/DD/YYYY

Parameters:
* from, to - time period, up to 1 year timespan

### Output
```json
{
    "sharedServices": [ {
      "sharedServiceId":"",
      "costs": [
          {"date":"", "cost":"", "currency":""}
          ]
      }],
    "workspace": {
      "id": "workspace id",
      "name": "workspace name", 
      "workspaceServices":[{
        "id": "workspace service id",
        "name": "workspace service name", 
          "costs":[{"date":"", "cost":"", "currency":""}], 
          "userResources":[{
            "id": "user resource id",
            "name": "user resource name", 
            "costs":[{"date":"", "cost":"", "currency":""}], 
          }]
        }]
      }
}
```

### Sequence diagram

![image](https://user-images.githubusercontent.com/3179107/166151876-21a926e4-875e-4e23-a8f5-05b6e0b25d42.png)

**Comment by guybartal** [comment]
@eladiw @tamirkamara @joalmeid @marrobi can you please approve the design?

**Comment by marrobi** [comment]
@guybartal while adding tags, can everything be tagged with `tre_id` in the instance where there are multiple TREs this would be useful when filtering resources etc. 

Also can we use the format `tre_workspace_id` and `tre_workspace_service_id`, to distinguish that these tags are the TRE tags. In some cases there are many, many tags, so if they are grouped together alphabetically makes life easier when working in the portal.

Also not necessarily part of v1, but is there any way we can check that resources that have just been deployed have appropriate tags? Maybe check all resources deployed by the resource processor in the RG have a `tre_id` and at least a `tre_shared_service` or `tre_workspace_id` tag?

Thanks.

**Comment by guybartal** [comment]
> @guybartal while adding tags, can everything be tagged with `tre_id` in the instance where there are multiple TREs this would be useful when filtering resources etc.
> 
> Also can we use the format `tre_workspace_id` and `tre_workspace_service_id`, to distinguish that these tags are the TRE tags. In some cases there are many, many tags, so if they are grouped together alphabetically makes life easier when working in the portal.
> 
> Also not necessarily part of v1, but is there any way we can check that resources that have just been deployed have appropriate tags? Maybe check all resources deployed by the resource processor in the RG have a `tre_id` and at least a `tre_shared_service` or `tre_workspace_id` tag?
> 
> Thanks.

Thanks for commenting on this @marrobi, acctually I was counting on this tag for better perfomance upon calling the Cost Management API... I've updated the design,

**Comment by guybartal** [comment]
@joalmeid @marrobi @eladiw @tamirkamara 
design updated to reflect cache + gralularity options (daily + totals) between custom time frame

**Comment by tamirkamara** [comment]
@guybartal @joalmeid can we close this feature is it's done?
