### ISSUE TITLE
[BUG] Fails to access Key Vault when running make tre-deploy

### ISSUE THREAD

**Issue by limorl** [microsoft/AzureTRE#470]
**Describe the bug**
Fails to access Key Vault when running make tre-deploy

**Steps to reproduce**

1. Follow the (/docs/manual-deployment-md) 
2. TRE deployment fails on accessing keyvauls
3. See the following error:
     
![image](https://user-images.githubusercontent.com/1086572/125792302-6639dce9-6e8b-4df2-a8e2-b29cfb2a0409.png)

**Comment by marrobi** [comment]
I've tried to reproduce this, both using azure cli credentials and SP, and failed.

Wonder if it's linked to dev containers on a mac? @eladiw @limorl @tamirkamara all hit this and all on macs?

**Comment by marrobi** [comment]
This occurs when using a mac  connected tot he MS corp network. Closing as not specific to this project.
