### ISSUE TITLE
[Story] Azure Administrator can manage updates of TRE Instance

### ISSUE THREAD

**Issue by adishachar** [microsoft/AzureTRE#485]
## Description

**As an Azure Administrator I would like to** be able to update the deployed infrastructure and code within an Azure TRE instance, either manually or using CI/CD.

**Acceptance Criteria:**

- [ ] The Azure Administrator is able to manage updates to deployed infrastructure and code within an Azure  TRE instance. 

Tasks
- [ ] Explore and prepare proposal of updates that can be done on a TRE instance.
- [ ] Define mechanism for updating template version of deployed workspaces, workspaces services and user resources

**Comment by TessFerrandez** [comment]
@adishachar can we be a bit more specific here, what does it mean to manage updates to deployed infrastructure? where, how and why?

**Comment by marrobi** [comment]
Merging into #141
