### ISSUE TITLE
Improve  resource processor VMSS update behavior 

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#512]
**Description**
If the custom data for the resource processor VMSS is updated - for example new docker image. The instances need reimaging before the custom data and docker image is updated ( https://docs.microsoft.com/en-us/azure/virtual-machines/custom-data#can-i-update-custom-data-after-the-vm-has-been-created )

This behavior should be documented and the pipeline reimage existing VMSS instances using CLI.

https://docs.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest#az_vmss_reimage

**Comment by tamirkamara** [comment]
@marrobi I believe the VMSS is re-created every make tre-deploy run because of the cloud-init

**Comment by marrobi** [comment]
@tamirkamara need to validate this - what I saw was happening was the VMMS properties would get updated by TF but not the instance images. 

Need to look at the TF logs and see what TF is updating/recreating. We should try to avoid recreate as this will fail any in progress deployment jobs.

**Comment by tompaana** [comment]
I went to inspect the images (Bastion -> docker exec ... /bin/bash) to verify a change ~45 minutes after the merged PR had been through deploy/test cycle and noticed that the image running didn't contain the changes. Unfortunately, I didn't take note of the image tag that was running to see just how old the image was.

**Comment by ross-p-smith** [comment]
My code has just hit main where the RP version is 1.1.13. The main build is failing and when I go onto the bastion and check the RP it is 

`a2e443d901ae   maintre1mgmt.azurecr.io/microsoft/azuretre/resource-processor-vm-porter:0.1.12   "./run.sh"   2 days ago   Up 2 days `

I thought this should have re-imaged?
