### ISSUE TITLE
Define subnets address space

### ISSUE THREAD

**Issue by christoferlof** [microsoft/AzureTRE#52]
As a TRE Administrator 
I want to define the size of an address space used by the workspace virtual network
So that I do not create a workspace with too few IP addresses.

Subnets should have sensible defaults given the number of IP-addresses needed. For workspaces we should consider the user being able to choose from a set of defaults like "small", "medium", "large".

_Originally posted by @deniscep in https://github.com/microsoft/AzureTRE/pull/49#discussion_r628229886_

## Acceptance criteria

- [x] Define and document the existing defaults (might need appropriate defaults selecting - are they too small?)
- [x] ~~Implement defaults in existing TF templates~~ (see comments)
- [x] Available address pool available to be assigned to workspaces pre defined within TRE configuration.
- [x] #1254
- [x] A new workspace is created with the next available, address range of the specified size.
- [x] If a size is set to "custom", the "addressSpace" parameter is read, validated as being available and used to deploy the TRE.
- [x] #771 
- [x] #772 
- [x] #773 
- [x] #804

**Comment by christoferlof** [comment]
To be split into two.

**Comment by marrobi** [comment]
Potentially useful library:

https://github.com/netaddr/netaddr: A
A network address manipulation library for Python

- iterating, slicing, sorting, summarizing and classifying IP networks
- supernetting and subnetting

**Comment by marrobi** [comment]
Also interesting: https://stackoverflow.com/questions/62780989/ipv4network-in-python-calculating-next-minimum-subnet-of-different-size

**Comment by ross-p-smith** [comment]
Quick comment. I don't think it is worth putting the CORE_ADDRESS_SPACE and TRE_ADDRESS_SPACE as defaults in Terraform as these are needed as ENV vars when you run the tests. Therefore, I think it will be problematic changing them in 2 places.
