### ISSUE TITLE
Researcher should only have network access resources within my current workspace and ...

### ISSUE THREAD

**Issue by christoferlof** [microsoft/AzureTRE#53]
As a Researcher I should ONLY have network access to resources within my current workspace,  shared services, and whitelisted internet locations
So that I cannot upload data outside of the workspace virtual network.

* Modify current TF templates to include the default NSG rules. See original conversation in PR #49 

- [x] Default route directs Internet traffic through the Firewall
- [x] NSG on workspace services subnet allows traffic to shared services
- [x] NSG on workspace services subnet blocks outbound access to all other subnets

_Originally posted by @deniscep in https://github.com/microsoft/AzureTRE/pull/49#discussion_r628238286_

**Comment by marrobi** [comment]
Network security groups should exist that prohibit all traffic in and out of each subnet, other than that which is necessary for the TRE to function. 

Workspace users should ONLY have network access resources within their current workspace, to shared services, and whitelisted internet locations.

**Comment by christoferlof** [comment]
@marrobi @deniscep Since #85 is merged, please verify the acceptance criteria on this one and if fulfilled, please close.
