### ISSUE TITLE
[Story] Azure Admin - TRE journey - documentation

### ISSUE THREAD

**Issue by adishachar** [microsoft/AzureTRE#534]
## Description

As an Azure Administrator
I want to have TRE functionality and procedures that are the responsibility of the Azure Administrator documented
So that I can follow the processes to deploy, manage and observe TRE instances.

## Acceptance criteria
Azure Administrator should be able to:
1. Deploy TRE Instance.
    a. manually, from local machine (with Dev Container - but also ideally on local machine with pre requisites installed (TF, Docker, Porter)
    b. Using CI/CD (GitHub actions).
2. Publish template bundles to Azure Container Registry (For registration the API requires TRE Administrator rights)
3. Perform troubleshooting of failed resource deployment operations on the TRE instance
4. Observe and manage  TRE instance, either using TRE specific mechanisms or using the Azure Portal
    a. Monitor resources - quotas, cpu/memory (dashboard as part of the solution?)
    b. Create alerts (use alerts provided as part of the solution?)
    d. Backup and restore core TRE data and resources.
5. Create App Registrations for TRE API, UI and workspaces.

**Comment by christoferlof** [comment]
1 - need to revive the quickstart - create issue to write new.
2 - review [workspace authoring guide](https://github.com/microsoft/AzureTRE/blob/develop/docs/authoring-workspace-templates.md)
3 - For now, considered done. See [ops debugging & troubleshooting
](https://github.com/microsoft/AzureTRE/blob/develop/docs/ops_debugging_troubleshooting.md)4 - is handled by  #484 , #485, #486

**Comment by christoferlof** [comment]
1. #698 created. Closing this
