### ISSUE TITLE
[Story] Configure Resource Processor to use Azure storage for Porter remote state

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#536]
## Description

As a TRE developer
I want to be able to access the state of previous porter deployments
So that I can uninstall bundles.

## Acceptance criteria

- [x] [Porter Azure plugin](https://porter.sh/plugins/azure/) installed for Resource Processor
- [x] Porter Azure plugin configured: Runner uses MGMT_STORAGE_ACCOUNT_NAME for porter state - https://github.com/getporter/azure-plugins (azure cli and MSI)
- [x] Functionality documented in Resource Processor README

**Comment by christoferlof** [comment]
Currently Porter state is persisted on the VM within the scaleset. Will be lost.

**Comment by tamirkamara** [comment]
@marrobi I think we talked about this plugin being very "fresh"... do you have an opinion about using an azure share instead?

**Comment by marrobi** [comment]
@tamirkamara  The challenge with shares is that we are having to deploy bundles within bundles as Porter cannot pass parameters into dependencies:

https://github.com/getporter/porter/issues/990

We also need to be able to uninstall these dependent bundles.

This means mounting the share to the the bundle, which I'm not sure is possible, I was planning to use the blob storage plugin once sorted at the base level (although haven't tested this). 

Ideally the bundle dependencies would work and then it wouldn't matter.
