### ISSUE TITLE
Document the hierarchy and terminology of workspaces/workspace-services/user-resources

### ISSUE THREAD

**Issue by TessFerrandez** [microsoft/AzureTRE#546]
## Description

As a TRE developer (and TRE user)
I want to understand the terminology and the structure of a workspace and the parts within it
So that I can make the right choices when developing or selecting services/resources etc.

## Acceptance critiera

- [x] Documentation on what a workspace, how to register a template and how to instantiate it 
- [x] Documentation on what a workspace service is, how to register a template, and how to instantiate it
- [x] Documentation on what a user-resource is, how to register a template and how to instantiate it
- [x] Update authoring documentation to cover the above concepts
- [x] [Existing concepts doc](https://github.com/microsoft/AzureTRE/blob/develop/docs/concepts.md) updated to reflect reality

**Comment by TessFerrandez** [comment]
@marrobi @adishachar - FYI

**Comment by christoferlof** [comment]
Please update existing docs where available
* [Concepts](https://github.com/microsoft/AzureTRE/blob/develop/docs/concepts.md)
* [Authoring workspace templates](https://github.com/microsoft/AzureTRE/blob/develop/docs/authoring-workspace-templates.md)
* [Registering workspace templates](https://github.com/microsoft/AzureTRE/blob/develop/docs/registering-workspace-templates.md)

**Comment by christoferlof** [comment]
In #471, clarification on creating and registering workspace templates is also requested. Perhaps close #471 also?

**Comment by adishachar** [comment]
> In #471, clarification on creating and registering workspace templates is also requested. Perhaps close #471 also?
@christoferlof   #471 is not about documentation of registering workspaces templates etc, but the intention was for the documentation of the Service Integrator persona journey - what actions this persona can do and how. 
This issue was created as reminder to add this aspect of documentation, when we tried to validate the doc and realized it was written mainly for a TRE developer.
