### ISSUE TITLE
[Story] Implement GET /api/workspace-service-templates

### ISSUE THREAD

**Issue by TessFerrandez** [microsoft/AzureTRE#557]
## Description

As a TRE Admin
I want to list all workspace-service-templates available to add to a workspace
So that I can create workspace-services

## Acceptance critiera

- [x] Only available for admin
- [x] Returns name, description for the current version of all workspace-service-templates (see implementation for workspace-templates)

## Tasks

- [x] #589 
- [x] #590

**Comment by TessFerrandez** [comment]
@marrobi please check if this looks ok - added to backlog per yesterdays discussion

**Comment by marrobi** [comment]
@TessFerrandez do you mean "So that I can create workspace-services"
