### ISSUE TITLE
[Story] Implement credentials retrival in Guacamole Auth extension

### ISSUE THREAD

**Issue by adishachar** [microsoft/AzureTRE#561]
## Description

As a TRE extension developer
I want the Guacamole auth extension to be able to fetch the user credentials for a specific vm from kv
So that the credentials will be properly stored and retrieved only when needed and authorized

## Acceptance criteria

- [x] #630
- [x] #631 
- [x] #576 
- [x] #632 
- [x] #733
- [x] #721
- [x] #751
- [x] #705

**Comment by TessFerrandez** [comment]
@adishachar is someone actively working on this? can we assign the story to that person if so (so we know who is working on what)
