### ISSUE TITLE
Research and implement database migrations

### ISSUE THREAD

**Issue by TessFerrandez** [microsoft/AzureTRE#563]
## Description

As a TRE API developer
I want to be able to write database migrations
So that I can update my database models without manually having to update all the documents in cosmos

## Acceptance critiera

- [x] Understand and document how to create atomic migrations for cosmos
- [ ] #1824
- [ ] Don't run migrations that have already been executed.
- [ ] Add db migration step to the build so that we can guarantee that they are run every time

**Comment by ross-p-smith** [comment]
Fixed as #1726
