### ISSUE TITLE
[Story] Add API functionality to delete workspace-service

### ISSUE THREAD

**Issue by adishachar** [microsoft/AzureTRE#569]
## Description

As a TRE owner
I want to be able to delete a workspace
So that the resources are no longer deployed to Azure

TRE owner can delete workspace-service that has already been disabled -- DELETE  /api/workspaces/{workspace_id}/workspace-services

## Acceptance criteria

- [x]  If attempting to delete an enabled workspace-service - this should return an error "workspace-service must be disabled before being deleted"

- [x]  If attempting to delete a workspace-service with "non-deleted" user-resources - this should return an error stating that you need to delete the user-resources first

When deleting a workspace-service:
-  (Cloud resources are removed) - See comment below.
-  Status changes to deleted
-  Workspace-service is not available through -- GET /api/workspaces/ or GET /api/workspaces/{workspace_id}/workspace-services

**Comment by christoferlof** [comment]
@Lybecker @marrobi , I believe this needs a bit more thought before assigning for implementation

**Comment by christoferlof** [comment]
Removing cloud resources will require the bundle to implement the uninstall action. Additional stories to plan this work to be created, bundle by bundle as needed.
