### ISSUE TITLE
[Story] Add API functionality to delete user-resource

### ISSUE THREAD

**Issue by adishachar** [microsoft/AzureTRE#570]
## Description

As a TRE owner / researcher / user
I want to be able to delete a user resource associated to a workspace-service
So that all Azure resources of this user-resources are no longer deployed to Azure.

## Acceptance criteria

- [ ] TRE owner / researcher can delete user-resource that was been disabled --DELETE 
 /api/workspaces/{workspace_id}/workspace-services/{service_id}/user-resources
- [ ] if attempting to delete enabled user-resource this should return an error stating user-resource must be disabled before being deleted.
- [ ] When deleting a user-resource - 
- ~~Cloud resources are removed~~
- user-resources status changes to deleted
- user-resource is not available through -- GET  /api/workspaces/{workspace_id}/workspace-services/{service_id}/user-resources

**Comment by christoferlof** [comment]
Removal of resources to be implemented separately in each bundle using the uninstall action
