### ISSUE TITLE
Create initial scripts and docs for deploying the TRE solution into an existing Azure subscription

### ISSUE THREAD

**Issue by christoferlof** [microsoft/AzureTRE#58]
## User story

As a cloud administrator
I need basic instructions on how to clone the repo and how to install the core TRE pieces into my subscription
So that I can participate in the test cycle from the beginning.

## Acceptance critiera

- [x] Initial instructions on how to install the TRE solution, created in the docs section of the repo
- [x] Initial scripts for installing the TRE into an existing azure subscription created and available within the repo
- [x] Cloud admin can follow the instructions and use the scripts to repeatedly install the baseline TRE solution

**Comment by marrobi** [comment]
@christoferlof let me know if you think what is merged is sufficient for now.
