### ISSUE TITLE
Create Windows DSVM user resource template for Guacamole Workspace Service

### ISSUE THREAD

**Issue by eladiw** [microsoft/AzureTRE#582]
As a researcher
I want to deploy a Windows Data Science Virtual Machine
So I  that tools are already installed. 

**Description**
Currently we deploy a win 10 machine. We would like to also / instead deploy a DSVM machine

**Comment by jjgriff93** [comment]
Currently the Windows DSVM images are failing to deploy - when both provisioned via the CLI, through the AzureTRE resource processor, and through the Azure portal. They time out and end up in a failed state, so unable to log on to the machine. Will discuss workarounds in parking lot - either changing to deploy Linux, or creating our own post deploy scripts
