### ISSUE TITLE
[BUG] Failed workspace deployment: only one positional argument may be specified, the installation name, but multiple were received

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#585]
**Describe the bug**
Workspace deployment failed with:

```
only one positional argument may be specified, the installation name, but multiple were received [mrtre17-9c1d X secure project]
```

**Steps to reproduce**

Deployed a workspace with following values:

```
"azure_location":"westeurope",
"workspace_id":"9c1d",
"tre_id":"mrtre17",
"address_space":"192.168.10.0/24",
"display_name":"Project X",
"description":"Very secure project"
```

**Comment by marrobi** [comment]
This seems to be caused by parameter values not being enclosed with quotations in the porter command.

**Comment by tamirkamara** [comment]
I saw the same and believe it's about the description having multiple words - one word works just fine.
