### ISSUE TITLE
Document initial workspace bundle authoring experience

### ISSUE THREAD

**Issue by christoferlof** [microsoft/AzureTRE#59]
## User story

As a TRE service integrator
I want to know the rules and conventions to create a new workspace bundle with a simple workspace service
so that I can create a new bundle

## Acceptance criteria

Initial documentation on how to author a workspace bundle.

- [x] How you create the bundle
- [x] How you pass and store input parameters (static, dynamic [ex. ip range], secrets)
- [x] What interfaces the bundle needs to implement
- [ ] Where the output is going, and what output is expected
- [x] How templates and bundles are updated and versioned
- [x] How is the workspace bundle added to the registry on private connection. (Possible we can't use this due to how ACI and App Service work with registries on private networks)
- [x] Where are the workspace templates and bundles stored?

**Comment by tompaana** [comment]
Split workspace services documentation into its own story: #128

**Comment by christoferlof** [comment]
We will handle outputs in future iterations of the doc. Closing this issue.
