### ISSUE TITLE
[Task] Create a proposal for automatic App registration for story #220

### ISSUE THREAD

**Issue by Lybecker** [microsoft/AzureTRE#597]
**Description**
Describe the solution in story #220:

- Describe how should the app registration be automated
- Should the app registration happen at in the Bundle or should it be handled at TRE level
- Should it be configurable how app registration should be performed? Automatic/manual (as some orgs might not allow AD changes by TRE)

**Comment by Lybecker** [comment]
@marrobi, @TessFerrandez, @sachinkundu, @christoferlof I've updated the original story #220 with my view on how this should be implemented. Please review

**Comment by marrobi** [comment]
Ok, will add some comments/questions, maybe later today.
