### ISSUE TITLE
[BUG] Wrong partition key is set for Resources CosmosDB container

### ISSUE THREAD

**Issue by LizaShak** [microsoft/AzureTRE#606]
**Describe the bug**
The  Resources CosmosDB container is currently partitioned by a field called "appId". This field  is not set on the items in the container. Causing for that when calling queries on the container which require a partition key to fail.

**Steps to reproduce**

1. Go to CosmosDB resource -> Data Explorer -> Azure TRE -> Resources -> Settings -> PartitionKey
1. Or see in the AzureTRE/management_api_app/db/repositories/base.py
1. To reproduce : In the AzureTRE/management_api_app/db/repositories/base.py add a method and call `self.container.delete_item(item=<item dict or id>,partition_key=<partition>)`

**Comment by TessFerrandez** [comment]
ResourceType might be a good partition key -- but perhaps research a bit to understand if we should include the ResourceType even in the by id queries then

**Comment by TessFerrandez** [comment]
After closer consideration /id is probably best per documentation https://docs.microsoft.com/en-us/azure/cosmos-db/partitioning-overview
