### ISSUE TITLE
[BUG] Cannot create multiple instances of Guacamole workspace service

### ISSUE THREAD

**Issue by tamirkamara** [microsoft/AzureTRE#634]
**Describe the bug**
Creating multiple instances of the same service type (guacamole) doesn't actually create them.

**Steps to reproduce**

1. Issue multiple POSTs for new instances of the guacamole service
1. See that all complete successfully but only a single instance actually gets created. This might be related to the random service id generated within terraform

**Comment by marrobi** [comment]
#897 fixes some of the problems, #900 is still blocking this from working.

**Comment by marrobi** [comment]
Confirmed as duplicate of #900 will fix in #900
