### ISSUE TITLE
[BUG] Permissions missing for running Docker in Codespaces

### ISSUE THREAD

**Issue by Lybecker** [microsoft/AzureTRE#641]
When trying to execute docker commands in Codespaces the following error appers

vscode ➜ /workspaces/AzureTRE (develop) $ docker version
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:02 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version": dial unix /var/run/docker.sock: connect: permission denied

To fix it run:

source ./devops/scripts/set_docker_sock_permission.sh

**Comment by marrobi** [comment]
I get this locally in WSL occasionally too.

**Comment by Lybecker** [comment]
@msebragge have you seen this bug lately?

I have not seen it

**Comment by msebragge** [comment]
@Lybecker  Still need to run the script everytime on codespaces

**Comment by jjgriff93** [comment]
Will resolve this by moving `devops/scripts/set_docker_sock_permission.sh` into dev container postCreateCommand (which will mean we can remove every call in make commands). Depends on GitHub Actions using dev container as currently we would also need to manually call the script in Actions

**Comment by Lybecker** [comment]
Remember to test with CodeSpaces, as we had some issues there

**Comment by jjgriff93** [comment]
@Lybecker that's my main environment right now as Im on Mac M1 :) so will do!

**Comment by jjgriff93** [comment]
Depends on #1166
