### ISSUE TITLE
[Story] Add tests that create a new workspace service deployment

### ISSUE THREAD

**Issue by deniscep** [microsoft/AzureTRE#643]
As a TRE Developer
I want to ensure that all workspace services are deploying correctly. 
So that I can react to any issues that might arise from system modifications

Task:
Add tests that creates a new workspace service deployment

BLOCKED: due to no service templates being deployed by the provisioning pipeline.
To unblock, add a service template setup to Deploy TRE pipeline.

**Comment by christoferlof** [comment]
Predecessors to unblock: #569 , #693
