### ISSUE TITLE
Add bundle registry to TRE templates

### ISSUE THREAD

**Issue by christoferlof** [microsoft/AzureTRE#65]
## User story

As a TRE service integrator
I need to place my workspace bundles in the bundle registry
So that the services can be instantiated by researchers and read by the deployment client / resource processor.

## Acceptance critiera

- [x] Bundle registry defined in IaC and integrated into TRE IaC
- [x] Bundle registry deployed as part of TRE deployment
- [x] Sample bundle added to bundle registry in shared environment for demo

**Comment by christoferlof** [comment]
@deniscep  please see whether we can or should repurpose the ACR already in the templates.

**Comment by tompaana** [comment]
The DevOps bits to publish the workspace use custom scripts now run by the `Makefile`, but if at some point we want to move it to typical workflow steps we can refer to https://github.com/getporter/pipeline-demo
