### ISSUE TITLE
[Task] Configure outbound Firewall rules for Virtual Desktop Service

### ISSUE THREAD

**Issue by Lybecker** [microsoft/AzureTRE#655]
**Description**

Outbound traffic is restricted, so any internet must be explicated allowed.

Configure in the Azure Firewall the Service Tags and URLs allowed for outbound/inbound traffic
Document why each of the Service Tag/URL is needed

**Comment by christoferlof** [comment]
Virtual desktop service most likely don't need specific outbound rules. However, individual VMs might require for scenarios like AD join - would then be configured at workspace level.

**Comment by christoferlof** [comment]
@tamirkamara /  @Lybecker please associate with a parent story

**Comment by Lybecker** [comment]
@tamirkamara I cannot think of any reason for the Virtual Desktop Service to need Internet access. If you agree, then please close this one
