### ISSUE TITLE
TRE developer creates SSL certificate for development purposes

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#66]
## Description

As a developer I want to acquire a certificate that can be used when I deploy the TRE.

So that I can provide the certificate when deploying the TRE #51 

## Acceptance criteria

- [ ] Set of commands to create certificate request and process certificate request
- [ ] Works cross platform
- [ ] Document the commands
- [ ] Wildcard certificate to enable subdomains to be used on workspaces
- [ ] Mirrors process of acquiring a certificate from corporate IT as close as possible. I.e. Create request, process request. So that the same process can be used to create a request to give to corporate IT to process.

**Comment by askew** [comment]
I've got scripts that will use certbot to request a cert and upload it to KeyVault. We don't need to try to guess what a customers CA workflow might be, it will vary. But we should be able to assume a customer is able to store and renew certs in KeyVault.

**Comment by askew** [comment]
Working draft #103
