### ISSUE TITLE
[BUG] Make the ARM_TENANT_ID and ARM_SUBSCRIPTION_ID environment variable optional

### ISSUE THREAD

**Issue by Lybecker** [microsoft/AzureTRE#681]
When deploying TRE, the `ARM_TENANT_ID` and `ARM_SUBSCRIPTION_ID` should be defaulted to the current `az cli` session selected subscription.

**Describe the bug**
The values are currently mandatory in the [manual deployment](https://github.com/microsoft/AzureTRE/blob/develop/docs/manual-deployment.md#configure-variables), which they shouldn't be. If specified the specified value is overwritten with `ARM_SUBSCRIPTION_ID=$(echo "$AZURE_CREDENTIALS" | jq -r '.subscriptionId')`

Hint `grep -r "ARM_SUBSCRIPTION_ID"`

**Comment by christoferlof** [comment]
Moving to backlog, not blocking 0.2 release.

**Comment by marrobi** [comment]
@ross-p-smith I don't think these are need anymore? If so we can close this.
