### ISSUE TITLE
Manual setup fails if Gitea is enabled

### ISSUE THREAD

**Issue by msebragge** [microsoft/AzureTRE#682]
Remember to label the issue with the appropriate area, and also assign it to yourself if you plan to work on the issue in the near future.

**Describe the bug**
Manual setup fails if Gitea is enabled and no credentials are given. Gitea step tries to do something with keyVault and fails with no permission.

**Steps to reproduce**

I will update later

1. Click on '....'
1. Scroll down to '....'
1. See error

**Comment by marrobi** [comment]
No steps to repro.
