### ISSUE TITLE
[BUG] After setting the environment using manual setup CosmosDb is not updated correctly after workspace deployment. 

### ISSUE THREAD

**Issue by msebragge** [microsoft/AzureTRE#688]
**Describe the bug**
CosmosDb is not updated.

**Steps to reproduce**

1. Setup environment using manual steps (not CI/CD).
2. Create new AML workspace.
3. Workspace is deployed correctly.
4. CosmosDb is not updated. Stays in state:   "This resource is not yet deployed"

**Comment by marrobi** [comment]
@msebragge what errors were there in the logs? How long did the deployment take from start to finish in the logs?

The autorenew on service bus only works for 30 mins:

https://github.com/microsoft/AzureTRE/blob/d7de262c8e3569785fd2e49a4925a89c5387745e/resource_processor/vmss_porter/runner.py#L47

So if was more that 30 mins might explain why the job did not return its status. IF this is a case need to have an error such as deployment job exceeded maximum time.

**Comment by christoferlof** [comment]
@Lybecker , @msebragge please keep this in mind when deploying InnerEye workspaces - we'll not assign explicitly nor invest more time investigating for now. If you stumble upon this happening, please add details to this issue thanks.

**Comment by tamirkamara** [comment]
@marrobi have you deployed AML recently? did you see this?

**Comment by marrobi** [comment]
I think this can be closed. 

There is a new AML issue due to HNS being enabled by default under milestone 3, so haven't done an AML deployment for a few weeks.
