### ISSUE TITLE
Trigger the Workspace Bundle when Workspace is created through the API

### ISSUE THREAD

**Issue by Lybecker** [microsoft/AzureTRE#69]
## Description

As a Researcher/TRE admin, 
I want the notify the Workspace Bundle executor when changing a Workspace or Workspace Service, 
so the Workspace Bundle can perform the requested changes

When a change is requested through the Management API, a command (message) with information about the change is added to a queue. The message is picked up by Resource Processor and passed to the Workspace Bundle.

It should be implemented as part of the API in #62.

The command (message) should contain the Workspace schema information.

## Acceptance criteria

- [x] Message successfully placed on the queue

**Comment by christoferlof** [comment]
Removing the requirement of sb sessions for now as we only see this important when handling concurrent service deployments in the future.
Closing.
