### ISSUE TITLE
[Story] Retrofit existing bundles to new RP param process

### ISSUE THREAD

**Issue by tamirkamara** [microsoft/AzureTRE#690]
**Description**
The resource process now handles params differently and that might impact how existing bundles are deployed.
Examples are: using id for the tf-store-key, how to use workspace id, acr, etc.

- [x] mgmt_acr_name removed from custom parameters as is system provided
- [x] update existing bundles to use short installation id
- [x] #942 
- [x] #964
- [x] Ensure every bundle has a template_schema.json

# Implementation

- [x] #908

**Comment by christoferlof** [comment]
Also see #834
