### ISSUE TITLE
[BUG] User resource should include a property of who created it

### ISSUE THREAD

**Issue by tamirkamara** [microsoft/AzureTRE#692]
**Describe the bug**
Some user resource (like a vm) are per user (hence the name) and should be used by the person who created them. Currently the item persisted to the db doesn't include that information (perhaps like the workspace?) and makes this requirement impossible.

**Steps to reproduce**

1. POST a new user resource to the api
1. Look at the item in the db and see it doesn't include any ownership information

**Comment by marrobi** [comment]
@tamirkamara is this already covered in https://github.com/microsoft/AzureTRE/issues/679 ?

**Comment by tamirkamara** [comment]
Right @marrobi. Didn't find that.
Closing...

**Comment by tamirkamara** [comment]
Actually, no - I don't see any ownership info. Keeping open for now.
