### ISSUE TITLE
[Story] Register workspace service templates as part of e2e tests

### ISSUE THREAD

**Issue by deniscep** [microsoft/AzureTRE#693]
As a TRE Developer
I want to deploy all available workspace services templates
So that I can have the services available to be consumed by the workspaces. 

## Acceptance critiera

- [ ] All service templates are deployed and pushed to ACR
- [ ] Deployment process either documented or automated

**Comment by christoferlof** [comment]
@deniscep  is this to enable e2e tests? We have capability to register workspace services.

**Comment by Lybecker** [comment]
As I recall the discussion, this is about the InnerEye Workspace Template has pseudo [Workspace Services](https://github.com/microsoft/AzureTRE/tree/develop/templates/workspace_services) - by that I mean, that they are not registered as Workspace Services and provisioned via the Workspace Template.
