### ISSUE TITLE
[Story] Register innereye workspace template

### ISSUE THREAD

**Issue by deniscep** [microsoft/AzureTRE#694]
As a TRE Developer
I want to register InnerEye and InnerEye Inference workspace templates
So that I can use the templates to deploy InnerEye Workspaces. 

## Acceptance critiera

- [ ] InnerEye and InnerEye Inference templates registered and deployed to ACR
- [ ] Deployment either documented or automated (prefer automated)

**Comment by christoferlof** [comment]
@deniscep does this relate to the e2e tests?
