### ISSUE TITLE
Remove redundant system params

### ISSUE THREAD

**Issue by tamirkamara** [microsoft/AzureTRE#729]
## Description

As a developer, I should only need to provide the required system parameters and for the system to infer the rest.

## Acceptance criteria

- [ ] params.workspace_id isn't sent anymore by the API when creating a new workspace
- [ ] All workspace bundles are updated to use the id of the "tre resource" for both the TF state and for azure resources as the short_workspace_id. Note that this will likely cause problems in the MSR subscription when merged.
- [ ] concatjsonschema.py (api class) is updated (refactored)

**Comment by marrobi** [comment]
@martinpeck are you intending to do this? If not suggest unassign yourself and @tamirkamara might be one for your team to consider.

**Comment by martinpeck** [comment]
done

**Comment by tamirkamara** [comment]
I think this is now obsolete.
