### ISSUE TITLE
Remove ACI subnet

### ISSUE THREAD

**Issue by Lybecker** [microsoft/AzureTRE#735]
Do it the defaultroute branch

**Comment by tompaana** [comment]
Changes implemented in commits:
- [b24f308cacb46cf331a817ad982d74a99fc48274](https://github.com/microsoft/AzureTRE/commit/b24f308cacb46cf331a817ad982d74a99fc48274)
- [1a0451c550ab3f739dcc0682d5e8751a45841e48](https://github.com/microsoft/AzureTRE/commit/1a0451c550ab3f739dcc0682d5e8751a45841e48)
