### ISSUE TITLE
[BUG] Devcontainer fails to start

### ISSUE THREAD

**Issue by tompaana** [microsoft/AzureTRE#740]
Devcontainer fails to start due the following issues:

- [ ] *In Windows*, the volumes specified in `docker-compose.yml` fail since they are Unix-like environment specific

- [ ] The base image is based on `bullseye` whose packages repository does not appear to have contain Azure CLI release version

  ```plaintext
  #7 8.251 Ign:6 https://packages.microsoft.com/repos/azure-cli bullseye InRelease
  #7 8.313 Err:7 https://packages.microsoft.com/repos/azure-cli bullseye Release
  #7 8.313   404  Not Found [IP: 13.80.99.124 443]
  #7 8.594 Reading package lists...
  #7 9.439 E: The repository 'https://packages.microsoft.com/repos/azure-cli bulls
  eye Release' does not have a Release file.
  ```

**Comment by Lybecker** [comment]
I think I fixed this bug with this PR https://github.com/microsoft/AzureTRE/pull/732

**Comment by Lybecker** [comment]
I just created a CodeSpace devcontainer and it works :)

**Comment by tompaana** [comment]
Confirmed. It works.
