### ISSUE TITLE
Nexus - verify description and correct the required egress rules

### ISSUE THREAD

**Issue by Lybecker** [microsoft/AzureTRE#748]
Make sure that below egress firewall rules are what is needed for the Nexus and the description of each of them is described in detail.

- [Documentation](https://github.com/microsoft/AzureTRE/blob/defaultroute/templates/shared_services/sonatype-nexus/readme.md#network-requirements)
- [Firewall settings](https://github.com/microsoft/AzureTRE/blob/defaultroute/templates/core/terraform/firewall/firewall.tf#L82-L145) - be aware these rules seems to be shared with Gitea

Please create a PR to the defaultroute branch or let me know what to change.

**Comment by Lybecker** [comment]
@tamirkamara who can help me with this task?

**Comment by tamirkamara** [comment]
@Lybecker what should be the output from this task? Should I change something in the branch? TF / Doc?

**Comment by Lybecker** [comment]
@tamirkamara I would like you to check that the URLs/ServiceTags are needed and describe why each of these are needed, so I can include it in the documentation.

You can either share it here or commit directly to the `defaultroute` branch
