### ISSUE TITLE
Add Inbound security rule between WebAppsSubnet and ServicesSubnet

### ISSUE THREAD

**Issue by anatbal** [microsoft/AzureTRE#751]

**Comment by Lybecker** [comment]
Why does the Workspace needs access to the TRE API?

**Comment by anatbal** [comment]
@Lybecker , after discussing the networking dilemma form today's parking lot about making the api call to the gateway externally or the api internally with @marrobi and @tamirkamara , we decided on going with the internal approach, therefore the guacamole service needs to have access to the api in the other subnet.
