### ISSUE TITLE
Delete old docker packages each night

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#78]
## Description

As a cloud administrator
I want to delete all docker images that were built from PRs each evening
So that the container registry is kept clean

## Acceptance critiera

- [ ] Scheduled nightly GitHub workflow that deletes Docker images without `main-*` or `develop-*` (i.e. tagged with commit sha), and older that 24 hours.

**Comment by christoferlof** [comment]
Docker images now published to ACR deployed as part of Azure TRE deployment.  See #93

**Comment by marrobi** [comment]
@christoferlof has a PR merge against it. The workflow will need amending to clean up our ACR.
