### ISSUE TITLE
[BUG] Terraform files refer to variables that don't exist

### ISSUE THREAD

**Issue by TessFerrandez** [microsoft/AzureTRE#782]
The following lines in terraform files refer to variables that don't exist

appgateway -> certificate.tf
3:  tenant_id    = azurerm_user_assigned_identity.agw_id.tenant_id

main.tf
93:   app_insights_connection_string             = azurerm_application_insights.core.connection_string
127:  app_insights_connection_string             = azurerm_application_insights.core.connection_string
163:  managed_identity_tenant_id = module.identity.managed_identity.tenant_id

gitea/terraform/gitea-webapp.tf

236:  tenant_id    = azurerm_user_assigned_identity.gitea_id.tenant_id

workspace_services/guacamole/terranform/keyvault.tf
36:   tenant_id    = data.azurerm_user_assigned_identity.vmss_id.tenant_id

workspace services/innereye_deeplearning/terraform/compute.tf

 108: principal_id         = jsondecode(azurerm_resource_group_template_deployment.deploy_compute_cluster.output_content).cluster_principal_id.value

both output_content and value

**Comment by anatbal** [comment]
Hi, so I took a look at this and it seems to be a bug in the jetbrains terraform plugin. All of these attributes do exist and are being created, and also appear in the official terraform documentation. 
There are a few open issues about the "Unresolved reference" issue under the plugin source code like [this](https://github.com/VladRassokhin/intellij-hcl/issues/309), and [this](https://github.com/VladRassokhin/intellij-hcl/issues/308).
@TessFerrandez , @tamirkamara , do you think we can close this one?

**Comment by TessFerrandez** [comment]
cool cool, yeah, as far as I am concerned we can close it then
