### ISSUE TITLE
Access management API at /api

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#80]
## Description

As a TRE Developer
I want to expose the management api at /api
So that I can run other services through the application gateway.

Need to discuss change management API image path vs rewrite rule

## Acceptance critiera

- [ ] Can access the management API at  /api

**Comment by TessFerrandez** [comment]
I'm actually making this change in my current work for #76 - noticed the need for this too :)

**Comment by marrobi** [comment]
@TessFerrandez the app gateway path rule should be changed at the same time:

```
path_rule {
      name = "api"
      paths = ["/*"]
``` 
to

```
path_rule {
      name = "api"
      paths = ["/api/*"]
```
