### ISSUE TITLE
[BUG] Using -a switch on aad-app-reg.sh to grant admin consent fails

### ISSUE THREAD

**Issue by SvenAelterman** [microsoft/AzureTRE#802]
Running aad-app-reg.sh with the `-a` switch fails with the error message below. It appears the failure occurs during the granting of the admin consent. The app registration for the API is successfully created, but admin consent is not granted. There is no Swagger UI app created.

**Steps to reproduce**

1. Run the script with the following command line:
`./aad-app-reg.sh -n aztrehack23 -r https://aztrehack23.eastus2.cloudapp.azure.com/oidc-redirect -a`
1. Observe error message below
1. In AAD, the API app registration (and enterprise app) are created, but no admin consent is granted.

Bad Request({"ClassName":"Microsoft.Portal.Framework.Exceptions.ClientException","Message":"Graph call failed with httpCode=BadRequest, errorCode=Request_BadRequest, errorMessage=Application 'c111e4d6-4b89-4462-8790-9dc7891f9bb4' is requesting permissions that are either invalid or out of date., reason=Bad Request, correlationId = 1ad6c585-e959-4424-9045-81667e1fd014, response = {\"odata.error\":{\"code\":\"Request_BadRequest\",\"message\":{\"lang\":\"en\",\"value\":\"Application 'c111e4d6-4b89-4462-8790-9dc7891f9bb4' is requesting permissions that are either invalid or out of date.\"},\"requestId\":\"018a2378-c3db-40e6-ad6d-90d75f19671f\",\"date\":\"2021-09-09T13:39:29\"}}","Data":{},"HResult":-2146233088,"XMsServerRequestId":null,"Source":null,"HttpStatusCode":400,"ClientData":{"errorCode":"Request_BadRequest","localizedErrorDetails":{"errorDetail":"Application 'c111e4d6-4b89-4462-8790-9dc7891f9bb4' is requesting permissions that are either invalid or out of date."},"operationResults":null,"timeStampUtc":"2021-09-09T13:39:29.1748809Z","clientRequestId":"1ad6c585-e959-4424-9045-81667e1fd014","internalTransactionId":"d0201830-422e-4467-98c3-64d5a1deccd1","tenantId":"6c7dbaa5-c725-4e29-a340-123bdf8d0049","userObjectId":"6e41d2a3-ec8f-417d-9fe4-e2f29db038c7","exceptionType":"AADGraphException"}})

**Comment by SvenAelterman** [comment]
Additional info: when cleaning up the created app registration and enterprise application and re-running the script with the same command line except for the `-a` switch, the command completes as expected.

**Comment by christoferlof** [comment]
We have some additional issues reported with the aad-app-reg script. Please also have a look at 
#822, #820, #816, #792 and see if any of them can be addressed at the same time as this one.

**Comment by christoferlof** [comment]
#839 also

**Comment by tompaana** [comment]
I'm unable to reproduce the error. I suspect the error is due to the signed user lacking the directory administrator privileges (required by Azure CLI when granting admin consent - see [az ad app permission admin-consent](https://docs.microsoft.com/cli/azure/ad/app/permission?view=azure-cli-latest#az_ad_app_permission_admin_consent), although the error message does not explicitly state this. I will try to reproduce the error using another subscription where I don't have the directory admin privileges. However, the script/docs should clearly state this requirement.

**Comment by SvenAelterman** [comment]
I am a Global Admin in the tenant where this occurred.

**Comment by tompaana** [comment]
I managed to reproduce the error. I'm not sure about the root cause yet, but I think it might have something to do with the newly created app not being ready. Re-running the script succeeds.
