### ISSUE TITLE
[BUG] Deploying AzureTRE without an authentication token fails on aad-app-reg.sh

### ISSUE THREAD

**Issue by guybartal** [microsoft/AzureTRE#820]
When deploying Azure TRE you must be logged in with az cli before running aad-app-reg.sh script.

**Steps to reproduce**

1. Follow https://github.com/microsoft/AzureTRE/blob/develop/docs/deployment-quickstart.md for deploying a new environment
1. When you run aad-app-reg.sh script it will fail with the following error:

![image](https://user-images.githubusercontent.com/3179107/132986416-60703f73-b12e-4acd-a771-62a4f0ab7415.png)

**Comment by christoferlof** [comment]
@guybartal since you merged the PR, I assume this can be closed?
