### ISSUE TITLE
[BUG] Swagger UI is a public client app registration should allow public client flow when generating with aad-app-reg.sh script

### ISSUE THREAD

**Issue by guybartal** [microsoft/AzureTRE#822]
```aad-app-reg.sh``` script generates two app registrations, the second one is a public client app registration for Swagger UI, and it should have been set to allow public client flow.

**Steps to reproduce**

1. run ```./scripts/aad-app-reg.sh``` as part of the deployment.
1. search for the app registration and look for the second app which the scripts outputs in the AAD app registrations on Azure Portal.
1. click on ```Authentication``` in the side menu and look at the settings under ```Allow public client flows```, it will be disabled while the expected result should have been enabled.

![image](https://user-images.githubusercontent.com/3179107/132989992-78be8c27-0634-4cd4-b694-4153b9cc07ba.png)

**Comment by christoferlof** [comment]
Please validate this one first.

**Comment by marrobi** [comment]
@tompaana was this validated as being required? Thanks.

**Comment by christoferlof** [comment]
See #915 for validation.
