### ISSUE TITLE
Create E2E tests for user resource

### ISSUE THREAD

**Issue by LizaShak** [microsoft/AzureTRE#831]
Origin story: #623 

**Description**
Add an E2E for deploying a user resource, validating that it is deployed and updated successfully. Disabled and deleted at the end.

**Comment by msebragge** [comment]
Waiting for user resource registration.

**Comment by christoferlof** [comment]
@msebragge , please link the issue blocking this one for reference, thanks.

**Comment by LizaShak** [comment]
@marrobi   I think we can remove the blocked label here right?

**Comment by marrobi** [comment]
Agreed, and removed.
