### ISSUE TITLE
[Task]  Document workspace service compatibility,

### ISSUE THREAD

**Issue by LizaShak** [microsoft/AzureTRE#832]
Story: #623 

**Description**
Document which workspace services are compatible with which workspace template. Same for user resources and their compatible workspace service.

**Comment by marrobi** [comment]
@LizaShak  not sure what trying to achieve here - but for the ones we build all the workspace services will work with all the workspace templates.

User resources won't work with all workspace services - but this is "documented" in the directory structure of the repo - the user resources live within their workspace service directory.
