### ISSUE TITLE
[Task] Add a before and after setups in the E2E tests

### ISSUE THREAD

**Issue by LizaShak** [microsoft/AzureTRE#845]
Story: #623 

**Description**
Creation of workspace and workspace services take a lot of time.
Those basic resources are reused in different tests.
To save time we should decide how and when do we want to create those shared tests resources.
Setup order for the tests.
And then have them setup/created at the beginning. And disabled and deleted when tests are finished.

**Comment by TessFerrandez** [comment]
Closing this as this is already fixed with @msebragge PR #856
