### ISSUE TITLE
[BUG] Make deploy TRE follow DRY

### ISSUE THREAD

**Issue by deniscep** [microsoft/AzureTRE#853]
There is a bit of repetitive code around workspace and template registration, which should be written as a loop.

**Comment by TessFerrandez** [comment]
@deniscep are you referring to a script or the workflow here?

**Comment by tamirkamara** [comment]
Who ever picks this up can take a look at tamirkamara/register-matrix branch for some ideas. It's not done and I won't be able to finish it myself in the next few weeks...

**Comment by deniscep** [comment]
@TessFerrandez why not both ;) ? Specifically I was talking about workflow, but now that you mention it, I remember there are things that can be cleaned up in the script itself as well.
