### ISSUE TITLE
Provide operation history to TRE users via API

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#865]
## Description

As an TRE Administrator I want to be able to view the operation history for all resources so that I can see who created/updated/deleted what, when and the outcome of the operation.

As an Researcher I want to be able to view the operation history for my resources so I can see when I created/updated/deleted resources and the outcome of the operation.

As an Workspace Owner I want to be able to view the operation history for all resources in a workspace so that I can see who created/updated/deleted what, when and the outcome of the operation.

**Comment by damoodamoo** [comment]
Proposal:
- Update resource document in Cosmos to include `operations: []` (structure below)
- An operation is a create / update / delete of the resource
- API adds a new entry in list each time
- Each operation has a unique Id and newest ones are appended to the top of the list, so clients can query for the outcome of a specific operation if needed
- This replaces the current `deployment` object

```json
{
  "id": "guid....",
  ...,
  "operations": [
    { 
      "id": "guid-here",
      "status": "waiting",
      "message": "etc",
      "type": "update",
      "triggered_by": "...",
      "triggered_when": datetime,
      "completed_when": datetime
      ...
    },
    { 
      "id": "guid-blah",
      "status": "complete",
      "type": "create",
      ...
    }
  ]
```

**Comment by marrobi** [comment]
@damoodamoo Are operations always associated with a resource?

Should these operations live under a resource or as a new collection in cosmos, referencing the resources.

Other than that, looks good.

**Comment by damoodamoo** [comment]
ok good question - my thinking was that operations would always relate to a resource - an operation being 'an action that happens to a resource'. If 'Add User' was an operation, would that not also relate to a resource, or not?

**Comment by damoodamoo** [comment]
also relevant is how do you see this data being surfaced - I was assuming a client would navigate to a resource and then view the operations history for that resource. Do you see there being an `/operations` API endpoint that would surface all operations across the TRE regardless of resource?

**Comment by marrobi** [comment]
I think you are probably correct as far as there would always be a TRE resource mirrored. with any "deployed" or configurable resource. It's not the case for shared services at the moment but will be. How about "tre start" or "tre stop"...

As for surfacing the data - see the user stories above in this issue. Queries will not always be done at a resource level. For example in time might want to see what VMs were deployed in the TRE (or workspace) over a period of time.

**Comment by damoodamoo** [comment]
ok to summarise:
- New cosmos collection for `operations`
- At the point of enqueueing the message, and updating the status - instead of updating the `deployment:{}` block, we create/update a doc in the `operations` collection
- Each operation in the collection is a single doc, referencing the type, status, resourceId etc
- New API endpoints on top of the resources - such: `/user_resources/1234567890/operations` 
- `deployment` block gone
- Resource Processor to get and return the Operation Id as well as the ResourceId - this will also support future work on multiple updates

**Comment by marrobi** [comment]
Looks good, you need to add updating the operations doc when the job completes.
