### ISSUE TITLE
Network flow diagram

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#87]
## Description

As a TRE Developer
I want to understand what network flows are allowed/denied by default
So that I can troubleshoot connectivity issues

## Acceptance criteria

- [x] Diagram of network components
- [x]  Show network flow from each core and workspace subnet to each other subnet and the internet.
- [x] For each flow show if the traffic is allowed or denied by default

**Comment by christoferlof** [comment]
Need diagram and description for TRE base setup and individual workspace templates / bundles.
