### ISSUE TITLE
[BUG] Can't deploy tre using 'make all' if both nexus and gitea are disabled.

### ISSUE THREAD

**Issue by eladiw** [microsoft/AzureTRE#891]
Can't deploy tre using 'make all' if both nexus and gita are disabled.

**Describe the bug**
when setting gitea and nexus to disabled, the shared subnet can't be created since no rules are generated.
we get the following error:

Error: Insufficient rule blocks
│ 
│   on firewall/firewall.tf line 82, in resource "azurerm_firewall_application_rule_collection" "shared_services_subnet":
│   82: resource "azurerm_firewall_application_rule_collection" "shared_services_subnet" {

**Steps to reproduce**

1. Go to .env file in the core directory
1. update to
DEPLOY_GITEA=false
DEPLOY_NEXUS=false

1. Run 'make all'
1. See error

**Comment by marrobi** [comment]
Duplicate of #827?

**Comment by eladiw** [comment]
yes
