### ISSUE TITLE
[Story] Revisit Azure TRE setup instructions

### ISSUE THREAD

**Issue by tompaana** [microsoft/AzureTRE#903]
## Description

As a new TRE administrator
I want to have clear, ordered setup instructions for a new Azure TRE instance
So that the the time it takes to have it up and running is minimized and can be done without excessive troubleshooting

Related issue: #718 

## Acceptance criteria

- [x] Outline the new structure of the documentation with respect to deployment etc. and list other required changes
- [x] Write pages covering the steps in logical order under what is currently named "Deploying the TRE" in the docs
- [x] Revise development quickstart to be a summary of the steps linked to the new pages
- [x] Modify GitHub workflows deployment guide to match the newly created changes and minimize duplicate information #949 
- [x] Make `aad-app-reg-sh` remind the user at the end of the run to grant admin consent (or contact the admin to do this) in case they didn't use the option when running the script
- [x] #931

**Comment by TessFerrandez** [comment]
Some feedback items from my run-through (note some are also above)

1. Make the quickstart a bit more step-by-step
1. Call out (at the top of each section) what the purpose is, and also what the caveats are (you need admin etc)

## Set Management config
1. /devops/.env vars - would be nice with examples in the table

## Set Azure TRE config
1. Make the create auth apps a separate section -- and add a "warning" for the info that domain admin is needed

## Deploying
1. Make all - Didn't have docker running - that error should have stopped the run
1. Lets encrypt - was difficult to install, but got it working in the end (might be a non-issue) 

## DevContainer
1. Hang with dev container (on first create) - very high cpu and memory
2. Can't install porter in the dev container (might just be my machine)

**Comment by TessFerrandez** [comment]
From Marcus, a suggested outline of the quickstart

1. quickstart
1. add user as admin
1. publish and register workspace, workspace service, user resource, bundle
1. create workspace app reg
1. create workspace
1. create workspace service
1. create user resource
