### ISSUE TITLE
[BUG] .env setting MANAGEMENT_API_IMAGE_TAG is ignored in App Service configuration

### ISSUE THREAD

**Issue by SvenAelterman** [microsoft/AzureTRE#910]
I set the value of `MANAGEMENT_API_IMAGE_TAG` in /templates/core/.env to `dev`. When I deployed the TRE, the API app tried to pull the `microsoft/azuretre/api` image with the tag `main-latest`.

**Comment by SvenAelterman** [comment]
The issue seems to be related to line 60 of /templates/core/terraform/api-webapp/api-webapp.tf. There's a reference to Terraform variable `api_image_tag`, the default of which is set to `main-latest` on line 39 of /core/terraform/variables.tf. However, in `deploy.sh`, I don't see (what I believe to be a necessary) `export TF_VAR_api_image_tag=...`.

**Comment by marrobi** [comment]
Sorry, breaking change. The term management was overloaded and causing confusion so some things were renamed a week or so ago. 

It's now API_IMAGE_TAG 

Check: 

https://github.com/microsoft/AzureTRE/blob/develop/templates/core/.env.sample
