### ISSUE TITLE
[Task] Test whether public client flow for Swagger UI app is needed or not

### ISSUE THREAD

**Issue by tompaana** [microsoft/AzureTRE#915]
App registration for Swagger UI has public client flow enabled (see "Authentication" blade in Azure Portal). We are not sure if that is even required for it to work and if not, it should be disabled.

Task:
1. Test if the API works via Swagger UI when public client flow is disabled
2. If yes, remove the line enabling public client flow in `aad-app-reg.sh` script and **update the docs**

**Comment by christoferlof** [comment]
Swagger UI use the oauth2 authorization code grant, which is not a public client flow. 
Will update app-reg.sh and docs.

```plaintext
Authorization URL: https://login.microsoftonline.com/<tenant-id>/oauth2/v2.0/authorize

Token URL: https://login.microsoftonline.com/<tenant-id>/oauth2/v2.0/token

Flow: authorizationCode
```
