### ISSUE TITLE
Create bootstrap and deploy scripts

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#92]
## Description

As a cloud administrator I want to bootstrap my subscription with TF state storage, and an ACR, so that I can deploy the TRE

## Acceptance criteria

- [x] Scripts to create TF state storage and ACR in subscription
- [x] Scripts to build and push docker images to the ACR
- [x] Scripts to deploy TRE using the provisioned storage for TF state and ACR for pulling the images

Includes #71

**Comment by christoferlof** [comment]
Looks very similar to #58 . Possible dupe or different scope @marrobi ?

**Comment by marrobi** [comment]
Yes, that's covered in this PR. Can you link that issue too and merge this?
