### ISSUE TITLE
[BUG] Excessive logging from Firewall

### ISSUE THREAD

**Issue by Lybecker** [microsoft/AzureTRE#934]
AML is trying to send logs to Azure Monitor/App Insights from Workspaces, which is being denied by the Azure Firewall. This fills the log with a large amount of data which incurs a cost.

The proper solution is #742 Enable private link for Azure Monitor.

The solution for now is to enable Azure ML and Dev Test Labs Workspace template to allow egress traffic to Azure Monitor.

**Comment by tompaana** [comment]
The issue will be fixed properly in #742.
