### ISSUE TITLE
Register API with Azure AD to enable auth

### ISSUE THREAD

**Issue by christoferlof** [microsoft/AzureTRE#95]
## User story

As a Cloud Administrator, 
I want to be able to register an instance of Azure TRE in Azure AD,
so that I can assign users permissions to access the Azure TRE API.

## Acceptance criteria

- [ ] Script to create the application registration.
- [ ] Script to grant consent to the application.
- [ ] App role `TRE Administrator` created.

**Comment by christoferlof** [comment]
App registration for cross workspace operations at TRE level.

**Comment by marrobi** [comment]
@askew  I have a script to do this, will need you to review happy for me to pick this up while waiting for some deployments to run?
