### ISSUE TITLE
[BUG] Gitea not accessible from the internal network

### ISSUE THREAD

**Issue by deniscep** [microsoft/AzureTRE#955]
The GITEA__server__ROOT_URL config is now pointing to public URL of Gitea. This works from the outside, but not from the workspace, where user should be accessing Gitea over internal address. 

In order to get both to work, Gitea should listen to https://url/gitea instead of https://url/.
nginx.conf needs to be set to /gitea as per: https://docs.gitea.io/en-us/reverse-proxies/#nginx-with-a-sub-path

- [ ] Modify the Gitea image to serve Gitea from /gitea
- [ ] Remove the override backendpath from Application Gateway GItea Http setting (from "/" to "")
- [ ] Change the path in Gitea health probe in Application Gateway from "/" to "/gitea"

**Comment by christoferlof** [comment]
Accessing Gitea will be through jump box, see #981 
Closing as `wontfix`
