### ISSUE TITLE
Support workspace tokens in API

### ISSUE THREAD

**Issue by LizaShak** [microsoft/AzureTRE#983]
## Description

#985 is a pre-decessor

As a workspace owner
I want to be able to send API requests to edit/create workspace resources using different workspaces app registrations
So that I can access the management API and authorized based on the workspace app registration

## Technical notes

- When we create a workspace and appId param is passed on which represents the app registration used for this workspace
- Having a token issued for workspace
- Send  a request to create workspace service with the issued token to the management api
- Take the aud claim from the token
- Query the cosmos resources collection with the workspaceId==workspace_id on the request url and authorize the call only if appId param equals the aud claim. 

## Acceptance criteria

- [x] API requests, made on TRE level (creation of: shared services,  workspace... ) remain the current authentication logic(the access is made through SWAGGER UI app registration and the token aud claim is TRE API)
- [x] Create workspace service API with token issued for a different workspace gets 401 Unauthorized response.
- [x] Create workspace service API with token issued for the workspace but is expired gets 401 Unauthorized response.
- [x] Create workspace service API with a valid token issued for the workspace is authorized and the workspace service is created.

- [x] Update docs to match new experience
- [x] #1076
- [x] Ensure end to end tests work

**Comment by marrobi** [comment]
@LizaShak end to ends passed so thing good to close this 👍
