### ISSUE TITLE
Nightly/on demand workflow for from-scratch deployment and tear-down

### ISSUE THREAD

**Issue by tompaana** [microsoft/AzureTRE#992]
Create workflow `deploy_and_teardown.yml`, which does the following:

1. Deploys a new TRE instance from scratch with generated TRE ID with form `testMMddHmm` e.g., for datetime Oct 6th 3:18pm: `test10061518`
    - Make sure TRE core ACR has similarly unique ID
1. Tears down the instance using `make` commands e.g., `make tre-destroy`
1. Finally, no matter what the result of any of the previous jobs, will do a forced tear-down of **all** resources

The workflow should run nightly and on demand (`workflow_dispatch`).

**Comment by ross-p-smith** [comment]
@marrobi - have'nt we got this with our PR builds

**Comment by marrobi** [comment]
@ross-p-smith I think so, but do we have a from scratch on main each night?

**Comment by tamirkamara** [comment]
@marrobi no - we reuse the same core environment on the scheduled nightly run. But on PRs we create a whole complete one.
I think we should close as done.

**Comment by marrobi** [comment]
Ok, lets close this.
